objects/Account.object
<CustomObject>
    <fields>
        <fullName>ID_Creation_Status_Code__c</fullName>
        <label>ID Creation Status Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Paperwork will be sent to the primary member on the ACCOUNT</inlineHelpText>
        <label>Main Contact</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.Account.Id</field>
                <operation>equals</operation>
                <valueField>$Source.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UUID__c</fullName>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>WW_Sync_Request__c</fullName>
        <defaultValue>false</defaultValue>
        <label>WW Sync Request</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>WW_Synced__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If checked, this record was successfully synced with WeWork.com API</inlineHelpText>
        <label>WW Synced</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Building__c.object
<CustomObject>
    <fields>
        <fullName>UUID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Building</label>
    <nameField>
        <label>Building</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Actual_Start_Date__c</fullName>
        <formula>Account.Start_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Actual Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Building__c</fullName>
        <description>Pulls Building Location without 3 character city reference</description>
        <formula>Location__r.Location_No_City__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Building</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_Creation_Status_Code__c</fullName>
        <label>ID Creation Status Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Member__c</fullName>
        <formula>if( Billing_Account__r.Primary_Member__r.Id =  Id , "Yes","No")</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Primary Member</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reservable__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reservable</label>
        <referenceTo>Reservable__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This is the latest status coming from Space systems through Jitterbunny of the individual member. This tells us if the user is active or not.</description>
        <inlineHelpText>This is accurate status of a contact if it is an active member of our products or not.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>active</fullName>
                </value>
                <value>
                    <fullName>inactive</fullName>
                    <default>true</default>
                    <label>inactive</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UUID__c</fullName>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>WW_Sync_Request__c</fullName>
        <defaultValue>false</defaultValue>
        <label>WW Sync Request</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>WW_Synced__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If checked, this record was successfully synced with WeWork.com API</inlineHelpText>
        <label>WW Synced</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Actual_Start_Date__c</fullName>
        <inlineHelpText>This is the Expected Start Date until Closed Won</inlineHelpText>
        <label>Actual Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Building__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Enter the specific building for which opportunity is associated</description>
        <inlineHelpText>This is the building / Nearest building to the geography entered by customer</inlineHelpText>
        <label>Building/Nearest Building</label>
        <referenceTo>Building__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Encoded_ID__c</fullName>
        <label>Encoded ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Reservable__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity Reservable</label>
        <referenceTo>Opportunity_Reservable__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Member__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>This is the Main Contact of the Opportunity</inlineHelpText>
        <label>Main Contact</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity_Reservable__c.object
<CustomObject>
    <fields>
        <fullName>Building__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>When we get building uuid insted of reservable uuid in Contract event payload map here.</description>
        <inlineHelpText>When we get building uuid insted of reservable uuid in Contract event payload map here.</inlineHelpText>
        <label>Sellable Building</label>
        <referenceTo>Building__c</referenceTo>
        <relationshipLabel>Opportunity Reservables</relationshipLabel>
        <relationshipName>Opportunity_Reservables</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Reservables</relationshipLabel>
        <relationshipName>Opportunity_Offices</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reservable__c</fullName>
        <label>Reservable</label>
        <referenceTo>Reservable__c</referenceTo>
        <relationshipLabel>Opportunity Reservables</relationshipLabel>
        <relationshipName>Opportunity_Offices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Opportunity Reservable</label>
    <nameField>
        <displayFormat>OO-{0000}</displayFormat>
        <label>Office ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Reservables</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Reservable__c.object
<CustomObject>
    <fields>
        <fullName>Building__c</fullName>
        <label>Building</label>
        <referenceTo>Building__c</referenceTo>
        <relationshipLabel>Reservables</relationshipLabel>
        <relationshipName>Offices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Open_Date__c</fullName>
        <label>Open Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Available</fullName>
                </value>
                <value>
                    <fullName>Unavailable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UUID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Reservable</label>
    <nameField>
        <label>Reservable Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reservables</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/RESTOpportunitySendTest.cls
@isTest
private class RESTOpportunitySendTest {
	static {
        SalesConsoleSettings.createSettings();
    }
    @isTest static void testPOSTSuccess() {        
        Opportunity testOpportunity = RESTOpportunitySendTest.createTestOpportunity();
        String id = testOpportunity.id;
        
        // Fetch again for encoded ID
        Opportunity opportunity = [select Encoded_ID__c from Opportunity where id=:id];
        String encodedId = opportunity.Encoded_ID__c;
        
        System.debug('-------- id:' + id);
        System.debug('-------- encoded id:' + encodedId);
        
        Test.startTest();
        
		RestRequest req 	= new RestRequest(); 
	    RestResponse res 	= new RestResponse();		 
      	req.requestURI = 'https://cs95.salesforce.com/services/apexrest/OpportunitySend/' + encodedId;  
      
      	req.httpMethod = 'POST';
      	RestContext.request 	= req;
 		RestContext.response 	= res;
 		
 		RESTOpportunitySend.Response response = RESTOpportunitySend.doPost();
	 	
	 	System.debug(response.message);
	 	//confirm response
		system.assertEquals(true, response.success);
		
		//confirm contract stage is sent
		Opportunity o = [SELECT StageName FROM Opportunity WHERE id=:id];
		system.assertEquals('Closing', o.StageName);
      	
        Test.stopTest();
    }
    
    public static Opportunity createTestOpportunity() {
    	Account a = new Account(
			name = 'Test Account',
			WW_Synced__c = true,
			WW_Sync_Request__c = false,
			ID_Creation_Status_Code__c = '200'
		);
		insert a;

		Contact john = new Contact(
			firstname = 'John',
			lastname = 'Rambo',
			email = 'john@rambo.com',
			accountID = a.Id,
			Status__c = 'active'
		);
		insert john;

		//add contact as primary member
		a.Primary_Member__c = john.Id;
		update a;

		Contact paul = new Contact(
			firstname = 'Paul',
			lastname = 'Rambo',
			email = 'paul@rambo.com',
			accountID = a.Id,
			Status__c = 'active'
		);
		insert paul;

		Building__c b = new Building__c(
			Name='b1',
			uuid__c = 'abc123'
		);
		insert b;

		Opportunity o = new Opportunity(
			AccountID 						= a.Id,
			CloseDate 						= system.today(),
			Actual_Start_Date__c 	= system.today(),
			StageName 						= 'Qualifying',
			Name 							= 'test Opoortunity',
			Building__c						= b.Id,
            Primary_Member__c 				=paul.Id
            //Encoded_ID__c					= EncodingUtil.base64Encode(Blob.valueOf('10')) 
		);
		insert o;

		// to avoid validation error
		Reservable__c r = new Reservable__c(Name='r1',Building__c=b.Id,Status__c='Available',Open_Date__c=system.today().addDays(-1));
		insert r;
		Opportunity_Reservable__c opres = new Opportunity_Reservable__c(Reservable__c=r.Id, Opportunity__c=o.Id);
		insert opres;
		
		return o;
    }
    
    @isTest static void test_POST_failure() {
			Test.startTest();

			RestRequest req 	= new RestRequest(); 
	    	RestResponse res 	= new RestResponse();
	 		
			//submit post
			RESTOpportunitySend.Response response = RESTOpportunitySend.doPost();
	
			//confirm response
			system.assertEquals(false, response.success);
	
		Test.stopTest();
	}
}