objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Queue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference of account queue</description>
        <label>Account Queue</label>
        <referenceTo>Account_Queue__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <description>This field will updated by Lead to Activity mapping.</description>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alexandria</fullName>
                </value>
                <value>
                    <fullName>Alpharetta</fullName>
                </value>
                <value>
                    <fullName>Amsterdam</fullName>
                </value>
                <value>
                    <fullName>Ann Arbor</fullName>
                </value>
                <value>
                    <fullName>Atlanta</fullName>
                </value>
                <value>
                    <fullName>Austin</fullName>
                </value>
                <value>
                    <fullName>Balston</fullName>
                </value>
                <value>
                    <fullName>Baltimore</fullName>
                </value>
                <value>
                    <fullName>Bangkok</fullName>
                </value>
                <value>
                    <fullName>Barcelona</fullName>
                </value>
                <value>
                    <fullName>Barranquilla</fullName>
                </value>
                <value>
                    <fullName>Be'er Sheva</fullName>
                </value>
                <value>
                    <fullName>Beijing</fullName>
                </value>
                <value>
                    <fullName>Belo Horizonte</fullName>
                </value>
                <value>
                    <fullName>Bengaluru</fullName>
                </value>
                <value>
                    <fullName>Berkeley</fullName>
                </value>
                <value>
                    <fullName>Berlin</fullName>
                </value>
                <value>
                    <fullName>Bethesda</fullName>
                </value>
                <value>
                    <fullName>Bogota</fullName>
                </value>
                <value>
                    <fullName>Bogotá</fullName>
                </value>
                <value>
                    <fullName>Boston</fullName>
                </value>
                <value>
                    <fullName>Boulder</fullName>
                </value>
                <value>
                    <fullName>Brasilia</fullName>
                </value>
                <value>
                    <fullName>Brisbane</fullName>
                </value>
                <value>
                    <fullName>Brussels</fullName>
                </value>
                <value>
                    <fullName>Budapest</fullName>
                </value>
                <value>
                    <fullName>Buenos Aires</fullName>
                </value>
                <value>
                    <fullName>Busan</fullName>
                </value>
                <value>
                    <fullName>Calgary</fullName>
                </value>
                <value>
                    <fullName>Cali</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Account_Queue__c.object
<CustomObject>
    <fields>
        <fullName>Account_Record_Type__c</fullName>
        <description>This will filter out the account for which we need to force the account assignment rule.</description>
        <label>Account Record Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Consumer</fullName>
                </value>
                <value>
                    <fullName>Mid Market</fullName>
                    <default>true</default>
                    <label>Mid Market</label>
                </value>
                <value>
                    <fullName>Enterprise Solutions</fullName>
                </value>
                <value>
                    <fullName>Referral</fullName>
                </value>
                <value>
                    <fullName>Partnership</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_Member_Active__c</fullName>
        <description>This field will ensure whether the member is active or not.</description>
        <formula>Member__r.IsActive</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Member Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Queue_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>This field will ensure that this record can be used for account assignment rule.</description>
        <label>Is Queue Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <description>This field will hep us to match to account for Account assignment.</description>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Amsterdam</fullName>
                </value>
                <value>
                    <fullName>Atlanta</fullName>
                </value>
                <value>
                    <fullName>Austin</fullName>
                </value>
                <value>
                    <fullName>Baltimore</fullName>
                </value>
                <value>
                    <fullName>Bangkok</fullName>
                </value>
                <value>
                    <fullName>Barranquilla</fullName>
                </value>
                <value>
                    <fullName>Be'er Sheva</fullName>
                </value>
                <value>
                    <fullName>Beijing</fullName>
                </value>
                <value>
                    <fullName>Bengaluru</fullName>
                </value>
                <value>
                    <fullName>Berkeley</fullName>
                </value>
                <value>
                    <fullName>Berlin</fullName>
                </value>
                <value>
                    <fullName>Bogota</fullName>
                </value>
                <value>
                    <fullName>Boston</fullName>
                </value>
                <value>
                    <fullName>Boulder</fullName>
                </value>
                <value>
                    <fullName>Buenos Aires</fullName>
                </value>
                <value>
                    <fullName>Charlotte</fullName>
                </value>
                <value>
                    <fullName>Chicago</fullName>
                </value>
                <value>
                    <fullName>Dallas</fullName>
                </value>
                <value>
                    <fullName>Delhi</fullName>
                </value>
                <value>
                    <fullName>Denver</fullName>
                </value>
                <value>
                    <fullName>Detroit</fullName>
                </value>
                <value>
                    <fullName>Dublin</fullName>
                </value>
                <value>
                    <fullName>Fort Worth</fullName>
                </value>
                <value>
                    <fullName>Frankfurt</fullName>
                </value>
                <value>
                    <fullName>Guangzhou</fullName>
                </value>
                <value>
                    <fullName>Hamburg</fullName>
                </value>
                <value>
                    <fullName>Herzliya</fullName>
                </value>
                <value>
                    <fullName>Ho Chi Minh City</fullName>
                </value>
                <value>
                    <fullName>Hong Kong</fullName>
                </value>
                <value>
                    <fullName>Houston</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is a lookup of the user and will be used in account assignment use case as an owner.</description>
        <label>Member</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_Queues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Portfolio__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Portfolio</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Account Queues</relationshipLabel>
        <relationshipName>Account_Queues</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>This object will be used in Account assignment use case.</description>
    <label>Account Queue</label>
    <nameField>
        <displayFormat>Queue-{00000}</displayFormat>
        <label>Queue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Queues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Market__c.object
<CustomObject>
    <fields>
        <fullName>Portfolio__c</fullName>
        <description>Display name for portfolio, something user friendly to end users</description>
        <inlineHelpText>Display name (text)</inlineHelpText>
        <label>Portfolio Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <description>We are introducing new object Market so that same building can fall under multiple Markets as per Marketing department requirement.</description>
    <label>Portfolio</label>
    <nameField>
        <label>Portfolio</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portfolios</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/AccountQueueTriggerHandler.cls
/************************************************************************************************************************************
   	Author 		: Dipak Pawar
   	Description : Logic of AccountQueueTriggers.

   	History		:
	----------------------------------------------------------------------------------------------------------------------------------
	VERSION		DATE				AUTHOR				DETAIL
	1			26 April 2017		Dipak Pawar 		Initial Developement
**************************************************************************************************************************************/

public with sharing class AccountQueueTriggerHandler extends ITriggerHandler{
    public AccountQueueTriggerHandler(){
        super('Account_Queue__c');
    }
    
    /************************************************************************************************************************************
         Author 			: Pragalbha Mahajan
         Description 		: This method overrides before insert method from ITriggerHander which will control the execution flow.
         Last Modified Date	: 02 February 2018
         Last Modified By	: Pragalbha Mahajan (added Comment)
	**************************************************************************************************************************************/
    public override void BeforeInsert(List<SObject> listNewItems){
        if(TriggerSettings.mappedField.AccountQueue_RestrictDuplicateRecordsForAccountAssignment){
            restrictDuplicateRecordsForAccountAssignment((List<Account_Queue__c>)listNewItems,null,null,null);
        }
    }
    
    /************************************************************************************************************************************
    	Author 				: Pragalbha Mahajan
        Description 		: This method overrides before update method from ITriggerHander which will control the execution flow.
        Last Modified Date	: 02 February 2018
        Last Modified By	: Pragalbha Mahajan (added Comment)
	**************************************************************************************************************************************/
    public override void BeforeUpdate(List<SObject> listNewItems, Map<Id, SObject> mapNewItems, List<SObject> listOldItems, Map<Id, SObject> mapOldItems){
        if(TriggerSettings.mappedField.AccountQueue_RestrictDuplicateRecordsForAccountAssignment){
            restrictDuplicateRecordsForAccountAssignment((List<Account_Queue__c>) listNewItems, (Map<Id, Account_Queue__c>) mapNewItems, (List<Account_Queue__c>) listOldItems, (Map<Id, Account_Queue__c>) mapOldItems);
        }
    }
    
	/************************************************************************************************************************************
  		Author 				: Dipak Pawar
        Description 		: Restrict duplicate records for account assignment based on Account_Record_Type__c, Market__c and Member__c of AccountQueue.
        Last Modified Date	: 26,April 2017
        Last Modified By	: Dipak Pawar
	**************************************************************************************************************************************/
    public static void restrictDuplicateRecordsForAccountAssignment(List<Account_Queue__c> listNewItems, Map<Id, Account_Queue__c> mapNewItems, List<Account_Queue__c> listOldItems, Map<Id, Account_Queue__c> mapOldItems) {     
        Debug.log('Trigger.New :: '+(List<Account_Queue__c>)listNewItems);
        Set<String> setAccountRecordTypes = new Set<String>();
        Set<String> setPortfolios = new Set<String>();
        Set<String> setMembers = new Set<String>();
        Map<String, Account_Queue__c> mapAccountQueue = new Map<String, Account_Queue__c>();
        Map<Id, Account_Queue__c> triggerOldMap = new Map<Id, Account_Queue__c>();
        if(Trigger.IsUpdate) {
            triggerOldMap = (Map<Id, Account_Queue__c>)mapOldItems;
        }
        for(Account_Queue__c accountQueueRec : (List<Account_Queue__c>)listNewItems) {
            if(Trigger.IsInsert) {
                setAccountRecordTypes.add(accountQueueRec.Account_Record_Type__c);
                setPortfolios.add(accountQueueRec.Portfolio__c);
                setMembers.add(accountQueueRec.Member__c);
            } else if(Trigger.IsUpdate) {
                if((accountQueueRec.Is_Queue_Active__c != null && accountQueueRec.Is_Queue_Active__c != triggerOldMap.get(accountQueueRec.Id).Is_Queue_Active__c) || (accountQueueRec.Account_Record_Type__c != null && accountQueueRec.Account_Record_Type__c != triggerOldMap.get(accountQueueRec.Id).Account_Record_Type__c) || (accountQueueRec.Portfolio__c != null && accountQueueRec.Portfolio__c != triggerOldMap.get(accountQueueRec.Id).Portfolio__c) || (accountQueueRec.Member__c != null && accountQueueRec.Member__c != triggerOldMap.get(accountQueueRec.Id).Member__c) ){
                    setAccountRecordTypes.add(accountQueueRec.Account_Record_Type__c);
                    setPortfolios.add(accountQueueRec.Portfolio__c);
                    setMembers.add(accountQueueRec.Member__c);
                }
            }            
        }
        Debug.log('setAccountRecordTypes :: '+setAccountRecordTypes);
        Debug.log('setPortfolios :: '+setPortfolios);
        Debug.log('setMembers :: '+setMembers);
        
        if(setAccountRecordTypes.size() > 0 && setPortfolios.size() > 0 && setMembers.size() > 0) {
            for(Account_Queue__c accountQueueRec : [SELECT Id, 
                                                    Account_Record_Type__c,
                                                    Is_Member_Active__c,
                                                    Is_Queue_Active__c,
                                                    Market__c,
                                                    Portfolio__c,
                                                    Member__c
                                                    FROM Account_Queue__c
                                                    WHERE
                                                    Account_Record_Type__c IN :setAccountRecordTypes
                                                    AND Portfolio__c IN :setPortfolios
                                                    AND Member__c IN :setMembers
                                                    AND Is_Member_Active__c =: true
                                                    AND Is_Queue_Active__c =: true
                                                   ]) {
                                                       mapAccountQueue.put(accountQueueRec.Account_Record_Type__c+'-'+accountQueueRec.Portfolio__c+'-'+accountQueueRec.Member__c, accountQueueRec);
                                                   }
            Debug.log('mapAccountQueue :: '+mapAccountQueue);
            for(Account_Queue__c accountQueueRec : (List<Account_Queue__c>)Trigger.New) {
                if(accountQueueRec.Is_Queue_Active__c && mapAccountQueue.get(accountQueueRec.Account_Record_Type__c+'-'+accountQueueRec.Portfolio__c+'-'+accountQueueRec.Member__c) != null)
                    accountQueueRec.addError('Duplicate Record found, ID:'+mapAccountQueue.get(accountQueueRec.Account_Record_Type__c+'-'+accountQueueRec.Portfolio__c+'-'+accountQueueRec.Member__c).Id);                
            } 
        }        
    }   
}