objects/Account.object
<CustomObject>
    <fields>
        <fullName>UUID__c</fullName>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>By_Pass_Campaign_Assignment__c</fullName>
        <formula>IF((BEGINS(Lead_Owner__c, "005") || BEGINS(Lead_Owner__c,"00G")),false,true)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>By Pass Campaign Assignment</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_Address__c</fullName>
        <description>Email Address From Splash</description>
        <label>Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Lead_Owner__c</fullName>
        <description>This field is used to route leads assigned to a campaign</description>
        <inlineHelpText>This field is used to route leads assigned to a campaign. Enter the user or queue ID.
See link below for regional queue list 
https://docs.google.com/spreadsheets/d/16_uqpniUGsFaqVEzxppQPy5MsaXho9xGaaiTDxW7Gw0/edit?usp=sharing</inlineHelpText>
        <label>Lead Owner</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/City__c.object
<CustomObject>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <referenceTo>State__c</referenceTo>
        <relationshipLabel>Cities</relationshipLabel>
        <relationshipName>Cities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <description>This field will store the name of the city</description>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Source_Detail__c</fullName>
        <description>This field captures the information from where the lead is coming.</description>
        <inlineHelpText>This field captures the information from where the lead is coming.</inlineHelpText>
        <label>Lead Source Detail</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UUID__c</fullName>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Journey__c.object
<CustomObject>
    <fields>
        <fullName>CampaignId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It contains related Campaign Id</description>
        <inlineHelpText>It contains related Campaign Id</inlineHelpText>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Related Campaigns</relationshipLabel>
        <relationshipName>Journeys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead_Source_Detail__c</fullName>
        <description>Details of Lead Source from where Tour was booked. e.g. specific form of the website.</description>
        <label>Lead Source Detail</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Locations_Interested__c</fullName>
        <label>Locations Interested</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>32 Village</fullName>
                </value>
                <value>
                    <fullName>AMS-Labs</fullName>
                </value>
                <value>
                    <fullName>AMS-Metropool</fullName>
                </value>
                <value>
                    <fullName>AMS-Strawinskylaan</fullName>
                </value>
                <value>
                    <fullName>AMS-Weteringschans</fullName>
                </value>
                <value>
                    <fullName>ARC-Andres Arguibel 2860</fullName>
                </value>
                <value>
                    <fullName>ARC-Avenida Corrientes 800</fullName>
                </value>
                <value>
                    <fullName>ARC-Ing. Enrique Butty 275</fullName>
                </value>
                <value>
                    <fullName>ARC-Libertador 1000</fullName>
                </value>
                <value>
                    <fullName>ARC- Torre Bellini</fullName>
                </value>
                <value>
                    <fullName>ARN-Urban Escape</fullName>
                </value>
                <value>
                    <fullName>ATL-1372 Peachtree</fullName>
                </value>
                <value>
                    <fullName>ATL-3280 Peachtree Road NE</fullName>
                </value>
                <value>
                    <fullName>ATL-Colony Square</fullName>
                </value>
                <value>
                    <fullName>ATL-Tower Place</fullName>
                </value>
                <value>
                    <fullName>AUS-Congress</fullName>
                </value>
                <value>
                    <fullName>AUS-Domain</fullName>
                </value>
                <value>
                    <fullName>AUS-Labs</fullName>
                </value>
                <value>
                    <fullName>AUS-University Park</fullName>
                </value>
                <value>
                    <fullName>AUS-Westview</fullName>
                </value>
                <value>
                    <fullName>AUS-WeWork 801 Barton Springs</fullName>
                </value>
                <value>
                    <fullName>BCN-Diagonal 444</fullName>
                </value>
                <value>
                    <fullName>BHZ-Boulevard Shopping</fullName>
                </value>
                <value>
                    <fullName>BKK-Asia Centre</fullName>
                </value>
                <value>
                    <fullName>BKK-T-One Building</fullName>
                </value>
                <value>
                    <fullName>BKN-109 S 5th St</fullName>
                </value>
                <value>
                    <fullName>BKN-Brooklyn Heights</fullName>
                </value>
                <value>
                    <fullName>BKN-Dumbo Heights (Prospect)</fullName>
                </value>
                <value>
                    <fullName>BKN-Dumbo Heights (Sands)</fullName>
                </value>
                <value>
                    <fullName>BKN-Montague St</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Primary Contact of the Journey</description>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Journeys</relationshipLabel>
        <relationshipName>Journeys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>If journey is for a Lead this will be the Primary Lead. Only Primary Contact or Primary Lead can be specified not both.</description>
        <label>Primary Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Journeys</relationshipLabel>
        <relationshipName>Journeys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UUID__c</fullName>
        <description>Globally Unique Identifier of the record used by all systems at WeWork</description>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <description>We are going to use this object as Sales Journey of the user. Which begins when a person shows interest in one of our products or we decide to reach out to show our products.</description>
    <label>Journey</label>
    <nameField>
        <label>Customer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Journeys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Campaign_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign Id</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City (Custom)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Amsterdam</fullName>
                </value>
                <value>
                    <fullName>Austin</fullName>
                </value>
                <value>
                    <fullName>Boston</fullName>
                </value>
                <value>
                    <fullName>Brooklyn</fullName>
                </value>
                <value>
                    <fullName>Chicago</fullName>
                </value>
                <value>
                    <fullName>Israel</fullName>
                </value>
                <value>
                    <fullName>London</fullName>
                </value>
                <value>
                    <fullName>Los Angeles</fullName>
                </value>
                <value>
                    <fullName>Miami</fullName>
                </value>
                <value>
                    <fullName>New York</fullName>
                </value>
                <value>
                    <fullName>San Francisco</fullName>
                </value>
                <value>
                    <fullName>Seattle</fullName>
                </value>
                <value>
                    <fullName>Washington</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Lead_Assignment_Stage__c</fullName>
        <inlineHelpText>This field will keep track of Lead/Journey Hold Back</inlineHelpText>
        <label>Lead Assignment Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>6</fullName>
                    <label>Hold queue</label>
                </value>
                <value>
                    <fullName>11</fullName>
                    <label>Assignments Run</label>
                </value>
                <value>
                    <fullName>1000</fullName>
                    <label>Bypass Hold Back</label>
                </value>
                <value>
                    <fullName>Lead Converted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Lead_Source_Detail__c</fullName>
        <label>Lead Source Detail</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Office_Type__c</fullName>
        <label>Office Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Shared Desk</fullName>
                </value>
                <value>
                    <fullName>Lounge Membership</fullName>
                </value>
                <value>
                    <fullName>Daily Desk</fullName>
                </value>
                <value>
                    <fullName>Hot desk</fullName>
                </value>
                <value>
                    <fullName>Dedicated Desk</fullName>
                </value>
                <value>
                    <fullName>Private 1 Person</fullName>
                </value>
                <value>
                    <fullName>Private 2 Person</fullName>
                </value>
                <value>
                    <fullName>Private 3 Person</fullName>
                </value>
                <value>
                    <fullName>Private 4 Person</fullName>
                </value>
                <value>
                    <fullName>Private 5 Person</fullName>
                </value>
                <value>
                    <fullName>Private 6 Person</fullName>
                </value>
                <value>
                    <fullName>Private 8 Person</fullName>
                </value>
                <value>
                    <fullName>Private 10 Person</fullName>
                </value>
                <value>
                    <fullName>Private 10 Person+</fullName>
                </value>
                <value>
                    <fullName>Commons</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/MetadataSetting__mdt.object
<CustomObject>
    <fields>
        <fullName>Data__c</fullName>
        <description>This is used to store new Journey Creation criteria</description>
        <inlineHelpText>Journey Creation criteria</inlineHelpText>
        <label>Data</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <description>This is used to filter for Journey creation criteria.</description>
    <label>MetadataSetting</label>
    <pluralLabel>MetadataSettings</pluralLabel>
</CustomObject>

classes/LeadRoutingHelperTest.cls
/*****************************************************************************************************************************
  Yet to do
  1. Modularize the code into multiple method calls.
  2. Put comments for each method call to establish references.
  3. Get it reviewed from the peer team.
******************************************************************************************************************************
    Author      :  Krishana Tupe  
    Description :  This class contains the test methods of LeadRoutingHelper class.
					It will covers the LeadConverterHelper.manageLead(lstLeads, payload) methods and JourneyHelperUtility class.
    History     :  --
      
    ----------------------------------------------------------------------------------------------------------------------------------
    VERSION                 DATE            ISSUE       AUTHOR                          DETAIL
    1                       26 Nov 2018      -     		Krishana Tupe                   Initial Developement    
******************************************************************************************************************************/
@isTest
public class LeadRoutingHelperTest {
    

    public static string strHoldBackQueueId;
    static {
        if(String.isBlank(strHoldBackQueueId)){
            MetadataSetting__mdt objJourneyCreationMDT = Settings.getMetadataSettingByDevName('Hold_Back_Queue');  
            strHoldBackQueueId = String.isNotBlank(objJourneyCreationMDT.Data__c) ? objJourneyCreationMDT.Data__c : null;      
        }        
    }
    
 /************************************************************************************************************************************
        Author              :   Krishana Tupe
        Description         :   This method is to get user record								
      	Created Date  		:   27 Nov 2018        
 *************************************************************************************************************************************/
    public static User getUser(String strEmail, String strUserName, String profileId){
        return new User(Alias = 'testU', Email = strEmail, EmailEncodingKey='UTF-8', LastName='User', LanguageLocaleKey='en_US', 
                        LocaleSidKey='en_US', ProfileId = profileId, IsActive = true,
                        TimeZoneSidKey='America/Los_Angeles', UserName = strUserName, CommunityNickname = TestingUtility.createUserCommunityName());
    }
    
 /************************************************************************************************************************************
        Author              :   Krishana Tupe
        Description         :   This setup method is used to create test data for LeadRoutingHelperTest class								
      	Created Date  		:   27 Nov 2018        
 *************************************************************************************************************************************/
    @TestSetup
    public static void testSetup(){
        SalesConsoleSettings.createSettings(); 
        List<User> lstUser = new List<User>();
        Profile weworkSysAdmin = [SELECT Id FROM Profile WHERE Name='WeWork System Administrator'];        
        lstUser.add(getUser('testinguser1@example.com', 'testinguser1@example.com', weworkSysAdmin.Id));
        lstUser.add(getUser('testinguser2@example.com', 'testinguser2@example.com', weworkSysAdmin.Id));
        Database.insert(lstUser);
        
        List<Campaign> lstCampaigns = new List<Campaign>();
        lstCampaigns.add(new Campaign(Name = 'Test Campaign 1', City__c = 'Chicago', State__c = 'IL', Email_Address__c = 'Building1@example.com', Type = 'Splash Event'));
        lstCampaigns.add(new Campaign(Name = 'Test Campaign 2', State__c = 'DC', City__c = 'Washington DC', Type = 'Splash Event', Email_Address__c='abc3@example.com', Lead_Owner__c =lstUser[0].Id));
        Database.insert(lstCampaigns);
    }
    
 /************************************************************************************************************************************
    Author              :   Krishana Tupe
    Description         :   This method is used to verify insert lead and Journey for Hold back flow
    Created Date  		:   26 Nov 2018   
 *************************************************************************************************************************************/
    @isTest
    public static void verifyManualLeadInsertion(){
        List<Lead> lstLeads = new List<Lead>(); 
        LeadRoutingHelperTest.getLeadRecords(lstLeads, 1, 6, null, null);
        Test.startTest();
        TestingUtility.insertListWithAssert(lstLeads); 
        Test.stopTest();
        List<Lead> lstLeadsInserted = [SELECT Id, Name, OwnerId, Lead_Assignment_Stage__c, (SELECT Id,OwnerId FROM Journeys__r) FROM Lead WHERE Id IN : lstLeads AND IsConverted = false];
        System.assertEquals(6, lstLeadsInserted.size()); 
        verifyAssertions(lstLeadsInserted, 1, UserInfo.getUserId(), '1');
    }
    
        
/************************************************************************************************************************************
        Author              :   Krishana Tupe
        Description         :   This method verifies bypass Lead insertion hold back logic 								
      	Created Date  		:   27 Nov 2018        
 *************************************************************************************************************************************/
    @isTest
    public static void verifyBypassHoldBackLeadInsertion(){
        List<Lead> lstLeads = new List<Lead>(); 
        LeadRoutingHelperTest.getLeadRecords(lstLeads, 1, 6, null, '1000');        
        Test.startTest();
        TestingUtility.insertListWithAssert(lstLeads); 
        Test.stopTest();
        List<Lead> lstLeadsInserted = [SELECT Id, Name, OwnerId, Lead_Assignment_Stage__c, (SELECT Id,OwnerId FROM Journeys__r) FROM Lead WHERE Id IN : lstLeads AND IsConverted = false];
        System.assertEquals(6, lstLeadsInserted.size()); 
        verifyAssertions(lstLeadsInserted, 1, UserInfo.getUserId(), '1000');
    }
    
 /************************************************************************************************************************************
        Author              :   Krishana Tupe
        Description         :   This method verifies common assertions							
      	Created Date  		:   27 Nov 2018        
 *************************************************************************************************************************************/
    public static void verifyAssertions(List<Lead> lstLeadsInserted, Integer journeySize, String leadOwnerId, String assgnStage){
        for(Lead objLead : lstLeadsInserted){
            System.assert(objLead.Journeys__r.size() == journeySize);
            System.assertEquals(objLead.OwnerId, leadOwnerId);
            if(journeySize != 0){
                System.assertEquals(objLead.OwnerId, objLead.Journeys__r[0].OwnerId);
            }           
            System.assertEquals(objLead.Lead_Assignment_Stage__c, assgnStage);
        }   
    }
   
  /************************************************************************************************************************************
        Author              :   Krishana Tupe
        Description         :   This method verifies Lead/journey hold back logic when lead comes from Website 								
      	Created Date  		:   27 Nov 2018        
 *************************************************************************************************************************************/
    @isTest
    public static void verifyLeadInsertionHoldBack(){
        List<Lead> lstLeads = new List<Lead>(); 
        LeadRoutingHelperTest.getLeadRecords(lstLeads, 1, 6, null, null);
        RESTInboundLeadAPIHelper.isLeadFromWeb = true;
        Test.startTest();
        TestingUtility.insertListWithAssert(lstLeads); 
        Test.stopTest();
        List<Lead> lstLeadsInserted = [SELECT Id, Name, OwnerId, Lead_Assignment_Stage__c, (SELECT Id, OwnerId FROM Journeys__r) FROM Lead WHERE Id IN : lstLeads AND IsConverted = false];
        System.assertEquals(6, lstLeadsInserted.size()); 
        verifyAssertions(lstLeadsInserted, 1, Id.valueOf(strHoldBackQueueId), '6');
    }
    
 /************************************************************************************************************************************
        Author              :   Krishana Tupe
        Description         :   This method verifies Lead/journey hold back logic when lead comes from Website  with campaign								
      	Created Date  		:   27 Nov 2018        
 *************************************************************************************************************************************/
    @isTest
    public static void verifyLeadInsertionWithCampaign(){
        List<Lead> lstLeads = new List<Lead>(); 
        List<Campaign> lstCampaigns = [SELECT Id, Lead_Owner__c, By_Pass_Campaign_Assignment__c FROM Campaign];      
        LeadRoutingHelperTest.getLeadRecords(lstLeads, 1, 3, lstCampaigns[0].Id, null);
        LeadRoutingHelperTest.getLeadRecords(lstLeads, 4, 6, lstCampaigns[1].Id, null);
        RESTInboundLeadAPIHelper.isLeadFromWeb = true;
        Test.startTest();
        TestingUtility.insertListWithAssert(lstLeads); 
        Test.stopTest();
        List<Lead> lstLeadsInserted = [SELECT Id, Name, OwnerId, Campaign_Id__c, Lead_Assignment_Stage__c, Lead_Source_Detail__c, (SELECT Id, OwnerId FROM Journeys__r) FROM Lead WHERE Id IN : lstLeads AND IsConverted = false];
        System.assertEquals(6, lstLeadsInserted.size()); 
        for(Lead objLead : lstLeadsInserted){
            System.assert(objLead.Journeys__r.size() == 1);
            System.assertEquals(objLead.Lead_Assignment_Stage__c, '1');
            System.assertNotEquals(objLead.OwnerId, Id.valueOf(strHoldBackQueueId));   
            System.assertNotEquals(objLead.OwnerId, UserInfo.getUserId());  
            System.assertEquals(objLead.OwnerId, objLead.Journeys__r[0].OwnerId);
            if(objLead.Lead_Source_Detail__c == 'TEST LEAD SOURCE 4'){
                System.assertEquals(objLead.OwnerId, objLead.Journeys__r[0].OwnerId);  
                System.assertEquals(objLead.OwnerId, objLead.Journeys__r[0].OwnerId); 
                System.assertEquals(objLead.Campaign_Id__c, lstCampaigns[1].Id); 
                System.assertEquals(objLead.OwnerId, lstCampaigns[1].Lead_Owner__c); 
            }else{
                System.assertEquals(objLead.Campaign_Id__c, lstCampaigns[0].Id);      
            }
        }
    }
   
 /************************************************************************************************************************************
        Author              :   Krishana Tupe
        Description         :   This method verifies Lead/journey hold back logic when duplicate lead comes from Website  without campaign								
      	Created Date  		:   27 Nov 2018        
 *************************************************************************************************************************************/
    @isTest
    public static void verifyDuplicateLeadInsertionWithoutCampaign(){
        List<Lead> lstLeads = new List<Lead>();
        LeadRoutingHelperTest.getLeadRecords(lstLeads, 1, 3, null, null);
        RESTInboundLeadAPIHelper.isLeadFromWeb = true;       
        TestingUtility.insertListWithAssert(lstLeads);
        List<Lead> lstLeadsInserted = [SELECT Id, Name, OwnerId, Campaign_Id__c, Lead_Assignment_Stage__c, Lead_Source_Detail__c, (SELECT Id, OwnerId FROM Journeys__r) FROM Lead WHERE Id IN : lstLeads AND IsConverted = false];
        System.assertEquals(3, lstLeadsInserted.size()); 
        lstLeads.clear();        
        LeadRoutingHelperTest.getLeadRecords(lstLeads, 1, 3, null, null);
        Test.startTest();
        Database.insert(lstLeads);
        Test.stopTest();        
        List<Lead> lstDuplicateLeadsInserted = [SELECT Id, Name, OwnerId, Lead_Assignment_Stage__c, (SELECT Id, OwnerId FROM Journeys__r) FROM Lead WHERE IsConverted = false];
        System.assertEquals(6, lstDuplicateLeadsInserted.size()); 
        for(Integer iIndex = 0; iIndex < lstDuplicateLeadsInserted.size(); iIndex++){
            Lead objLead = lstDuplicateLeadsInserted[iIndex];
            System.assertEquals(objLead.OwnerId, Id.valueOf(strHoldBackQueueId));            
            System.assertEquals(objLead.Lead_Assignment_Stage__c, '6');
            if(iIndex <= 2){
                System.assertEquals(objLead.Journeys__r[0].OwnerId, Id.valueOf(strHoldBackQueueId));
                System.assert(objLead.Journeys__r.size() == 1);
            }else{
                System.assert(objLead.Journeys__r.size() == 0);
            } 
        }
    }
    
/************************************************************************************************************************************
        Author              :   Krishana Tupe
        Description         :   This method verifies Lead/journey hold back logic when lead comes from Website and contact exist								
      	Created Date  		:   27 Nov 2018        
 *************************************************************************************************************************************/
    @isTest
    public static void verifyHoldBackForExistingContact(){
        Map<String, sObject> mapLeadContactData = getExistingContactData(true, null);
        Lead objLead = (Lead)mapLeadContactData.get('lead');
        Contact objContact = (Contact)mapLeadContactData.get('contact');
        List<Lead> lstDuplicateLeadsInserted = [SELECT Id, Name, OwnerId, Lead_Assignment_Stage__c, (SELECT Id, OwnerId FROM Journeys__r) FROM Lead WHERE Id =: objLead.Id AND IsConverted = false];
        System.assertEquals(1, lstDuplicateLeadsInserted.size()); 
        verifyAssertions(lstDuplicateLeadsInserted, 0, Id.valueOf(strHoldBackQueueId), '6');
        Contact objContactInserted = [SELECT Id, Name, OwnerId, (SELECT Id, OwnerId FROM Journeys__r) FROM Contact WHERE Id =: objContact.Id];
        System.assertEquals(objContactInserted.OwnerId, UserInfo.getUserId());
        System.assertEquals(1, objContactInserted.Journeys__r.size());
    }
   
    /************************************************************************************************************************************
        Author              :   Krishana Tupe
        Description         :   This method inserts the contact and Lead in the system								
      	Created Date  		:   27 Nov 2018        
 *************************************************************************************************************************************/
    public static Map<String, sObject> getExistingContactData(Boolean isFromWeb, string campaignId){
        Account objAccount = new Account(name = 'Test Account1 org', UUID__c = 'testAccount1UUID1');
        TestingUtility.insertWithAssert(objAccount);
        Contact objContact = new Contact(AccountId = objAccount.Id, LastName = 'Test Contact 1', Email = 'johndoe1582018_1@example.com');
        TestingUtility.insertWithAssert(objContact);
        Lead objLead = new Lead(LeadSource='WeWork.com', Lead_Source_Detail__c='TEST LEAD SOURCE', LastName = 'Doe', FirstName = 'John', Email = 'johndoe1582018_1@example.com', Office_Type__c = 'Daily Desk', Status = 'Open', Locations_Interested__c = 'Test Building Tour', Company = 'Enzigma ltd', Generate_Journey__c = true, Number_of_Full_Time_Employees__c = 15);        
        if(String.isNotBlank(campaignId)){
            objLead.Campaign_Id__c =  campaignId; 
        }
        if(isFromWeb){
            RESTInboundLeadAPIHelper.isLeadFromWeb = true;   
        }
        Test.startTest();
        TestingUtility.insertWithAssert(objLead);
        Test.stopTest(); 
        return new Map<String, sObject>{'lead' => objLead, 'contact' => objContact};
    }
    
    /************************************************************************************************************************************
        Author              :   Krishana Tupe
        Description         :   This method verifies by pass Lead/journey hold back logic when lead created manually and contact exist								
      	Created Date  		:   27 Nov 2018        
 *************************************************************************************************************************************/
    @isTest
    public static void verifyBypassHoldBackForExistingContact(){
        Map<String, sObject> mapLeadContactData = getExistingContactData(false, null);
        Lead objLead = (Lead)mapLeadContactData.get('lead');
        Contact objContact = (Contact)mapLeadContactData.get('contact');
        List<Lead> lstDuplicateLeadsInserted = [SELECT Id, Name, OwnerId, Lead_Assignment_Stage__c, (SELECT Id, OwnerId FROM Journeys__r) FROM Lead WHERE Id =: objLead.Id AND IsConverted = true];
        System.assertEquals(1, lstDuplicateLeadsInserted.size());      
        Contact objContactInserted = [SELECT Id, Name, OwnerId, (SELECT Id, OwnerId FROM Journeys__r) FROM Contact WHERE Id =: objContact.Id];
        System.assertEquals(objContactInserted.OwnerId, UserInfo.getUserId());
        System.assertEquals(1, objContactInserted.Journeys__r.size());
        System.assertEquals(objContactInserted.Journeys__r[0].OwnerId, UserInfo.getUserId());
    }
    
 /************************************************************************************************************************************
        Author              :   Krishana Tupe
        Description         :   This method verifies Lead/journey hold back logic when lead comes from Website with campaign and contact exist								
      	Created Date  		:   27 Nov 2018        
 *************************************************************************************************************************************/
    @isTest
    public static void verifyLeadExistingContactWithCampaign(){
        List<Campaign> lstCampaigns = [SELECT Id, Lead_Owner__c, By_Pass_Campaign_Assignment__c FROM Campaign];       
        Map<String, sObject> mapLeadContactData = getExistingContactData(true, lstCampaigns[1].Id);     
        Lead objLead = (Lead)mapLeadContactData.get('lead');
        Contact objContact = (Contact)mapLeadContactData.get('contact');
        List<Lead> lstDuplicateLeadsInserted = [SELECT Id, Name, OwnerId, Lead_Assignment_Stage__c, (SELECT Id, OwnerId FROM Journeys__r) FROM Lead WHERE Id =: objLead.Id AND IsConverted = true];
        System.assertEquals(1, lstDuplicateLeadsInserted.size()); 
        verifyAssertions(lstDuplicateLeadsInserted, 0, lstCampaigns[1].Lead_Owner__c, 'Lead Converted');
        Contact objContactInserted = [SELECT Id, Name, OwnerId, (SELECT Id, OwnerId FROM Journeys__r) FROM Contact WHERE Id =: objContact.Id];
        System.assertEquals(objContactInserted.OwnerId, UserInfo.getUserId());
        System.assertEquals(1, objContactInserted.Journeys__r.size());
        System.assertEquals(lstCampaigns[1].Lead_Owner__c, objContactInserted.Journeys__r[0].OwnerId);        
    }
    
/************************************************************************************************************************************
        Author              :   Krishana Tupe
        Description         :   This method is used to create the lead records data 
      	Created Date  		:   27 Nov 2018        
 *************************************************************************************************************************************/
    public static void getLeadRecords(List<Lead> lstLeads, Integer initialValue, Integer finalValue, String strCampaignId, String assignStage){      
        for(Integer iIndex = initialValue; iIndex <= finalValue; iIndex++){ 
            Lead objLead = new Lead(LeadSource='WeWork.com', Lead_Source_Detail__c='TEST LEAD SOURCE '+initialValue, LastName = 'Doe'+iIndex, FirstName = 'John', Email = 'johndoe1582018_'+iIndex+'@example.com', Office_Type__c = 'Daily Desk', Status = 'Open', Locations_Interested__c = 'Test Building Tour', Company = 'Enzigma ltd', Generate_Journey__c = true, Number_of_Full_Time_Employees__c = 15);
            if(String.isNotBlank(strCampaignId)){
                objLead.Campaign_Id__c = strCampaignId; 
            }
            if(String.isNotBlank(assignStage)){
                objLead.Lead_Assignment_Stage__c = assignStage; 
            }
            lstLeads.add(objLead); 
        }
    }
    
    /************************************************************************************************************************************
        Author              :   Pragalbha Mahajan
        Description         :   This method is used to verify delete leads
      	Created Date  		:   5 Dec 2018        
    *************************************************************************************************************************************/
    @isTest
    public static void verifyDeleteLeads(){
        List<Lead> lstLeads = new List<Lead>();
        Lead objLead = new Lead(LeadSource='WeWork.com', Lead_Source_Detail__c='TEST LEAD SOURCE ', LastName = 'Doe', FirstName = 'John', Email = 'johndoe2018@example.com', Office_Type__c = 'Daily Desk', Status = 'Open', Locations_Interested__c = 'Test Building Tour', Company = 'Enzigma ltd', Generate_Journey__c = true, Number_of_Full_Time_Employees__c = 15);
        lstLeads.add(objLead);
        Lead objLead1 = new Lead(LeadSource='WeWork.com', Lead_Source_Detail__c='TEST LEAD SOURCE ', LastName = 'Doe2', FirstName = 'John', Email = 'johndoe2018@example.com', Office_Type__c = 'Daily Desk', Status = 'Open', Locations_Interested__c = 'Test Building Tour', Company = 'Enzigma ltd', Generate_Journey__c = true, Number_of_Full_Time_Employees__c = 5);
        lstLeads.add(objLead1);       
        Test.startTest();
        TestingUtility.insertListWithAssert(lstLeads); 
        Test.stopTest();      
        List<Lead> lstLeadsInserted = [SELECT Id, Name, Email, OwnerId, Lead_Assignment_Stage__c, IsConverted, Number_of_Full_Time_Employees__c FROM Lead WHERE Id IN : lstLeads];
        System.assertEquals(1, lstLeadsInserted.size());
        System.assertEquals(UserInfo.getUserId(), lstLeadsInserted[0].OwnerId);
    }
    
    /************************************************************************************************************************************
        Author              :   Pragalbha Mahajan
        Description         :   This method is used to verify delete leads
      	Created Date  		:   5 Dec 2018        
    *************************************************************************************************************************************/
    @isTest
    public static void verifyDeleteLeadsWithoutJourney(){        
        List<Lead> lstLeads = new List<Lead>();
        List<Map<String, sObject>> lstJourneyParents = new List<Map<String, sObject>>();
        List<Id> lstLeadsToDelete = new List<Id>();
        List<CampaignMember> lstCampaignMembers = new List<CampaignMember>();
        Lead objLead = new Lead(LeadSource='WeWork.com', Lead_Source_Detail__c='TEST LEAD SOURCE ', LastName = 'Tie', FirstName = 'John', Email = 'johntie2018@example.com', Office_Type__c = 'Daily Desk', Status = 'Open', Locations_Interested__c = 'Test Building Tour', Company = 'Enzigma ltd', Generate_Journey__c = false, Number_of_Full_Time_Employees__c = 15);
        lstLeads.add(objLead);
        Lead objLead1 = new Lead(LeadSource='WeWork.com', Lead_Source_Detail__c='TEST LEAD SOURCE ', LastName = 'Tie2', FirstName = 'John', Email = 'johntie2018@example.com', Office_Type__c = 'Daily Desk', Status = 'Open', Locations_Interested__c = 'Test Building Tour', Company = 'Enzigma ltd', Generate_Journey__c = false, Number_of_Full_Time_Employees__c = 5);
        lstLeads.add(objLead1);       
        TestingUtility.insertListWithAssert(lstLeads); 
        List<Lead> lstLeadsInserted = [SELECT Id, Name, Email, OwnerId, Lead_Assignment_Stage__c, IsConverted, Number_of_Full_Time_Employees__c, Generate_Journey__c, Campaign_Id__c, (SELECT Id, OwnerId FROM Journeys__r) FROM Lead WHERE Id IN : lstLeads];
        for(Lead deleteLead : lstLeadsInserted){
            lstLeadsToDelete.add(deleteLead.Id);
        }
        LeadRoutingHelper.manageLeadRelatedRecords(true, lstJourneyParents, lstLeadsToDelete, lstCampaignMembers, null);       
        lstLeadsInserted = [SELECT Id, Name, Email, OwnerId, Lead_Assignment_Stage__c, IsConverted, Number_of_Full_Time_Employees__c, Generate_Journey__c, Campaign_Id__c, (SELECT Id, OwnerId FROM Journeys__r) FROM Lead WHERE Id IN : lstLeads];
        System.assertEquals(1, lstLeadsInserted.size());       
        System.assertEquals(0, lstLeadsInserted[0].Journeys__r.size());
    }
}