objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <description>This is Picklist which Contains three values
1. Org : It is Main account in hierarchy which is Parent Account of Sales And Bill.
2. Sales: One Sales Account may contain multiple Bill Or Sales Account and It is Under Org Account in hierarchy
3. Bill: Bill Account is under Sales or Org. It never child of Bill Account.
4. ' '(Blank) : It is like Bill type which is under Sales or Org.</description>
        <inlineHelpText>This Picklist is used to determine the account type.</inlineHelpText>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Org</fullName>
                    <default>true</default>
                    <label>Org</label>
                </value>
                <value>
                    <fullName>Sales</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cleansed_Account_Name__c</fullName>
        <description>This field is used to save cleansed Account Name</description>
        <label>Cleansed Account Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cleansed_Unomy_Company_Name__c</fullName>
        <description>This field is used to save cleansed unomy company name</description>
        <label>Cleansed Unomy Company Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Interested_in_Number_of_Desks_Min__c</fullName>
        <label>Interested in Number of Desks Min</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Interested_in_Number_of_Desks__c</fullName>
        <label>Interested in Number of Desk(s)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unomy_Company_ID__c</fullName>
        <externalId>true</externalId>
        <label>Unomy Company ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unomy_Company_Name__c</fullName>
        <label>Unomy Company Name</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Building__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Buildings</relationshipLabel>
        <relationshipName>Buildings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Building</label>
    <nameField>
        <label>Building</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <formula>text(Account.Type)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cleansed_Company_Name__c</fullName>
        <externalId>true</externalId>
        <label>Cleansed Company Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cleansed_Unomy_Company_Name__c</fullName>
        <description>This field contains Cleansed Unomy Company Name value</description>
        <label>Cleansed Unomy Company Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Email_Domain__c</fullName>
        <formula>RIGHT(Email,LEN(Email)-FIND('@',Email))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Email Domain</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Interested_in_Number_of_Desks__c</fullName>
        <label>Interested in Number of Desk(s)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Lead_Source_Detail__c</fullName>
        <description>This field captures the information from where the lead is coming.</description>
        <inlineHelpText>This field captures the information from where the lead is coming.</inlineHelpText>
        <label>Lead Source Detail</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <label>Product Line</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>WeWork</fullName>
                </value>
                <value>
                    <fullName>WeLive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Referrer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referrer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unomy_Company_ID__c</fullName>
        <label>Unomy Company ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unomy_Company_Name__c</fullName>
        <label>Unomy Company Name</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field contains the value of Org account for which lead is associated.</description>
        <inlineHelpText>Enter the name of the organization associated with this new Opportunity. If an existing organization does not appear when typing the name, click "New Organization" to create a new one.</inlineHelpText>
        <label>Organization</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Account.Account_Type__c</field>
                <operation>equals</operation>
                <value>Org</value>
            </filterItems>
            <filterItems>
                <field>Account.Account_Type__c</field>
                <operation>equals</operation>
                <value>Sales</value>
            </filterItems>
            <infoMessage>Leads can only be associated to accounts havinng account type 'Org'.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads (Account)</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Building_Interested_In__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Building Interested In</label>
        <referenceTo>Building__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>By_Pass_Journey_Creation_Criteria__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If lead is creating from Journey Importer (Kickbox) then while uploading the file if user check Generate Journey. Then we will check it as true and while creating journey we not check Journey Creation Criteria of the lead source and lead source details and user and queue.</description>
        <inlineHelpText>If lead is creating from Journey Importer (Kickbox) then while uploading the file if user check Generate Journey. Then we will check it as true and while creating journey we not check Journey Creation Criteria of the lead source and lead source details</inlineHelpText>
        <label>By Pass Journey Creation Criteria</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Campaign_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign Id</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cleansed_Company_Name__c</fullName>
        <label>Cleansed Company Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cleansed_Unomy_Company_Name__c</fullName>
        <description>Cleansed Unomy Company Name value</description>
        <label>Cleansed Unomy Company Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Email_Domain__c</fullName>
        <formula>RIGHT(Email,LEN(Email)-FIND('@',Email))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Email Domain</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Generate_Journey__c</fullName>
        <defaultValue>true</defaultValue>
        <description>If this check box is checked , create journey for converted lead</description>
        <label>Generate Journey</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Interested_in_Number_of_Desks_Min__c</fullName>
        <description>This will be updated from inbound lead api with desks_interested_min</description>
        <label>Interested in Number of Desks Min</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Interested_in_Number_of_Desks__c</fullName>
        <label>Interested in Number of Desk(s)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Lead_Source_Detail__c</fullName>
        <label>Lead Source Detail</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Locations_Interested__c</fullName>
        <label>Locations Interested</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AMS-Labs</fullName>
                </value>
                <value>
                    <fullName>AMS-Metropool</fullName>
                </value>
                <value>
                    <fullName>AMS-Strawinskylaan</fullName>
                </value>
                <value>
                    <fullName>AMS-Weteringschans</fullName>
                </value>
                <value>
                    <fullName>ARC-Avenida Corrientes 800</fullName>
                </value>
                <value>
                    <fullName>ARC-Ing. Enrique Butty 275</fullName>
                </value>
                <value>
                    <fullName>ARC-Libertador 1000</fullName>
                </value>
                <value>
                    <fullName>ARG- Torre Bellini</fullName>
                </value>
                <value>
                    <fullName>ARN-Urban Escape</fullName>
                </value>
                <value>
                    <fullName>ATL-1372 Peachtree</fullName>
                </value>
                <value>
                    <fullName>ATL-3280 Peachtree Road NE</fullName>
                </value>
                <value>
                    <fullName>ATL-Colony Square</fullName>
                </value>
                <value>
                    <fullName>ATL-Tower Place</fullName>
                </value>
                <value>
                    <fullName>AUS-Congress</fullName>
                </value>
                <value>
                    <fullName>AUS-Domain</fullName>
                </value>
                <value>
                    <fullName>AUS-Labs</fullName>
                </value>
                <value>
                    <fullName>AUS-University Park</fullName>
                </value>
                <value>
                    <fullName>AUS-West 6th</fullName>
                </value>
                <value>
                    <fullName>AUS-Westview</fullName>
                </value>
                <value>
                    <fullName>AUS-WeWork 801 Barton Springs</fullName>
                </value>
                <value>
                    <fullName>BCN-Diagonal 444</fullName>
                </value>
                <value>
                    <fullName>BEV-Gav-Yam Negev</fullName>
                </value>
                <value>
                    <fullName>BHZ-Boulevard Shopping</fullName>
                </value>
                <value>
                    <fullName>BKK-Asia Centre</fullName>
                </value>
                <value>
                    <fullName>BKN-109 S 5th St</fullName>
                </value>
                <value>
                    <fullName>BKN-Brooklyn Heights</fullName>
                </value>
                <value>
                    <fullName>BKN-Dumbo Heights (Prospect)</fullName>
                </value>
                <value>
                    <fullName>BKN-Dumbo Heights (Sands)</fullName>
                </value>
                <value>
                    <fullName>BKN-Montague St</fullName>
                </value>
                <value>
                    <fullName>BKN-Williamsburg</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <label>Product Line</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>WeWork</fullName>
                </value>
                <value>
                    <fullName>WeLive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Referrer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This will be the contact who referred us the Lead. It can be a member, employee or a broker.</description>
        <inlineHelpText>Enter the contact who referred us the Lead. It can be a member, employee or a broker.</inlineHelpText>
        <label>Referrer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Leads (Referrer)</relationshipLabel>
        <relationshipName>ReferredLeads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unomy_Company_ID__c</fullName>
        <label>Unomy Company ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unomy_Company_Name__c</fullName>
        <label>Unomy Company Name</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/AccountSelectorControllerTest.cls
/************************************************************************************************************************************
Author 		: Sunil Bhosale
Description : This class Contains Unit Test of Account selector page functionality

History		:
----------------------------------------------------------------------------------------------------------------------------------
VERSION		DATE				    AUTHOR				DETAIL
1.0			16 october 2018			Sunil Bhosale 		Initial Developement
**************************************************************************************************************************************/

@isTest
public class AccountSelectorControllerTest {
    @TestSetup
    static void initData(){ 
        SalesConsoleSettings.createSettings();
        WeWorkValidatorHelper.createTerritoryStructure();
        Account orgAccount1 = TestingUtility.createAccount('strAccountName', false);
        orgAccount1.Account_Type__c = 'Org'; 
        orgAccount1.Unomy_Company_ID__c = 1234 ;
        orgAccount1.Unomy_Company_Name__c = 'test company1';
        orgAccount1.Cleansed_Account_Name__c = 'test company cleansed';
        Database.insert(orgAccount1, false);
        System.assert(orgAccount1.id != null);
        
        List<Lead> lstLead = new List<Lead>();
        Lead objLead = new Lead();        
        objLead.LastName = 'lastName';       
        objLead.Email = 'john.smith1610201801@example.com'; 
        objLead.Phone = '1234567891';
        objLead.Company = 'Test Company';
        objLead.Locations_Interested__c='Test Building Tour';
        objLead.Unomy_Company_ID__c = 1234 ;
        objLead.LeadSource= 'Broker';        
        objLead.Lead_Source_Detail__c = 'Broker1';
        lstLead.add(objLead);
        
        Lead objLead2 = new Lead();        
        objLead2.LastName = 'lastName2';       
        objLead2.Email = 'john.smith1610201802@example.com'; 
        objLead2.Phone = '1234567891';
        objLead2.Company = 'Test Company2';
        objLead2.Unomy_Company_ID__c = 1234 ;
        objLead2.Locations_Interested__c='Test Building Tour';
        objLead2.LeadSource= 'Broker';
        objLead2.Lead_Source_Detail__c = 'Broker1';
        lstLead.add(objLead2);  
        insert lstLead;
    }
    
    /************************************************************************************************************************************
    Author         : Sunil Bhosale
    Description     : This method verify the getMatchedAccounts (AuraEnabled) Metohd
    Created  Date    : 16 october 2018
  **************************************************************************************************************************************/    
    static testMethod void verifyGetMatchedAccounts1(){
        Lead objLead = [SELECT Id, Title , FirstName, Name, Interested_in_Number_of_Desks_Min__c,Interested_in_Number_of_Desks__c,LastName,Product_Line__c,OwnerId,Email_Domain__c,Company,Account__c,Account__r.Name,Account__r.Account_Type__c,Referrer__c,Cleansed_Unomy_Company_Name__c,Cleansed_Company_Name__c,Email,Unomy_Company_ID__c,Unomy_Company_Name__c,LeadSource,Lead_Source_Detail__c,Generate_Journey__c,By_Pass_Journey_Creation_Criteria__c,Campaign_Id__c,Building_Interested_In__c,Building_Interested_In__r.City__c,Locations_Interested__c,Number_of_Full_Time_Employees__c, Unomy_Company_Size__c, Company_Size__c, Markets_Interested__c From Lead WHERE Email = 'john.smith1610201801@example.com'];
        DatabaseResult result = AccountSelectorController.getMatchedAccounts(objLead);
        System.assertNotEquals(null, result);     
        List<Account> lstMatchedAccounts = (List<Account>)result.data;
        System.assertEquals(1, lstMatchedAccounts.size());
        
        result = AccountSelectorController.getMatchedAccounts(null);
        lstMatchedAccounts = (List<Account>)result.data;
        System.assertEquals(0, lstMatchedAccounts.size());       
    }

    /************************************************************************************************************************************
    Author         : Sunil Bhosale
    Description     : This method verify the getMatchedAccounts (AuraEnabled) Metohd
    Created  Date    : 16 october 2018
  **************************************************************************************************************************************/ 
    static testMethod void verifyGetMatchedAccounts2(){
        List<Lead> lstLeads = [SELECT LastName,Name, Cleansed_Unomy_Company_Name__c, Unomy_Company_Name__c, Cleansed_Company_Name__c, Email, Phone, Company, Unomy_Company_ID__c, Locations_Interested__c, LeadSource, Lead_Source_Detail__c FROM Lead ];
        DatabaseResult databaseResult = AccountSelectorController.getMatchedAccounts(lstLeads[0]);  
        System.assertEquals('SObject row was retrieved via SOQL without querying the requested field: Lead.Account__c', databaseResult.message);        
    }
    
    /************************************************************************************************************************************
    Author         : Krishana Tupe
    Description    : This method verify the getRelatedSalesAccounts (AuraEnabled) Metohd
    Created  Date  : 16 october 2018
  **************************************************************************************************************************************/ 
    @isTest
    public static void verifyGetRelatedSales(){
        Account accRec = [SELECT Id From Account Where Name = 'strAccountName' AND Account_Type__c = 'Org'];   
        Debug.log('accRec==>'+accRec);
        List<Account> lstSalesAccount = new List<Account>();
        for(Integer iIndex = 1; iIndex <=5 ; iIndex++){
            Account accRecforSales = TestingUtility.createAccount('SalesAccount' + iIndex, false); 
            accRecforSales.Nickname__c = 'SalesAccount' + iIndex;
            accRecforSales.Account_Type__c = 'Sales';
            accRecforSales.ParentId = accRec.Id;
            lstSalesAccount.add(accRecforSales);
        }        
        Database.insert(lstSalesAccount);
        List<Account> lstAccounts = [SELECT Id, Name, Parent_Org_Id__c, Account_Type__c, OwnerId, Owner.Name, ParentId, Parent.Name, Primary_Member__c, Primary_Member__r.Name, Primary_Member__r.Email FROM Account WHERE Id IN : lstSalesAccount];
        Debug.log('lstAccounts==>'+lstAccounts);       
        DatabaseResult objResult =  AccountSelectorController.getRelatedSalesAccounts(lstAccounts[1].Id);       
        AccountSelectorControllerTest.checkAssert(objResult, 5); 
        DatabaseResult objResult1 =  AccountSelectorController.getRelatedSalesAccounts(accRec.Id);
        AccountSelectorControllerTest.checkAssert(objResult1, 5);
        
        objResult =  AccountSelectorController.getRelatedSalesAccounts(null);
    }
    
    /************************************************************************************************************************************
    Author         : Krishana Tupe
    Description    : This method verify the getRelatedViewHierarchy (AuraEnabled) Metohd
    Created  Date  : 16 october 2018
  **************************************************************************************************************************************/ 
    @isTest
    public static void verifyGetRelatedViewHierarchy(){
        Account accRec = [SELECT Id From Account Where Name = 'strAccountName' AND Account_Type__c = 'Org'];   
        Debug.log('accRec==>'+accRec);
        List<Account> lstSalesAccount = new List<Account>();
        for(Integer iIndex = 1; iIndex <=5 ; iIndex++){
            Account accRecforSales = TestingUtility.createAccount('SalesAccount' + iIndex, false); 
            accRecforSales.Nickname__c = 'SalesAccount' + iIndex;
            accRecforSales.Account_Type__c = 'Sales';
            accRecforSales.ParentId = accRec.Id;
            lstSalesAccount.add(accRecforSales);
        }        
        Database.insert(lstSalesAccount);
        List<Account> lstAccounts = [SELECT Id, Name, Parent_Org_Id__c, Account_Type__c, OwnerId, Owner.Name, ParentId, Parent.Name, Primary_Member__c, Primary_Member__r.Name, Primary_Member__r.Email FROM Account WHERE Id IN : lstSalesAccount];
        Debug.log('lstAccounts==>'+lstAccounts);       
        DatabaseResult objResult =  AccountSelectorController.getRelatedViewHierarchy(lstAccounts[1].Id);
        AccountSelectorControllerTest.checkAssert(objResult, 6); 
        DatabaseResult objResult1 =  AccountSelectorController.getRelatedViewHierarchy(accRec.Id);
        AccountSelectorControllerTest.checkAssert(objResult1, 6);
        
        objResult =  AccountSelectorController.getRelatedViewHierarchy(null);
    }
    
    /************************************************************************************************************************************
    Author         : Shivprasad Patil
    Description    : This method verify the getQueryDataTest (AuraEnabled) Metohd
    Created  Date  : 03 December 2018
    **************************************************************************************************************************************/ 
    @isTest
    public static void getQueryDataTest(){
        List<Account> lstAccount = [SELECT Id FROM Account WHERE Account_Type__c = 'Org'];
        Integer intOrgCount = lstAccount.size();
        Map<String, Object> mapOfParams = new Map<String, Object>{'accountName'=>'strAccount', 'accountType'=>'Org'};
        DatabaseResult result = AccountSelectorController.getQueryData('searchOrgAccounts', mapOfParams);
        System.assertEquals(true, result.success);
        List<sObject> lstOfAccounts = (List<sObject>)result.data;
        System.assertEquals(intOrgCount, lstOfAccounts.size());
    }
    /************************************************************************************************************************************
    Author         : Krishana Tupe
    Created  Date  : 16 october 2018
  **************************************************************************************************************************************/ 
    static void checkAssert(DatabaseResult objResult, Integer assertValue){ 
        Debug.log('objResult==>'+objResult);
        String str = JSON.serialize(objResult.data);
        List<Account> lstAccount = (List<Account>)JSON.deserialize(str, List<Account>.class);
        Debug.log('lstAccount==>'+lstAccount);
        System.assert(lstAccount.size() == assertValue);
    }
}