objects/Account.object
<CustomObject>
    <fields>
        <fullName>Primary_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Paperwork will be sent to the primary member on the ACCOUNT</inlineHelpText>
        <label>Main Contact</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.Account.Id</field>
                <operation>equals</operation>
                <valueField>$Source.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UUID__c</fullName>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Billing_Account__c.object
<CustomObject>
    <fields>
        <fullName>Primary_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the main point of contact for the Billing Account.</description>
        <inlineHelpText>Person at the member company responsible for managing the membership: invoices, key card replacements, MENA account manager tab. Responsible for signing legal agreement (unless an authorized signatory is designated).</inlineHelpText>
        <label>Primary Member</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UUID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>This is unique,case sensitive auto generated field used to identify Billing Account record.</description>
        <externalId>true</externalId>
        <inlineHelpText>This is unique,case sensitive auto generated field used to identify Billing Account record.</inlineHelpText>
        <label>UUID</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <description>All Billing account is moved to this Billing Account object it help Sales people to identify Org and Sales account easily and reduce the clutter of 100s of Accounts with same name.</description>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Building__c.object
<CustomObject>
    <fields>
        <fullName>UUID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Building</label>
    <nameField>
        <label>Building</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Members</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Building__c</fullName>
        <description>Pulls Building Location without 3 character city reference</description>
        <formula>Location__r.Location_No_City__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Building</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Member__c</fullName>
        <formula>if( Billing_Account__r.Primary_Member__r.Id =  Id , "Yes","No")</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Primary Member</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Licensee</fullName>
                </value>
                <value>
                    <fullName>Employee</fullName>
                </value>
                <value>
                    <fullName>Member</fullName>
                </value>
                <value>
                    <fullName>Broker</fullName>
                </value>
                <value>
                    <fullName>Affiliate</fullName>
                </value>
                <value>
                    <fullName>Potential</fullName>
                </value>
                <value>
                    <fullName>Lead</fullName>
                </value>
                <value>
                    <fullName>Unqualified Broker</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UUID__c</fullName>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field relates the opportunity to the billing account. The billing account is used in the space station for sending contracts.</description>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Building__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Enter the specific building for which opportunity is associated</description>
        <inlineHelpText>This is the building / Nearest building to the geography entered by customer</inlineHelpText>
        <label>Building/Nearest Building</label>
        <referenceTo>Building__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract_Stage__c</fullName>
        <label>Contract Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Contract Sent</fullName>
                </value>
                <value>
                    <fullName>Contract Voided</fullName>
                </value>
                <value>
                    <fullName>Contract Discarded</fullName>
                </value>
                <value>
                    <fullName>Contract Signed</fullName>
                </value>
                <value>
                    <fullName>Contract Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_Member__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>This is the Main Contact of the Opportunity</inlineHelpText>
        <label>Main Contact</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Event Space</fullName>
                </value>
                <value>
                    <fullName>Internal Transfer</fullName>
                </value>
                <value>
                    <fullName>Partnership</fullName>
                </value>
                <value>
                    <fullName>PxWe</fullName>
                </value>
                <value>
                    <fullName>Mixed</fullName>
                </value>
                <value>
                    <fullName>Global Access</fullName>
                </value>
                <value>
                    <fullName>WeWork</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Reservable_Hold__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Reservable Holds</relationshipLabel>
        <relationshipName>Reservable_Holds</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Reservable Holds</relationshipLabel>
        <relationshipName>Reservable_Holds</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UUID__c</fullName>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Reservable Hold</label>
    <nameField>
        <displayFormat>RH{000000}</displayFormat>
        <label>Hold Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reservable Holds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Setting__c.object
<CustomObject>
    <fields>
        <fullName>Data__c</fullName>
        <description>This should contain JSON formatted data for each setting record. The JSON object will vary from setting to setting.</description>
        <label>Data</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type of the Settings, if it is Field Mappings, it will contain mapping of source object to destination object in JSON format.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Field Mappings</fullName>
                </value>
                <value>
                    <fullName>Custom</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>We are creating object for Settings instead of using Custom Object because we need to store larger size of data which Custom Setting does not support. e.g. Mapping of Fields from Contact to Lead etc. which may go beyond 255 characters. 

It will not use caching but give more flexibility for coding.</description>
    <label>Sales Console Setting</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Console Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Building__c</fullName>
        <label>Building</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AMS-Metropool</fullName>
                </value>
                <value>
                    <fullName>AMS-Labs</fullName>
                </value>
                <value>
                    <fullName>AMS-Weteringschans</fullName>
                </value>
                <value>
                    <fullName>ATX-Congress</fullName>
                </value>
                <value>
                    <fullName>ATX-Labs</fullName>
                </value>
                <value>
                    <fullName>BKN-Dumbo Heights</fullName>
                </value>
                <value>
                    <fullName>BK-Williamsburg</fullName>
                </value>
                <value>
                    <fullName>BOS-Fort Point</fullName>
                </value>
                <value>
                    <fullName>BOS-Labs</fullName>
                </value>
                <value>
                    <fullName>BOS-South Station</fullName>
                </value>
                <value>
                    <fullName>CHI-Fulton Market</fullName>
                </value>
                <value>
                    <fullName>CHI-Labs</fullName>
                </value>
                <value>
                    <fullName>CHI-RiverNorth</fullName>
                </value>
                <value>
                    <fullName>DC-Chinatown</fullName>
                </value>
                <value>
                    <fullName>DC-DuPont Circle</fullName>
                </value>
                <value>
                    <fullName>DC-Labs</fullName>
                </value>
                <value>
                    <fullName>DC-Wonder Bread Factory</fullName>
                </value>
                <value>
                    <fullName>ISR-Labs</fullName>
                </value>
                <value>
                    <fullName>LA-Fine Arts</fullName>
                </value>
                <value>
                    <fullName>LA-Fine Arts Building</fullName>
                </value>
                <value>
                    <fullName>LA-Hollywood</fullName>
                </value>
                <value>
                    <fullName>LA-Labs</fullName>
                </value>
                <value>
                    <fullName>LA-Promenade</fullName>
                </value>
                <value>
                    <fullName>LA-Santa Monica</fullName>
                </value>
                <value>
                    <fullName>LON-Devonshire</fullName>
                </value>
                <value>
                    <fullName>LON-East London</fullName>
                </value>
                <value>
                    <fullName>LON-Labs</fullName>
                </value>
                <value>
                    <fullName>LON-Moorgate</fullName>
                </value>
                <value>
                    <fullName>LON-South Bank</fullName>
                </value>
                <value>
                    <fullName>LON-Soho London</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/HoldReservableController.cls
global without Sharing class HoldReservableController {
    public class HoldReservableControllerException extends Exception{}
    public static Boolean isInvoker = false;
    public static Savepoint sp {get;set;}
    static {
        isInvoker = ApexDebugLog.registerRootInvoker(ApexDebugLog.InvokerType.AURA, 'HoldReservableController' + 'getsObjectPrefix', ApexDebugLog.InvokerType.AURA);        
    }
    @AuraEnabled
    public static DatabaseResult initialize(Id opportunityId){
        debug.log('Id opportunity ::'+opportunityId);
        try{
            sp = Database.setSavepoint();
            Map<String,Object> mapInitData = new Map<String,Object>();
            Setting__c settingRecord = Settings.get('HoldReservableSettings');
            Opportunity opp = [Select Id,Name,StageName,RecordType.Name,Contract_Stage__c,Building__r.Name,Building__c,Building__r.UUID__c,Billing_Account__r.UUID__c,Billing_Account__r.Name,Primary_Member__c, Primary_Member__r.UUID__c, Primary_Member__r.Email, Primary_Member__r.Phone,Primary_Member__r.Name,Account.Name From Opportunity Where Id =: opportunityId];
            mapInitData.put('Setting',settingRecord);
            mapInitData.put('OpportunityData', opp);
            mapInitData.put('LoggedInUser',UserInfo.getUserId());
            mapInitData.put('currentDate',System.today());
            return new DatabaseResult(mapInitData);
        }catch(Exception pEx){
            if(sp != null){                
                Database.rollback(sp);  
            }
			ApexDebugLog.logException(pEx,opportunityId, 'HoldReservableController', 'initialize');            
            return (new DatabaseResult(pEx));       
        }
    }
    
    //Created by    : Samadhan Kadam
    //Created Date  : 29-Nov-2017
    webservice static String isValidHold(Id oppId){
        string isValid;
        try{
            ValidHoldResultWithOpp validResult = new ValidHoldResultWithOpp();
            validResult.isValidHold = true;
            Setting__c HoldReservable = new Setting__c();
            HoldReservable = Settings.get('HoldReservableSettings'); 
            
            debug.log('HoldReservableSetting'+HoldReservable);     
            HoldReservableSettings settingData = new HoldReservableSettings();
            settingData = (HoldReservableSettings)JSON.deserialize(HoldReservable.Data__c, HoldReservableSettings.class);
            debug.log('settingData123'+settingData);
            debug.log('settingData123 stages ::'+settingData.AllowedStages);
            debug.log('AllowRecordrtypes'+settingData.AllowedRecordTyes);
            Set<String> setOfLowerStages = new Set<String>();
            Set<String> setOfLowerRecordTypes = new Set<String>();
            for(String recordTypes : settingData.AllowedRecordTyes){
                setOfLowerRecordTypes.add(recordTypes.toLowercase());
            }
            for(String stages : settingData.AllowedStages){
                setOfLowerStages.add(stages.toLowercase());
            }
            List<Opportunity> lstOpp = [SELECT Id,StageName,Type__c,Account.OwnerId,Account.Account_Type__c,(SELECT Id,Name,TeamMemberRole,User.Email,User.Id FROM OpportunityTeamMembers), OwnerId,recordTypeId,recordType.Name FROM Opportunity WHERE Id =: oppId LIMIT 1];
            Debug.log('setOfLowerStages ::'+setOfLowerStages);
            Debug.log('lstOpp ::'+lstOpp);
            debug.log('UserInfo.getUserId() ::'+UserInfo.getUserId());
            
            //Modified by Samadhan kadam for ST-2368
            if(lstOpp != null && lstOpp.size() > 0){
                if(setOfLowerStages != null && !setOfLowerStages.isEmpty() && lstOpp.size() > 0 && !lstOpp.isEmpty()){
                    if(!setOfLowerStages.contains(lstOpp[0].StageName.toLowercase())){
                        validResult.isValidHold = false;
                        validResult.errorMsg = 'Opportunity stage should be Selling,Negotiating or Closing for Reservable Hold';
                        debug.log('validResult ::'+validResult);
                        return JSON.serialize(validResult);    
                    }
                    if(lstOpp[0].Type__c=='PxWe' || lstOpp[0].Type__c=='Mixed' || lstOpp[0].Type__c=='Global Access'){
                        validResult.isValidHold = false;
                        validResult.errorMsg = 'Opportunity Product Type should be \'WeWork\'.';
                        debug.log('validResult ::'+validResult);
                        return JSON.serialize(validResult);    
                    }
                }
                //only account owner or opportunity owner can do office hold
                //Modified by Samadhan Kadam for CSI-512 Added validation for hold off.
                Set<ID> setOfTeamMemberId = new Set<ID>();
                If( lstOpp[0].OpportunityTeamMembers.size()!=null){
                    for(OpportunityTeamMember ObjOppTeamMember : lstOpp[0].OpportunityTeamMembers){
                        setOfTeamMemberId.add(ObjOppTeamMember.User.Id);
                    }
                }            
                if((lstOpp[0].OwnerId == UserInfo.getUserId()) || (setOfTeamMemberId.contains(UserInfo.getUserId()))){
                    return JSON.serialize(validResult);
                }else{
                    validResult.isValidHold = false;
                    validResult.errorMsg = 'Only Opportunity Owner Or Opportunity Team Member Can do Reservable Hold';
                    debug.log('validResult ::'+validResult);
                    return JSON.serialize(validResult);
                } 
                debug.log('validResult ::'+validResult);
                return JSON.serialize(validResult); 
            }else{
                validResult.isValidHold = false;
                validResult.errorMsg = 'Opportunity not found with Id '+oppId+'.';
                debug.log('validResult Lstopp ::'+validResult);
                return JSON.serialize(validResult);
            }
            return JSON.serialize(validResult);
        }
        Catch(Exception ex){
            Debug.log('Exception'+ex.getMessage());
            return isValid;
        }
    }
    @AuraEnabled
    public static String isValidHoldLightning(Id oppId){
        return isValidHold(oppId);
    }  
    
    webservice static String holdOffReservable(Id holdId, String sourcePage){
        debug.log('holdId ::'+holdId);
        String methodName = 'POST';
        String endPointUrl;
        Boolean validOwner = false;
        Boolean validStatus = true;
        List<Reservable_Hold__c> lstReservableHold = [SELECT Id,UUID__c,Opportunity__c, Opportunity__r.OwnerId,Approval_Status__c FROM Reservable_Hold__c WHERE Id =: holdId];
        List<Opportunity> lstopp = [SELECT ID,Name,(SELECT Id,User.Email,User.Id FROM OpportunityTeamMembers),(SELECT Id,Name,Approval_Status__c FROM Reservable_Holds__r where Id=:holdId) FROM Opportunity Where ID=:lstReservableHold[0].Opportunity__c];
        Set<ID> setOfTeamMemberId = new Set<ID>();
        If( lstOpp[0].OpportunityTeamMembers.size()!=null){
            for(OpportunityTeamMember ObjOppTeamMember : lstOpp[0].OpportunityTeamMembers){
                setOfTeamMemberId.add(ObjOppTeamMember.User.Id);
            }
        }    
        if((setOfTeamMemberId.contains(UserInfo.getUserId())) || (lstReservableHold.size()!=null && (lstReservableHold[0].Opportunity__r.OwnerId == UserInfo.getUserId()))){
            validOwner = true;
        }else{
            Debug.log('Wrong OwnerId ::');
            return JSON.serialize('{"error": "Only Opportunity Owner or Opportunity Team Member Can Release Hold."}');
        }
        //Change in validation as we changes the Approval Status picklist value-CSI-512
        if((lstReservableHold[0].Approval_Status__c.toLowerCase() == 'released')){
            validStatus = false;
            return JSON.serialize('{"error": "This Reservable is already Released."}');
        }
         if((lstReservableHold[0].Approval_Status__c.toLowerCase() == 'expired')){
            validStatus = false;
            return JSON.serialize('{"error": "This Reservable is already Expired."}');
        }
        debug.log('validStatus ::'+validStatus);
        debug.log('validOwner ::'+validOwner);
        if(validStatus && validOwner){
            Setting__c HoldReservable = Settings.get('HoldReservableSettings'); 
            debug.log('HoldReservableSetting'+HoldReservable);     
            HoldReservableSettings settingData = new HoldReservableSettings();
            settingData = (HoldReservableSettings)JSON.deserialize(HoldReservable.Data__c, HoldReservableSettings.class);
            debug.log('settingData123 ::'+settingData.HoldoffAPI);
    
            String userId = UserInfo.getUserId();
            endPointUrl = settingData.HoldoffAPI.url.replace('HOLD_UUID',lstReservableHold[0].UUID__c);
            Http h1 = new Http();
            HttpRequest req1 = new HttpRequest();
            req1.setEndpoint(endPointUrl);
            req1.setMethod(methodName);
            req1.setHeader('Content-Type','application/json');
            req1.setHeader('Authorization',settingData.HoldoffAPI.Headers.get('Authorization'));
            req1.setHeader('CONTEXT_SALESFORCE_ID',userId);
            req1.setBody('{"removed_from":"'+sourcePage+'"}');
            debug.log('req1 :: '+req1.getBody());
            debug.log('req1 :: '+req1);
            HTTPResponse res = h1.send(req1);
            debug.log('Res :: '+res.getBody());
            debug.log('Res getStatusCode:: '+res.getStatusCode());
            if(res.getStatusCode() == 200){
                lstReservableHold[0].Approval_Status__c = 'Released';
                update lstReservableHold[0];
                Debug.log('Update Hold with Status Released :: '+lstReservableHold[0]);
            }
            debug.log('Res getXmlStreamReader:: '+res.getXmlStreamReader());
            return JSON.serialize(res.getBody());
        }
        return null;
    }
     @AuraEnabled
    public static String holdOffReservableLightning(Id holdId, String sourcePage){
        return holdOffReservable(holdId, sourcePage);
    }  
    global class ValidHoldResultWithOpp{
        global Boolean isValidHold {get;set;}
        global string errorMsg {get;set;}
        global Opportunity objOpportunity {get;set;}
        global List<String> opportunityBuildings {get;set;}
    }
    global class HoldReservableSettings {
        global Set<String> AllowedStages; 
        global Set<String> ReservableType;
        global Set<String> AllowedRecordTyes;
        global Set<String> EmailsForAlerts;
        global API ReservableAvailabilityAPI;
        global API HoldReservableApi;
        global API HoldoffAPI;
       
    }
    global class API{
        global String url;
        global Map<String,String> Headers;
    }
}