objects/Account.object
<CustomObject>
    <fields>
        <fullName>Primary_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Paperwork will be sent to the primary member on the ACCOUNT</inlineHelpText>
        <label>Main Contact</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.Account.Id</field>
                <operation>equals</operation>
                <valueField>$Source.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Consumer</fullName>
        <active>true</active>
        <description>This is Updated Record Type from Default to Consumer for New Sales Process and Changes</description>
        <label>Consumer</label>
    </recordTypes>
</CustomObject>

objects/Billing_Account__c.object
<CustomObject>
    <fields>
        <fullName>Primary_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the main point of contact for the Billing Account.</description>
        <inlineHelpText>Person at the member company responsible for managing the membership: invoices, key card replacements, MENA account manager tab. Responsible for signing legal agreement (unless an authorized signatory is designated).</inlineHelpText>
        <label>Primary Member</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>All Billing account is moved to this Billing Account object it help Sales people to identify Org and Sales account easily and reduce the clutter of 100s of Accounts with same name.</description>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Members</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Member__c</fullName>
        <formula>if( Billing_Account__r.Primary_Member__r.Id =  Id , "Yes","No")</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Primary Member</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Licensee</fullName>
                </value>
                <value>
                    <fullName>Employee</fullName>
                </value>
                <value>
                    <fullName>Member</fullName>
                </value>
                <value>
                    <fullName>Broker</fullName>
                </value>
                <value>
                    <fullName>Affiliate</fullName>
                </value>
                <value>
                    <fullName>Potential</fullName>
                </value>
                <value>
                    <fullName>Lead</fullName>
                </value>
                <value>
                    <fullName>Unqualified Broker</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Consumer</fullName>
        <active>true</active>
        <label>Consumer</label>
    </recordTypes>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field relates the opportunity to the billing account. The billing account is used in the space station for sending contracts.</description>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract_Sent_Date__c</fullName>
        <label>Contract Sent Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contract_Stage__c</fullName>
        <label>Contract Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Contract Sent</fullName>
                </value>
                <value>
                    <fullName>Contract Voided</fullName>
                </value>
                <value>
                    <fullName>Contract Discarded</fullName>
                </value>
                <value>
                    <fullName>Contract Signed</fullName>
                </value>
                <value>
                    <fullName>Contract Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract_UUID__c</fullName>
        <description>contractEvent Endpoint will contain 'Contract UUID' to search Opportunity</description>
        <externalId>true</externalId>
        <inlineHelpText>contractEvent Endpoint will contain 'Contract UUID' to search Opportunity</inlineHelpText>
        <label>Contract UUID</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Locations_Interested__c</fullName>
        <label>Locations Interested</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AMS-Labs</fullName>
                </value>
                <value>
                    <fullName>AMS-Metropool</fullName>
                </value>
                <value>
                    <fullName>AMS-Strawinskylaan</fullName>
                </value>
                <value>
                    <fullName>AMS-Weteringschans</fullName>
                </value>
                <value>
                    <fullName>ARC-Andres Arguibel 2860</fullName>
                </value>
                <value>
                    <fullName>ARC-Avenida Corrientes 800</fullName>
                </value>
                <value>
                    <fullName>ARC-Ing. Enrique Butty 275</fullName>
                </value>
                <value>
                    <fullName>ARC-Libertador 1000</fullName>
                </value>
                <value>
                    <fullName>ARC- Torre Bellini</fullName>
                </value>
                <value>
                    <fullName>ARG- Torre Bellini</fullName>
                </value>
                <value>
                    <fullName>ARN-Urban Escape</fullName>
                </value>
                <value>
                    <fullName>ATL-1372 Peachtree</fullName>
                </value>
                <value>
                    <fullName>ATL-3280 Peachtree Road NE</fullName>
                </value>
                <value>
                    <fullName>ATL-Colony Square</fullName>
                </value>
                <value>
                    <fullName>ATL-Tower Place</fullName>
                </value>
                <value>
                    <fullName>AUS-Congress</fullName>
                </value>
                <value>
                    <fullName>AUS-Domain</fullName>
                </value>
                <value>
                    <fullName>AUS-Labs</fullName>
                </value>
                <value>
                    <fullName>AUS-University Park</fullName>
                </value>
                <value>
                    <fullName>AUS-Westview</fullName>
                </value>
                <value>
                    <fullName>AUS-WeWork 801 Barton Springs</fullName>
                </value>
                <value>
                    <fullName>BCN-Diagonal 444</fullName>
                </value>
                <value>
                    <fullName>BHZ-Boulevard Shopping</fullName>
                </value>
                <value>
                    <fullName>BKK-Asia Centre</fullName>
                </value>
                <value>
                    <fullName>BKN-109 S 5th St</fullName>
                </value>
                <value>
                    <fullName>BKN-Brooklyn Heights</fullName>
                </value>
                <value>
                    <fullName>BKN-Dumbo Heights (Prospect)</fullName>
                </value>
                <value>
                    <fullName>BKN-Dumbo Heights (Sands)</fullName>
                </value>
                <value>
                    <fullName>BKN-Montague St.</fullName>
                </value>
                <value>
                    <fullName>BKN-Williamsburg</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Original_Contract_UUID__c</fullName>
        <description>contractEvent Endpoint will contain 'Original Contract UUID' to search Opportunity</description>
        <inlineHelpText>contractEvent Endpoint will contain 'Original Contract UUID' to search Opportunity</inlineHelpText>
        <label>Original Contract UUID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Paperwork_Sent_On_Date__c</fullName>
        <description>New date field which captures Paper sent On Date from payload of contract event.</description>
        <label>Paperwork Sent On (Date)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Primary_Member__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>This is the Main Contact of the Opportunity</inlineHelpText>
        <label>Main Contact</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Event Space</fullName>
                </value>
                <value>
                    <fullName>Internal Transfer</fullName>
                </value>
                <value>
                    <fullName>Partnership</fullName>
                </value>
                <value>
                    <fullName>PxWe</fullName>
                </value>
                <value>
                    <fullName>Mixed</fullName>
                </value>
                <value>
                    <fullName>Global Access</fullName>
                </value>
                <value>
                    <fullName>WeWork</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Consumer</fullName>
        <active>true</active>
        <businessProcess>Office Space</businessProcess>
        <label>Consumer</label>
    </recordTypes>
</CustomObject>

classes/ContractEventSent.cls
/**
* Name			:	ContractEventSent	 
* Issue No.		: 	CSI-492 
* Purpose		:	This is contains the logic for Contract Sent.
* History		
	Version			Author				Date			Detail						Feature			IssueNumber
	1.0				Mayuresh Ghodke		1/1/2018		Initial Development
	2.0				Shobhit Gahlot		9/1/2018		Payload structure Change	Sellable		CSI-441
//Modified By: Mayuresh Ghodke, Issue No:ST-1359, Date:29/08/2017, Comment: update contract uuid with new uuid received in payload for a closing opportunity with contract discarded stage
***********************************************************************************************************************************************************
*/ 
public class ContractEventSent {
    public static String contractSent(WWTypes.ContractEvent objContractEvent, ContractEventUtilities.UtilityWapper objUtilityWapper){

        //If any opportunity found then Update that Opportunity. Else Create new Opportunity.
        debug.log('objUtilityWapper.oppToUse ::'+objUtilityWapper.oppToUse);
        if(objUtilityWapper.oppToUse != null){
            Billing_Account__c objBillingAccount;
            if(objUtilityWapper.oppToUse.Billing_Account__c == null){
                objBillingAccount = ContractEventAccountHandler.createOrReuseBillingAccount(objContractEvent.company_uuid, objContractEvent.primary_member_email, objUtilityWapper.mapContactsMembers);
            }
            objUtilityWapper.udpateOpp = true;
            //Opportunity should be open and Payload should cointain reservable_uuids
            if(objUtilityWapper.setPayloadReservableUuid != null){
                ContractEventPayloadMapping.OpportunityFieldsWrapper objOpportunityFieldsWrapper = ContractEventPayloadMapping.mapPayloadWithOpportunityFields(objContractEvent, objUtilityWapper);
                if(objOpportunityFieldsWrapper.mapOppMultiPickListFields.get('Locations_Interested__c') != null && objOpportunityFieldsWrapper.mapOppMultiPickListFields.get('Locations_Interested__c').size() > 0 && String.isNotBlank(objUtilityWapper.oppToUse.Locations_Interested__c)){
                    objOpportunityFieldsWrapper.mapOppMultiPickListFields.put('Locations_Interested__c',OpportunityHelper.getUniquePickListValues(objUtilityWapper.oppToUse.Locations_Interested__c, objOpportunityFieldsWrapper.mapOppMultiPickListFields.get('Locations_Interested__c')));
                }
                if(String.isNotBlank(objUtilityWapper.objOpp.StageName) && String.isNotBlank(objUtilityWapper.objOpp.Original_Contract_UUID__c)){
                    objUtilityWapper.objOpp  = OpportunityHelper.createOpportunityWithFieldValues(objOpportunityFieldsWrapper.mapOppFields, objOpportunityFieldsWrapper.mapOppMultiPickListFields);
                    //CSI-534 now closed won opp will be updated so Stagname will also be updated as per discussion with Vidu, vaibhav
                    objUtilityWapper.objOpp.put('StageName','Closing');
                    objUtilityWapper.objOpp.put('Original_Contract_UUID__c',objUtilityWapper.oppToUse.Contract_UUID__c);
                }else{
                    objUtilityWapper.objOpp = OpportunityHelper.createOpportunityWithFieldValues(objOpportunityFieldsWrapper.mapOppFields, objOpportunityFieldsWrapper.mapOppMultiPickListFields);
                }
                objUtilityWapper.objOpp.Id = objUtilityWapper.oppToUse.Id;
                if(objBillingAccount != null){
                    objUtilityWapper.objOpp.Billing_Account__c = objBillingAccount.Id;
                }
                Debug.log('objUtilityWapper.objOpp.Contract_UUID__c in contract sent : '+objUtilityWapper.objOpp.Contract_UUID__c);
                
                objUtilityWapper.objOpp.Contract_UUID__c = objContractEvent.membership_agreement_uuid;
                if(objUtilityWapper.oppToUse.Primary_Member__c == null && objUtilityWapper.mapContactsMembers!= null && objUtilityWapper.mapContactsMembers.get('Contact') != null && objUtilityWapper.mapContactsMembers.get('Contact').get('PrimaryMemberEmailInContact') != null){
                    objUtilityWapper.objOpp.Primary_Member__c = objUtilityWapper.mapContactsMembers.get('Contact').get('PrimaryMemberEmailInContact').Id;
                }
                //If current opportunities record type id Consumer then only change StageName sholud change to Closing
                //ST-2078 Stage will be Closing for all recordtypes in case of contract sent as pointed out by Rachell during account heirarchy deployment
                //if(objUtilityWapper.oppToUse.RecordType.Name == 'Consumer')
                objUtilityWapper.objOpp.StageName ='Closing';
                objUtilityWapper.objOpp.Contract_Stage__c ='Contract Sent';
                //Modified By: Mayuresh Ghodke, Date: 29/12/2017, Issue No. :CSI-467, Comment: Apex: Don't Update the Close Date of the opportunity when the contract is sent.
                //objUtilityWapper.objOpp.CloseDate=system.today();
                //CSI-411 old field Contract_Sent_Date__c will not be update as per discussion with parag also Paperwork_Sent_On_c datetime field will not be used
                objUtilityWapper.objOpp.Paperwork_Sent_On_Date__c = (objContractEvent.contract_date != null && objContractEvent.contract_date != '') ? Date.valueOf(objContractEvent.contract_date) : Date.today();
                
                //ST-2223 Only opportunity Line items will decide the oppotunity type
                //if( objContractEvent.transfer_type != 'New Business')
                //   objUtilityWapper.objOpp.Type__c = 'Internal Transfer';
                if(!String.isBlank(objContractEvent.original_contract_uuid)){
                    objUtilityWapper.objOpp.Original_Contract_UUID__c = objContractEvent.original_contract_uuid;
                }
                //Update Opportunity Reservables, Opportunity MoveOuts,Opportunity Product
                String result = ContractEventUpdateOppUtility.updateOpportunityRelatedObjects(objContractEvent, objUtilityWapper);
                return ContractEventUtilities.getResult(result, false);
            }else{
                return 'objContractEvent.reservable_uuids is required field for API';
            }
        }else{
            debug.log('Opportunity to update not found in contract sent');
            //Create New Opportunity
            String result = ContractEventCreateOppUtility.createNewOpportunity(objContractEvent,objUtilityWapper);                       
            return ContractEventUtilities.getResult(result, true);
        }
    }
}