objects/Account.object
<CustomObject>
    <fields>
        <fullName>UUID__c</fullName>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Building__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UUID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Building</label>
    <nameField>
        <label>Building</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Building__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Building</label>
        <referenceTo>Building__c</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_Address__c</fullName>
        <description>Email Address From Splash</description>
        <label>Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Lead_Owner__c</fullName>
        <description>This field is used to route leads assigned to a campaign</description>
        <inlineHelpText>This field is used to route leads assigned to a campaign. Enter the user or queue ID.
See link below for regional queue list 
https://docs.google.com/spreadsheets/d/16_uqpniUGsFaqVEzxppQPy5MsaXho9xGaaiTDxW7Gw0/edit?usp=sharing</inlineHelpText>
        <label>Lead Owner</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/City__c.object
<CustomObject>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <referenceTo>State__c</referenceTo>
        <relationshipLabel>Cities</relationshipLabel>
        <relationshipName>Cities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Building__c</fullName>
        <description>Pulls Building Location without 3 character city reference</description>
        <formula>Location__r.Location_No_City__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Building</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>This field will store the name of the city</description>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UUID__c</fullName>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Journey__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <description>If Primary_Lead is exists, will return Primary Lead's Email otherwise It will check for Primary_Contact, If contact exists will return Email of Contact.</description>
        <formula>IF( Primary_Lead__c != NULL , Primary_Lead__r.Email , IF( Primary_Contact__c != NULL, Primary_Contact__r.Email , "" ))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Email(old)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Locations_Interested__c</fullName>
        <label>Locations Interested</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>32 Village</fullName>
                </value>
                <value>
                    <fullName>AMS-Labs</fullName>
                </value>
                <value>
                    <fullName>AMS-Metropool</fullName>
                </value>
                <value>
                    <fullName>AMS-Strawinskylaan</fullName>
                </value>
                <value>
                    <fullName>AMS-Weteringschans</fullName>
                </value>
                <value>
                    <fullName>ARC-Andres Arguibel 2860</fullName>
                </value>
                <value>
                    <fullName>ARC-Avenida Corrientes 800</fullName>
                </value>
                <value>
                    <fullName>ARC-Ing. Enrique Butty 275</fullName>
                </value>
                <value>
                    <fullName>ARC-Libertador 1000</fullName>
                </value>
                <value>
                    <fullName>ARC- Torre Bellini</fullName>
                </value>
                <value>
                    <fullName>ARN-Urban Escape</fullName>
                </value>
                <value>
                    <fullName>ATL-1372 Peachtree</fullName>
                </value>
                <value>
                    <fullName>ATL-3280 Peachtree Road NE</fullName>
                </value>
                <value>
                    <fullName>ATL-Colony Square</fullName>
                </value>
                <value>
                    <fullName>ATL-Tower Place</fullName>
                </value>
                <value>
                    <fullName>AUS-Congress</fullName>
                </value>
                <value>
                    <fullName>AUS-Domain</fullName>
                </value>
                <value>
                    <fullName>AUS-Labs</fullName>
                </value>
                <value>
                    <fullName>AUS-University Park</fullName>
                </value>
                <value>
                    <fullName>AUS-Westview</fullName>
                </value>
                <value>
                    <fullName>AUS-WeWork 801 Barton Springs</fullName>
                </value>
                <value>
                    <fullName>BCN-Diagonal 444</fullName>
                </value>
                <value>
                    <fullName>BHZ-Boulevard Shopping</fullName>
                </value>
                <value>
                    <fullName>BKK-Asia Centre</fullName>
                </value>
                <value>
                    <fullName>BKK-T-One Building</fullName>
                </value>
                <value>
                    <fullName>BKN-109 S 5th St</fullName>
                </value>
                <value>
                    <fullName>BKN-Brooklyn Heights</fullName>
                </value>
                <value>
                    <fullName>BKN-Dumbo Heights (Prospect)</fullName>
                </value>
                <value>
                    <fullName>BKN-Dumbo Heights (Sands)</fullName>
                </value>
                <value>
                    <fullName>BKN-Montague St</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UUID__c</fullName>
        <description>Globally Unique Identifier of the record used by all systems at WeWork</description>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <description>We are going to use this object as Sales Journey of the user. Which begins when a person shows interest in one of our products or we decide to reach out to show our products.</description>
    <label>Journey</label>
    <nameField>
        <label>Customer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Journeys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City (Custom)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Amsterdam</fullName>
                </value>
                <value>
                    <fullName>Austin</fullName>
                </value>
                <value>
                    <fullName>Boston</fullName>
                </value>
                <value>
                    <fullName>Brooklyn</fullName>
                </value>
                <value>
                    <fullName>Chicago</fullName>
                </value>
                <value>
                    <fullName>Israel</fullName>
                </value>
                <value>
                    <fullName>London</fullName>
                </value>
                <value>
                    <fullName>Los Angeles</fullName>
                </value>
                <value>
                    <fullName>Miami</fullName>
                </value>
                <value>
                    <fullName>New York</fullName>
                </value>
                <value>
                    <fullName>San Francisco</fullName>
                </value>
                <value>
                    <fullName>Seattle</fullName>
                </value>
                <value>
                    <fullName>Washington</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Building__c</fullName>
        <label>Building</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AMS-Metropool</fullName>
                </value>
                <value>
                    <fullName>AMS-Labs</fullName>
                </value>
                <value>
                    <fullName>AMS-Weteringschans</fullName>
                </value>
                <value>
                    <fullName>ATX-Congress</fullName>
                </value>
                <value>
                    <fullName>ATX-Labs</fullName>
                </value>
                <value>
                    <fullName>BKN-Dumbo Heights</fullName>
                </value>
                <value>
                    <fullName>BK-Williamsburg</fullName>
                </value>
                <value>
                    <fullName>BOS-Fort Point</fullName>
                </value>
                <value>
                    <fullName>BOS-Labs</fullName>
                </value>
                <value>
                    <fullName>BOS-South Station</fullName>
                </value>
                <value>
                    <fullName>CHI-Fulton Market</fullName>
                </value>
                <value>
                    <fullName>CHI-Labs</fullName>
                </value>
                <value>
                    <fullName>CHI-RiverNorth</fullName>
                </value>
                <value>
                    <fullName>DC-Chinatown</fullName>
                </value>
                <value>
                    <fullName>DC-DuPont Circle</fullName>
                </value>
                <value>
                    <fullName>DC-Labs</fullName>
                </value>
                <value>
                    <fullName>DC-Wonder Bread Factory</fullName>
                </value>
                <value>
                    <fullName>ISR-Labs</fullName>
                </value>
                <value>
                    <fullName>LA-Fine Arts</fullName>
                </value>
                <value>
                    <fullName>LA-Fine Arts Building</fullName>
                </value>
                <value>
                    <fullName>LA-Hollywood</fullName>
                </value>
                <value>
                    <fullName>LA-Labs</fullName>
                </value>
                <value>
                    <fullName>LA-Promenade</fullName>
                </value>
                <value>
                    <fullName>LA-Santa Monica</fullName>
                </value>
                <value>
                    <fullName>LON-Devonshire</fullName>
                </value>
                <value>
                    <fullName>LON-East London</fullName>
                </value>
                <value>
                    <fullName>LON-Labs</fullName>
                </value>
                <value>
                    <fullName>LON-Moorgate</fullName>
                </value>
                <value>
                    <fullName>LON-South Bank</fullName>
                </value>
                <value>
                    <fullName>LON-Soho London</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/CampaignMemberTriggerHandlerTest.cls
/************************************************************************************************************************************
    Author 		: 	RamseySolutions	
    Description : 	This class contain test methods for the different CampaignMember triggers.

    History		:
	----------------------------------------------------------------------------------------------------------------------------------
	VERSION		DATE				AUTHOR				ISSUE 			DETAIL
	1			22 January 2016		RamseySolutions						Initial Developement
	2			23 October 2018		Krishana Tupe		ST-2931			Done Required Changs
	3			23 October 2018		Krishana Tupe		ST-29312		Done Required Changs
***************************************************************************************************************************************/
@isTest
private class CampaignMemberTriggerHandlerTest {  
    static List<Account> lstAccounts = new List<Account>();
    static Lead[] leads = new List<Lead>();
    static List<Contact> lstContacts = new List<Contact>();
    static List<Campaign> lstCampaigns = new List<Campaign>();
    static List<Building__c> lstBuildings= new List<Building__c>();
    static List<User> lstUser = new List<User>();
    static List<CampaignMember> lstCampaignMembersToInsert = new List<CampaignMember>();   
    static List<Building__c> lstBuilding = new List<Building__c>();
    static Id[] leadIds = new List<Id>();
    static Contact contact;
    static CampaignMember[] members = new List<CampaignMember>();
    static List<Lead> lstLeads = new List<Lead>();
    
    static {               
        SalesConsoleSettings.createSettings();
        Profile p1 = [SELECT Id FROM Profile WHERE Name='System Administrator'];
        lstUser.add(new User(Alias = 'testU', Email='testUserName1@example.com', 
                             EmailEncodingKey='UTF-8', LastName='User', LanguageLocaleKey='en_US', 
                             LocaleSidKey='en_US', ProfileId = p1.Id, IsActive = true,
                             TimeZoneSidKey='America/Los_Angeles', UserName='testUserName1@example.com',CommunityNickname = 'Test User 001'));  
        
        lstUser.add(new User(Alias = 'testU1', Email='testUser1LeadOwner@example.com', 
                             EmailEncodingKey='UTF-8', LastName='User', LanguageLocaleKey='en_US', 
                             LocaleSidKey='en_US', ProfileId = p1.Id, IsActive = true,
                             TimeZoneSidKey='America/Los_Angeles', UserName='testUser1LeadOwner@example.com',CommunityNickname = 'Test User 002'));  
        
        lstUser.add(new User(Alias = 'testU3',Email='testinactiveuser@example.com', 
                             EmailEncodingKey='UTF-8', LastName='User', LanguageLocaleKey='en_US', 
                             LocaleSidKey='en_US', ProfileId = p1.Id, IsActive = false,
                             TimeZoneSidKey='America/Los_Angeles', UserName='testinactiveuser@example.com',CommunityNickname = 'Test User 003'));        
        TestingUtility.insertListWithAssert(lstUser); 
        
        lstCampaigns.add(new Campaign(Name = 'Test Campaign 1', City__c = 'Chicago', State__c = 'IL',Email_Address__c='Building1@example.com',Type = 'Splash Event', Lead_Owner__c = lstUser[2].Id));
        lstCampaigns.add(new Campaign(Name = 'Test Campaign 2', City__c = 'Chicago', State__c = 'IL', Type = 'Splash Event',Email_Address__c='Building1@example.com', Lead_Owner__c = lstUser[2].Id));        
        lstCampaigns.add( new Campaign(Name = 'Test Campaign 3', State__c = 'DC', City__c = 'Washington DC', Type = 'Splash Event',Email_Address__c='abc3@example.com', Lead_Owner__c = lstUser[1].Id));       
        lstCampaigns.add(new Campaign(Name = 'Test Campaign 4', State__c = 'DC', City__c = 'Chicago', Type = 'Splash Event', Lead_Owner__c = lstUser[2].Id));        
        lstCampaigns.add(new Campaign(Name = 'Test Campaign 5', State__c = 'DC', Type = 'Splash Event',  Lead_Owner__c = lstUser[2].Id));
        TestingUtility.insertListWithAssert(lstCampaigns); 
        
        //Buildings
        lstBuildings.add(new Building__c(Name='Building15318_1', UUID__c = '15318_1', Email__c = 'Building1@example.com'));        
        lstBuildings.add(new Building__c(Name = 'B1',UUID__c='111222333444555',Email__c='abc1@example.com'));
        lstBuildings.add( new Building__c(Name = 'B2',UUID__c='222333444555666',Email__c='abc2@example.com'));
        TestingUtility.insertListWithAssert(lstBuildings);
        
        //Accounts        
        lstAccounts.add(new Account(name = 'Test Account1', UUID__c = 'testAccount1UUID1'));
        TestingUtility.insertListWithAssert(lstAccounts);
        
        //Insert Test Leads 
        lstLeads.add(new Lead(LastName = 'Doe', FirstName = 'John', Email='testcampaign1@example.com', Company = 'WeWork Inc', Locations_Interested__c = lstBuildings[0].Name, Generate_Journey__c = true));
        lstLeads.add(new Lead(LastName = 'Doe', FirstName = 'John', Email='testcampaign2@example.com', Company = 'WeWork Inc', Generate_Journey__c = true));
        lstLeads.add(new Lead(LastName = 'Doe', FirstName = 'John', Email='testcampaign3@example.com', Company = 'WeWork Inc', Locations_Interested__c=lstBuildings[0].Name, Generate_Journey__c = true));
        lstLeads.add(new Lead(LastName = 'Doe',FirstName = 'John', Email='testcampaign4@example.com', Company = 'WeWork Inc', Locations_Interested__c=lstBuildings[1].Name, Generate_Journey__c = true));
        lstLeads.add(new Lead(LastName = 'Doe',FirstName = 'John', Email='testcampaign5@example.com', Company = 'WeWork Inc', Locations_Interested__c=lstBuildings[1].Name, Generate_Journey__c = true));        
        TestingUtility.insertListWithAssert(lstLeads);
        
        lstContacts.add(new Contact(LastName = 'TestContact1', Email = 'testcontact1RestCon@example.com',AccountId = lstAccounts[0].Id));
        lstContacts.add(new Contact(LastName = 'TestContact2', Email = 'testcontact2RestCon@example.com',AccountId = lstAccounts[0].Id));       
        TestingUtility.insertListWithAssert(lstContacts);
        
        List<Journey__c> lstJourneys = new List<Journey__c>();
        lstJourneys.add(new Journey__c(Name = lstLeads[3].LastName, Primary_Lead__c = lstLeads[3].Id, Status__c = 'Started', Primary_Email__c = lstLeads[3].Email, NMD_Next_Contact_Date__c = Date.today()));
        lstJourneys.add(new Journey__c(Name = lstContacts[0].LastName, Primary_Contact__c = lstContacts[0].Id, Status__c = 'Started', Primary_Email__c = lstContacts[0].Email, NMD_Next_Contact_Date__c = Date.today()));       
        TestingUtility.insertListWithAssert(lstJourneys);
        
        SalesConsoleSettings.createUnassignedNMDUSQueueSetting();
        SalesConsoleSettings.createSplashEventJourney();       
        lstCampaignMembersToInsert.add(new CampaignMember(LeadId = lstLeads[0].Id, CampaignId = lstCampaigns[0].Id));
        lstCampaignMembersToInsert.add(new CampaignMember(ContactId = lstContacts[0].Id, CampaignId = lstCampaigns[0].Id));
        TestingUtility.insertListWithAssert(lstCampaignMembersToInsert); 
    }
    
    
 /************************************************************************************************************************************
        Author 				: 	Priyanka Ambre
    	Description			:	
		Created Date		:	
**************************************************************************************************************************************/
    @isTest
    public static void testUpdateLeadFromSplashCampaigns (){ 
        Test.startTest();
        lstCampaigns = [SELECT Id, Name, City__c, State__c, Email_Address__c, Type, Lead_Owner__c, StartDate FROM Campaign WHERE Id IN: lstCampaigns];
        debug.log('lstCampaigns: '+lstCampaigns);
        CampaignMemberStatus cmStatus = new CampaignMemberStatus(CampaignId = lstCampaigns[0].Id, IsDefault = true, HasResponded = true, Label='RSVP_Yes', SortOrder = 3);
        insert cmStatus;
        System.assertNotEquals(null, cmStatus.Id);
        List<CampaignMember> lstCampaignMembers = new List<CampaignMember>();
        lstCampaignMembers.add(new CampaignMember(LeadId = lstLeads[0].Id, CampaignId = lstCampaigns[1].Id));
        lstCampaignMembers.add(new CampaignMember(LeadId = lstLeads[1].Id, CampaignId = lstCampaigns[0].Id, Status = 'RSVP_Yes'));
        lstCampaignMembers.add(new CampaignMember(LeadId = lstLeads[2].Id, CampaignId = lstCampaigns[0].Id, Status = 'RSVP_Yes'));
        lstCampaignMembers.add(new CampaignMember(LeadId = lstLeads[3].Id, CampaignId = lstCampaigns[2].Id));
        TestingUtility.insertListWithAssert(lstCampaignMembers);
        Test.stopTest();
        
        for(Lead leadRec : [SELECT Last_Event_Name__c, Last_Event_Date__c, City, State FROM Lead]){
            debug.log('leadRec in testmethod: '+leadRec);
            debug.log('lstCampaigns in testmethod: '+lstCampaigns);
            if(leadRec.Id == lstLeads[0].Id ){              
                System.assertEquals(lstCampaigns[0].City__c, leadRec.City );
                System.assertEquals(lstCampaigns[0].State__c, leadRec.State );
            }else if(leadRec.Id == lstLeads[1].Id ){
                System.assertEquals(lstCampaigns[0].City__c, leadRec.City );
                System.assertEquals(lstCampaigns[0].State__c, leadRec.State );
                System.assertEquals(lstCampaigns[0].Name, leadRec.Last_Event_Name__c );
                System.assertEquals(lstCampaigns[0].StartDate, leadRec.Last_Event_Date__c );
            }else if(leadRec.Id == lstLeads[2].Id ){
                System.assertEquals(lstCampaigns[0].City__c, leadRec.City );
                System.assertEquals(lstCampaigns[0].State__c, leadRec.State );
                System.assertEquals(lstCampaigns[0].Name, leadRec.Last_Event_Name__c );
                System.assertEquals(lstCampaigns[0].StartDate, leadRec.Last_Event_Date__c );
            }else if(leadRec.Id == lstLeads[3].Id ){
                System.assertEquals(lstCampaigns[2].City__c, leadRec.City );
                System.assertEquals(lstCampaigns[2].State__c, leadRec.State );
            }
        }
    }
    
    @isTest
    public static void testCampaignMemberFromSplashCampaigns(){ 
        Test.startTest();
        lstCampaigns = [SELECT Id, Name, City__c, State__c, Email_Address__c, Type, Lead_Owner__c, StartDate FROM Campaign WHERE Id IN: lstCampaigns];
        CampaignMemberStatus cmStatus = new CampaignMemberStatus(CampaignId = lstCampaigns[0].Id, IsDefault = true, HasResponded = true, Label='RSVP_Yes', SortOrder = 3);
        insert cmStatus;
        System.assertNotEquals(null, cmStatus.Id);
        List<CampaignMember> lstCampaignMembers = new List<CampaignMember>();
        lstCampaignMembers.add(new CampaignMember(LeadId = lstLeads[0].Id, CampaignId = lstCampaigns[1].Id));
        lstCampaignMembers.add(new CampaignMember(LeadId = lstLeads[1].Id, CampaignId = lstCampaigns[0].Id));
        lstCampaignMembers.add(new CampaignMember(LeadId = lstLeads[2].Id, CampaignId = lstCampaigns[0].Id));
        lstCampaignMembers.add(new CampaignMember(LeadId = lstLeads[3].Id, CampaignId = lstCampaigns[2].Id));
        TestingUtility.insertListWithAssert(lstCampaignMembers);        
        lstCampaignMembers[1].Status = 'RSVP_Yes'; 
        lstCampaignMembers[2].Status = 'RSVP_Yes'; 
        TestingUtility.updateListWithAssert(lstCampaignMembers);
        Test.stopTest();        
        for(Lead leadRec : [SELECT Last_Event_Name__c, Last_Event_Date__c, City, State FROM Lead]){
            if(leadRec.Id == lstLeads[0].Id ){              
                System.assertEquals(lstCampaigns[0].City__c, leadRec.City );
                System.assertEquals(lstCampaigns[0].State__c, leadRec.State );
            }else if(leadRec.Id == lstLeads[1].Id ){
                System.assertEquals(lstCampaigns[0].City__c, leadRec.City );
                System.assertEquals(lstCampaigns[0].State__c, leadRec.State );
                System.assertEquals(lstCampaigns[0].Name, leadRec.Last_Event_Name__c );
                System.assertEquals(lstCampaigns[0].StartDate, leadRec.Last_Event_Date__c );
            }else if(leadRec.Id == lstLeads[2].Id ){
                System.assertEquals(lstCampaigns[0].City__c, leadRec.City );
                System.assertEquals(lstCampaigns[0].State__c, leadRec.State );
                System.assertEquals(lstCampaigns[0].Name, leadRec.Last_Event_Name__c );
                System.assertEquals(lstCampaigns[0].StartDate, leadRec.Last_Event_Date__c );
            }else if(leadRec.Id == lstLeads[3].Id ){
                System.assertEquals(lstCampaigns[2].City__c, leadRec.City );
                System.assertEquals(lstCampaigns[2].State__c, leadRec.State );
            }
        }
    }
   
}