objects/Account.object
<CustomObject>
    <fields>
        <fullName>Authorized_Signatory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Authorized Signatory</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts (Authorized Signatory)</relationshipLabel>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Paperwork will be sent to the primary member on the ACCOUNT</inlineHelpText>
        <label>Main Contact</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.Account.Id</field>
                <operation>equals</operation>
                <valueField>$Source.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UUID__c</fullName>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Building__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>UUID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Building</label>
    <nameField>
        <label>Building</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Actual_Start_Date__c</fullName>
        <formula>Account.Start_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Actual Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Building__c</fullName>
        <description>Pulls Building Location without 3 character city reference</description>
        <formula>Location__r.Location_No_City__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Building</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Member__c</fullName>
        <formula>if( Billing_Account__r.Primary_Member__r.Id =  Id , "Yes","No")</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Primary Member</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reservable__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reservable</label>
        <referenceTo>Reservable__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This is the latest status coming from Space systems through Jitterbunny of the individual member. This tells us if the user is active or not.</description>
        <inlineHelpText>This is accurate status of a contact if it is an active member of our products or not.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>active</fullName>
                </value>
                <value>
                    <fullName>inactive</fullName>
                    <default>true</default>
                    <label>inactive</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UUID__c</fullName>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Actual_Start_Date__c</fullName>
        <inlineHelpText>This is the Expected Start Date until Closed Won</inlineHelpText>
        <label>Actual Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Building__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Enter the specific building for which opportunity is associated</description>
        <inlineHelpText>This is the building / Nearest building to the geography entered by customer</inlineHelpText>
        <label>Building/Nearest Building</label>
        <referenceTo>Building__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Encoded_ID__c</fullName>
        <label>Encoded ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Reservable__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity Reservable</label>
        <referenceTo>Opportunity_Reservable__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Member__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>This is the Main Contact of the Opportunity</inlineHelpText>
        <label>Main Contact</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity_Reservable__c.object
<CustomObject>
    <fields>
        <fullName>Building__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>When we get building uuid insted of reservable uuid in Contract event payload map here.</description>
        <inlineHelpText>When we get building uuid insted of reservable uuid in Contract event payload map here.</inlineHelpText>
        <label>Sellable Building</label>
        <referenceTo>Building__c</referenceTo>
        <relationshipLabel>Opportunity Reservables</relationshipLabel>
        <relationshipName>Opportunity_Reservables</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Reservables</relationshipLabel>
        <relationshipName>Opportunity_Offices</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reservable__c</fullName>
        <label>Reservable</label>
        <referenceTo>Reservable__c</referenceTo>
        <relationshipLabel>Opportunity Reservables</relationshipLabel>
        <relationshipName>Opportunity_Offices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Opportunity Reservable</label>
    <nameField>
        <displayFormat>OO-{0000}</displayFormat>
        <label>Office ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Reservables</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Reservable__c.object
<CustomObject>
    <fields>
        <fullName>Archived_On__c</fullName>
        <label>Archived On</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Building__c</fullName>
        <label>Building</label>
        <referenceTo>Building__c</referenceTo>
        <relationshipLabel>Reservables</relationshipLabel>
        <relationshipName>Offices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Next_Move_Out__c</fullName>
        <label>Next Move Out</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Office_Work_Station_Type__c</fullName>
        <label>Office/Work Station Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>HotDeskArea</fullName>
                </value>
                <value>
                    <fullName>DedicatedDesk</fullName>
                </value>
                <value>
                    <fullName>HotDesk</fullName>
                </value>
                <value>
                    <fullName>Office</fullName>
                </value>
                <value>
                    <fullName>ResidentialUnit</fullName>
                </value>
                <value>
                    <fullName>SharedOfficeDesk</fullName>
                </value>
                <value>
                    <fullName>Bed</fullName>
                </value>
                <value>
                    <fullName>VirtualReservable</fullName>
                </value>
                <value>
                    <fullName>HQbyWeWork</fullName>
                </value>
                <value>
                    <fullName>WWLO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Open_Date__c</fullName>
        <label>Open Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Available</fullName>
                </value>
                <value>
                    <fullName>Unavailable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UUID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Reservable</label>
    <nameField>
        <label>Reservable Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reservables</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/SendContractControllerTest.cls
@isTest
private class SendContractControllerTest {
    static{
        SalesConsoleSettings.createSettings();
    }     
	@isTest static void test_success() {
		//pre-context
			Account a = new Account(
				name = 'S.H.I.E.L.D.'
			);
			insert a;

			Contact nick = new Contact(
				firstname = 'Nick',
				lastname = 'Fury',
				email = 'nick@shield.com',
				AccountID = a.Id
			);
			insert nick;

			Contact steve = new Contact(
				firstname = 'Steve',
				lastname = 'Rogers',
				email = 'captain_america@shield.com',
				AccountID = a.Id
			);
			insert steve;

			a.Primary_Member__c = steve.Id;
			a.Authorized_Signatory__c = nick.Id;
			update a;

			Building__c b = new Building__c(
				name = 'Stark Tower',
				uuid__c = 'abc1234',
				email__c = 'fultoncenter@wework.com'
			);
			insert b;

			Opportunity o = new Opportunity(
				AccountID = a.Id,
				StageName = 'Qualifying',
				CloseDate = system.today(),
				Building__c = b.Id,
				name 			= 'Test Opportunity',
				Actual_Start_Date__c = date.today(),
				Primary_Member__c = steve.Id,
				Encoded_ID__c = '123'
			);
			insert o;

			// to avoid validation error
			Reservable__c r = new Reservable__c(Name='r1',Building__c=b.Id, Status__c = 'Available', Open_Date__c = date.today());
			insert r;
			Opportunity_Reservable__c res = new Opportunity_Reservable__c(Reservable__c=r.Id, Opportunity__c=o.Id);
			insert res;

		//test
		Test.startTest();
	
			//create controller
			SendContractController controller = new SendContractController();
			controller.OpportunityID = o.Id;
			controller.sendContract();

			//re-query
			o = [	SELECT StageName 
						FROM Opportunity 
						WHERE Id = :o.Id 
						LIMIT 1
					];		

			//assert
			system.assertEquals(
				'Closing', 
				o.StageName, 
				'The contract should be marked as sent'
			);

			system.assertNotEquals(
				null,
				controller.goBack(),
				'The page reference must be declared!'
			);

		Test.stopTest();
	}

	@isTest static void test_failure_reservable_not_available_1() {
		//pre-context
			Account a = new Account(
				name = 'S.H.I.E.L.D.'
			);
			insert a;

			Contact nick = new Contact(
				firstname = 'Nick',
				lastname = 'Fury',
				email = 'nick@shield.com',
				AccountID = a.Id
			);
			insert nick;

			Contact steve = new Contact(
				firstname = 'Steve',
				lastname = 'Rogers',
				email = 'captain_america@shield.com',
				AccountID = a.Id
			);
			insert steve;

			a.Primary_Member__c = steve.Id;
			a.Authorized_Signatory__c = nick.Id;
			update a;

			Building__c b = new Building__c(
				name = 'Stark Tower',
				uuid__c = 'abc1234',
				email__c = 'fultoncenter@wework.com'
			);
			insert b;

			Opportunity o = new Opportunity(
				AccountID = a.Id,
				StageName = 'Qualifying',
				CloseDate = system.today(),
				Building__c = b.Id,
				name 			= 'Test Opportunity',
				Actual_Start_Date__c = date.today(),
				Primary_Member__c = steve.Id,
				Encoded_ID__c = '123'
			);
			insert o;

			// to avoid validation error
			Reservable__c r = new Reservable__c(Name='r1',Building__c=b.Id, Status__c = 'Unvailable', Open_Date__c = date.today());
			insert r;
			Opportunity_Reservable__c res = new Opportunity_Reservable__c(Reservable__c=r.Id, Opportunity__c=o.Id);
			insert res;

		//test
		Test.startTest();
	
			//create controller
			SendContractController controller = new SendContractController();
			controller.OpportunityID = o.Id;
			controller.sendContract();

			//re-query
			o = [	SELECT StageName 
						FROM Opportunity 
						WHERE Id = :o.Id 
						LIMIT 1
					];		

			//assert
			/*system.assertEquals(
				'Closing', 
				o.StageName, 
				'The contract should not be marked as sent with Unvailable reservables'
			);*/

		Test.stopTest();
	}

	@isTest static void test_failure_reservable_not_available_2() {
		//pre-context
			Account a = new Account(
				name = 'S.H.I.E.L.D.'
			);
			insert a;

			Contact nick = new Contact(
				firstname = 'Nick',
				lastname = 'Fury',
				email = 'nick@shield.com',
				AccountID = a.Id
			);
			insert nick;

			Contact steve = new Contact(
				firstname = 'Steve',
				lastname = 'Rogers',
				email = 'captain_america@shield.com',
				AccountID = a.Id
			);
			insert steve;

			a.Primary_Member__c = steve.Id;
			a.Authorized_Signatory__c = nick.Id;
			update a;

			Building__c b = new Building__c(
				name = 'Stark Tower',
				uuid__c = 'abc1234',
				email__c = 'fultoncenter@wework.com'
			);
			insert b;

			Opportunity o = new Opportunity(
				AccountID = a.Id,
				StageName = 'Qualifying',
				CloseDate = system.today(),
				Building__c = b.Id,
				name 			= 'Test Opportunity',
				Actual_Start_Date__c = date.today(),
				Primary_Member__c = steve.Id,
				Encoded_ID__c = '123'
			);
			insert o;

			// to avoid validation error
			Reservable__c r = new Reservable__c(Name='r1',Building__c=b.Id, Status__c = 'Available', Archived_On__c = Date.today(), Open_Date__c = date.today() );
			insert r;
			Opportunity_Reservable__c res = new Opportunity_Reservable__c(Reservable__c=r.Id, Opportunity__c=o.Id);
			insert res;

		//test
		Test.startTest();
	
			//create controller
			SendContractController controller = new SendContractController();
			controller.OpportunityID = o.Id;
			controller.sendContract();

			//re-query
			o = [	SELECT StageName 
						FROM Opportunity 
						WHERE Id = :o.Id 
						LIMIT 1
					];		

			//assert
			/*system.assertEquals(
				'Closing', 
				o.StageName, 
				'The contract should not be marked as sent with Unvailable reservables'
			);*/

		Test.stopTest();
	}

	@isTest static void test_failure_reservable_not_available_3() {
		//pre-context
			Account a = new Account(
				name = 'S.H.I.E.L.D.'
			);
			insert a;

			Contact nick = new Contact(
				firstname = 'Nick',
				lastname = 'Fury',
				email = 'nick@shield.com',
				AccountID = a.Id
			);
			insert nick;

			Contact steve = new Contact(
				firstname = 'Steve',
				lastname = 'Rogers',
				email = 'captain_america@shield.com',
				AccountID = a.Id
			);
			insert steve;

			a.Primary_Member__c = steve.Id;
			a.Authorized_Signatory__c = nick.Id;
			update a;

			Building__c b = new Building__c(
				name = 'Stark Tower',
				uuid__c = 'abc1234',
				email__c = 'fultoncenter@wework.com'
			);
			insert b;

			Opportunity o = new Opportunity(
				AccountID = a.Id,
				StageName = 'Qualifying',
				CloseDate = system.today(),
				Building__c = b.Id,
				name 			= 'Test Opportunity',
				Actual_Start_Date__c = date.today(),
				Primary_Member__c = steve.Id,
				Encoded_ID__c = '123'
			);
			insert o;

			// to avoid validation error
			Reservable__c r = new Reservable__c(Name='r1',Building__c=b.Id, Open_Date__c = date.today());
			insert r;
			Opportunity_Reservable__c res = new Opportunity_Reservable__c(Reservable__c=r.Id, Opportunity__c=o.Id);
			insert res;

		//test
		Test.startTest();
	
			//create controller
			SendContractController controller = new SendContractController();
			controller.OpportunityID = o.Id;
			controller.sendContract();

			//re-query
			o = [	SELECT StageName 
						FROM Opportunity 
						WHERE Id = :o.Id 
						LIMIT 1
					];		

			//assert
			/*system.assertEquals(
				'Closing', 
				o.StageName, 
				'The contract should not be marked as sent with Unvailable reservables'
			);*/

		Test.stopTest();
	}

	@isTest static void test_failure_reservable_already_used_1() {
		//pre-context
			Account a = new Account(
				name = 'S.H.I.E.L.D.'
			);
			insert a;

			Contact nick = new Contact(
				firstname = 'Nick',
				lastname = 'Fury',
				email = 'nick@shield.com',
				AccountID = a.Id
			);
			insert nick;

			Contact steve = new Contact(
				firstname = 'Steve',
				lastname = 'Rogers',
				email = 'captain_america@shield.com',
				AccountID = a.Id
			);
			insert steve;

			a.Primary_Member__c = steve.Id;
			a.Authorized_Signatory__c = nick.Id;
			update a;

			Building__c b = new Building__c(
				name = 'Stark Tower',
				uuid__c = 'abc1234',
				email__c = 'fultoncenter@wework.com'
			);
			insert b;

			Opportunity o = new Opportunity(
				AccountID = a.Id,
				StageName = 'Qualifying',
				CloseDate = system.today(),
				Building__c = b.Id,
				name 			= 'Test Opportunity',
				Actual_Start_Date__c = date.today(),
				Primary_Member__c = steve.Id,
				Encoded_ID__c = '123'
			);
			insert o;

			// to avoid validation error
			Reservable__c r = new Reservable__c(Name='r1',Building__c=b.Id, Status__c = 'Available', Open_Date__c = date.today());
			insert r;
			Opportunity_Reservable__c res = new Opportunity_Reservable__c(Reservable__c=r.Id, Opportunity__c=o.Id);
			insert res;

			//create another opportunity
			Opportunity o2 = new Opportunity(
				AccountID = a.Id,
				StageName = 'Qualifying',
				CloseDate = system.today(),
				Building__c = b.Id,
				name 			= 'Test Opportunity',
				Actual_Start_Date__c = date.today()
			);
			insert o2;

			//create an opportunity reservable for the same reservable as before
			Opportunity_Reservable__c res2 = new Opportunity_Reservable__c(Reservable__c=r.Id, Opportunity__c=o2.Id);
			insert res2;

		//test
		Test.startTest();
	
			//create controller
			SendContractController controller = new SendContractController();
			controller.OpportunityID = o.Id;
			controller.sendContract();

			//re-query
			o = [	SELECT StageName 
						FROM Opportunity 
						WHERE Id = :o.Id 
						LIMIT 1
					];		

			//assert
			system.assertEquals(
				'Closing', 
				o.StageName, 
				'The contract should be marked as sent with available reservables'
			);

			//now that the reservable is on an opportunity with status Contract sent
			//another opportunity can't send contract if it references that reservable
			controller.OpportunityID = o2.Id;
			controller.sendContract();

			//re-query
			o2 = [	SELECT StageName 
						FROM Opportunity 
						WHERE Id = :o2.Id 
						LIMIT 1
					];		

			//assert
			/*system.assertEquals(
				'Closing', 
				o2.StageName, 
				'The contract should not be marked as sent with an already used reservable'
			);*/

		Test.stopTest();
	}

	@isTest static void test_success_reservable_already_used_hot_desk() {
		//pre-context
			Account a = new Account(
				name = 'S.H.I.E.L.D.'
			);
			insert a;

			Contact nick = new Contact(
				firstname = 'Nick',
				lastname = 'Fury',
				email = 'nick@shield.com',
				AccountID = a.Id
			);
			insert nick;

			Contact steve = new Contact(
				firstname = 'Steve',
				lastname = 'Rogers',
				email = 'captain_america@shield.com',
				AccountID = a.Id
			);
			insert steve;

			a.Primary_Member__c = steve.Id;
			a.Authorized_Signatory__c = nick.Id;
			update a;

			Building__c b = new Building__c(
				name = 'Stark Tower',
				uuid__c = 'abc1234',
				email__c = 'fultoncenter@wework.com'
			);
			insert b;

			Opportunity o = new Opportunity(
				AccountID = a.Id,
				StageName = 'Qualifying',
				CloseDate = system.today(),
				Building__c = b.Id,
				name 			= 'Test Opportunity',
				Actual_Start_Date__c = date.today(),
				Primary_Member__c = steve.Id,
				Encoded_ID__c = '123'
			);
			insert o;

			// to avoid validation error
			Reservable__c r = new Reservable__c(Name='r1',Building__c=b.Id, Status__c = 'Available', Office_Work_Station_Type__c = 'HotDeskArea', Open_Date__c = date.today());
			insert r;
			Opportunity_Reservable__c res = new Opportunity_Reservable__c(Reservable__c=r.Id, Opportunity__c=o.Id );
			insert res;

			//create another opportunity
			Opportunity o2 = new Opportunity(
				AccountID = a.Id,
				StageName = 'Qualifying',
				CloseDate = system.today(),
				Building__c = b.Id,
				name 			= 'Test Opportunity',
				Actual_Start_Date__c = date.today(),
				Primary_Member__c = steve.Id,
				Encoded_ID__c = '123'
			);
			insert o2;

			//create an opportunity reservable for the same reservable as before
			Opportunity_Reservable__c res2 = new Opportunity_Reservable__c(Reservable__c=r.Id, Opportunity__c=o2.Id);
			insert res2;

		//test
		Test.startTest();
	
			//create controller
			SendContractController controller = new SendContractController();
			controller.OpportunityID = o.Id;
			controller.sendContract();

			//re-query
			o = [	SELECT StageName 
						FROM Opportunity 
						WHERE Id = :o.Id 
						LIMIT 1
					];		

			//assert
			/*system.assertEquals(
				'Closing', 
				o.StageName, 
				'The contract should be marked as sent with available reservables'
			);*/

			//now that the reservable is on an opportunity with status Contract sent
			//another opportunity can send contract if it references that reservable (hot desk)
			controller.OpportunityID = o2.Id;
			controller.sendContract();

			//re-query
			o2 = [	SELECT StageName 
						FROM Opportunity 
						WHERE Id = :o2.Id 
						LIMIT 1
					];		

			//assert
			/*system.assertEquals(
				'Closing', 
				o2.StageName, 
				'The contract should be marked as sent with an already used reservable (hot desk)'
			);*/

		Test.stopTest();
	}

	@isTest static void test_failure_reservable_not_open_1() {
		//pre-context
			Account a = new Account(
				name = 'S.H.I.E.L.D.'
			);
			insert a;

			Contact nick = new Contact(
				firstname = 'Nick',
				lastname = 'Fury',
				email = 'nick@shield.com',
				AccountID = a.Id
			);
			insert nick;

			Contact steve = new Contact(
				firstname = 'Steve',
				lastname = 'Rogers',
				email = 'captain_america@shield.com',
				AccountID = a.Id
			);
			insert steve;

			a.Primary_Member__c = steve.Id;
			a.Authorized_Signatory__c = nick.Id;
			update a;

			Building__c b = new Building__c(
				name = 'Stark Tower',
				uuid__c = 'abc1234',
				email__c = 'fultoncenter@wework.com'
			);
			insert b;

			Opportunity o = new Opportunity(
				AccountID = a.Id,
				StageName = 'Qualifying',
				CloseDate = system.today(),
				Building__c = b.Id,
				name 			= 'Test Opportunity',
				Actual_Start_Date__c = date.today()
			);
			insert o;

			// create reservable that will open next month
			Reservable__c r = new Reservable__c(Name='r1',Building__c=b.Id, Status__c = 'Available', Open_Date__c = date.today().addMonths(1));
			insert r;
			Opportunity_Reservable__c res = new Opportunity_Reservable__c(Reservable__c=r.Id, Opportunity__c=o.Id);
			insert res;

		//test
		Test.startTest();
	
			//create controller
			SendContractController controller = new SendContractController();
			controller.OpportunityID = o.Id;
			controller.sendContract();

			//re-query
			o = [	SELECT StageName 
						FROM Opportunity 
						WHERE Id = :o.Id 
						LIMIT 1
					];		

			//assert
			/*system.assertEquals(
				'Closing', 
				o.StageName, 
				'The contract should not be marked as sent because an associated reservable was not opened'
			);*/

		Test.stopTest();
	}

	@isTest static void test_failure_reservable_next_move_out_1() {
		//pre-context
			Account a = new Account(
				name = 'S.H.I.E.L.D.'
			);
			insert a;

			Contact nick = new Contact(
				firstname = 'Nick',
				lastname = 'Fury',
				email = 'nick@shield.com',
				AccountID = a.Id
			);
			insert nick;

			Contact steve = new Contact(
				firstname = 'Steve',
				lastname = 'Rogers',
				email = 'captain_america@shield.com',
				AccountID = a.Id
			);
			insert steve;

			a.Primary_Member__c = steve.Id;
			a.Authorized_Signatory__c = nick.Id;
			update a;

			Building__c b = new Building__c(
				name = 'Stark Tower',
				uuid__c = 'abc1234',
				email__c = 'fultoncenter@wework.com'
			);
			insert b;

			Opportunity o = new Opportunity(
				AccountID = a.Id,
				StageName = 'Qualifying',
				CloseDate = system.today(),
				Building__c = b.Id,
				name 			= 'Test Opportunity',
				Actual_Start_Date__c = date.today()
			);
			insert o;

			// create reservable that will open next month
			Reservable__c r = new Reservable__c(Name='r1',Building__c=b.Id, Status__c = 'Available', Next_Move_Out__c = date.today().addMonths(1));
			insert r;
			Opportunity_Reservable__c res = new Opportunity_Reservable__c(Reservable__c=r.Id, Opportunity__c=o.Id);
			insert res;

		//test
		Test.startTest();
	
			//create controller
			SendContractController controller = new SendContractController();
			controller.OpportunityID = o.Id;
			controller.sendContract();

			//re-query
			o = [	SELECT StageName 
						FROM Opportunity 
						WHERE Id = :o.Id 
						LIMIT 1
					];		

			//assert
			/*system.assertEquals(
				'Closing', 
				o.StageName, 
				'The contract should not be marked as sent because an associated reservable has a next moved out date AFTER Opportunity actual start date' 
			);*/

		Test.stopTest();
	}

	@isTest static void test_x() {
		//pre-context
	
		//test
		Test.startTest();
			//create controller
			SendContractController controller = new SendContractController();
			controller.OpportunityID = null;
			controller.sendContract();

			System.assert(ApexPages.getMessages().size() > 0);

			system.assertNotEquals(
				null,
				controller.goBack(),
				'The page reference must be declared!'
			);

		Test.stopTest();
	}
	
}