objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <description>This is Picklist which Contains three values
1. Org : It is Main account in hierarchy which is Parent Account of Sales And Bill.
2. Sales: One Sales Account may contain multiple Bill Or Sales Account and It is Under Org Account in hierarchy
3. Bill: Bill Account is under Sales or Org. It never child of Bill Account.
4. ' '(Blank) : It is like Bill type which is under Sales or Org.</description>
        <inlineHelpText>This Picklist is used to determine the account type.</inlineHelpText>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Org</fullName>
                    <default>true</default>
                    <label>Org</label>
                </value>
                <value>
                    <fullName>Sales</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cleansed_Unomy_Company_Name__c</fullName>
        <description>This field is used to save cleansed unomy company name</description>
        <label>Cleansed Unomy Company Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Locale__c</fullName>
        <label>Locale</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>af</fullName>
                </value>
                <value>
                    <fullName>af-ZA</fullName>
                </value>
                <value>
                    <fullName>sq</fullName>
                </value>
                <value>
                    <fullName>sq-AL</fullName>
                </value>
                <value>
                    <fullName>gsw-FR</fullName>
                </value>
                <value>
                    <fullName>am-ET</fullName>
                </value>
                <value>
                    <fullName>ar</fullName>
                </value>
                <value>
                    <fullName>ar-DZ</fullName>
                </value>
                <value>
                    <fullName>ar-BH</fullName>
                </value>
                <value>
                    <fullName>ar-EG</fullName>
                </value>
                <value>
                    <fullName>ar-IQ</fullName>
                </value>
                <value>
                    <fullName>ar-JO</fullName>
                </value>
                <value>
                    <fullName>ar-KW</fullName>
                </value>
                <value>
                    <fullName>ar-LB</fullName>
                </value>
                <value>
                    <fullName>ar-LY</fullName>
                </value>
                <value>
                    <fullName>ar-MA</fullName>
                </value>
                <value>
                    <fullName>ar-OM</fullName>
                </value>
                <value>
                    <fullName>ar-QA</fullName>
                </value>
                <value>
                    <fullName>ar-SA</fullName>
                </value>
                <value>
                    <fullName>ar-SY</fullName>
                </value>
                <value>
                    <fullName>ar-TN</fullName>
                </value>
                <value>
                    <fullName>ar-AE</fullName>
                </value>
                <value>
                    <fullName>ar-YE</fullName>
                </value>
                <value>
                    <fullName>hy</fullName>
                </value>
                <value>
                    <fullName>hy-AM</fullName>
                </value>
                <value>
                    <fullName>as-IN</fullName>
                </value>
                <value>
                    <fullName>az</fullName>
                </value>
                <value>
                    <fullName>az-Cyrl-AZ</fullName>
                </value>
                <value>
                    <fullName>az-Latn-AZ</fullName>
                </value>
                <value>
                    <fullName>ba-RU</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Parent_Account__c</fullName>
        <formula>CASESAFEID(ParentId)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Parent Account(Pipeline Reporting)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Org_Id__c</fullName>
        <description>Shows the ID of the Ultimate Org when we have the multi-level hierarchy.</description>
        <formula>IF(ISBLANK(Parent.Id), null, IF(ISBLANK(Parent.Parent.Id), Parent.Id,IF(ISBLANK(Parent.Parent.Parent.Id), Parent.Parent.Id,IF(ISBLANK(Parent.Parent.Parent.Parent.Id), Parent.Parent.Parent.Id,IF(ISBLANK(Parent.Parent.Parent.Parent.Parent.Id), Parent.Parent.Parent.Parent.Id,Parent.Parent.Parent.Parent.Parent.Id)))))</formula>
        <inlineHelpText>Shows the ID of the Ultimate Org when we have the multi-level hierarchy.</inlineHelpText>
        <label>Parent Org Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UUID__c</fullName>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Unomy_Company_ID__c</fullName>
        <externalId>true</externalId>
        <label>Unomy Company ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unomy_Company_Name__c</fullName>
        <label>Unomy Company Name</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Billing_Account__c.object
<CustomObject>
    <fields>
        <fullName>Cleansed_Unomy_Company_Name__c</fullName>
        <description>This field is used to save cleansed version of unomy company name by removing suffix,prefix and special character based on AccountCleansingSetting  sales console setting</description>
        <inlineHelpText>This field is used to save cleansed version of unomy company name by removing suffix,prefix and special character based on AccountCleansingSetting  sales console setting</inlineHelpText>
        <label>Cleansed Unomy Company Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is lookup to the Parent Account</description>
        <inlineHelpText>This is lookup to the Parent Account</inlineHelpText>
        <label>Parent Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UUID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>This is unique,case sensitive auto generated field used to identify Billing Account record.</description>
        <externalId>true</externalId>
        <inlineHelpText>This is unique,case sensitive auto generated field used to identify Billing Account record.</inlineHelpText>
        <label>UUID</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Ultimate_Parent_Org__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Shows the Ultimate Org when we have the multi-level hierarchy.</description>
        <inlineHelpText>Shows the Ultimate Org when we have the multi-level hierarchy.</inlineHelpText>
        <label>Ultimate Parent Org</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts (Ultimate Parent Org Name)</relationshipLabel>
        <relationshipName>Billing_Accounts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unomy_Company_ID__c</fullName>
        <externalId>true</externalId>
        <label>Unomy Company ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unomy_Company_Name__c</fullName>
        <label>Unomy Company Name</label>
        <type>TextArea</type>
    </fields>
    <description>All Billing account is moved to this Billing Account object it help Sales people to identify Org and Sales account easily and reduce the clutter of 100s of Accounts with same name.</description>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <formula>Account.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Type__c</fullName>
        <formula>text(Account.Type)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Members</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cleansed_Company_Name__c</fullName>
        <externalId>true</externalId>
        <label>Cleansed Company Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cleansed_Unomy_Company_Name__c</fullName>
        <description>This field contains Cleansed Unomy Company Name value</description>
        <label>Cleansed Unomy Company Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <label>Company</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_Domain__c</fullName>
        <formula>RIGHT(Email,LEN(Email)-FIND('@',Email))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Email Domain</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Source_Detail__c</fullName>
        <description>This field captures the information from where the lead is coming.</description>
        <inlineHelpText>This field captures the information from where the lead is coming.</inlineHelpText>
        <label>Lead Source Detail</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Licensee</fullName>
                </value>
                <value>
                    <fullName>Employee</fullName>
                </value>
                <value>
                    <fullName>Member</fullName>
                </value>
                <value>
                    <fullName>Broker</fullName>
                </value>
                <value>
                    <fullName>Affiliate</fullName>
                </value>
                <value>
                    <fullName>Potential</fullName>
                </value>
                <value>
                    <fullName>Lead</fullName>
                </value>
                <value>
                    <fullName>Unqualified Broker</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UUID__c</fullName>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Unomy_Company_ID__c</fullName>
        <label>Unomy Company ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unomy_Company_Name__c</fullName>
        <label>Unomy Company Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>utm_campaign__c</fullName>
        <label>utm_campaign</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>utm_campaign_id__c</fullName>
        <label>utm_campaign id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>utm_content__c</fullName>
        <label>utm_content</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>utm_medium__c</fullName>
        <label>utm_medium</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>utm_source__c</fullName>
        <label>utm_source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>utm_term__c</fullName>
        <label>utm_term</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Market__c.object
<CustomObject>
    <fields>
        <fullName>UUID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <description>We are introducing new object Market so that same building can fall under multiple Markets as per Marketing department requirement.</description>
    <label>Portfolio</label>
    <nameField>
        <label>Portfolio</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portfolios</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/PersonEndpointHelper.cls
/************************************************************************************************************************************
    Author      :   Ajaysinh Chauhan    
    Description :   This class contain a logic of Person Endpoint.....
    
    History     :
    ----------------------------------------------------------------------------------------------------------------------------------
    VERSION     DATE                AUTHOR                  DETAIL
    1           19 June 2018        Ajaysinh Chauhan        Initial Developement
    2           22 June 2018        Krishana Tupe           Changes and API Versioning
  	3           31 July 2018        Krishana Tupe           Implementation of Person endpoint version 4
**************************************************************************************************************************************/
public class PersonEndpointHelper {
    public static Id personContactId;
    /************************************************************************************************************************************
        Author              :   Krishana Tupe
        Description         :   This method has business logic of person endpoint.
        Created Date        :   31 July 2018 
   **************************************************************************************************************************************/    
    public static Map<String,String> managePerson(RESTAPIPersonModelsV2.Input body){        
        Debug.log('body==>'+body);
         Contact contactRecord = new Contact();
        if(String.isNotBlank(body.email)){                      
            String query = 'Select Id,Name,Billing_Account__c,Unomy_Company_Name__c,Billing_Account__r.Parent_Account__c,Account.Parent_Org_Id__c,Account_Name__c,Billing_Account__r.Ultimate_Parent_Org__c,Billing_Account__r.UUID__c,AccountId,Account.Name,Account.Account_Type__c,UUID__c,Email,Email_Domain__c,Company__c,Cleansed_Company_Name__c,Unomy_Company_Id__c,Cleansed_Unomy_Company_Name__c,FirstName,LastName,Phone,Type__c,LeadSource,Lead_Source_Detail__c,utm_campaign_id__c,utm_campaign__c,utm_content__c,utm_medium__c,utm_source__c,utm_term__c,Locale__c,Country_Code__c From Contact Where Email=\''+body.email+'\'';   
            List<Contact> lstPersonContacts = (List<Contact>)Database.query(query);
            Debug.log('lstPersonContacts==>'+lstPersonContacts);
            Contact objPersonContact;
            if(lstPersonContacts.size()>0){
                objPersonContact = lstPersonContacts[0];
                if(String.isBlank(objPersonContact.AccountId)){
                    if(String.isNotBlank(body.type) && body.type.equalsIgnoreCase('broker')){
                    	personContactId = objPersonContact.Id;    
                    }                    
                    objPersonContact.AccountId = OrganizationHelper.findOrCreateRelatedOrg(objPersonContact);
                    update objPersonContact;
                }
                if(String.isNotBlank(objPersonContact.Billing_Account__c)){
                    if(String.isBlank(objPersonContact.Billing_Account__r.Parent_Account__c)){
                        Billing_Account__c objBillingAccount = new Billing_Account__c(); 
                        objBillingAccount.Parent_Account__c = objPersonContact.AccountId; 
                        objBillingAccount.Id = objPersonContact.Billing_Account__c;
                        update objBillingAccount;
                    }
                    contactRecord = fillContactByPerson(body,objPersonContact);
                    contactRecord.Id = objPersonContact.Id;
                    update contactRecord;                             
                }else{
                    contactRecord.Id = createPersonStructure(body,objPersonContact);
                    contactRecord = fillContactByPerson(body,objPersonContact);
                    update contactRecord;
                }               
            }else{               
                contactRecord.Id = createPersonStructure(body,null); 
            }            
        }else{
            throw new RESTAPIPersonV2.PersonEndpointException('Email is required.');   
        } 
        if(String.isNotBlank(contactRecord.Id)){
            Contact conRecord = [Select Id,Name,AccountId,Billing_Account__c,UUID__c FROM Contact Where Id=:contactRecord.Id];
            return new Map<String, String>{'contact_sfid'=>conRecord.Id,'account_sfid'=> conRecord.AccountId,'billing_account_sfid'=> conRecord.Billing_Account__c,'contact_uuid'=> conRecord.UUID__c};  
                }
        return null;
    }
    /************************************************************************************************************************************
        Author              :   Krishana Tupe
        Description         :   This method is used to create new contact for personn endpoint with billing account.
        Created Date        :   31 July 2018 
   **************************************************************************************************************************************/ 
    public static Id createPersonStructure(RESTAPIPersonModelsV2.Input body,Contact objContact){
        Contact contactRecord;
        if(objContact==null){
            contactRecord = getContactByPerson(body);
            insert contactRecord; 
            String query = 'Select Id,Name,Billing_Account__c,Unomy_Company_Name__c,Billing_Account__r.Parent_Account__c,Account.Parent_Org_Id__c,Account_Name__c,Billing_Account__r.Ultimate_Parent_Org__c,Billing_Account__r.UUID__c,AccountId,Account.Name,Account.Account_Type__c,UUID__c,Email,Email_Domain__c,Company__c,Cleansed_Company_Name__c,Unomy_Company_Id__c,Cleansed_Unomy_Company_Name__c,FirstName,LastName,Phone,Type__c,LeadSource,Lead_Source_Detail__c,utm_campaign_id__c,utm_campaign__c,utm_content__c,utm_medium__c,utm_source__c,utm_term__c,Locale__c,Country_Code__c From Contact Where Id=\''+contactRecord.Id+'\'';   
            List<Contact> lstPersonContacts = (List<Contact>)Database.query(query);
            Debug.log('When new Contact is Created lstPersonContacts==>'+lstPersonContacts);
            if(String.isNotBlank(body.type) && body.type.equalsIgnoreCase('broker')){
                personContactId = contactRecord.Id;
            }
            contactRecord.AccountId = OrganizationHelper.findOrCreateRelatedOrg(lstPersonContacts[0]);
        }else{
            contactRecord = fillContactByPerson(body, objContact);
            contactRecord = objContact;
        } 
        DEbug.log('createPersonStructure contactRecord Before update==>'+contactRecord);
        update contactRecord;
        return contactRecord.Id;        
    }    
   
   /************************************************************************************************************************************
        Author              :   Ajaysinh Chauhan
        Description         :   This method returns the contact object from person endpoint payload.
        Created Date        :   19 June 2018    
   **************************************************************************************************************************************/ 
    public static Contact getContactByPerson(RESTAPIPersonModelsV2.Input body){
        Contact objContact = new contact();
        objContact.Email = body.email;
        objContact.Company__c = (String.isNotBlank(body.company_name)) ? body.company_name : (body.first_name+' '+body.last_name);
        objContact.FirstName = body.first_name;
        objContact.LastName = body.last_name;
        objContact.Phone = body.phone;
        objContact.Type__c = body.type;
        objContact.LeadSource = body.lead_source;
        objContact.Lead_Source_Detail__c = body.lead_source_detail;
        objContact.utm_campaign_id__c = body.utm_campaign_id;    
        objContact.utm_campaign__c = body.utm_campaign;
        objContact.utm_content__c = body.utm_content;
        objContact.utm_medium__c = body.utm_medium;
        objContact.utm_source__c = body.utm_source;
        objContact.utm_term__c = body.utm_term;
        objContact.Locale__c = body.locale;
        objContact.Country_Code__c = body.country_code;
        objContact.Market__c = body.market;
        if(String.isNotBlank(body.marketing_consent)){
            objContact.Marketing_Consent__c = Boolean.valueOf(body.marketing_consent);
        }
        if(String.isNotBlank(body.email_opt_out)){
            objContact.HasOptedOutOfEmail = Boolean.valueOf(body.email_opt_out);
        }
        return objContact;
    }
    
    /************************************************************************************************************************************
        Author              :   Ajaysinh Chauhan
        Description         :   This method fills the contact information from person endpoint payload.
        Created Date        :   19 June 2018    
    **************************************************************************************************************************************/ 
    public static Contact fillContactByPerson(RESTAPIPersonModelsV2.Input body,Contact objContact){
        if(objContact.Email==null)
            objContact.Email = body.email;
        if(objContact.FirstName==null)
            objContact.FirstName = body.first_name;
        if(objContact.LastName==null)
            objContact.LastName = body.last_name;
        if(objContact.Phone==null)
            objContact.Phone = body.phone;
        if(objContact.Type__c==null)
            objContact.Type__c = body.type;       
        if(objContact.LeadSource==null)
            objContact.LeadSource = body.lead_source;
        if(objContact.Lead_Source_Detail__c==null)
            objContact.Lead_Source_Detail__c = body.lead_source_detail;
        if(objContact.utm_campaign_id__c==null)
            objContact.utm_campaign_id__c = body.utm_campaign_id;
        if(objContact.utm_campaign__c==null)
            objContact.utm_campaign__c = body.utm_campaign;
        if(objContact.utm_content__c==null)
            objContact.utm_content__c = body.utm_content;
        if(objContact.utm_medium__c==null)
            objContact.utm_medium__c = body.utm_medium;
        if(objContact.utm_source__c==null)
            objContact.utm_source__c = body.utm_source;
        if(objContact.utm_term__c==null)
            objContact.utm_term__c = body.utm_term;
        if(objContact.Locale__c==null)
            objContact.Locale__c = body.locale;
        if(objContact.Country_Code__c==null)
            objContact.Country_Code__c = body.country_code;
        if(String.isNotBlank(body.market))
            objContact.Market__c = body.market;
        if(String.isNotBlank(body.marketing_consent))
            objContact.Marketing_Consent__c = Boolean.valueOf(body.marketing_consent);
        if(String.isNotBlank(body.email_opt_out))
            objContact.HasOptedOutOfEmail = Boolean.valueOf(body.email_opt_out);
        return objContact;
    }
}