objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Queue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference of account queue</description>
        <label>Account Queue</label>
        <referenceTo>Account_Queue__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <description>This field will updated by Lead to Activity mapping.</description>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alexandria</fullName>
                </value>
                <value>
                    <fullName>Alpharetta</fullName>
                </value>
                <value>
                    <fullName>Amsterdam</fullName>
                </value>
                <value>
                    <fullName>Ann Arbor</fullName>
                </value>
                <value>
                    <fullName>Atlanta</fullName>
                </value>
                <value>
                    <fullName>Austin</fullName>
                </value>
                <value>
                    <fullName>Balston</fullName>
                </value>
                <value>
                    <fullName>Baltimore</fullName>
                </value>
                <value>
                    <fullName>Bangkok</fullName>
                </value>
                <value>
                    <fullName>Barcelona</fullName>
                </value>
                <value>
                    <fullName>Barranquilla</fullName>
                </value>
                <value>
                    <fullName>Be'er Sheva</fullName>
                </value>
                <value>
                    <fullName>Beijing</fullName>
                </value>
                <value>
                    <fullName>Belo Horizonte</fullName>
                </value>
                <value>
                    <fullName>Bengaluru</fullName>
                </value>
                <value>
                    <fullName>Berkeley</fullName>
                </value>
                <value>
                    <fullName>Berlin</fullName>
                </value>
                <value>
                    <fullName>Bethesda</fullName>
                </value>
                <value>
                    <fullName>Bogota</fullName>
                </value>
                <value>
                    <fullName>Bogotá</fullName>
                </value>
                <value>
                    <fullName>Boston</fullName>
                </value>
                <value>
                    <fullName>Boulder</fullName>
                </value>
                <value>
                    <fullName>Brasilia</fullName>
                </value>
                <value>
                    <fullName>Brisbane</fullName>
                </value>
                <value>
                    <fullName>Brussels</fullName>
                </value>
                <value>
                    <fullName>Budapest</fullName>
                </value>
                <value>
                    <fullName>Buenos Aires</fullName>
                </value>
                <value>
                    <fullName>Busan</fullName>
                </value>
                <value>
                    <fullName>Calgary</fullName>
                </value>
                <value>
                    <fullName>Cali</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Paperwork will be sent to the primary member on the ACCOUNT</inlineHelpText>
        <label>Main Contact</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.Account.Id</field>
                <operation>equals</operation>
                <valueField>$Source.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Consumer</fullName>
        <active>true</active>
        <description>This is Updated Record Type from Default to Consumer for New Sales Process and Changes</description>
        <label>Consumer</label>
    </recordTypes>
</CustomObject>

objects/Account_Queue__c.object
<CustomObject>
    <fields>
        <fullName>Market__c</fullName>
        <description>This field will hep us to match to account for Account assignment.</description>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Amsterdam</fullName>
                </value>
                <value>
                    <fullName>Atlanta</fullName>
                </value>
                <value>
                    <fullName>Austin</fullName>
                </value>
                <value>
                    <fullName>Baltimore</fullName>
                </value>
                <value>
                    <fullName>Bangkok</fullName>
                </value>
                <value>
                    <fullName>Barranquilla</fullName>
                </value>
                <value>
                    <fullName>Be'er Sheva</fullName>
                </value>
                <value>
                    <fullName>Beijing</fullName>
                </value>
                <value>
                    <fullName>Bengaluru</fullName>
                </value>
                <value>
                    <fullName>Berkeley</fullName>
                </value>
                <value>
                    <fullName>Berlin</fullName>
                </value>
                <value>
                    <fullName>Bogota</fullName>
                </value>
                <value>
                    <fullName>Boston</fullName>
                </value>
                <value>
                    <fullName>Boulder</fullName>
                </value>
                <value>
                    <fullName>Buenos Aires</fullName>
                </value>
                <value>
                    <fullName>Charlotte</fullName>
                </value>
                <value>
                    <fullName>Chicago</fullName>
                </value>
                <value>
                    <fullName>Dallas</fullName>
                </value>
                <value>
                    <fullName>Delhi</fullName>
                </value>
                <value>
                    <fullName>Denver</fullName>
                </value>
                <value>
                    <fullName>Detroit</fullName>
                </value>
                <value>
                    <fullName>Dublin</fullName>
                </value>
                <value>
                    <fullName>Fort Worth</fullName>
                </value>
                <value>
                    <fullName>Frankfurt</fullName>
                </value>
                <value>
                    <fullName>Guangzhou</fullName>
                </value>
                <value>
                    <fullName>Hamburg</fullName>
                </value>
                <value>
                    <fullName>Herzliya</fullName>
                </value>
                <value>
                    <fullName>Ho Chi Minh City</fullName>
                </value>
                <value>
                    <fullName>Hong Kong</fullName>
                </value>
                <value>
                    <fullName>Houston</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is a lookup of the user and will be used in account assignment use case as an owner.</description>
        <label>Member</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_Queues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Portfolio__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Portfolio</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Account Queues</relationshipLabel>
        <relationshipName>Account_Queues</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>This object will be used in Account assignment use case.</description>
    <label>Account Queue</label>
    <nameField>
        <displayFormat>Queue-{00000}</displayFormat>
        <label>Queue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Queues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Building__c.object
<CustomObject>
    <fields>
        <fullName>Market__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Portfolio</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Buildings</relationshipLabel>
        <relationshipName>Buildings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Building</label>
    <nameField>
        <label>Building</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Building__c</fullName>
        <description>Pulls Building Location without 3 character city reference</description>
        <formula>Location__r.Location_No_City__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Building</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Member__c</fullName>
        <formula>if( Billing_Account__r.Primary_Member__r.Id =  Id , "Yes","No")</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Primary Member</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Consumer</fullName>
        <active>true</active>
        <label>Consumer</label>
    </recordTypes>
</CustomObject>

objects/Market__c.object
<CustomObject>
    <fields>
        <fullName>Portfolio__c</fullName>
        <description>Display name for portfolio, something user friendly to end users</description>
        <inlineHelpText>Display name (text)</inlineHelpText>
        <label>Portfolio Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <description>We are introducing new object Market so that same building can fall under multiple Markets as per Marketing department requirement.</description>
    <label>Portfolio</label>
    <nameField>
        <label>Portfolio</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portfolios</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Building__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Enter the specific building for which opportunity is associated</description>
        <inlineHelpText>This is the building / Nearest building to the geography entered by customer</inlineHelpText>
        <label>Building/Nearest Building</label>
        <referenceTo>Building__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Member__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>This is the Main Contact of the Opportunity</inlineHelpText>
        <label>Main Contact</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Consumer</fullName>
        <active>true</active>
        <businessProcess>Office Space</businessProcess>
        <label>Consumer</label>
    </recordTypes>
</CustomObject>

objects/Tour_Outcome__c.object
<CustomObject>
    <fields>
        <fullName>Primary_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Member</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Tours (Primary Member)</relationshipLabel>
        <relationshipName>Tours3</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Tour</label>
    <nameField>
        <displayFormat>TRO-{0000}</displayFormat>
        <label>Tour Outcome ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tours</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/WeWorkValidatorAssertions.cls
/************************************************************************************************************************************
    Author 		: 	Ajaysinh Chauhan
    Description : 	

    History:
	----------------------------------------------------------------------------------------------------------------------------------
	VERSION		DATE				AUTHOR					DETAIL											Issue No.
    1			08 Feb 2018			Ajaysinh Chauhan		Initial Developement.							-
**************************************************************************************************************************************/
public class WeWorkValidatorAssertions {
    public static void verifyLeadCreation(Map<String,Object> mapData){
        List<Lead> lstLeads = [Select Id,FirstName,LastName,Email,Company From Lead Where Email=:String.valueOf(mapData.get('email'))];
        if(lstLeads.size()>0){
            Lead objLead = lstLeads[0];
            System.assertEquals(String.valueOf(mapData.get('first_name')),objLead.FirstName,'First Name not mapped on lead.');
            System.assertEquals(String.valueOf(mapData.get('last_name')),objLead.LastName,'Last Name not mapped on lead.');
            System.assertEquals(String.valueOf(mapData.get('email')),objLead.Email,'Email not mapped on lead.');
            System.assertEquals(String.valueOf(mapData.get('company_name')),objLead.Company,'Company Name not mapped on lead.');
        }else{
            System.assert(false,'Lead creation failed.');
        }
    }
    public static void verifyLeadConversion(List<Lead> lstLeads){
        if(lstLeads.size()>0){
            System.assertEquals(true, lstLeads[0].IsConverted,'Lead conversion failed');
        }else{
            System.assert(false,'Lead has been deleted.');
        }
    }
    public static void verifyAccountStructure(Lead objLead,Account objAccount,Contact objContact,Opportunity objOpportunity,Building__c objBuilding){
        System.assertEquals(objLead.FirstName,objContact.FirstName,'First Name not mapped on contact.');
        System.assertEquals(objLead.LastName,objContact.LastName,'Last Name not mapped on contact.');
        System.assertEquals(objLead.Email,objContact.Email,'Email not mapped on contact.');
        System.assertEquals(objLead.Company,objAccount.Name,'Company Name not mapped on account.');
        System.assertEquals(objAccount.Id,objContact.AccountId,'Account not mapped on contact.');
        System.assertEquals(objAccount.Id,objOpportunity.AccountId,'Account not mapped on opportunity.');
        System.assertEquals(objContact.Id,objOpportunity.Primary_Member__c,'Primary member not mapped on opportunity.');
        System.assertEquals(objBuilding.Id,objOpportunity.Building__c,'Building not mapped on opportunity.');
    }
    public static void verifyAccountAssignments(Account objAccount,Contact objContact,Opportunity objOpportunity,Building__c objBuilding,String strRecordType,String strDealType){
        System.assertEquals(strRecordType,objAccount.RecordType.Name,'Invalid record type for account.');
        if(strDealType=='Stratergic' || strRecordType=='Enterprize Solutions'){
            Account_Queue__c objQueue = [Select Id,Member__c From Account_Queue__c Where Portfolio__c=:objBuilding.Market__c AND Account_Record_Type__c='Consumer'][0];
            System.assertEquals(objQueue.Member__c,objAccount.OwnerId,'Invalid assignment for Relational Deal Type.');
        }else if(strDealType=='Relational'){
            System.assertEquals(objBuilding.Cluster__r.Sales_Lead__c,objAccount.OwnerId,'Invalid assignment for Relational Deal Type.');
        }else if(strDealType=='Transactional'){
            System.assertEquals('005F0000003KmbwIAC',objAccount.OwnerId,'Invalid assignment for Transactional Deal Type.');
            
        }
    }
    public static void verifyChangeChildsRecordType(Account objAccount,Contact objContact,Opportunity objOpportunity){
        System.assertEquals(objAccount.RecordType.Name,objContact.RecordType.Name,'Contact record type is diffrent from account.');
        System.assertEquals(objAccount.OwnerId,objContact.OwnerId,'Contact owner is diffrent from account.');
        System.assertEquals(objAccount.RecordType.Name,objOpportunity.RecordType.Name,'Opportunity record type is diffrent from account.');
        System.assertEquals(objAccount.OwnerId,objOpportunity.OwnerId,'Opportunity owner is diffrent from account.');
    }
  
    /*---------------------------------------
     * Sr	From		To		Allow Merge
     * --------------------------------------
	 * 1	Org		To	Org		Yes
	 * 2	Sales	To	Sales	No
	 * 3	Bill	To	Bill	No
	 * 4	Blank	To	Bill	Yes
	 * 5	Blank	To	Blank	Yes
	 * --------------------------------------
     */
    public static void verifyUnomyAccountMergePositive(List<Account> lstParentAcc,List<Account> lstChildAccount){
        if(lstParentAcc[0].Account_Type__c =='Org'){
            System.assertEquals(0, lstChildAccount.size(), 'Child Account is Not Merged with the Parent Account' );
        }else if(lstParentAcc[0].Account_Type__c =='Bill'){
            System.assertEquals(0, lstChildAccount.size(), 'Child Account is Not Merged with the Parent Account' );
        }else if(lstParentAcc[0].Account_Type__c ==null){
            System.assertEquals(0, lstChildAccount.size(), 'Child Account is Not Merged with the Parent Account' );
        }
    }
    
    public static void verifyTourOutcome(Tour_Outcome__C tour){
        
    }
}