objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <description>This is Picklist which Contains three values
1. Org : It is Main account in hierarchy which is Parent Account of Sales And Bill.
2. Sales: One Sales Account may contain multiple Bill Or Sales Account and It is Under Org Account in hierarchy
3. Bill: Bill Account is under Sales or Org. It never child of Bill Account.
4. ' '(Blank) : It is like Bill type which is under Sales or Org.</description>
        <inlineHelpText>This Picklist is used to determine the account type.</inlineHelpText>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Org</fullName>
                    <default>true</default>
                    <label>Org</label>
                </value>
                <value>
                    <fullName>Sales</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cleansed_Unomy_Company_Name__c</fullName>
        <description>This field is used to save cleansed unomy company name</description>
        <label>Cleansed Unomy Company Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Interested_in_Number_of_Desks_Min__c</fullName>
        <label>Interested in Number of Desks Min</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Interested_in_Number_of_Desks__c</fullName>
        <label>Interested in Number of Desk(s)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unomy_Company_ID__c</fullName>
        <externalId>true</externalId>
        <label>Unomy Company ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unomy_Company_Name__c</fullName>
        <label>Unomy Company Name</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Building__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Buildings</relationshipLabel>
        <relationshipName>Buildings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Building</label>
    <nameField>
        <label>Building</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <formula>text(Account.Type)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>This field will store the name of the city</description>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cleansed_Company_Name__c</fullName>
        <externalId>true</externalId>
        <label>Cleansed Company Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cleansed_Unomy_Company_Name__c</fullName>
        <description>This field contains Cleansed Unomy Company Name value</description>
        <label>Cleansed Unomy Company Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Email_Domain__c</fullName>
        <formula>RIGHT(Email,LEN(Email)-FIND('@',Email))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Email Domain</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Interested_in_Number_of_Desks__c</fullName>
        <label>Interested in Number of Desk(s)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Lead_Source_Detail__c</fullName>
        <description>This field captures the information from where the lead is coming.</description>
        <inlineHelpText>This field captures the information from where the lead is coming.</inlineHelpText>
        <label>Lead Source Detail</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <label>Product Line</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>WeWork</fullName>
                </value>
                <value>
                    <fullName>WeLive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Referrer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referrer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unomy_Company_ID__c</fullName>
        <label>Unomy Company ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unomy_Company_Name__c</fullName>
        <label>Unomy Company Name</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field contains the value of Org account for which lead is associated.</description>
        <inlineHelpText>Enter the name of the organization associated with this new Opportunity. If an existing organization does not appear when typing the name, click "New Organization" to create a new one.</inlineHelpText>
        <label>Organization</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Account.Account_Type__c</field>
                <operation>equals</operation>
                <value>Org</value>
            </filterItems>
            <filterItems>
                <field>Account.Account_Type__c</field>
                <operation>equals</operation>
                <value>Sales</value>
            </filterItems>
            <infoMessage>Leads can only be associated to accounts havinng account type 'Org'.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads (Account)</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Building_Interested_In__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Building Interested In</label>
        <referenceTo>Building__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>By_Pass_Journey_Creation_Criteria__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If lead is creating from Journey Importer (Kickbox) then while uploading the file if user check Generate Journey. Then we will check it as true and while creating journey we not check Journey Creation Criteria of the lead source and lead source details and user and queue.</description>
        <inlineHelpText>If lead is creating from Journey Importer (Kickbox) then while uploading the file if user check Generate Journey. Then we will check it as true and while creating journey we not check Journey Creation Criteria of the lead source and lead source details</inlineHelpText>
        <label>By Pass Journey Creation Criteria</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City (Custom)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Amsterdam</fullName>
                </value>
                <value>
                    <fullName>Austin</fullName>
                </value>
                <value>
                    <fullName>Boston</fullName>
                </value>
                <value>
                    <fullName>Brooklyn</fullName>
                </value>
                <value>
                    <fullName>Chicago</fullName>
                </value>
                <value>
                    <fullName>Israel</fullName>
                </value>
                <value>
                    <fullName>London</fullName>
                </value>
                <value>
                    <fullName>Los Angeles</fullName>
                </value>
                <value>
                    <fullName>Miami</fullName>
                </value>
                <value>
                    <fullName>New York</fullName>
                </value>
                <value>
                    <fullName>San Francisco</fullName>
                </value>
                <value>
                    <fullName>Seattle</fullName>
                </value>
                <value>
                    <fullName>Washington</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cleansed_Company_Name__c</fullName>
        <label>Cleansed Company Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cleansed_Unomy_Company_Name__c</fullName>
        <description>Cleansed Unomy Company Name value</description>
        <label>Cleansed Unomy Company Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Email_Domain__c</fullName>
        <formula>RIGHT(Email,LEN(Email)-FIND('@',Email))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Email Domain</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Generate_Journey__c</fullName>
        <defaultValue>true</defaultValue>
        <description>If this check box is checked , create journey for converted lead</description>
        <label>Generate Journey</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Interested_in_Number_of_Desks_Min__c</fullName>
        <description>This will be updated from inbound lead api with desks_interested_min</description>
        <label>Interested in Number of Desks Min</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Interested_in_Number_of_Desks__c</fullName>
        <label>Interested in Number of Desk(s)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Lead_Source_Detail__c</fullName>
        <label>Lead Source Detail</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <label>Product Line</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>WeWork</fullName>
                </value>
                <value>
                    <fullName>WeLive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Referrer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This will be the contact who referred us the Lead. It can be a member, employee or a broker.</description>
        <inlineHelpText>Enter the contact who referred us the Lead. It can be a member, employee or a broker.</inlineHelpText>
        <label>Referrer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Leads (Referrer)</relationshipLabel>
        <relationshipName>ReferredLeads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unomy_Company_ID__c</fullName>
        <label>Unomy Company ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unomy_Company_Name__c</fullName>
        <label>Unomy Company Name</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/SalesAccountController.cls
/************************************************************************************************************************************
    Author      :   Prashant Mane
    Description :   This class contain all aura methods related to CreateNewSalesAccount Component.
    ----------------------------------------------------------------------------------------------------------------------------------
    VERSION     DATE                AUTHOR                  DETAIL
    1           10 Jan 2019         Prashant Mane        	Initial Developement
**************************************************************************************************************************************/
global without sharing class SalesAccountController {
    public static Boolean isInvoker = false;
    public static Savepoint sp {get;set;}
    static {
        isInvoker = ApexDebugLog.registerRootInvoker(ApexDebugLog.InvokerType.AURA, 'SalesAccountController' + 'getsObjectPrefix', ApexDebugLog.InvokerType.AURA);        
    }
    @AuraEnabled
    public static DatabaseResult isValidForSalesAccount(String recordId){
        try{
            ValidForSalesAccountResult objValidForSalesAccountResult = new ValidForSalesAccountResult();
            objValidForSalesAccountResult.isValid = true;
            Account accRec = [SELECT Id, OwnerId , Account_Type__c FROM Account Where Id =:recordId];
            Debug.log('accRec---'+accRec);
            if(accRec.Account_Type__c != null && (accRec.Account_Type__c.toLowerCase() == 'org' || accRec.Account_Type__c.toLowerCase() == 'sales')){
                if(accRec.OwnerId == UserInfo.getUserId()){
                    objValidForSalesAccountResult.isValid = true;
                }else if(OrganizationHelper.getUltimateParents(new Set<Id>{accRec.Id},new List<String>{'OwnerId'}).get(accRec.Id).OwnerId == UserInfo.getUserId()){
                    objValidForSalesAccountResult.isValid = true;                    
                }else {
                    List<CustomPermission> lstCustomPermissions = [SELECT Id, DeveloperName, (SELECT Id, Parent.Name, Parent.Profile.Name FROM SetupEntityAccessItems WHERE Parent.Profile.Id =: UserInfo.getProfileId()) FROM CustomPermission WHERE DeveloperName = 'Can_Create_Sales_Account'];
                    if(lstCustomPermissions != null && lstCustomPermissions.size() > 0 && lstCustomPermissions[0].SetupEntityAccessItems != null && lstCustomPermissions[0].SetupEntityAccessItems.size()>0){
                        objValidForSalesAccountResult.isValid = true;
                    }else{
                        objValidForSalesAccountResult.isValid = false;
                        objValidForSalesAccountResult.errorMessage = 'You can not create Sales Account as you are not the owner of the Account.';
                    } 
                }
            }else{
                objValidForSalesAccountResult.isValid = false;
                objValidForSalesAccountResult.errorMessage = 'Sales account can only be created under Org or Sales accounts.';
            }
            return new DatabaseResult(JSON.serialize(objValidForSalesAccountResult));
        }catch(Exception pEx){
            ApexDebugLog.logException(pEx,'AccountId==> '+ recordId, 'SalesAccountController', 'isValidForSalesAccount');                      
            return new DatabaseResult(pEx);  
        } 
    }
    
 /****************************************************************************************************************************
    Author              :   Krishana Tupe
    Description         :   This method is used to find ultimate org for Lead record and returns its related sales account records                           
    Created Date        :   23 July 2018   
    Issue No.           :   ST-2669
 *********************************************************************************************************************************/  
    @AuraEnabled
    public static DatabaseResult getRelatedAccounts(String leadId,String parentId){
        try{
            String ultimateOrgId;
            if(String.isBlank(parentId)){
                Lead leadRecord = [Select Id,FirstName,Interested_in_Number_of_Desks_Min__c,Interested_in_Number_of_Desks__c,LastName,Name,Product_Line__c,OwnerId,Email_Domain__c,Company,Account__c,Account__r.Account_Type__c,Referrer__c,Cleansed_Unomy_Company_Name__c,Cleansed_Company_Name__c,Email,Unomy_Company_ID__c,Unomy_Company_Name__c,LeadSource,Lead_Source_Detail__c,Generate_Journey__c,By_Pass_Journey_Creation_Criteria__c,Building_Interested_In__c,Building_Interested_In__r.City__c,Locations_Interested__c,Number_of_Full_Time_Employees__c,Company_Size__c,Markets_Interested__c From  Lead Where Id=:leadId];
                ultimateOrgId =  OrganizationHelper.findRelatedOrg(leadRecord);
                Debug.log('ultimateOrgId ==>'+ultimateOrgId);
            }else{
                ultimateOrgId = parentId;   
            }
            Map<String,List<Account>> mapAccount = new Map<String,List<Account>>();
            if(String.isNotBlank(ultimateOrgId)){
                List<Account> lstAccounts = [Select Id,Name,Parent_Org_Id__c,Account_Type__c From Account Where Id=:ultimateOrgId];          
                if(lstAccounts != null && lstAccounts.size() >0){
                    mapAccount.put('OrgAccount',lstAccounts);
                    String query='';
                    if(String.isNotBlank(lstAccounts[0].Parent_Org_Id__c)){
                        query += 'Select Id,Name,Primary_Member__c,Primary_Member__r.Name,Primary_Member__r.Email,Parent_Org_Id__c,Parent_Org_Name__c,RecordType.Name,Account_Type__c,OwnerId,Owner.Name,ID_Status2__c,CreatedDate From Account Where (Parent_Org_Id__c=\''+String.valueOf(lstAccounts[0].Parent_Org_Id__c).substring(0,15)+'\' OR ParentId=\''+lstAccounts[0].Parent_Org_Id__c+'\' OR Id=\''+lstAccounts[0].Parent_Org_Id__c+'\') AND (Account_Type__c=\'Sales\' OR Account_Type__c=\'Org\')';
                    }else if(lstAccounts[0].Account_Type__c =='Org'){
                        query += 'Select Id,Name,Primary_Member__c,Primary_Member__r.Name,Primary_Member__r.Email,Parent_Org_Id__c,Parent_Org_Name__c,RecordType.Name,Account_Type__c,OwnerId,Owner.Name,ID_Status2__c,CreatedDate From Account Where (Parent_Org_Id__c=\''+String.valueOf(lstAccounts[0].Id).substring(0,15)+'\' OR ParentId=\''+lstAccounts[0].Id+'\') AND (Account_Type__c=\'Sales\' OR Account_Type__c=\'Org\')';   
                    }
                    Debug.log('query==>'+query);
                    List<Account> lstSalesAccounts = (List<Account>)Database.query(query);            
                    mapAccount.put('SalesAccounts',lstSalesAccounts);        
                    return new DatabaseResult(mapAccount);            
                }else{
                    return null;
                }  
            }
            return null;
        }catch(Exception pEx){
            ApexDebugLog.logException(pEx,'LeadId==>'+leadId+' AccountId==>'+parentId, 'SalesAccountController', 'getRelatedAccounts');                      
            return new DatabaseResult(pEx);   
        }
    }
    
    @AuraEnabled
    public static DatabaseResult isValisUserToShowAccountSelector(){
        try{
            Boolean showPage = false;
            User loggedInUser = Settings.getUserById(UserInfo.getUserId());
            Setting__c accountSelectorSettings = settings.get('AccountSelectorSettings');
            Map<String,set<String>> mapExcludedProfiles;
            if(accountSelectorSettings != null){
                mapExcludedProfiles  = (Map<String,set<String>>)JSON.deserialize(accountSelectorSettings.Data__c.toLowerCase(), Map<String,set<String>>.class);             
                Debug.log('mapExcludedProfiles==>'+mapExcludedProfiles);
                if(mapExcludedProfiles != null && !mapExcludedProfiles.get('profiles').contains(String.valueOf(loggedInUser.Profile.Name).toLowerCase())){
                    showPage = true;
                }
            }
            return new DatabaseResult(showPage);
        }catch(Exception pEx){
            ApexDebugLog.logException(pEx,'', 'SalesAccountController', 'isValisUserToShowAccountSelector');                      
            return new DatabaseResult(pEx);   
        }
    } 
    
    public class ValidForSalesAccountResult {
        public Boolean isValid {get;set;}
        public String errorMessage {get;set;}
    }
}