objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <description>This is Picklist which Contains three values
1. Org : It is Main account in hierarchy which is Parent Account of Sales And Bill.
2. Sales: One Sales Account may contain multiple Bill Or Sales Account and It is Under Org Account in hierarchy
3. Bill: Bill Account is under Sales or Org. It never child of Bill Account.
4. ' '(Blank) : It is like Bill type which is under Sales or Org.</description>
        <inlineHelpText>This Picklist is used to determine the account type.</inlineHelpText>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Org</fullName>
                    <default>true</default>
                    <label>Org</label>
                </value>
                <value>
                    <fullName>Sales</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Number_of_Full_Time_Employees__c</fullName>
        <label>Number of Full Time Employees</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Parent_Account__c</fullName>
        <formula>CASESAFEID(ParentId)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Parent Account(Pipeline Reporting)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Org_Name__c</fullName>
        <description>Shows the name of the Ultimate Org when we have the multi-level hierarchy.</description>
        <formula>IF( OR( ISPICKVAL(Account_Type__c, 'Org'),ISBLANK(Parent.Id)),Name,IF(OR(ISPICKVAL(Parent.Account_Type__c, 'Org'),ISBLANK(Parent.Parent.Id)),Parent.Name,IF(OR(ISPICKVAL(Parent.Parent.Account_Type__c, 'Org'),ISBLANK(Parent.Parent.Parent.Id)), Parent.Parent.Name,IF(OR(ISPICKVAL(Parent.Parent.Parent.Account_Type__c, 'Org'),ISBLANK(Parent.Parent.Parent.Parent.Id)), Parent.Parent.Parent.Name,IF(OR(ISPICKVAL(Parent.Parent.Parent.Parent.Account_Type__c, 'Org'),ISBLANK(Parent.Parent.Parent.Parent.Parent.Id)), Parent.Parent.Parent.Parent.Name,Parent.Parent.Parent.Parent.Parent.Name)))))</formula>
        <inlineHelpText>Shows the name of the Ultimate Org when we have the multi-level hierarchy.</inlineHelpText>
        <label>Org Account Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Paperwork will be sent to the primary member on the ACCOUNT</inlineHelpText>
        <label>Main Contact</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.Account.Id</field>
                <operation>equals</operation>
                <valueField>$Source.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UUID__c</fullName>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Billing_Account__c.object
<CustomObject>
    <fields>
        <fullName>ID_Status__c</fullName>
        <description>This field determine whether or not the company is active in WeWork spaces</description>
        <inlineHelpText>This field determine whether or not the company is active in WeWork spaces</inlineHelpText>
        <label>ID Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Member</fullName>
                </value>
                <value>
                    <fullName>Potential</fullName>
                </value>
                <value>
                    <fullName>Past Member</fullName>
                </value>
                <value>
                    <fullName>active</fullName>
                </value>
                <value>
                    <fullName>inactive</fullName>
                    <default>true</default>
                    <label>inactive</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Number_of_Full_Time_Employees__c</fullName>
        <label>Number of Full Time Employees</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Parent_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is lookup to the Parent Account</description>
        <inlineHelpText>This is lookup to the Parent Account</inlineHelpText>
        <label>Parent Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the main point of contact for the Billing Account.</description>
        <inlineHelpText>Person at the member company responsible for managing the membership: invoices, key card replacements, MENA account manager tab. Responsible for signing legal agreement (unless an authorized signatory is designated).</inlineHelpText>
        <label>Primary Member</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UUID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>This is unique,case sensitive auto generated field used to identify Billing Account record.</description>
        <externalId>true</externalId>
        <inlineHelpText>This is unique,case sensitive auto generated field used to identify Billing Account record.</inlineHelpText>
        <label>UUID</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Ultimate_Parent_Org__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Shows the Ultimate Org when we have the multi-level hierarchy.</description>
        <inlineHelpText>Shows the Ultimate Org when we have the multi-level hierarchy.</inlineHelpText>
        <label>Ultimate Parent Org</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts (Ultimate Parent Org Name)</relationshipLabel>
        <relationshipName>Billing_Accounts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>All Billing account is moved to this Billing Account object it help Sales people to identify Org and Sales account easily and reduce the clutter of 100s of Accounts with same name.</description>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <formula>text(Account.Type)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Members</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number_of_Full_Time_Employees__c</fullName>
        <label>Number of Full Time Employees</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Primary_Member__c</fullName>
        <formula>if( Billing_Account__r.Primary_Member__r.Id =  Id , "Yes","No")</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Primary Member</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UUID__c</fullName>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Checking</fullName>
                </value>
                <value>
                    <fullName>Savings</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field relates the opportunity to the billing account. The billing account is used in the space station for sending contracts.</description>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Merged_Opprtunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field contain id of primary opportunity in which current opportunity is merged</description>
        <label>Merged Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number_of_Full_Time_Employees__c</fullName>
        <label>Number of Full Time Employees</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Primary_Member__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>This is the Main Contact of the Opportunity</inlineHelpText>
        <label>Main Contact</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/BillingAccountController.cls
/************************************************************************************************************************************
    Author      :   Prashant Mane
    Description :   This class contain all aura methods related to TransferPaperwork.
    ----------------------------------------------------------------------------------------------------------------------------------
    VERSION     DATE                AUTHOR                  DETAIL
    1           10 Jan 2019         Prashant Mane        	Initial Developement
**************************************************************************************************************************************/
global without sharing class BillingAccountController {
    public static Boolean isInvoker = false;
    public static Savepoint sp {get;set;}
    static {
        isInvoker = ApexDebugLog.registerRootInvoker(ApexDebugLog.InvokerType.AURA, 'BillingAccountController' + 'getsObjectPrefix', ApexDebugLog.InvokerType.AURA);        
    }
    
    /************************************************************************************************************************************
        Author              : Shivprasad Patil
        Description         : This method takes record Id and returns All Bill type and Blank type Billing_Accounts in hierarchy.
        Created Date        : 06 April 2018
        Issue No.           : 
        Last Modified Date  : 31,May 2018
        Last Modified By    : Ashish Mishra
	**************************************************************************************************************************************/
    @AuraEnabled
    public static DatabaseResult getBillAccountsOfAccountHierarchy(String accountId, String opportunityId){
        try{
            BillAccountsForAccountHierarchy billAccountsForAccountHierarchyRec = new BillAccountsForAccountHierarchy(); 
            Id ultimateParentOrgId;
            billAccountsForAccountHierarchyRec.accountInfo = [Select Id,Account_Type__c,Parent_Org_Name__c,Number_of_Full_Time_Employees__c From Account Where Id =:accountId LIMIT 1];
            if(String.isNotBlank(billAccountsForAccountHierarchyRec.accountInfo.Account_Type__c) && billAccountsForAccountHierarchyRec.accountInfo.Account_Type__c.toLowerCase() != 'bill'){
                DataBaseResult orgData = LightningComponentController.getOrg(accountId);
                if(orgData != null && orgData.data != null){
                    ultimateParentOrgId = Id.valueOf((String)JSON.deserialize(JSON.serialize(LightningComponentController.getOrg(accountId).data), String.class));   
                    system.debug('ultimateParentOrgId'+ultimateParentOrgId);
                    billAccountsForAccountHierarchyRec.ultimateParentOrgId = ultimateParentOrgId;
                    billAccountsForAccountHierarchyRec.lstBillAccounts = [SELECT Id, OwnerId,ID_Status__c, Owner.Name,Parent_Account__r.Name,Parent_Account__r.Account_Type__c, Parent_Account__c, Name, Primary_Member__c, Primary_Member__r.Name,Primary_Member__r.Email, Primary_Member__r.Id, UUID__c, (Select Id From Opportunities__r where stagename='Selling' OR stagename='Qualifying' OR stagename='Negotiating' Or stagename='Closing') FROM Billing_Account__c WHERE (Ultimate_Parent_Org__c =:ultimateParentOrgId)];        
                    billAccountsForAccountHierarchyRec.accountInfo = [Select Id,Parent_Org_Name__c,Account_Type__c,Number_of_Full_Time_Employees__c From Account Where Id =:ultimateParentOrgId LIMIT 1];
                } 
                Opportunity objOpportunity = [SELECT Id, Name, Primary_Member__c, Primary_Member__r.Email, Primary_Member__r.Phone, Primary_Member__r.AccountId, Primary_Member__r.Account.Parent_Org_Name__c, Primary_Member__r.Billing_Account__c, Primary_Member__r.Billing_Account__r.Name FROM Opportunity WHERE Id =:opportunityId LIMIT 1];
                billAccountsForAccountHierarchyRec.opportunityPrimaryMember = objOpportunity.Primary_Member__r;
                Debug.log('getBillAccountsOfAccountHierarchy billAccountsForAccountHierarchyRec--- '+billAccountsForAccountHierarchyRec);  
            }
            return (new DatabaseResult(billAccountsForAccountHierarchyRec));
        }catch(Exception pEx){
            ApexDebugLog.logException(pEx,'accountId==>'+accountId + ' opportunityId '+opportunityId, 'BillingAccountController', 'getBillAccountsOfAccountHierarchy');            
            return (new DatabaseResult(pEx)); 
        }
    }
    
   /**************************************************************************************************************************************************
        Author              : Ajaysinh Chauhan
        Description         : This method is used to check account is already present or not, if not present then insert NewAccount For SendPaperwork.
        Created Date        : -
        Last Modified By    : Ashish Mishra
        Last Modified Date  : 31,May 2018
   ***************************************************************************************************************************************************/
    @AuraEnabled
    public static DatabaseResult insertNewAccountForSendPaperwork(Map<String,String> mapNewObject){
        try{
            sp = Database.setSavepoint();
            List<Billing_Account__c> lstAccounts = [Select Id,UUID__c From Billing_Account__c Where UUID__c=:mapNewObject.get('accountUUID')];
            if(lstAccounts.size()>0){
                return new DatabaseResult(lstAccounts[0]);
            }else{
                Debug.Log('value--->'+mapNewObject.get('parentId'));
                Billing_Account__c billingAccountRec = (Billing_Account__c)FieldMappingsHelper.getMappings(mapNewObject.get('parentId'), 'FieldMappings:AccountToBillingAccount');
                billingAccountRec.Name = mapNewObject.get('AccountName');
                billingAccountRec.UUID__c = mapNewObject.get('accountUUID');
                billingAccountRec.Name = mapNewObject.get('AccountName');
                billingAccountRec.Parent_Account__c = mapNewObject.get('parentId');
                Contact objContact;
                if(mapNewObject.get('contactId') != null){
                    billingAccountRec.Primary_Member__c  = mapNewObject.get('contactId');
                    insert billingAccountRec;
                    objContact = new Contact(Id=mapNewObject.get('contactId'),UUID__c = mapNewObject.get('primaryMemberUUID'),Billing_Account__c=billingAccountRec.Id);
                    if(mapNewObject.containsKey('contactAccountId') && mapNewObject.get('contactAccountId') != null){
                        objContact.AccountId = (mapNewObject.containsKey('contactAccountId') && mapNewObject.get('contactAccountId')!= null ? mapNewObject.get('contactAccountId') : null);
                    }
                    UPDATE objContact;
                }else{
                    insert billingAccountRec;
                    List<String> lstNames = mapNewObject.get('ContactName').split(' ');
                    String strFirstName = '',strLastName = '';
                    if(lstNames.size()>1){
                        strFirstName = lstNames[0];
                        lstNames.remove(0);
                        strLastName = String.join(lstNames,' ');
                    }else{
                        strLastName = String.join(lstNames,' ');
                    }
                    objContact = new Contact(FirstName=strFirstName,LastName=strLastName,Billing_Account__c=billingAccountRec.Id,AccountId=(mapNewObject.containsKey('parentId') && mapNewObject.get('parentId')!= null ? mapNewObject.get('parentId') : null),Email=mapNewObject.get('Email'),Phone=mapNewObject.get('Phone'),UUID__c=mapNewObject.get('primaryMemberUUID'));
                    insert objContact;
                    billingAccountRec.Primary_Member__c = objContact.Id;
                    update billingAccountRec;
                }
                return new DatabaseResult(billingAccountRec);
            }
        }catch(Exception pEx){
            LightningComponentController.rollbackTransaction(sp);
            ApexDebugLog.logException(pEx,'', 'BillingAccountController', 'insertNewAccountForSendPaperwork');            
            return (new DatabaseResult(pEx)); 
        }
    }
        
    class BillAccountsForAccountHierarchy{
        @AuraEnabled
        public Id ultimateParentOrgId;
        @AuraEnabled
        public List<Billing_Account__c> lstBillAccounts;
        @AuraEnabled
        public Account accountInfo;
        @AuraEnabled
        public Contact opportunityPrimaryMember;
    }
}