objects/Account.object
<CustomObject>
    <fields>
        <fullName>Primary_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Paperwork will be sent to the primary member on the ACCOUNT</inlineHelpText>
        <label>Main Contact</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.Account.Id</field>
                <operation>equals</operation>
                <valueField>$Source.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Consumer</fullName>
        <active>true</active>
        <description>This is Updated Record Type from Default to Consumer for New Sales Process and Changes</description>
        <label>Consumer</label>
    </recordTypes>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Primary_Member__c</fullName>
        <formula>if( Billing_Account__r.Primary_Member__r.Id =  Id , "Yes","No")</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Primary Member</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Referrer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referrer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This is the latest status coming from Space systems through Jitterbunny of the individual member. This tells us if the user is active or not.</description>
        <inlineHelpText>This is accurate status of a contact if it is an active member of our products or not.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>active</fullName>
                </value>
                <value>
                    <fullName>inactive</fullName>
                    <default>true</default>
                    <label>inactive</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Consumer</fullName>
        <active>true</active>
        <label>Consumer</label>
    </recordTypes>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Broker_Involved_DateTime__c</fullName>
        <label>Broker Involved DateTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Broker_Involved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Broker Involved [OLD]</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Broker_Involvement_Indicated__c</fullName>
        <description>This field is created for new created opportunity page, Used for ST-3250</description>
        <inlineHelpText>Stores the broker involvement values from create opportunity page.</inlineHelpText>
        <label>Is Broker Involved ?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_Member__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>This is the Main Contact of the Opportunity</inlineHelpText>
        <label>Main Contact</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Referrer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referrer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Referrer)</relationshipLabel>
        <relationshipName>Opportunities3</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Consumer</fullName>
        <active>true</active>
        <businessProcess>Office Space</businessProcess>
        <label>Consumer</label>
    </recordTypes>
</CustomObject>

classes/BrokerInvolvedControllerTest.cls
/*****************************************************************************************************************************
Author 		:  Sunil Bhosale
Description :  This class is used as 
Date		:  15 July 2018
Issue		:  ST-2655
----------------------------------------------------------------------------------------------------------------------------------
VERSION					DATE					AUTHOR							DETAIL
1.0					15,July 2018		    Sunil Bhosale	                Initial Developement

******************************************************************************************************************************/
@isTest
public class BrokerInvolvedControllerTest {
    
    @Testsetup
    static void initData(){
        SalesConsoleSettings.createSettings();  
        Account accRec = TestingUtility.createAccount('TestAccount1', true);
        Contact conRec = new Contact(
            firstname  = 'John',
            lastname   = 'Rambo',
            email     = 'test1@example.com',
            accountID  = accRec.Id,
            Status__c  = 'active'
        );
        insert conRec;
        accRec.Primary_Member__c = conRec.Id;
        update accRec;
        Contact referrerContact = new Contact(
            firstname  = 'John',
            lastname   = 'Rambo',
            email     = 'test2@example.com',
            accountID  = accRec.Id,
            Status__c  = 'active'
        );
        insert referrerContact;
        
        Map<String, Id> oppRecordType = TestingUtility.getRecordTypeMapByName(Opportunity.sObjectType);
        Opportunity oppRec = TestingUtility.createOpportunity(accRec.Id, false);
        oppRec.Primary_Member__c = conRec.Id;
        oppRec.Broker_Involved__c = false;
        oppRec.StageName = 'Selling';
        oppRec.CloseDate = system.today().addDays(5);
        oppRec.Amount = 150;
        oppRec.RecordTypeId = oppRecordType.get('Consumer');
        TestingUtility.insertWithAssert(oppRec);
        
        Opportunity oppRec1 = TestingUtility.createOpportunity(accRec.Id, false);
        oppRec1.Primary_Member__c = conRec.Id;
        oppRec1.StageName = 'Selling';
        oppRec1.Broker_Involved__c = false;
        oppRec1.CloseDate = system.today().addDays(5);
        oppRec1.RecordTypeId = oppRecordType.get('Enterprise Solutions');
        TestingUtility.insertWithAssert(oppRec1);
        List<Opportunity> lstOpportunity = [select id from Opportunity ];
        System.assert(lstOpportunity.size() > 0);
        List<Opportunity> lstOpportunityToUpdate = new List<Opportunity>();
        for(Opportunity opportunity : lstOpportunity){
            opportunity.Referrer__c = referrerContact.Id;
            lstOpportunityToUpdate.add(opportunity);
        }
        update lstOpportunityToUpdate ;
    }
    
    static testMethod void verifyBrokerInvolved(){
        List<Opportunity> lstOpportunity = [SELECT Id, Referrer__c FROM Opportunity ];
        test.startTest();
        BrokerInvolvedController.updateBrokerInvolved(lstOpportunity[0].Id);
        BrokerInvolvedController.updateBrokerInvolved(lstOpportunity[1].Id);
        test.stopTest();
        for(Opportunity opportunity : [SELECT Id, Referrer__c, Broker_Involved_DateTime__c, Broker_Involved__c, Broker_Involvement_Indicated__c FROM Opportunity ]){
            System.assertEquals(Date.today(), opportunity.Broker_Involved_DateTime__c);
            System.assertEquals('Yes', opportunity.Broker_Involvement_Indicated__c);
        }
    }
    
}