objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <description>This is Picklist which Contains three values
1. Org : It is Main account in hierarchy which is Parent Account of Sales And Bill.
2. Sales: One Sales Account may contain multiple Bill Or Sales Account and It is Under Org Account in hierarchy
3. Bill: Bill Account is under Sales or Org. It never child of Bill Account.
4. ' '(Blank) : It is like Bill type which is under Sales or Org.</description>
        <inlineHelpText>This Picklist is used to determine the account type.</inlineHelpText>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Org</fullName>
                    <default>true</default>
                    <label>Org</label>
                </value>
                <value>
                    <fullName>Sales</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cleansed_Account_Name__c</fullName>
        <description>This field is used to save cleansed Account Name</description>
        <label>Cleansed Account Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Geography__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to store the geography record which is created when we find the market for account. Created for ST-3198</description>
        <inlineHelpText>Store the geography record which is created when we find the market for account.</inlineHelpText>
        <label>Geography</label>
        <referenceTo>Geography__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Nickname__c</fullName>
        <description>This field stores Nickname value for sales account</description>
        <inlineHelpText>This field stores Nickname value for sales account</inlineHelpText>
        <label>Sales Account Nickname</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unomy_Company_ID__c</fullName>
        <externalId>true</externalId>
        <label>Unomy Company ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unomy_Company_Name__c</fullName>
        <label>Unomy Company Name</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Billing_Account__c.object
<CustomObject>
    <fields>
        <fullName>Cleansed_Account_Name__c</fullName>
        <description>This field is used to save cleansed Billing Account Name</description>
        <inlineHelpText>This field shows the cleansed version of the Billing Account Name.</inlineHelpText>
        <label>Cleansed Account Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unomy_Company_ID__c</fullName>
        <externalId>true</externalId>
        <label>Unomy Company ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unomy_Company_Name__c</fullName>
        <label>Unomy Company Name</label>
        <type>TextArea</type>
    </fields>
    <description>All Billing account is moved to this Billing Account object it help Sales people to identify Org and Sales account easily and reduce the clutter of 100s of Accounts with same name.</description>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Building__c.object
<CustomObject>
    <fields>
        <fullName>Geography__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is a lookup of Geography object which is used to represent Google Maps Location so that we can reuse the same location as and when required within multiple objects.</description>
        <inlineHelpText>This field provides the exact or nearest google location where the building is located.</inlineHelpText>
        <label>Geography</label>
        <referenceTo>Geography__c</referenceTo>
        <relationshipLabel>Buildings</relationshipLabel>
        <relationshipName>Buildings_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Building</label>
    <nameField>
        <label>Building</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Building__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Building</label>
        <referenceTo>Building__c</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <formula>text(Account.Type)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Members</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Building__c</fullName>
        <description>Pulls Building Location without 3 character city reference</description>
        <formula>Location__r.Location_No_City__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Building</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Geography__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores the geography of nearest HQ Market.</description>
        <inlineHelpText>Stores the geography of nearest HQ Market.</inlineHelpText>
        <label>Geography</label>
        <referenceTo>Geography__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unomy_Company_ID__c</fullName>
        <label>Unomy Company ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unomy_Company_Name__c</fullName>
        <label>Unomy Company Name</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Geography__c.object
<CustomObject>
    <description>This object will represent Google Maps Location so that we can reuse same location as and when required within multiple objects.</description>
    <label>Geography</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Geographies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Checking</fullName>
                </value>
                <value>
                    <fullName>Savings</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field relates the opportunity to the billing account. The billing account is used in the space station for sending contracts.</description>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Building__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Enter the specific building for which opportunity is associated</description>
        <inlineHelpText>This is the building / Nearest building to the geography entered by customer</inlineHelpText>
        <label>Building/Nearest Building</label>
        <referenceTo>Building__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract_Stage__c</fullName>
        <label>Contract Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Contract Sent</fullName>
                </value>
                <value>
                    <fullName>Contract Voided</fullName>
                </value>
                <value>
                    <fullName>Contract Discarded</fullName>
                </value>
                <value>
                    <fullName>Contract Signed</fullName>
                </value>
                <value>
                    <fullName>Contract Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Geography__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will show the location where the lead is interested to find the spaces.</description>
        <inlineHelpText>Search for the relevant geographic location</inlineHelpText>
        <label>Geography</label>
        <referenceTo>Geography__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tour_Outcome__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tour Outcome</label>
        <referenceTo>Tour_Outcome__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Tour_Outcome__c.object
<CustomObject>
    <fields>
        <fullName>Tour_Outcome__c</fullName>
        <inlineHelpText>Outcome Status from SpaceStation</inlineHelpText>
        <label>Tour Outcome</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Ready to sign now</fullName>
                </value>
                <value>
                    <fullName>Interested</fullName>
                    <label>Tour Interested</label>
                </value>
                <value>
                    <fullName>Did not show up</fullName>
                    <label>No Show</label>
                </value>
                <value>
                    <fullName>Not Interested</fullName>
                    <label>Does not want Membership</label>
                </value>
                <value>
                    <fullName>Tour Reschedule</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Tour</label>
    <nameField>
        <displayFormat>TRO-{0000}</displayFormat>
        <label>Tour Outcome ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tours</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/MergeOrganizationsControllerTest.cls
@isTest
public class MergeOrganizationsControllerTest {
    /************************************************************************************************************************************
        Author 			: Rupesh Patil
        Description 	: This method has setup data for all test methods 
        Created Date	: 28 Nov 2018 
    **************************************************************************************************************************************/
    @TestSetup
    static void initData(){          
        SalesConsoleSettings.createSettings();
        Test.startTest();
        List<Contact> lstContacts = (List<Contact>)TestingUtility.getRecords(new Map<String, Object>{'objName' => 'Contact', 'numberOfRecords' => 4});
        List<Account> lstAccounts = (List<Account>)TestingUtility.getRecords(new Map<String, Object>{'objName' => 'Account', 'numberOfRecords' => 6});
        List<Building__c> lstBuildings = (List<Building__c>)TestingUtility.getRecords(new Map<String, Object>{'objName' => 'Building__c', 'numberOfRecords' => 1});
        List<Tour_Outcome__c> lstTours = (List<Tour_Outcome__c>)TestingUtility.getRecords(new Map<String, Object>{'objName' => 'Tour', 'numberOfRecords' => 4});
        List<Geography__c> lstGeographies = (List<Geography__c>)TestingUtility.getRecords(new Map<String, Object>{'objName' => 'Geography__c', 'numberOfRecords' => 2});
        List<Billing_Account__c> lstBillingAccounts = (List<Billing_Account__c>)TestingUtility.getRecords(new Map<String, Object>{'objName' => 'Billing_Account__c', 'numberOfRecords' => 1, 'doInsert' => true, 'method' => 'simpleBillingAccount'});        
        List<Opportunity> lstOpportunities = (List<Opportunity>)TestingUtility.getRecords(new Map<String, Object>{'objName' => 'Opportunity', 'numberOfRecords' => 1, 'doInsert' => true, 'mapFieldValues' => new Map<String, List<Object>>{'Contract_Stage__c' => new List<Object>{'Contract Sent'}, 'Billing_Account__c' => new List<Object>{lstBillingAccounts[0].Id}}});
        List<Campaign> lstCampaigns = (List<Campaign>)TestingUtility.getRecords(new Map<String, Object>{'objName' => 'Campaign', 'numberOfRecords' => 1});       
        Test.stopTest();
    }
    
/************************************************************************************************************************************
        Author 			: Sunil Bhosale
        Description 	: This method verify the merge organization functionality.
        Created Date	: 27 July 2018 
  **************************************************************************************************************************************/
    public static testMethod void verifyValidateAccounts(){
        List<Id> lstAccountIDs = new List<Id>();        
        Account orgAccount = TestingUtility.createAccount('strAccountName', false);
        orgAccount.Account_Type__c = 'Org'; 
        orgAccount.Unomy_Company_ID__c = 1234 ;
        orgAccount.Unomy_Company_Name__c = 'test company1';
        orgAccount.Cleansed_Account_Name__c = 'test company cleansed';
        insert orgAccount;
        lstAccountIDs.add(orgAccount.id);
        
        Account orgAccount1 = TestingUtility.createAccount('strAccountName1', false);
        orgAccount1.Account_Type__c = 'Org'; 
        orgAccount1.Unomy_Company_ID__c = 12345 ;
        orgAccount1.Unomy_Company_Name__c = 'test company2';
        orgAccount1.Cleansed_Account_Name__c = 'test company2 cleansed';
        insert orgAccount1;
        lstAccountIDs.add(orgAccount1.id);
        
        Account orgAccount2 = TestingUtility.createAccount('strAccountName2', false);
        orgAccount2.Account_Type__c = 'Org'; 
        orgAccount2.Unomy_Company_ID__c = 12345 ;
        orgAccount2.Unomy_Company_Name__c = 'test company2';
        orgAccount2.Cleansed_Account_Name__c = 'test company2 cleansed';
        insert orgAccount2;
        lstAccountIDs.add(orgAccount2.id); 
        MergeOrganizationsController.validateAccounts(orgAccount.Id,lstAccountIDs);
    }
   
    public static testMethod void verifyGetAccounts(){
        List<String> lstQuery = new List<String>();
        List<Account> lstAccount = new List<Account>();
        Account masterAcc = TestingUtility.createAccount('AccountName', false);
        masterAcc.Account_Type__c = 'Org';
        masterAcc.Nickname__c='PrinarySalesAcc';
        insert masterAcc;
        
        Account objAccount = TestingUtility.createAccount('AccountName', false);
        objAccount.Account_Type__c = 'Sales';
        objAccount.Nickname__c='PrinarySalesAcc';
        objAccount.ParentId = masterAcc.id;
        lstAccount.add(objAccount);
        
        Account objAccount2 = TestingUtility.createAccount('AccountName2', false);
        objAccount2.Account_Type__c = 'Sales';
        objAccount2.ParentId = masterAcc.id;
        objAccount2.Nickname__c='SalesAcc2';
       	lstAccount.add(objAccount2);
        insert lstAccount;
            
        lstQuery.add('SELECT Id FROM Account');
        lstQuery.add('SELECT Id FROM Account');
        
        MergeOrganizationsController.getAccountsToDisplay(lstQuery);
    }
    
    /************************************************************************************************************************************
        Author 			: Krishana Tupe
        Description 	: This method verify the merge organization functionality.
        Created Date	: 27 July 2018 
		Last Modified By: Rupesh Patil
		Last Modified Date : 28 Nov 2018
  **************************************************************************************************************************************/
    public static testMethod void verifyMergeAccounts(){		
        List<Account> lstAccounts = [SELECT Id, Name, Account_Type__c, Nickname__c FROM Account LIMIT 7];
        List<Id> lstAccountIDs = new List<Id>{lstAccounts[0].Id, lstAccounts[1].Id, lstAccounts[2].Id};
            
        Map<String, List<Account>> mapAccountsToMerge  = (Map<String, List<Account>>)MergeOrganizationsController.validateMergeAccounts(lstAccounts[0].Id, lstAccountIDs).data;        
        System.assert(mapAccountsToMerge.get('masterRecord') != null);
        System.assert(mapAccountsToMerge.get('lstMergedAccount') != null);
        LightningComponentController.ReturnValidResults objResults = new LightningComponentController.ReturnValidResults();
        
        String result  = (String)MergeOrganizationsController.mergeAccountsToMaster(mapAccountsToMerge.get('masterRecord')[0], mapAccountsToMerge.get('lstMergedAccount')).data;
        Map<String, Object> mapResult = (Map<String, Object>)JSON.deserializeUntyped(result);        
        System.assertEquals(true, mapResult.get('isSuccess'));
        System.assert(String.valueOf(mapResult.get('message')).equalsIgnoreCase('Accounts merged successfully. Redirecting you to the Primary Account'));
        
        //Insert three Sales accounts under one Org Account ,one is primary account and two Sales account for merge 
        lstAccounts[3].Account_Type__c = 'Sales';
        lstAccounts[3].Nickname__c = 'ParentSales';
        lstAccounts[3].ParentId = lstAccounts[0].Id;
        lstAccounts[4].Account_Type__c = 'Sales';
        lstAccounts[4].Nickname__c = 'SalesNic1';
        lstAccounts[4].ParentId = lstAccounts[0].Id;
        lstAccounts[5].Account_Type__c = 'Sales';
        lstAccounts[5].Nickname__c = 'SalesNic2';
        lstAccounts[5].ParentId = lstAccounts[0].Id;
        List<Account> lstSalesAcount = new  List<Account>{lstAccounts[3], lstAccounts[4], lstAccounts[5]};
        TestingUtility.updateListWithAssert(lstSalesAcount);
        
        lstAccountIDs = new List<Id>{lstAccounts[3].Id, lstAccounts[4].Id, lstAccounts[5].Id};
        mapAccountsToMerge  = (Map<String,List<Account>>)MergeOrganizationsController.validateMergeAccounts(lstAccounts[3].Id, lstAccountIDs).data;        
        System.assert(mapAccountsToMerge.get('masterRecord') != null);
        System.assert(mapAccountsToMerge.get('lstMergedAccount') != null);        
        
        result  = (String)MergeOrganizationsController.mergeAccountsToMaster(mapAccountsToMerge.get('masterRecord')[0], mapAccountsToMerge.get('lstMergedAccount')).data;
        mapResult = (Map<String, Object>)JSON.deserializeUntyped(result);       
        System.assertEquals(true, mapResult.get('isSuccess'));
        System.assert(String.valueOf(mapResult.get('message')).equalsIgnoreCase('Accounts merged successfully. Redirecting you to the Primary Account'));       
        
        DatabaseResult result2 = MergeOrganizationsController.mergeAccountsToMaster(lstAccounts[5], mapAccountsToMerge.get('lstMergedAccount'));
        System.assert(result2.success);
    }
}