objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Queue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference of account queue</description>
        <label>Account Queue</label>
        <referenceTo>Account_Queue__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <description>This field will updated by Lead to Activity mapping.</description>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alexandria</fullName>
                </value>
                <value>
                    <fullName>Alpharetta</fullName>
                </value>
                <value>
                    <fullName>Amsterdam</fullName>
                </value>
                <value>
                    <fullName>Ann Arbor</fullName>
                </value>
                <value>
                    <fullName>Atlanta</fullName>
                </value>
                <value>
                    <fullName>Austin</fullName>
                </value>
                <value>
                    <fullName>Balston</fullName>
                </value>
                <value>
                    <fullName>Baltimore</fullName>
                </value>
                <value>
                    <fullName>Bangkok</fullName>
                </value>
                <value>
                    <fullName>Barcelona</fullName>
                </value>
                <value>
                    <fullName>Barranquilla</fullName>
                </value>
                <value>
                    <fullName>Be'er Sheva</fullName>
                </value>
                <value>
                    <fullName>Beijing</fullName>
                </value>
                <value>
                    <fullName>Belo Horizonte</fullName>
                </value>
                <value>
                    <fullName>Bengaluru</fullName>
                </value>
                <value>
                    <fullName>Berkeley</fullName>
                </value>
                <value>
                    <fullName>Berlin</fullName>
                </value>
                <value>
                    <fullName>Bethesda</fullName>
                </value>
                <value>
                    <fullName>Bogota</fullName>
                </value>
                <value>
                    <fullName>Bogotá</fullName>
                </value>
                <value>
                    <fullName>Boston</fullName>
                </value>
                <value>
                    <fullName>Boulder</fullName>
                </value>
                <value>
                    <fullName>Brasilia</fullName>
                </value>
                <value>
                    <fullName>Brisbane</fullName>
                </value>
                <value>
                    <fullName>Brussels</fullName>
                </value>
                <value>
                    <fullName>Budapest</fullName>
                </value>
                <value>
                    <fullName>Buenos Aires</fullName>
                </value>
                <value>
                    <fullName>Busan</fullName>
                </value>
                <value>
                    <fullName>Calgary</fullName>
                </value>
                <value>
                    <fullName>Cali</fullName>
                </value>
                <value>
                    <fullName>London</fullName>
                </value>
                <value>
                    <fullName>Sydney</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UUID__c</fullName>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Consumer</fullName>
        <active>true</active>
        <description>This is Updated Record Type from Default to Consumer for New Sales Process and Changes</description>
        <label>Consumer</label>
    </recordTypes>
</CustomObject>

objects/Account_Queue__c.object
<CustomObject>
    <fields>
        <fullName>Account_Record_Type__c</fullName>
        <description>This will filter out the account for which we need to force the account assignment rule.</description>
        <label>Account Record Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Consumer</fullName>
                </value>
                <value>
                    <fullName>Mid Market</fullName>
                    <default>true</default>
                    <label>Mid Market</label>
                </value>
                <value>
                    <fullName>Enterprise Solutions</fullName>
                </value>
                <value>
                    <fullName>Referral</fullName>
                </value>
                <value>
                    <fullName>Partnership</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_Queue_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>This field will ensure that this record can be used for account assignment rule.</description>
        <label>Is Queue Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Last_Account_Assigned__c</fullName>
        <description>This field will be updated with current date/time when the member of current record assigned as the owner of any record.</description>
        <label>Last Account Assigned</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <description>This field will hep us to match to account for Account assignment.</description>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Amsterdam</fullName>
                </value>
                <value>
                    <fullName>Atlanta</fullName>
                </value>
                <value>
                    <fullName>Austin</fullName>
                </value>
                <value>
                    <fullName>Baltimore</fullName>
                </value>
                <value>
                    <fullName>Bangkok</fullName>
                </value>
                <value>
                    <fullName>Barranquilla</fullName>
                </value>
                <value>
                    <fullName>Be'er Sheva</fullName>
                </value>
                <value>
                    <fullName>Beijing</fullName>
                </value>
                <value>
                    <fullName>Bengaluru</fullName>
                </value>
                <value>
                    <fullName>Berkeley</fullName>
                </value>
                <value>
                    <fullName>Berlin</fullName>
                </value>
                <value>
                    <fullName>Bogota</fullName>
                </value>
                <value>
                    <fullName>Boston</fullName>
                </value>
                <value>
                    <fullName>Boulder</fullName>
                </value>
                <value>
                    <fullName>Buenos Aires</fullName>
                </value>
                <value>
                    <fullName>Charlotte</fullName>
                </value>
                <value>
                    <fullName>Chicago</fullName>
                </value>
                <value>
                    <fullName>Dallas</fullName>
                </value>
                <value>
                    <fullName>Delhi</fullName>
                </value>
                <value>
                    <fullName>Denver</fullName>
                </value>
                <value>
                    <fullName>Detroit</fullName>
                </value>
                <value>
                    <fullName>Dublin</fullName>
                </value>
                <value>
                    <fullName>Fort Worth</fullName>
                </value>
                <value>
                    <fullName>Frankfurt</fullName>
                </value>
                <value>
                    <fullName>Guangzhou</fullName>
                </value>
                <value>
                    <fullName>Hamburg</fullName>
                </value>
                <value>
                    <fullName>Herzliya</fullName>
                </value>
                <value>
                    <fullName>Ho Chi Minh City</fullName>
                </value>
                <value>
                    <fullName>Hong Kong</fullName>
                </value>
                <value>
                    <fullName>Houston</fullName>
                </value>
                <value>
                    <fullName>London</fullName>
                </value>
                <value>
                    <fullName>Sydney</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is a lookup of the user and will be used in account assignment use case as an owner.</description>
        <label>Member</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_Queues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Portfolio__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Portfolio</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Account Queues</relationshipLabel>
        <relationshipName>Account_Queues</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>This object will be used in Account assignment use case.</description>
    <label>Account Queue</label>
    <nameField>
        <displayFormat>Queue-{00000}</displayFormat>
        <label>Queue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Queues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Building__c.object
<CustomObject>
    <fields>
        <fullName>Market__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Portfolio</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Buildings</relationshipLabel>
        <relationshipName>Buildings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UUID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Building</label>
    <nameField>
        <label>Building</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Market__c.object
<CustomObject>
    <fields>
        <fullName>Portfolio__c</fullName>
        <description>Display name for portfolio, something user friendly to end users</description>
        <inlineHelpText>Display name (text)</inlineHelpText>
        <label>Portfolio Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UUID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <description>We are introducing new object Market so that same building can fall under multiple Markets as per Marketing department requirement.</description>
    <label>Portfolio</label>
    <nameField>
        <label>Portfolio</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portfolios</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Building__c</fullName>
        <label>Building</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AMS-Metropool</fullName>
                </value>
                <value>
                    <fullName>AMS-Labs</fullName>
                </value>
                <value>
                    <fullName>AMS-Weteringschans</fullName>
                </value>
                <value>
                    <fullName>ATX-Congress</fullName>
                </value>
                <value>
                    <fullName>ATX-Labs</fullName>
                </value>
                <value>
                    <fullName>BKN-Dumbo Heights</fullName>
                </value>
                <value>
                    <fullName>BK-Williamsburg</fullName>
                </value>
                <value>
                    <fullName>BOS-Fort Point</fullName>
                </value>
                <value>
                    <fullName>BOS-Labs</fullName>
                </value>
                <value>
                    <fullName>BOS-South Station</fullName>
                </value>
                <value>
                    <fullName>CHI-Fulton Market</fullName>
                </value>
                <value>
                    <fullName>CHI-Labs</fullName>
                </value>
                <value>
                    <fullName>CHI-RiverNorth</fullName>
                </value>
                <value>
                    <fullName>DC-Chinatown</fullName>
                </value>
                <value>
                    <fullName>DC-DuPont Circle</fullName>
                </value>
                <value>
                    <fullName>DC-Labs</fullName>
                </value>
                <value>
                    <fullName>DC-Wonder Bread Factory</fullName>
                </value>
                <value>
                    <fullName>ISR-Labs</fullName>
                </value>
                <value>
                    <fullName>LA-Fine Arts</fullName>
                </value>
                <value>
                    <fullName>LA-Fine Arts Building</fullName>
                </value>
                <value>
                    <fullName>LA-Hollywood</fullName>
                </value>
                <value>
                    <fullName>LA-Labs</fullName>
                </value>
                <value>
                    <fullName>LA-Promenade</fullName>
                </value>
                <value>
                    <fullName>LA-Santa Monica</fullName>
                </value>
                <value>
                    <fullName>LON-Devonshire</fullName>
                </value>
                <value>
                    <fullName>LON-East London</fullName>
                </value>
                <value>
                    <fullName>LON-Labs</fullName>
                </value>
                <value>
                    <fullName>LON-Moorgate</fullName>
                </value>
                <value>
                    <fullName>LON-South Bank</fullName>
                </value>
                <value>
                    <fullName>LON-Soho London</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/AccountQueueTriggerHandlerTest.cls
/************************************************************************************************************************************
   	Author 		: Dipak Pawar
   	Description : This class Contains Unit Tests of AccountQueueTriggerHandler.

   	History		:
	----------------------------------------------------------------------------------------------------------------------------------
	VERSION		DATE				AUTHOR				DETAIL
	1			26 April 2017		Dipak Pawar 		Initial Developement
**************************************************************************************************************************************/

@isTest
public with sharing class AccountQueueTriggerHandlerTest {
    @TestSetup
    static void ininData(){
        SalesConsoleSettings.createSettings();
    }
    /************************************************************************************************************************************
        Author 				: Dipak Pawar
        Description 		: Test method for Restrict Duplicate Records for Account Assignment
        Last Modified Date	: 26 April 2017
        Last Modified By	: Dipak Pawar
	**************************************************************************************************************************************/	
    static testMethod void testRestrictDuplicateRecordsForAccountAssignment() {
        
        Profile testProfile = [SELECT Id FROM Profile WHERE Name='System Administrator'];
        Debug.log('testProfile :: '+testProfile);
        System.assertNotEquals(null, testProfile);
        
        User testUser = new User(Alias = 'testU', Email='testWeworkUser@example.com', 
                                 EmailEncodingKey='UTF-8', LastName='User', LanguageLocaleKey='en_US', 
                                 LocaleSidKey='en_US', ProfileId = testProfile.Id, IsActive = true,
                                 TimeZoneSidKey='America/Los_Angeles', UserName='testWeworkUser@example.com', CommunityNickname = TestingUtility.createUserCommunityName());
        
        
        insert testUser;
        Debug.log('testUser :: '+testUser);
        System.assertNotEquals(null, testUser.ID);
        
        Map<String, Id> accountRecordType = TestingUtility.getRecordTypeMapByName(Account.sObjectType);
        Debug.log('accountRecordType :: '+accountRecordType);
        
        Account testAccount = new Account(Name = 'TestCompany', RecordTypeId = accountRecordType.get('Mid Market'));
        insert testAccount;
        Debug.log('testAccount : '+testAccount);
        System.assertNotEquals(null, testAccount.Id);
        
        Building__c testMarket = new Building__c(
            Name='Test Market',
            uuid__c = 'testUUID'
        );
        insert testMarket;
        Debug.log('testMarket :: '+testMarket);
        System.assertNotEquals(null, testMarket.Id);
        
        List<Market__c> lstMarkets = new List<Market__c>(); 
        lstMarkets.add(new Market__c(Name='Sydney',CurrencyIsoCode='USD'));
        lstMarkets.add(new Market__c(Name='London',CurrencyIsoCode='USD'));
        insert lstMarkets;
        
        Account_Queue__c accountQueueRec = new Account_Queue__c(
            Account_Record_Type__c = 'Consumer',
            Is_Queue_Active__c = true,
            Market__c = testMarket.Name,
            Portfolio__c = lstMarkets[0].Id,
            Member__c = testUser.Id,
            Last_Account_Assigned__c = System.now()
        );
        insert accountQueueRec;
        Debug.log('accountQueueRec :: '+accountQueueRec);
        System.assertNotEquals(null, accountQueueRec.Id);
        
        accountQueueRec = new Account_Queue__c(
            Account_Record_Type__c = 'Enterprise Solutions',
            Is_Queue_Active__c = true,
            Market__c = testMarket.Name,
            Portfolio__c = lstMarkets[0].Id,
            Member__c = testUser.Id,
            Last_Account_Assigned__c = System.now()
        );
        insert accountQueueRec;
        
        accountQueueRec.Account_Record_Type__c = 'Mid Market';
        accountQueueRec.Market__c = 'Test Market';
        accountQueueRec.Member__c = testUser.Id+'';
        accountQueueRec.Last_Account_Assigned__c = system.today().addDays(1);
        update accountQueueRec;
        
        LIst<Account_Queue__c> accQueueRec = [SELECT Id, Account_Record_Type__c, Is_Member_Active__c, Is_Queue_Active__c, Market__c, Member__c FROM Account_Queue__c WHERE Id =:accountQueueRec.Id ];
        Debug.log('accQueueRec :: '+accQueueRec);
        System.assertNotEquals(0, accQueueRec.size());
        
        List<Account_Queue__c> lstToInsert = new List<Account_Queue__c>();
        
        accountQueueRec = new Account_Queue__c(
            Account_Record_Type__c = 'Mid Market',
            Is_Queue_Active__c = true,
            Market__c = testMarket.Name,
            Portfolio__c = lstMarkets[0].Id,
            Member__c = testUser.Id,
            Last_Account_Assigned__c = System.now()
        );
        lstToInsert.add(accountQueueRec);
        
        accountQueueRec = new Account_Queue__c(
            Account_Record_Type__c = 'Enterprise Solutions',
            Is_Queue_Active__c = true,
            Market__c = testMarket.Name,
            Portfolio__c = lstMarkets[0].Id,
            Member__c = testUser.Id,
            Last_Account_Assigned__c = System.now()
        );
        lstToInsert.add(accountQueueRec); 
        
        accountQueueRec = new Account_Queue__c(
            Account_Record_Type__c = 'Enterprise Solutions',
            Is_Queue_Active__c = true,
            Market__c = testMarket.Name,
            Portfolio__c = lstMarkets[0].Id,
            Member__c = testUser.Id,
            Last_Account_Assigned__c = System.now()
        );
        lstToInsert.add(accountQueueRec); 
        Debug.log('lstToInsert :: '+lstToInsert);
        
        try {
            insert lstToInsert;
            Debug.log('lstToInsert :: '+lstToInsert);
        } catch(Exception e) {
            Boolean expectedExceptionThrown =  e.getMessage().contains('Duplicate Record found') ? true : false;
            System.AssertEquals(expectedExceptionThrown, true);
        } 
    }
}