objects/Account.object
<CustomObject>
    <fields>
        <fullName>Company_Size__c</fullName>
        <label>Company Size</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1-5</fullName>
                </value>
                <value>
                    <fullName>6-20</fullName>
                </value>
                <value>
                    <fullName>21-50</fullName>
                </value>
                <value>
                    <fullName>51-100</fullName>
                </value>
                <value>
                    <fullName>101-200</fullName>
                </value>
                <value>
                    <fullName>200+</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Interested_in_Number_of_Desks__c</fullName>
        <label>Interested in Number of Desk(s)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Full_Time_Employees__c</fullName>
        <label>Number of Full Time Employees</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unomy_Company_Size__c</fullName>
        <label>Unomy Company Size</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Billing_Account__c.object
<CustomObject>
    <fields>
        <fullName>Number_of_Full_Time_Employees__c</fullName>
        <label>Number of Full Time Employees</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unomy_Company_Size__c</fullName>
        <label>Unomy Company Size</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <description>All Billing account is moved to this Billing Account object it help Sales people to identify Org and Sales account easily and reduce the clutter of 100s of Accounts with same name.</description>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Building__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Buildings</relationshipLabel>
        <relationshipName>Buildings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Building</label>
    <nameField>
        <label>Building</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Company_Size__c</fullName>
        <formula>IF(Account.Number_of_Full_Time_Employees__c != NULL , Text(Account.Number_of_Full_Time_Employees__c) , null)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Company Size</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Interested_in_Number_of_Desks__c</fullName>
        <label>Interested in Number of Desk(s)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Building__c</referenceTo>
        <relationshipLabel>Members</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number_of_Full_Time_Employees__c</fullName>
        <label>Number of Full Time Employees</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This is the latest status coming from Space systems through Jitterbunny of the individual member. This tells us if the user is active or not.</description>
        <inlineHelpText>This is accurate status of a contact if it is an active member of our products or not.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>active</fullName>
                </value>
                <value>
                    <fullName>inactive</fullName>
                    <default>true</default>
                    <label>inactive</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unomy_Company_Size__c</fullName>
        <label>Unomy Company Size</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Journey__c.object
<CustomObject>
    <fields>
        <fullName>Building_Interested_In__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Building Interested In</label>
        <referenceTo>Building__c</referenceTo>
        <relationshipLabel>Journeys</relationshipLabel>
        <relationshipName>Journeys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Interested_in_Number_of_Desks__c</fullName>
        <label>Interested in Number of Desk(s)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Full_Time_Employees__c</fullName>
        <label>Number of Full Time Employees</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Primary Contact of the Journey</description>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Journeys</relationshipLabel>
        <relationshipName>Journeys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>If journey is for a Lead this will be the Primary Lead. Only Primary Contact or Primary Lead can be specified not both.</description>
        <label>Primary Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Journeys</relationshipLabel>
        <relationshipName>Journeys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>New Field to Capture Journey Status</description>
        <label>Journey Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Started</fullName>
                    <default>true</default>
                    <label>Started</label>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Trying to Reach</fullName>
                </value>
                <value>
                    <fullName>In Contact</fullName>
                </value>
                <value>
                    <fullName>Nurture</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Transferred</fullName>
                </value>
                <value>
                    <fullName>Unresponsive</fullName>
                </value>
                <value>
                    <fullName>No Contact</fullName>
                </value>
                <value>
                    <fullName>Unqualified</fullName>
                </value>
                <value>
                    <fullName>Auto-Complete/Expiration</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unomy_Company_Size__c</fullName>
        <formula>IF( Primary_Lead__c != NULL , Primary_Lead__r.Unomy_Company_Size__c, IF( Primary_Contact__c != NULL, Primary_Contact__r.Unomy_Company_Size__c ,""))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unomy Company Size</label>
        <type>Text</type>
    </fields>
    <description>We are going to use this object as Sales Journey of the user. Which begins when a person shows interest in one of our products or we decide to reach out to show our products.</description>
    <label>Journey</label>
    <nameField>
        <label>Customer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Journeys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field contains the value of Org account for which lead is associated.</description>
        <inlineHelpText>Enter the name of the organization associated with this new Opportunity. If an existing organization does not appear when typing the name, click "New Organization" to create a new one.</inlineHelpText>
        <label>Organization</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Account.Account_Type__c</field>
                <operation>equals</operation>
                <value>Org</value>
            </filterItems>
            <filterItems>
                <field>Account.Account_Type__c</field>
                <operation>equals</operation>
                <value>Sales</value>
            </filterItems>
            <infoMessage>Leads can only be associated to accounts havinng account type 'Org'.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads (Account)</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Building_Interested_In__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Building Interested In</label>
        <referenceTo>Building__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Company_Size__c</fullName>
        <label>Company Size</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1-5</fullName>
                </value>
                <value>
                    <fullName>6-20</fullName>
                </value>
                <value>
                    <fullName>21-50</fullName>
                </value>
                <value>
                    <fullName>51-100</fullName>
                </value>
                <value>
                    <fullName>101-200</fullName>
                </value>
                <value>
                    <fullName>201+</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Interested_in_Number_of_Desks__c</fullName>
        <label>Interested in Number of Desk(s)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Full_Time_Employees__c</fullName>
        <label>Number of Full Time Employees</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unomy_Company_Size__c</fullName>
        <label>Unomy Company Size</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Company_Size__c</fullName>
        <label>Company Size</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1-5</fullName>
                </value>
                <value>
                    <fullName>6-20</fullName>
                </value>
                <value>
                    <fullName>21-50</fullName>
                </value>
                <value>
                    <fullName>51-100</fullName>
                </value>
                <value>
                    <fullName>101-200</fullName>
                </value>
                <value>
                    <fullName>201+</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Interested_in_Number_of_Desks__c</fullName>
        <label>Interested in Number of Desk(s)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Journey__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Journey</label>
        <referenceTo>Journey__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number_of_Full_Time_Employees__c</fullName>
        <label>Number of Full Time Employees</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Primary Contact)</relationshipLabel>
        <relationshipName>Opportunities4</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/AddOpportunityController.cls
/************************************************************************************************************************************
    Author      :   Priyanka Ambre
    Description :   This class contain all aura methods related to AddOpportunity.
    ----------------------------------------------------------------------------------------------------------------------------------
    VERSION     DATE                AUTHOR                  DETAIL
    1           30 Oct 2018         Priyanka Ambre      	Initial Developement
	2           31 Oct 2018         Krishana Tupe         	Code Optimization
**************************************************************************************************************************************/
global without sharing class AddOpportunityController {    
    public static Boolean isInvoker = false;
    public static Savepoint sp;
    static {
        isInvoker = ApexDebugLog.registerRootInvoker(ApexDebugLog.InvokerType.AURA, 'AddOpportunityController' + 'getsObjectPrefix', ApexDebugLog.InvokerType.AURA);        
    }
    
 /****************************************************************************************************************************
        Author              : Ajaysinh Chauhan
        Description         : This method is used to get Opportunity related detail data like account name, contact name and lead name. 
  *****************************************************************************************************************************/   
    @AuraEnabled
    public static DatabaseResult getAddOpportunityData(Id journeyId){        
        try{
            if(String.isBlank(journeyId)){
                throw new AddOpportunityControllerException('Please provide journey Id');  
            }
            AddOpportunityData objAddOpportunityData = new AddOpportunityData();
            objAddOpportunityData.journeyRecord = [SELECT Id, Name, Primary_Lead__c, Primary_Lead__r.Account__c, Primary_Contact__r.Name, Primary_Contact__r.Account.Name, Status__c, Primary_Lead__r.Name, Primary_Lead__r.Email, Primary_Lead__r.Company, OwnerId, Owner.Name FROM Journey__C WHERE Id =: journeyId];
            objAddOpportunityData.settingData = Settings.get('SendPaperworkSetting').Data__c; 
            objAddOpportunityData.excludedProfiles = Settings.get('AccountSelectorSettings').Data__c;        
            objAddOpportunityData.systemDate = system.today();
            objAddOpportunityData.currentUserProfile = [SELECT Id, ProfileId, Profile.Name FROM USER WHERE Id =: UserInfo.getUserId()].Profile.Name;            
            return new DatabaseResult(JSON.serialize(objAddOpportunityData)); 
        }catch(Exception pEx){ 
            ApexDebugLog.logException(pEx,'journeyId==>'+journeyId, 'AddOpportunityController', 'getAddOpportunityData'); 
            return (new DatabaseResult(pEx));
        }    
    }   
     
 /****************************************************************************************************************************
        Author              : Ajaysinh Chauhan
        Description         : This method is used to get Opportunity related detail data like account name, contact name and lead name.
        Created Date        : -
        Last Modified By    : Ashish Mishra
        Last Modified Date  : 31,May 2018
  *****************************************************************************************************************************/
    @AuraEnabled
    public static DatabaseResult getJourneyOpportunityData(Map<String, String> mapOpportunityData){
        try{
            if(mapOpportunityData == null){
                throw new AddOpportunityControllerException('Parameter should not be blank');     
            }
            JourneyOpportunityData journeyOpportunityData = new JourneyOpportunityData();
            if(mapOpportunityData.containsKey('journeyId')){
                journeyOpportunityData.journey = [SELECT Id, Building_Interested_In__c, Primary_Contact__r.AccountId, Primary_Contact__c,Primary_Lead__c FROM Journey__c WHERE Id =: Id.valueOf(mapOpportunityData.get('journeyId'))]; 
            } 
            if(mapOpportunityData.containsKey('accountId')){               
                journeyOpportunityData.account = [SELECT Id, OwnerId, RecordType.Name, Number_of_Full_Time_Employees__c, Company_Size__c, Unomy_Company_Size__c, Interested_in_Number_of_Desks__c FROM Account WHERE Id =: Id.valueOf(mapOpportunityData.get('accountId'))];         
            }
            if(mapOpportunityData.containsKey('contactId')){              
                journeyOpportunityData.contact = [SELECT Id, Number_of_Full_Time_Employees__c, Interested_in_Number_of_Desks__c, Location__c, Location_Interested__c FROM Contact WHERE Id =: Id.valueOf(mapOpportunityData.get('contactId'))];
            }
            if(mapOpportunityData.containsKey('leadId')){                
                journeyOpportunityData.lead = [SELECT Id, Number_of_Full_Time_Employees__c,Unomy_Company_Size__c,Interested_in_Number_of_Desks__c  FROM Lead WHERE Id =: Id.valueOf(mapOpportunityData.get('leadId'))];
            }
            journeyOpportunityData.opportunityRecordTypes = Schema.SObjectType.Opportunity.getRecordTypeInfosByName();
            journeyOpportunityData.accountRecordTypes = Schema.SObjectType.Account.getRecordTypeInfosByName();            
            journeyOpportunityData.mapBuildings = new map<Id, Building__c>([SELECT Id, Name, UUID__c FROM Building__c]);
            return new DatabaseResult(JSON.serialize(journeyOpportunityData) ); 
        }catch(Exception pEx){
            ApexDebugLog.logException(pEx,'', 'AddOpportunityController', 'getJourneyOpportunityData');   
            return (new DatabaseResult(pEx));
        }  
    }
    
 /****************************************************************************************************************************
        Author              : Priyanka Ambre
        Description         : This method is used to get required query data.
        Created Date        : 30 Oct 2018        
   *****************************************************************************************************************************/ 
    @AuraEnabled
    public static DatabaseResult getQueryData(String queryLable, Id journeyId, Id contactId, Id accountId){           
        try{
            sp = Database.setSavepoint();    
            if(String.isBlank(queryLable)){
                throw new AddOpportunityControllerException('Please provide queryLable');  
            }
            String query;
            switch on queryLable {
                when 'getJourneyRelatedOpportunities' {
                    query = 'SELECT Id, RecordType.Name, Name, Type__c, Account.Name, Billing_Account__c, Billing_Account__r.UUID__c, Primary_Member__r.Name, Building__r.Name, Building__r.UUID__c, StageName, CloseDate, Encoded_ID__c, Actual_Start_Date__c, Quantity__c, Deal_Type__c FROM Opportunity WHERE Primary_Member__c =: contactId OR Journey__c =: journeyId';
                }
                when 'getAccountRecord' {
                    query = 'SELECT Id, Name, Parent_Org_Id__c,Account_Type__c FROM Account WHERE Id =: accountId';
                }
            }            
            if(String.isNotBlank(query)){
                return new DatabaseResult(Database.query(query));                
            }
            return null;            
        }catch(Exception pEx){                   
            LightningComponentController.rollbackTransaction(sp);
            ApexDebugLog.logException(pEx, queryLable + ' ' + journeyId + ' ' + accountId, 'AddOpportunityController', 'getQueryData');
            return (new DatabaseResult(pEx));             
        }
    }
    
 /****************************************************************************************************************************
    Author              : Krishana Tupe
    Description         : This method is used to insert new Opportunity from AddOpportunity component.
    Created Date        : 01 Nov 2018    
*****************************************************************************************************************************/    
    @AuraEnabled  
    global static DatabaseResult insertAddOpportunity(Map<String,Object> mapOpportunityData){       
        try{
            Debug.log('mapOpportunityData ==>'+mapOpportunityData);
            sp = Database.setSavepoint();
            if(mapOpportunityData == null){
                throw new AddOpportunityControllerException('Parameter should not be blank');     
            }
            Opportunity objOpportunity = new Opportunity();
            objOpportunity = (Opportunity)FieldMappingsHelper.getMappings((String)mapOpportunityData.get('Primary_Member__c'), objOpportunity, 'FieldMappings:ContactToOpportunity');      
            Debug.log('Close Date ==>'+mapOpportunityData.get('CloseDate'));
            if(mapOpportunityData.get('CloseDate') != null){
                String closedate = (String)mapOpportunityData.get('CloseDate');
                objOpportunity.CloseDate = Date.valueOf(closedate);
                objOpportunity.Is_From_Add_Opportunity__c = true;
            }else{
                objOpportunity.CloseDate = System.today();                
            }   
            
            for(String field : mapOpportunityData.keySet()){  
                if(!field.equalsIgnoreCase('CloseDate')){
                    objOpportunity.put(field, mapOpportunityData.get(field)); 
                }           
            }
            Set<Id> setProfileId = (Set<Id>)JSON.deserialize(Settings.getMetadataSettingByDevName('AddOpportunitySetStageClosing').Data__c, Set<Id>.class);
            objOpportunity.StageName = (!setProfileId.isEmpty() && setProfileId.contains(UserInfo.getProfileId())) ? 'Closing' : 'Qualifying';
            objOpportunity.OwnerId = userInfo.getUserId();
            objOpportunity.Owner_Auto_Assign__c = false;
            return new DatabaseResult(JSON.serialize(Database.insert(objOpportunity))); 
        }catch(Exception pEx){
            LightningComponentController.rollbackTransaction(sp);
            ApexDebugLog.logException(pEx,mapOpportunityData != null ? JSON.serialize(mapOpportunityData) : '', 'AddOpportunityController', 'insertAddOpportunity');  
            return (new DatabaseResult(pEx));
        }
    } 
    
    /************************************************************************************************************************************
        Author              : Rohit Nimase
        Description         : This method checks is opportunity is valid for SendPaperWork functionality.
        Created Date        : 23 July 2018 
        Issue No            : CSI-1571
    **************************************************************************************************************************************/	
    @AuraEnabled
    public static DatabaseResult isValidOppforSendPaperwork(Id oppId){        
        return new DatabaseResult(SendPaperWorkController.isValidOppforSendPaperwork(oppId));
    }
    
 /****************************************************************************************************************************
        Author              : Milanjeet
        Description         : Added from Ajay instance for Add Opportunity Functionality
        Created Date        : 9:33 PM 08/16/2017
        Issue               : ST-1262,1270
  *****************************************************************************************************************************/
    global class AddOpportunityData{
        @AuraEnabled
        public Journey__c journeyRecord {get;set;}
        @AuraEnabled
        public String settingData {get;set;}
        @AuraEnabled
        public String excludedProfiles {get;set;}
        @AuraEnabled
        public String currentUserProfile {get;set;}
        @AuraEnabled
        public Date systemDate {get;set;}
    }

 /****************************************************************************************************************************
        Author              : Ajaysinh Chauhan
        Description         : Class for Journey Opportunity Data.             
  ****************************************************************************************************************************/ 
    global class JourneyOpportunityData{
        @AuraEnabled
        public Account account {get;set;}
        @AuraEnabled
        public Contact contact {get;set;}
        @AuraEnabled
        public Journey__c journey {get;set;}
        @AuraEnabled
        public Lead lead {get;set;}
        @AuraEnabled
        public Map<Id, Building__c> mapBuildings {get;set;}
        @AuraEnabled
        public Map<String, Object> opportunityRecordTypes {get;set;}
        @AuraEnabled
        public Map<String, Object> accountRecordTypes {get;set;}
    }   
    
 /****************************************************************************************************************************
        Author              : Krishana Tupe
        Description         : This class is used for handle the custom exception of AddOpportunity class.
		CreatedDate 		: 31 Oct 2018
  ****************************************************************************************************************************/ 
    public class AddOpportunityControllerException extends Exception{}
    
}