objects/Account.object
<CustomObject>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Referral</fullName>
        <active>true</active>
        <label>Referral</label>
    </recordTypes>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_Broker__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Contact Broker</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Referrer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referrer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Licensee</fullName>
                </value>
                <value>
                    <fullName>Employee</fullName>
                </value>
                <value>
                    <fullName>Member</fullName>
                </value>
                <value>
                    <fullName>Broker</fullName>
                </value>
                <value>
                    <fullName>Affiliate</fullName>
                </value>
                <value>
                    <fullName>Potential</fullName>
                </value>
                <value>
                    <fullName>Lead</fullName>
                </value>
                <value>
                    <fullName>Unqualified Broker</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Referral</fullName>
        <active>true</active>
        <label>Referral</label>
    </recordTypes>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Contact_Broker__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>DO NOT Call the Lead directly if this is checked. Please call the Broker instead.</inlineHelpText>
        <label>Contact Broker Only</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Referrer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This will be the contact who referred us the Lead. It can be a member, employee or a broker.</description>
        <inlineHelpText>Enter the contact who referred us the Lead. It can be a member, employee or a broker.</inlineHelpText>
        <label>Referrer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Leads (Referrer)</relationshipLabel>
        <relationshipName>ReferredLeads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Office Space</fullName>
                    <default>true</default>
                    <label>Office Space</label>
                </value>
                <value>
                    <fullName>Network Membership</fullName>
                </value>
                <value>
                    <fullName>Premium Network Membership</fullName>
                </value>
                <value>
                    <fullName>Event Space</fullName>
                </value>
                <value>
                    <fullName>Commons</fullName>
                </value>
                <value>
                    <fullName>Residential Space</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Contact_Broker__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to identify whether lead to be contacted  by the Broker</description>
        <inlineHelpText>Flag to identify whether lead to be contacted  by the Broker</inlineHelpText>
        <label>Contact Broker</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contract_Sent_Date__c</fullName>
        <label>Contract Sent Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Merged_Opprtunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field contain id of primary opportunity in which current opportunity is merged</description>
        <label>Merged Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Member__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>This is the Main Contact of the Opportunity</inlineHelpText>
        <label>Main Contact</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Referrer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referrer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Referrer)</relationshipLabel>
        <relationshipName>Opportunities3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tour_Outcome__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tour Outcome</label>
        <referenceTo>Tour_Outcome__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Event Space</fullName>
                </value>
                <value>
                    <fullName>Internal Transfer</fullName>
                </value>
                <value>
                    <fullName>Partnership</fullName>
                </value>
                <value>
                    <fullName>PxWe</fullName>
                </value>
                <value>
                    <fullName>Mixed</fullName>
                </value>
                <value>
                    <fullName>Global Access</fullName>
                </value>
                <value>
                    <fullName>WeWork</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Referral__c.object
<CustomObject>
    <fields>
        <fullName>Expires_On__c</fullName>
        <description>Date on which this Reference Expires, every time reference needs to be extended this date should be updated to reflect the extension. Any Opportunity created while this reference is not expired, for the primary contact matching the email provided in this reference will be have Referrer set with Referrer in this record.</description>
        <label>Expires On</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Referral_Email__c</fullName>
        <description>Captures the email of the new lead coming to the system with reference of a referrer.</description>
        <label>Referral Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Referral_Source__c</fullName>
        <description>Captures the source of the lead from where the lead is coming from ?</description>
        <label>Referral Source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Referrer_Type__c</fullName>
        <description>Captures the type of the referrer (contact) either a member or employee or any other value fetched from the contact level.</description>
        <label>Referrer Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Referrer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contact who Referred the Person identified by given email address.</description>
        <label>Referrer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Referrals</relationshipLabel>
        <relationshipName>Referrals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Captures the start date of the reference, on which the referrer has referred the new lead. This is used to calculate the expiry of the reference record.</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <description>This object will represent references made by either Member/Broker/Employee to certain person identified by email. 

This is generally valid for 60 days and may be extended by another 60 days based on certain events like if referred person books a tour, completes a tour or paperwork is sent to the person referred.</description>
    <label>Referral</label>
    <nameField>
        <label>Referral Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referrals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Setting__c.object
<CustomObject>
    <fields>
        <fullName>Data__c</fullName>
        <description>This should contain JSON formatted data for each setting record. The JSON object will vary from setting to setting.</description>
        <label>Data</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type of the Settings, if it is Field Mappings, it will contain mapping of source object to destination object in JSON format.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Field Mappings</fullName>
                </value>
                <value>
                    <fullName>Custom</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>We are creating object for Settings instead of using Custom Object because we need to store larger size of data which Custom Setting does not support. e.g. Mapping of Fields from Contact to Lead etc. which may go beyond 255 characters. 

It will not use caching but give more flexibility for coding.</description>
    <label>Sales Console Setting</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Console Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Tour_Outcome__c.object
<CustomObject>
    <fields>
        <fullName>Primary_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Member</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Tours (Primary Member)</relationshipLabel>
        <relationshipName>Tours3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Referrer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referrer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Tours (Referrer)</relationshipLabel>
        <relationshipName>Tours5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tour_Outcome__c</fullName>
        <inlineHelpText>Outcome Status from SpaceStation</inlineHelpText>
        <label>Tour Outcome</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Ready to sign now</fullName>
                </value>
                <value>
                    <fullName>Interested</fullName>
                    <label>Tour Interested</label>
                </value>
                <value>
                    <fullName>Did not show up</fullName>
                    <label>No Show</label>
                </value>
                <value>
                    <fullName>Not Interested</fullName>
                    <label>Does not want Membership</label>
                </value>
                <value>
                    <fullName>Tour Reschedule</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Tour</label>
    <nameField>
        <displayFormat>TRO-{0000}</displayFormat>
        <label>Tour Outcome ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tours</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/RESTInboundLeadAPIController.cls
/************************************************************************************************************************************
	Author 		: 	Pranay Jadhav
	Description : 	This class having logic to handle the Lead via SFDC's REST API

	History     :	
	----------------------------------------------------------------------------------------------------------------------------------
	VERSION		DATE				AUTHOR					DETAIL
	1			8 June 2018			Pranay Jadhav		  -
**************************************************************************************************************************************/
public class RESTInboundLeadAPIController {
    private static WWTypes.InboundLead pInboundLead {get; set;}
    private Messaging.InboundEmail pEmail {get; set;}
    private Messaging.InboundEnvelope pEnv {get; set;}
    private Lead pLead {get; set;}
    private Contact pContact {get; set;}
    
    public RESTInboundLeadAPIController(WWTypes.InboundLead inboundLead){
        pInboundLead = inboundLead;
    }
    
    public RESTInboundLeadAPIController(Messaging.InboundEmail email, Messaging.InboundEnvelope env){
		pEmail = email;   
        pEnv = env;
    }
    
    /************************************************************************************************************************************
        Author 		: 	Pranay Jadhav
        Description : 	This method handle inbound email request and insert lead if it satisfies all criteria.
        
        History:
        ----------------------------------------------------------------------------------------------------------------------------------
        VERSION		DATE				AUTHOR					DETAIL
        1			8 June 2018			Pranay Jadhav		    -
    **************************************************************************************************************************************/
    public set<Id> handleInboundEmailRequest(){
        set<String> emailIds = new set<String>();
        if(pEmail.toAddresses != null && pEmail.toAddresses.size() > 0)
            emailIds.addAll(pEmail.toAddresses);
        for(String emailId : emailIds){
            if(emailId.endsWith('apex.salesforce.com') || emailId.endsWith('apex.sandbox.salesforce.com'))
                emailIds.remove(emailId);
        }
        if(pEmail.ccAddresses != null && pEmail.ccAddresses.size() > 0)
            emailIds.addAll(pEmail.ccAddresses);
        Debug.log('handleInboundEmailRequest emailIds=>'+emailIds);
        if(emailIds.size() > 0){
            return new RESTInboundLeadAPIHelper().insertLeadByEmail(emailIds, pEmail, pEnv);
        }  
        return null;
    }
    
    /************************************************************************************************************************************
        Author 		: 	Pranay Jadhav
        Description : 	This method handles post request coming from rest api.
        
        History:
        ----------------------------------------------------------------------------------------------------------------------------------
        VERSION		DATE				AUTHOR					DETAIL
        1			8 June 2018			Pranay Jadhav		    -
    **************************************************************************************************************************************/
    public Id handlePostRequest(){
        if(pInboundLead != null && String.isNotBlank(pInboundLead.email)){
            pLead = RESTInboundLeadAPIHelper.getRecentLeadByEmail(pInboundLead.email);
            Debug.log('pLead=='+pLead);
            pContact = RESTInboundLeadAPIHelper.getRecentContactByEmail(pInboundLead.email);
        }          
        if( String.isNotBlank(pInboundLead.referrer_sfid)){
            if(this.validateReferrer()){
                return new RESTInboundLeadAPIHelper().insertLeadByWeb(pInboundLead);
            }
        }else {
            return new RESTInboundLeadAPIHelper().insertLeadByWeb(pInboundLead);
        }
        return null;
    }
    
    /************************************************************************************************************************************
        Author 		: 	Pranay Jadhav
        Description : 	This method responsible to validate lead as per business requirements.
        
        History:
        ----------------------------------------------------------------------------------------------------------------------------------
        VERSION		DATE				AUTHOR					DETAIL
        1			8 June 2018			Pranay Jadhav		    -
    **************************************************************************************************************************************/
    private boolean validateReferrer(){
        Debug.log('pLead validateReferrer==='+pLead);
        Id referrerId = Id.valueOf(pInboundLead.referrer_sfid);
        if(pLead != null){
            Date createdDate = Date.newinstance(pLead.CreatedDate.year(), pLead.CreatedDate.month(), pLead.CreatedDate.day());
            if(createdDate.daysBetween(System.today()) <= 60)
                throw new InboundLeadException('A lead with given email was already submitted in last 60 days');
            else {
                pLead.Referrer__c = referrerId;
                pLead.Contact_Broker__c = pInboundLead.contact_referrer_only;
            }
        }
        if(pContact != null){
            if(pContact.Account.Type == 'Member' || pContact.Account.Type == 'Previous Member')
                throw new InboundLeadException('A member with given email already exists');
            
            for(Opportunity objOpportunity : pContact.Opportunities__r){
                Integer contractSentDateDiff, contractSignedDateDiff;
                if(objOpportunity.Contract_Sent_Date__c != null)
                    contractSentDateDiff = objOpportunity.Contract_Sent_Date__c.daysBetween(System.today());
                if(objOpportunity.StageName == 'Closed Won')
                    contractSignedDateDiff = objOpportunity.CloseDate.daysBetween(System.today());
                if(contractSentDateDiff < 60 || contractSignedDateDiff < 60){
                    throw new InboundLeadException('Person has a contract sent/signed in last 60 days');
                }
            }
            
            for(Tour_Outcome__c objTour : pContact.Tours3__r){
                Integer dayesBetweenTourCreatedAndToday = Date.newInstance(objTour.CreatedDate.year(), objTour.CreatedDate.month(), objTour.CreatedDate.day()).daysBetween(System.today());
                if(dayesBetweenTourCreatedAndToday <= 60){
                    throw new InboundLeadException('Person has booked a tour with us in last 60 days');
                }
            }
        }
        if(pInboundLead.email != null){
            if(ReferenceHandler.getActiveReference(pInboundLead.email) == null){
                List<Contact> lstReferrerContact = [SELECT Id, Type__c FROM Contact WHERE Id =: referrerId];
                Setting__c referenceSettingsObject = Settings.get('ReferenceSettings');
                if(referenceSettingsObject != null) {                     
                    ReferenceSettings refferenceSettingData = (ReferenceSettings)JSON.deserialize(referenceSettingsObject.Data__c, ReferenceSettings.class);
                    Referral__c referral = new Referral__c();
                    referral.Referral_Email__c = pInboundLead.email;
                    referral.Expires_On__c = System.today().addDays(refferenceSettingData.expireafter);
                    if(pInboundLead.lead_source_detail != null && pInboundLead.lead_source_detail == refferenceSettingData.ReferralSource.LeadSourceDetail) {
                        referral.Referral_Source__c = pInboundLead.lead_source_detail;  
                    } else if(pInboundLead.lead_source != null && pInboundLead.lead_source == refferenceSettingData.ReferralSource.LeadSource) {
                        referral.Referral_Source__c = pInboundLead.lead_source;
                    }
                    else {
                        referral.Referral_Source__c = refferenceSettingData.ReferralSource.Other;
                    }
                    if(lstReferrerContact != null && !lstReferrerContact.isEmpty())
                        referral.Referrer_Type__c = lstReferrerContact[0].Type__c;
                    referral.Referrer__c = referrerId;
                    referral.Start_Date__c = System.today();
                    insert referral;
                }   
            }
        }
        return true;
    }
   
    private class ReferenceSettings {
        private Integer expireafter {get; set;}
        private ReferralSource referralSource {get; set;}    
    }
    private class ReferralSource {
        private String LeadSourceDetail {get; set;}
        private String LeadSource {get; set;}
        private String Other {get; set;}
    }
    public class InboundLeadException extends Exception {}
}