objects/Account.object
<CustomObject>
    <fields>
        <fullName>Primary_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Paperwork will be sent to the primary member on the ACCOUNT</inlineHelpText>
        <label>Main Contact</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.Account.Id</field>
                <operation>equals</operation>
                <valueField>$Source.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Consumer</fullName>
        <active>true</active>
        <description>This is Updated Record Type from Default to Consumer for New Sales Process and Changes</description>
        <label>Consumer</label>
    </recordTypes>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Primary_Member__c</fullName>
        <formula>if( Billing_Account__r.Primary_Member__r.Id =  Id , "Yes","No")</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Primary Member</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This is the latest status coming from Space systems through Jitterbunny of the individual member. This tells us if the user is active or not.</description>
        <inlineHelpText>This is accurate status of a contact if it is an active member of our products or not.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>active</fullName>
                </value>
                <value>
                    <fullName>inactive</fullName>
                    <default>true</default>
                    <label>inactive</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Consumer</fullName>
        <active>true</active>
        <label>Consumer</label>
    </recordTypes>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Primary_Member__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>This is the Main Contact of the Opportunity</inlineHelpText>
        <label>Main Contact</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tour_Date__c</fullName>
        <label>Tour Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Tour_Outcome__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tour Outcome</label>
        <referenceTo>Tour_Outcome__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Consumer</fullName>
        <active>true</active>
        <businessProcess>Office Space</businessProcess>
        <label>Consumer</label>
    </recordTypes>
</CustomObject>

objects/Tour_Outcome__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Tours</relationshipLabel>
        <relationshipName>Tour_Outcome</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Member</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Tours (Primary Member)</relationshipLabel>
        <relationshipName>Tours3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Overall Status from SpaceStation</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>No Show</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Rescheduled</fullName>
                </value>
                <value>
                    <fullName>Not Rescheduled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tour_Date__c</fullName>
        <label>Tour Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Tour_Outcome__c</fullName>
        <inlineHelpText>Outcome Status from SpaceStation</inlineHelpText>
        <label>Tour Outcome</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Ready to sign now</fullName>
                </value>
                <value>
                    <fullName>Interested</fullName>
                    <label>Tour Interested</label>
                </value>
                <value>
                    <fullName>Did not show up</fullName>
                    <label>No Show</label>
                </value>
                <value>
                    <fullName>Not Interested</fullName>
                    <label>Does not want Membership</label>
                </value>
                <value>
                    <fullName>Tour Reschedule</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Tour</label>
    <nameField>
        <displayFormat>TRO-{0000}</displayFormat>
        <label>Tour Outcome ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tours</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/SFMCRepliesControllerTest.cls
@isTest
public class SFMCRepliesControllerTest {
	static {
        SalesConsoleSettings.createSettings();
		Profile testProfile = [SELECT Id FROM Profile WHERE Name='System Administrator'];
        User testUser = new User(Alias = 'testU', Email='testUser_1@example.com', 
            EmailEncodingKey='UTF-8', LastName='User', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = testProfile.Id, IsActive = true,
            TimeZoneSidKey='America/Los_Angeles', UserName='testUserName_1@example.com',
            CommunityNickname = TestingUtility.createUserCommunityName());
        insert testUser;
    }
    
    @isTest
    static void testGetSettingsData(){
        SFMCRepliesController.SFMCRepliesSetting setting = SFMCRepliesController.getSettingsData();
        Debug.log('setting : '+setting);
        
    }
    
    @isTest
    static void testReadCSV(){
        Account accRec = new Account(Name='Test Account');
      	insert accRec;
        Debug.log('accRec : '+accRec);
        
      	Contact conRec = new Contact(
      	AccountId =  accRec.Id,  
        firstname = 'TestFirstName',
        lastname = 'TestLastName',
        email = 'testEmail@example.com',
        Status__c = 'active'                       
        );
        insert conRec;
        Debug.log('conRec : '+conRec);
        
        
        Map<String, Id> oppRecordType = TestingUtility.getRecordTypeMapByName(Opportunity.sObjectType);
        Debug.log('oppRecordType : '+oppRecordType);
        
        Opportunity oppRec = TestingUtility.createOpportunity(accRec.Id, false);
        oppRec.Primary_Member__c = conRec.Id;
        oppRec.StageName = 'Qualifying';
        oppRec.CloseDate = system.today().addDays(5);
        oppRec.RecordTypeId = oppRecordType.get('Consumer');
        TestingUtility.insertWithAssert(oppRec);
        Debug.log('oppRec : '+oppRec);
        
        Tour_Outcome__c tourRec = new Tour_Outcome__c();
        tourRec.Primary_Member__c = conRec.Id;
        tourRec.Status__c = 'Inquiry';
        tourRec.Tour_Date__c = system.today().addDays(4);
        tourRec.Opportunity__c = oppRec.Id;
        TestingUtility.insertWithAssert(tourRec);
        Debug.log('tourRec : '+tourRec);
        
        Datetime tourDate = Datetime.now().addDays(-10);
		Test.setCreatedDate(tourRec.Id, tourDate);
        
        Tour_Outcome__c tourRec1 = new Tour_Outcome__c();
        tourRec1.Primary_Member__c = conRec.Id;
        tourRec1.Status__c = 'Inquiry';
        tourRec1.Tour_Date__c = system.today().addDays(4);
        tourRec1.Opportunity__c = oppRec.Id;
        TestingUtility.insertWithAssert(tourRec1);
        Debug.log('tourRec1 : '+tourRec1);
        
        List<String> lstEmails = new List<String>();
        lstEmails.add(conRec.Email);
        
        
        List<SFMCRepliesController.Request> lstRequests = new List<SFMCRepliesController.Request>();
        Datetime dt = Datetime.now().addDays(-5);
    	SFMCRepliesController.Request req = new SFMCRepliesController.Request();        
        req.emailId = conRec.Email;
        req.emailCount = 1;
        req.dateSent = dt.format('MM/dd/yyyy hh:mm a');        
        Debug.log('req : '+req);
        lstRequests.add(req);
        SFMCRepliesController.Request req2 = new SFMCRepliesController.Request();        
        req2.emailId = conRec.Email;
        req2.emailCount = 1;
        req2.dateSent = null;        
        Debug.log('req2 : '+req2);
        lstRequests.add(req2);
        Debug.log('lstRequests : '+lstRequests);
        
        try{
            List<String> csvResult = SFMCRepliesController.readCSV(lstRequests);
        	Debug.log('csvResult : '+csvResult);
        }catch(Exception exc){
            
        }
    }
    
    @isTest
    static void testSendAttachment(){
        Account accRec = new Account(Name='Test Account');
      	insert accRec;
        Debug.log('accRec : '+accRec);
        
      	Contact conRec = new Contact(
      	AccountId =  accRec.Id,  
        firstname = 'TestFirstName',
        lastname = 'TestLastName',
        email = 'testAtt@example.com',
        Status__c = 'active'                       
        );
        insert conRec;
        
        Attachment attach=new Attachment();   	
    	attach.Name='Unit Test Attachment';
    	Blob bodyBlob=Blob.valueOf('Unit Test Attachment Body');
    	attach.body=bodyBlob;
        attach.parentId=conRec.id;
        insert attach;
        Debug.log('attach : '+attach);
        Boolean result;
        try {            
            result = SFMCRepliesController.sendAttachment(attach.Id, false);
            Debug.log('result : '+result);
        } catch(Exception exc){
            
        }       
        Debug.log('result : '+result);
    }
}