objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <description>This is Picklist which Contains three values
1. Org : It is Main account in hierarchy which is Parent Account of Sales And Bill.
2. Sales: One Sales Account may contain multiple Bill Or Sales Account and It is Under Org Account in hierarchy
3. Bill: Bill Account is under Sales or Org. It never child of Bill Account.
4. ' '(Blank) : It is like Bill type which is under Sales or Org.</description>
        <inlineHelpText>This Picklist is used to determine the account type.</inlineHelpText>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Org</fullName>
                    <default>true</default>
                    <label>Org</label>
                </value>
                <value>
                    <fullName>Sales</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Lead_Source__c</fullName>
        <label>Lead Source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Number_of_Full_Time_Employees__c</fullName>
        <label>Number of Full Time Employees</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unomy_Company_ID__c</fullName>
        <externalId>true</externalId>
        <label>Unomy Company ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unomy_Location_Address__c</fullName>
        <label>Unomy Location Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unomy_Location_City__c</fullName>
        <label>Unomy Location City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unomy_Location_Country__c</fullName>
        <label>Unomy Location Country</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unomy_Location_State__c</fullName>
        <label>Unomy Location State</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unomy_Updated_DateTime__c</fullName>
        <description>The date/time a record was updated from Unomy</description>
        <label>Unomy Updated DateTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Update_HQ_Market_Status__c</fullName>
        <description>This field show the status where the batch is updated record or not.</description>
        <label>Update HQ Market Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Retry Round 1</fullName>
                </value>
                <value>
                    <fullName>Retry Round 2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Generate_Journey__c</fullName>
        <defaultValue>true</defaultValue>
        <description>If this check box is checked , create journey for converted lead</description>
        <label>Generate Journey</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lead_Demographic_Score_Re_calculate__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To capture the flag to re calculate the lead score based on the demographics</description>
        <inlineHelpText>To capture the flag to re calculate the lead score based on the demographics</inlineHelpText>
        <label>Lead Demographic Score Re-calculate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lead_Demographic_Score__c</fullName>
        <description>To capture the demographic score of the lead</description>
        <inlineHelpText>To capture the demographic score of the lead</inlineHelpText>
        <label>Lead Demographic Score</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Lead_Source_Detail__c</fullName>
        <label>Lead Source Detail</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Locations_Interested__c</fullName>
        <label>Locations Interested</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AMS-Labs</fullName>
                </value>
                <value>
                    <fullName>AMS-Metropool</fullName>
                </value>
                <value>
                    <fullName>AMS-Strawinskylaan</fullName>
                </value>
                <value>
                    <fullName>AMS-Weteringschans</fullName>
                </value>
                <value>
                    <fullName>ARC-Avenida Corrientes 800</fullName>
                </value>
                <value>
                    <fullName>ARC-Ing. Enrique Butty 275</fullName>
                </value>
                <value>
                    <fullName>ARC-Libertador 1000</fullName>
                </value>
                <value>
                    <fullName>ARG- Torre Bellini</fullName>
                </value>
                <value>
                    <fullName>ARN-Urban Escape</fullName>
                </value>
                <value>
                    <fullName>ATL-1372 Peachtree</fullName>
                </value>
                <value>
                    <fullName>ATL-3280 Peachtree Road NE</fullName>
                </value>
                <value>
                    <fullName>ATL-Colony Square</fullName>
                </value>
                <value>
                    <fullName>ATL-Tower Place</fullName>
                </value>
                <value>
                    <fullName>AUS-Congress</fullName>
                </value>
                <value>
                    <fullName>AUS-Domain</fullName>
                </value>
                <value>
                    <fullName>AUS-Labs</fullName>
                </value>
                <value>
                    <fullName>AUS-University Park</fullName>
                </value>
                <value>
                    <fullName>AUS-West 6th</fullName>
                </value>
                <value>
                    <fullName>AUS-Westview</fullName>
                </value>
                <value>
                    <fullName>AUS-WeWork 801 Barton Springs</fullName>
                </value>
                <value>
                    <fullName>BCN-Diagonal 444</fullName>
                </value>
                <value>
                    <fullName>BEV-Gav-Yam Negev</fullName>
                </value>
                <value>
                    <fullName>BHZ-Boulevard Shopping</fullName>
                </value>
                <value>
                    <fullName>BKK-Asia Centre</fullName>
                </value>
                <value>
                    <fullName>BKN-109 S 5th St</fullName>
                </value>
                <value>
                    <fullName>BKN-Brooklyn Heights</fullName>
                </value>
                <value>
                    <fullName>BKN-Dumbo Heights (Prospect)</fullName>
                </value>
                <value>
                    <fullName>BKN-Dumbo Heights (Sands)</fullName>
                </value>
                <value>
                    <fullName>BKN-Montague St</fullName>
                </value>
                <value>
                    <fullName>BKN-Williamsburg</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Number_of_Full_Time_Employees__c</fullName>
        <label>Number of Full Time Employees</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Office_Type__c</fullName>
        <label>Office Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Shared Desk</fullName>
                </value>
                <value>
                    <fullName>Lounge Membership</fullName>
                </value>
                <value>
                    <fullName>Daily Desk</fullName>
                </value>
                <value>
                    <fullName>Hot desk</fullName>
                </value>
                <value>
                    <fullName>Dedicated Desk</fullName>
                </value>
                <value>
                    <fullName>Private 1 Person</fullName>
                </value>
                <value>
                    <fullName>Private 2 Person</fullName>
                </value>
                <value>
                    <fullName>Private 3 Person</fullName>
                </value>
                <value>
                    <fullName>Private 4 Person</fullName>
                </value>
                <value>
                    <fullName>Private 5 Person</fullName>
                </value>
                <value>
                    <fullName>Private 6 Person</fullName>
                </value>
                <value>
                    <fullName>Private 8 Person</fullName>
                </value>
                <value>
                    <fullName>Private 10 Person</fullName>
                </value>
                <value>
                    <fullName>Private 10 Person+</fullName>
                </value>
                <value>
                    <fullName>Commons</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unomy_Company_ID__c</fullName>
        <label>Unomy Company ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unomy_Location_Address__c</fullName>
        <label>Unomy Location Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unomy_Location_City__c</fullName>
        <label>Unomy Location City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unomy_Location_Country__c</fullName>
        <label>Unomy Location Country</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unomy_Location_State__c</fullName>
        <label>Unomy Location State</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unomy_Updated_DateTime__c</fullName>
        <description>The date/time a record was updated from Unomy</description>
        <label>Unomy Updated DateTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Update_HQ_Market_Status__c</fullName>
        <description>This field show the status where the batch is updated record or not.</description>
        <label>Update HQ Market Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Retry Round 1</fullName>
                </value>
                <value>
                    <fullName>Retry Round 2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/RetrialBatchToUpdateMarketTest.cls
/************************************************************************************************************************************
	Author		: 	Krishana Tupe
	Description	: 	This batch class handle Geography insertion using google api account update related market on Account record.
	----------------------------------------------------------------------------------------------------------------------------------
	VERSION		DATE	        		AUTHOR                     	DETAIL
	1	    	28 January 2018			Krishana Tupe           	Initial Developement	
**************************************************************************************************************************************/
@isTest
public class RetrialBatchToUpdateMarketTest {
    
 /************************************************************************************************************************************
        Author              :   Krishana Tupe
        Description         :   This method is used to crete the Test data for this Test class
        Created Date  		:   23 January 2019	
		Issue No.			:	ST-3343
  **************************************************************************************************************************************/    
    @TestSetup
    public static void initData(){
        SalesConsoleSettings.createSettings();
    }
    
    
    /************************************************************************************************************************************
        Author              :   Krishana Tupe
        Description         :   This method returns the Accounts
        Created Date  		:   23 January 2019	
		Issue No.			:	ST-3343
  **************************************************************************************************************************************/    
    public static List<Account> getAccounts(List<Account> lstAccounts, Integer size){
        for(Integer iIndex = 0; iIndex < size; iIndex++){
            lstAccounts.add(new Account(Name='Master Account'+iIndex, Update_HQ_Market_Status__c ='Retry Round 1', Unomy_Company_ID__c = 123456+iIndex, Unomy_Updated_DateTime__c = Date.today(), Lead_Source__c = 'Test'+iIndex, Account_Type__c = 'Org', Unomy_Location_Address__c = 'USA', Unomy_Location_City__c = 'Seattle', Unomy_Location_State__c = 'Washington', Unomy_Location_Country__c = 'USA', BillingStreet = 'Washington', BillingCity = 'Seattle', BillingState = 'Washington', BillingCountry = 'USA')); 
        }
        return lstAccounts;
    }    
     
  /************************************************************************************************************************************
        Author              :   Krishana Tupe
        Description         :   This method returns the Leads
        Created Date  		:   23 January 2019	
		Issue No.			:	ST-3343
  **************************************************************************************************************************************/    
    public static List<Lead> getLeads(List<Lead> lstLeads, Integer size){
        for(Integer iIndex = 0; iIndex < size; iIndex++){
            lstLeads.add(new Lead(LeadSource='WeWork.com', Lead_Source_Detail__c='TEST LEAD SOURCE '+iIndex, LastName = 'Doe '+iIndex, 
                                  FirstName = 'John', Email = 'johndoe1582018_1'+iIndex+'@example.com', Office_Type__c = 'Daily Desk', 
                                  Status = 'Open', Locations_Interested__c = 'Test Building Tour', Company = 'Enzigma ltd', 
                                  Generate_Journey__c = true, Number_of_Full_Time_Employees__c = 15, Update_HQ_Market_Status__c ='Retry Round 1',
                                  Unomy_Location_Address__c = 'USA', Unomy_Location_City__c = 'Seattle', Unomy_Location_State__c = 'Greenland', Unomy_Location_Country__c = 'USA',
                                  Unomy_Updated_DateTime__c = System.today()));    
        }
        return lstLeads;
    }    
    
  /************************************************************************************************************************************
        Author              :   Krishana Tupe
        Description         :   This method verifies the Lead records on which we need to find and update market (Retrial Batch).
        Created Date  		:   23 January 2019	
		Issue No.			:	ST-3343
  **************************************************************************************************************************************/  
   @isTest
    public static void verifyUpdateMarketOnLeadSuccess(){   
        Test.setMock(HttpCalloutMock.class, new QueueInsertGeoForBuildingMockRes());
        Id marketId = BatchToUpdateMarketTest.createMarketData();
        RESTInboundLeadAPIHelper.isLeadFromWeb  = true;
        List<Lead> lstLeads = new List<Lead>();
        RetrialBatchToUpdateMarketTest.getLeads(lstLeads,5);       
        Database.insert(lstLeads, false);
        List<Lead> lstLeadsResult = [SELECT Id, Name, Email, Update_HQ_Market_Status__c, Lead_Demographic_Score_Re_calculate__c, Lead_Demographic_Score__c, Lead_Processing_Stage__c, Processing_Stage__c, Lead_Market__c FROM Lead WHERE Id IN : lstLeads AND isConverted = FALSE];
        BatchToUpdateMarketTest.verifyAssertions(lstLeadsResult, 'Pending', 'Created', '5');       
        for(Lead objLead : lstLeadsResult){
            objLead.Update_HQ_Market_Status__c ='Retry Round 1';           
        }
        Database.update(lstLeadsResult, false);
        Test.startTest();
        System.schedule('Update Market on Lead batch', '0 0 0 3 9 ? 2022', new ScheduleBatchToUpdateMarketOnLead());
        Database.executeBatch(new RetrialBatchToUpdateMarket('Lead'));
        Test.stopTest();
        lstLeadsResult = [SELECT Id, Name, Email, Update_HQ_Market_Status__c, Lead_Demographic_Score_Re_calculate__c, Lead_Demographic_Score__c, Lead_Processing_Stage__c, Processing_Stage__c, Lead_Market__c FROM Lead WHERE Id IN : lstLeads AND isConverted = FALSE];
        BatchToUpdateMarketTest.verifyAssertions(lstLeadsResult, 'Completed', 'Market Identified', '5');
        for(Lead objLead : lstLeadsResult){
            System.assertEquals(marketId, objLead.Lead_Market__c);
        }        
    }
    
   /************************************************************************************************************************************
        Author              :   Krishana Tupe
        Description         :   This method verifies the Account records on which we need to find and update market (Retrial Batch).
        Created Date  		:   23 January 2019	
		Issue No.			:	ST-3343
  **************************************************************************************************************************************/  
   @isTest
    public static void verifyUpdateMarketOnAccountSuccess(){   
        Test.setMock(HttpCalloutMock.class, new QueueInsertGeoForBuildingMockRes());
        Id marketId = BatchToUpdateMarketTest.createMarketData();      
        List<Account> lstAccounts = new List<Account>();
        getAccounts(lstAccounts,5);       
        Database.insert(lstAccounts, true);
        List<Account> lstAccountInserted = [SELECT Id, Processing_Stage__c, Account_Market__c, Unomy_Company_ID__c, Geography__c, Market_Identified_On__c, Update_HQ_Market_Status__c FROM Account WHERE Id IN : lstAccounts];
        for(Account objAccount : lstAccountInserted){
            objAccount.Update_HQ_Market_Status__c = 'Retry Round 1';   
        }
        update lstAccountInserted;
        Test.startTest();       
        System.schedule('Update Market on Account batch', '0 0 0 3 9 ? 2022', new ScheduleBatchToUpdateMarketOnAccount());
        Database.executeBatch(new RetrialBatchToUpdateMarket('Account'));
        Test.stopTest();
        lstAccountInserted = [SELECT Id, Processing_Stage__c, Account_Market__c, Unomy_Company_ID__c, Geography__c, Market_Identified_On__c, Update_HQ_Market_Status__c FROM Account WHERE Id IN : lstAccountInserted];
        for(Account objAccount : lstAccountInserted){
            System.assertEquals(marketId, objAccount.Account_Market__c);
            System.assertNotEquals(NULL, objAccount.Geography__c);
            System.assertEquals('Completed', objAccount.Update_HQ_Market_Status__c);
        }        
    }
}