objects/Account.object
<CustomObject>
    <fields>
        <fullName>ID_Creation_Status_Code__c</fullName>
        <label>ID Creation Status Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Paperwork will be sent to the primary member on the ACCOUNT</inlineHelpText>
        <label>Main Contact</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.Account.Id</field>
                <operation>equals</operation>
                <valueField>$Source.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UUID__c</fullName>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>WW_Sync_Request__c</fullName>
        <defaultValue>false</defaultValue>
        <label>WW Sync Request</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>WW_Synced__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If checked, this record was successfully synced with WeWork.com API</inlineHelpText>
        <label>WW Synced</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Building__c.object
<CustomObject>
    <fields>
        <fullName>UUID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Building</label>
    <nameField>
        <label>Building</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Building__c</fullName>
        <description>Pulls Building Location without 3 character city reference</description>
        <formula>Location__r.Location_No_City__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Building</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_Creation_Status_Code__c</fullName>
        <label>ID Creation Status Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Member__c</fullName>
        <formula>if( Billing_Account__r.Primary_Member__r.Id =  Id , "Yes","No")</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Primary Member</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reservable__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reservable</label>
        <referenceTo>Reservable__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This is the latest status coming from Space systems through Jitterbunny of the individual member. This tells us if the user is active or not.</description>
        <inlineHelpText>This is accurate status of a contact if it is an active member of our products or not.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>active</fullName>
                </value>
                <value>
                    <fullName>inactive</fullName>
                    <default>true</default>
                    <label>inactive</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UUID__c</fullName>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>WW_Sync_Request__c</fullName>
        <defaultValue>false</defaultValue>
        <label>WW Sync Request</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>WW_Synced__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If checked, this record was successfully synced with WeWork.com API</inlineHelpText>
        <label>WW Synced</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Building__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Enter the specific building for which opportunity is associated</description>
        <inlineHelpText>This is the building / Nearest building to the geography entered by customer</inlineHelpText>
        <label>Building/Nearest Building</label>
        <referenceTo>Building__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity_Reservable__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity Reservable</label>
        <referenceTo>Opportunity_Reservable__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Member__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>This is the Main Contact of the Opportunity</inlineHelpText>
        <label>Main Contact</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Send_Paperwork_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Paperwork Sent By</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Send Paperwork By)</relationshipLabel>
        <relationshipName>Send_Paperwork_By</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity_Reservable__c.object
<CustomObject>
    <fields>
        <fullName>Building__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>When we get building uuid insted of reservable uuid in Contract event payload map here.</description>
        <inlineHelpText>When we get building uuid insted of reservable uuid in Contract event payload map here.</inlineHelpText>
        <label>Sellable Building</label>
        <referenceTo>Building__c</referenceTo>
        <relationshipLabel>Opportunity Reservables</relationshipLabel>
        <relationshipName>Opportunity_Reservables</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Reservables</relationshipLabel>
        <relationshipName>Opportunity_Offices</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reservable__c</fullName>
        <label>Reservable</label>
        <referenceTo>Reservable__c</referenceTo>
        <relationshipLabel>Opportunity Reservables</relationshipLabel>
        <relationshipName>Opportunity_Offices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Opportunity Reservable</label>
    <nameField>
        <displayFormat>OO-{0000}</displayFormat>
        <label>Office ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Reservables</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Reservable__c.object
<CustomObject>
    <fields>
        <fullName>Building__c</fullName>
        <label>Building</label>
        <referenceTo>Building__c</referenceTo>
        <relationshipLabel>Reservables</relationshipLabel>
        <relationshipName>Offices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Open_Date__c</fullName>
        <label>Open Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Available</fullName>
                </value>
                <value>
                    <fullName>Unavailable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UUID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Reservable</label>
    <nameField>
        <label>Reservable Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reservables</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/RESTOpportunityInsertTest.cls
@isTest
private class RESTOpportunityInsertTest {
     static{
         SalesConsoleSettings.createSettings();
    }
	@isTest static void test_POST_success() {
		//pre-context
       		
        	Account a = new Account(
				name = 'Test Account',
				WW_Synced__c = true,
				WW_Sync_Request__c = false,
				ID_Creation_Status_Code__c = '200'
			);
			insert a;

			Contact john = new Contact(
				firstname = 'John',
				lastname = 'Rambo',
				email = 'john@rambo.com',
				accountID = a.Id,
				Status__c = 'active'
			);
			insert john;

			//add contact as primary member
			a.Primary_Member__c = john.Id;
			a.UUID__c = 'com001';
			update a;

			Contact paul = new Contact(
				firstname = 'Paul',
				lastname = 'Rambo',
				email = 'paul@rambo.com',
				accountID = a.Id,
				Status__c = 'active'
			);
			insert paul;

			Building__c b = new Building__c(
				Name='b1',
				uuid__c = 'bui001'
			);
			insert b;

			// fixed
			Reservable__c r1 = new Reservable__c(Name='r1',Building__c=b.Id, uuid__c='res001', Status__c = 'Available', Open_Date__c = date.today());
			insert r1;
        
        	// fixed
			Reservable__c r2 = new Reservable__c(Name='r2',Building__c=b.Id, uuid__c='res002', Status__c = 'Available', Open_Date__c = date.today());
			insert r2;
        
        	// fixed
			Reservable__c r3 = new Reservable__c(Name='r3',Building__c=b.Id, uuid__c='res003', Status__c = 'Available', Open_Date__c = date.today());
			insert r3;

		//test
		Test.startTest();
			Contact con = [ SELECT ID,Name,UUID__c from Contact Where ID =: paul.ID ];
			RestRequest req 	= new RestRequest(); 
	    	RestResponse res 	= new RestResponse();
      
      		// pass the req and resp objects to the method		 
      		req.requestURI = System.URL.getSalesforceBaseURL().getHost() + '/services/apexrest/OpportunityInsert';  
      		req.httpMethod = 'POST';

	 		//assign rest context
	 		RestContext.request 	= req;
	 		RestContext.response 	= res;
	 		
	 		//define container and set request Company and Reservable UUIDs
	 		WWTypes.OpportunityInsert oi = new WWTypes.OpportunityInsert();
        	oi.primary_member_email = 'paul@rambo.com';
        	oi.community_user = paul.Id;
	 		oi.company_uuid 					= a.UUID__c;
	 		oi.building_uuid 					= b.uuid__c;
	 		oi.opportunity_type 			= 'Office Space';
	 		oi.community_manager_uuid = 'xxx';
	 		oi.desk_number 						= 2;
	 		oi.actual_start_date 			= system.today();
			oi.reservable_uuids 			= new String[]{r1.uuid__c, r3.uuid__c};
            //oi.send_paperwork_by            = 'Agent Paper work';
			oi.send_paperwork_by			= con.UUID__c;
			WWTypes.Discount discount1 = new WWTypes.Discount();
			discount1.amount 				= 100;
			discount1.start_date 		= system.today();
			discount1.end_date 			= system.today();
			discount1.discount_type = 'Regular Discount';
			discount1.promotion_code = 'PROMO';
			discount1.promotion_override = true;

			WWTypes.Discount discount2 = new WWTypes.Discount();
			discount2.amount 				= 200;
			discount2.start_date 		= system.today();
			discount2.end_date 			= system.today();
			discount2.discount_type = 'Regular Discount';
			discount2.promotion_code = 'PROMO';
			discount2.promotion_override = false;
			
			//collect discounts
			oi.discounts.add(discount1);
			oi.discounts.add(discount2);
			Debug.log('Test : Before doPost oi ::: ' + oi);
			//submit post
			RESTOpportunityInsert.Response response = RESTOpportunityInsert.doPost(oi);
			//confirm response
			debug.log('response--'+response);
			system.assertEquals(true, response.success);
			
        	//confirm changes send_paperwork_by__c(string to lookup(Contact))
        	Opportunity opp = [ SELECT Id,Name,send_paperwork_by__c FROM Opportunity WHERE send_paperwork_by__c = : con.ID ];
        	system.assertEquals(opp.send_paperwork_by__c, paul.Id);
        	
			//check if a new opportunity was created
			Opportunity[] Os = [SELECT id, AccountID FROM Opportunity]; //, Send_Paperwork_By__c
        	Debug.log('Test : Os ::: ' + Os);
			system.assertEquals(
				1,
				Os.size(),
				'A new opportunity should be created'
			);

			//check if the opportunity is associated to the given account
			system.assertEquals(
				a.Id,
				Os[0].AccountID,
				'The new opportunity should be associated with the right Company(Account)'
			);
        	//System.assertEquals('Send PaperWork Agent', Os[0].Send_Paperwork_By__c);
			//check if the opportunity has the right opportunity-reservables records.
			Opportunity_Reservable__c[] ORs = [	SELECT Opportunity__c, Reservable__c 
																					FROM Opportunity_Reservable__c
																				];
			system.assertEquals(
				2,
				ORs.size(),
				'Given 2 reservables on an Opportunity should result in 2 Opportunity Reservable records'
			);

			system.assertEquals(
				Os[0].id,
				ORs[0].Opportunity__c,
				'The Opportunity Reservable must be associated to the right Opportunity'
			);

			system.assertEquals(
				Os[0].id,
				ORs[1].Opportunity__c,
				'The Opportunity Reservable must be associated to the right Opportunity'
			);

			system.assert(
				r1.Id == ORs[0].Reservable__c ||
				r1.Id == ORs[1].Reservable__c,
				'The Opportunity Reservable must be associated to the right Reservable'
			);

			system.assert(
				r3.Id == ORs[0].Reservable__c ||
				r3.Id == ORs[1].Reservable__c,
				'The Opportunity Reservable must be associated to the right Reservable'
			);
	
		Test.stopTest();
	}
	
	@isTest static void test_POST_failure() {
			Test.startTest();

			RestRequest req 	= new RestRequest(); 
	    	RestResponse res 	= new RestResponse();
	 		
			//submit post
			RESTOpportunityInsert.Response response = RESTOpportunityInsert.doPost(NULL);
	
			//confirm response
			system.assertEquals(false, response.success);
	
		Test.stopTest();
	}
}