objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Queue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference of account queue</description>
        <label>Account Queue</label>
        <referenceTo>Account_Queue__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account_Type__c</fullName>
        <description>This is Picklist which Contains three values
1. Org : It is Main account in hierarchy which is Parent Account of Sales And Bill.
2. Sales: One Sales Account may contain multiple Bill Or Sales Account and It is Under Org Account in hierarchy
3. Bill: Bill Account is under Sales or Org. It never child of Bill Account.
4. ' '(Blank) : It is like Bill type which is under Sales or Org.</description>
        <inlineHelpText>This Picklist is used to determine the account type.</inlineHelpText>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Org</fullName>
                    <default>true</default>
                    <label>Org</label>
                </value>
                <value>
                    <fullName>Sales</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Lead_Source__c</fullName>
        <label>Lead Source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <description>This field will updated by Lead to Activity mapping.</description>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alexandria</fullName>
                </value>
                <value>
                    <fullName>Alpharetta</fullName>
                </value>
                <value>
                    <fullName>Amsterdam</fullName>
                </value>
                <value>
                    <fullName>Ann Arbor</fullName>
                </value>
                <value>
                    <fullName>Atlanta</fullName>
                </value>
                <value>
                    <fullName>Austin</fullName>
                </value>
                <value>
                    <fullName>Balston</fullName>
                </value>
                <value>
                    <fullName>Baltimore</fullName>
                </value>
                <value>
                    <fullName>Bangkok</fullName>
                </value>
                <value>
                    <fullName>Barcelona</fullName>
                </value>
                <value>
                    <fullName>Barranquilla</fullName>
                </value>
                <value>
                    <fullName>Be'er Sheva</fullName>
                </value>
                <value>
                    <fullName>Beijing</fullName>
                </value>
                <value>
                    <fullName>Belo Horizonte</fullName>
                </value>
                <value>
                    <fullName>Bengaluru</fullName>
                </value>
                <value>
                    <fullName>Berkeley</fullName>
                </value>
                <value>
                    <fullName>Berlin</fullName>
                </value>
                <value>
                    <fullName>Bethesda</fullName>
                </value>
                <value>
                    <fullName>Bogota</fullName>
                </value>
                <value>
                    <fullName>Bogotá</fullName>
                </value>
                <value>
                    <fullName>Boston</fullName>
                </value>
                <value>
                    <fullName>Boulder</fullName>
                </value>
                <value>
                    <fullName>Brasilia</fullName>
                </value>
                <value>
                    <fullName>Brisbane</fullName>
                </value>
                <value>
                    <fullName>Brussels</fullName>
                </value>
                <value>
                    <fullName>Budapest</fullName>
                </value>
                <value>
                    <fullName>Buenos Aires</fullName>
                </value>
                <value>
                    <fullName>Busan</fullName>
                </value>
                <value>
                    <fullName>Calgary</fullName>
                </value>
                <value>
                    <fullName>Cali</fullName>
                </value>
                <value>
                    <fullName>Pune</fullName>
                </value>
                <value>
                    <fullName>Seattle</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unomy_Company_ID__c</fullName>
        <externalId>true</externalId>
        <label>Unomy Company ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unomy_Location_Address__c</fullName>
        <label>Unomy Location Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unomy_Location_City__c</fullName>
        <label>Unomy Location City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unomy_Location_Country__c</fullName>
        <label>Unomy Location Country</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unomy_Location_State__c</fullName>
        <label>Unomy Location State</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unomy_Updated_DateTime__c</fullName>
        <description>The date/time a record was updated from Unomy</description>
        <label>Unomy Updated DateTime</label>
        <type>DateTime</type>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Consumer</fullName>
        <active>true</active>
        <description>This is Updated Record Type from Default to Consumer for New Sales Process and Changes</description>
        <label>Consumer</label>
    </recordTypes>
</CustomObject>

objects/Account_Queue__c.object
<CustomObject>
    <fields>
        <fullName>Market__c</fullName>
        <description>This field will hep us to match to account for Account assignment.</description>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Amsterdam</fullName>
                </value>
                <value>
                    <fullName>Atlanta</fullName>
                </value>
                <value>
                    <fullName>Austin</fullName>
                </value>
                <value>
                    <fullName>Baltimore</fullName>
                </value>
                <value>
                    <fullName>Bangkok</fullName>
                </value>
                <value>
                    <fullName>Barranquilla</fullName>
                </value>
                <value>
                    <fullName>Be'er Sheva</fullName>
                </value>
                <value>
                    <fullName>Beijing</fullName>
                </value>
                <value>
                    <fullName>Bengaluru</fullName>
                </value>
                <value>
                    <fullName>Berkeley</fullName>
                </value>
                <value>
                    <fullName>Berlin</fullName>
                </value>
                <value>
                    <fullName>Bogota</fullName>
                </value>
                <value>
                    <fullName>Boston</fullName>
                </value>
                <value>
                    <fullName>Boulder</fullName>
                </value>
                <value>
                    <fullName>Buenos Aires</fullName>
                </value>
                <value>
                    <fullName>Charlotte</fullName>
                </value>
                <value>
                    <fullName>Chicago</fullName>
                </value>
                <value>
                    <fullName>Dallas</fullName>
                </value>
                <value>
                    <fullName>Delhi</fullName>
                </value>
                <value>
                    <fullName>Denver</fullName>
                </value>
                <value>
                    <fullName>Detroit</fullName>
                </value>
                <value>
                    <fullName>Dublin</fullName>
                </value>
                <value>
                    <fullName>Fort Worth</fullName>
                </value>
                <value>
                    <fullName>Frankfurt</fullName>
                </value>
                <value>
                    <fullName>Guangzhou</fullName>
                </value>
                <value>
                    <fullName>Hamburg</fullName>
                </value>
                <value>
                    <fullName>Herzliya</fullName>
                </value>
                <value>
                    <fullName>Ho Chi Minh City</fullName>
                </value>
                <value>
                    <fullName>Hong Kong</fullName>
                </value>
                <value>
                    <fullName>Houston</fullName>
                </value>
                <value>
                    <fullName>Seattle</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Portfolio__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Portfolio</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Account Queues</relationshipLabel>
        <relationshipName>Account_Queues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>Shows the region of related portfolio</description>
        <formula>Portfolio__r.TerritoryID__r.RegionID__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Shows the region of related portfolio</inlineHelpText>
        <label>Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <description>Shows the territory of related portfolio.</description>
        <formula>Portfolio__r.TerritoryID__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Shows the territory of related portfolio.</inlineHelpText>
        <label>Territory</label>
        <type>Text</type>
    </fields>
    <description>This object will be used in Account assignment use case.</description>
    <label>Account Queue</label>
    <nameField>
        <displayFormat>Queue-{00000}</displayFormat>
        <label>Queue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Queues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Market__c.object
<CustomObject>
    <fields>
        <fullName>Enterprise_Assignment_Override__c</fullName>
        <label>Enterprise_Assignment_Override</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Portfolio</fullName>
                    <default>true</default>
                    <label>Portfolio</label>
                </value>
                <value>
                    <fullName>Region</fullName>
                </value>
                <value>
                    <fullName>Territory</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Portfolio__c</fullName>
        <description>Display name for portfolio, something user friendly to end users</description>
        <inlineHelpText>Display name (text)</inlineHelpText>
        <label>Portfolio Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <formula>TerritoryID__r.RegionID__r.Region__c</formula>
        <inlineHelpText>Display name (text)</inlineHelpText>
        <label>Region Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TerritoryID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Territory</label>
        <referenceTo>Territory__c</referenceTo>
        <relationshipLabel>Portfolios</relationshipLabel>
        <relationshipName>Portfolio</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <formula>TerritoryID__r.Territory__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Display name (text)</inlineHelpText>
        <label>Territory Name</label>
        <type>Text</type>
    </fields>
    <description>We are introducing new object Market so that same building can fall under multiple Markets as per Marketing department requirement.</description>
    <label>Portfolio</label>
    <nameField>
        <label>Portfolio</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portfolios</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Region__c.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <description>Display name for region</description>
        <inlineHelpText>Display name (text)</inlineHelpText>
        <label>Region Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Region</label>
    <nameField>
        <label>Region</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Territory__c.object
<CustomObject>
    <fields>
        <fullName>RegionID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Region</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Territories</relationshipLabel>
        <relationshipName>Territories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <formula>RegionID__r.Region__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Display name (text)</inlineHelpText>
        <label>Region Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <description>Display Name for Territory, something user friendly to user</description>
        <inlineHelpText>Display name (text)</inlineHelpText>
        <label>Territory Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Territory</label>
    <nameField>
        <label>Territory</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AccountQueueServicesTest.cls
/************************************************************************************************************************************
	Author		:	Pragalbha Mahajan
	Description :	To Create multiple Test Records for AccountQueueServices.

	History:
	----------------------------------------------------------------------------------------------------------------------------------
	VERSION		DATE	        	AUTHOR                       DETAIL
	1	    	1 Feb 2017	  		Pragalbha Mahajan          	 Initial Developement
**************************************************************************************************************************************/
    @isTest
    public with sharing class AccountQueueServicesTest {
        static Id accRecordtypeMidMarket;
        static Id accRecordtypeConsumer;
        
        /************************************************************************************************************************************
    Author 				: 	Pragalbha Mahajan
    Description 		: 	This method is used to setup test data.
    Issue No.			:	ST-3391
	Created Date		:	06 Feb 2019
    **************************************************************************************************************************************/ 
        @testSetup
        static void setup(){
            SalesConsoleSettings.createSettings();
            Region__c objRegion = new Region__c(Name = 'Test Region', Region__c = 'Test Region');
            TestingUtility.insertWithAssert(objRegion, 'Region inserted');
            Territory__c objTerritory = new Territory__c(Name = 'Test Territory', Territory__c =' Test Territory', RegionID__c = objRegion.Id);
            TestingUtility.insertWithAssert(objTerritory, 'Territory inserted');
            
            List<Market__c> lstMarket = new List<Market__c>();
            Market__c objMarket = new Market__c(Name = 'Test Portfolio', Portfolio__c = 'Test Portfolio', TerritoryId__c = objTerritory.Id);
            lstMarket.add(objMarket);
            Market__c objMarket1 = new Market__c(Portfolio__c = 'Pune', Name = 'Pune', Enterprise_Assignment_Override__c = 'Region', TerritoryId__c = objTerritory.Id);
            lstMarket.add(objMarket1);
            Market__c objMarket2 = new Market__c(Portfolio__c = 'Bombay', Name = 'Bombay', Enterprise_Assignment_Override__c = 'Territory', TerritoryId__c = objTerritory.Id);
            lstMarket.add(objMarket2);
            Market__c objMarket3 = new Market__c(Portfolio__c = 'Aurangabad', Name = 'Aurangabad');
            lstMarket.add(objMarket3);
            TestingUtility.insertListWithAssert(lstMarket);
            
            Account acc1 = new Account(Name='Master Account1', Unomy_Company_ID__c = 123456, Unomy_Updated_DateTime__c = Date.today(), Lead_Source__c = 'Test', Account_Type__c = 'Org', Unomy_Location_Address__c = 'USA', Unomy_Location_City__c = 'Seattle', Unomy_Location_State__c = 'Washington', Unomy_Location_Country__c = 'USA', BillingStreet = 'Washington', BillingCity = 'Seattle', BillingState = 'Washington', BillingCountry = 'USA'); 
            TestingUtility.insertWithAssert(acc1, 'Account Not Inserted');
            acc1 = new Account(Name='Master Account2', Unomy_Company_ID__c = 789456, Unomy_Updated_DateTime__c = Date.today(), Lead_Source__c = 'Test', Account_Type__c = 'Org', BillingStreet = 'Washington', BillingCity = 'Seattle', BillingState = 'Washington', BillingCountry = 'USA'); 
            TestingUtility.insertWithAssert(acc1, 'Account Not Inserted');
            
            Profile weworkSystemAdmin = [SELECT Id FROM Profile WHERE Name='System Administrator'];
            
            List<User> lstUsers = new List<User>();
            Map<String,Object> userRecordMap = new Map<String,Object>{'LastName' => 'Last Name 1',
               'Username' =>  'testweworkuser1@example.com',
                'Email' => 'testweworkuser1@example.com'};
            lstUsers.add(TestingUtility.insertUserWithAssert(weworkSystemAdmin.Id, userRecordMap, false));
            
            userRecordMap = new Map<String,Object>{'LastName' => 'Last Name 2',
               'Username' =>  'testweworkuser2@example.com',
                'Email' => 'testweworkuser2@example.com'};
            lstUsers.add(TestingUtility.insertUserWithAssert(weworkSystemAdmin.Id, userRecordMap, false));
            
            userRecordMap = new Map<String,Object>{'LastName' => 'Last Name 3',
               'Username' =>  'testweworkuser3@example.com',
                'Email' => 'testweworkuser3@example.com'};
            lstUsers.add(TestingUtility.insertUserWithAssert(weworkSystemAdmin.Id, userRecordMap, false));
            
            TestingUtility.insertListWithAssert(lstUsers);
            
            accRecordtypeMidMarket = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Mid Market').getRecordTypeId();
            accRecordtypeConsumer = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Consumer').getRecordTypeId();
            
            List<Account_Queue__c> lstAccountQueues = new List<Account_Queue__c>();
            
            Map<String, Object> mapAccountQueues = new Map<String, Object>{'Member__c' => lstUsers[1].Id,
                'Account_Record_Type__c' => 'Mid Market',
                'Last_Account_Assigned__c' => Date.today(),
                'Market__c' => lstMarket[0].Name,
                'Portfolio__c' => lstMarket[0].Id,
                'Is_Queue_Active__c' => true};
            lstAccountQueues.add((Account_Queue__c)TestingUtility.createTestRecords(Account_Queue__c.sObjectType, mapAccountQueues, false));
            
            mapAccountQueues = new Map<String, Object>{'Member__c' => lstUsers[0].Id,
                'Account_Record_Type__c' => 'Consumer',
                'Last_Account_Assigned__c' => Date.today(),
                'Market__c' => lstMarket[1].Name,
                'Portfolio__c' => lstMarket[1].Id,
                'Is_Queue_Active__c' => true};
            lstAccountQueues.add((Account_Queue__c)TestingUtility.createTestRecords(Account_Queue__c.sObjectType, mapAccountQueues, false));
            
            mapAccountQueues = new Map<String, Object>{'Member__c' => lstUsers[2].Id,
                'Account_Record_Type__c' => 'Enterprise Solutions',
                'Last_Account_Assigned__c' => Date.today(),
                'Market__c' => lstMarket[2].Name,
                'Portfolio__c' => lstMarket[2].Id,
                'Is_Queue_Active__c' => true};
            lstAccountQueues.add((Account_Queue__c)TestingUtility.createTestRecords(Account_Queue__c.sObjectType, mapAccountQueues, false));
            
            TestingUtility.insertListWithAssert(lstAccountQueues);
            debug.log('lstAccountQueues query: '+[SELECT Id, Name, Market__c, Last_Account_Assigned__c, Account_Record_Type__c, Portfolio__c FROM  Account_Queue__c WHERE Id IN: lstAccountQueues]);
            
        }

        /************************************************************************************************************************************
            Author				: 	Pragalbha Mahajan
            Description 		: 	This method is used to verify Queue Owner By Market For Enterprise Solutions
            Last Modified Date  : 	02 Feb 2017
        **************************************************************************************************************************************/               
        static testMethod void testQueueOwnerByMarketForEnterpriseSolutions(){            
            User testuser03 = [Select Id,Name From User Where Username='testweworkuser3@example.com'];
            List<Market__c> lstMarkets = [SELECT Id, Name, Portfolio__c, TerritoryID__c, TerritoryID__r.RegionID__c, Mid_Market_Assignment_Override__c, Enterprise_Assignment_Override__c FROM Market__c]; 
            List<Account_Queue__c> lstAccountQueues = [SELECT Id, Name, Account_Record_Type__c, Last_Account_Assigned__c, Market__c, Portfolio__c, Is_Queue_Active__c FROM Account_Queue__c];
            Id returnUserId = AccountQueueServices.getQueueOwnerByMarketTerritoryOrRegion(new List<String>{'Enterprise Solutions'},String.valueOf(lstMarkets[2].Id), 'Enterprise Solutions');
            System.assertEquals( testuser03.Id, returnUserId);             
        }
        /************************************************************************************************************************************
            Author				:	Pragalbha Mahajan
            Description 		:	This method is used to verify Queue Owner By Market For Consumer
            Last Modified Date  :	02 Feb 2017
        **************************************************************************************************************************************/        
        static testMethod void testQueueOwnerByMarketForConsumer(){
            User testuser01=[Select Id,Name From User Where Username='testweworkuser1@example.com'];
            List<Market__c> lstMarkets = [SELECT Id, Name, Portfolio__c, TerritoryID__c, TerritoryID__r.RegionID__c, Mid_Market_Assignment_Override__c, Enterprise_Assignment_Override__c FROM Market__c];
            List<Account_Queue__c> lstAccountQueues = [SELECT Id, Name, Account_Record_Type__c, Last_Account_Assigned__c, Market__c, Portfolio__c, Is_Queue_Active__c FROM Account_Queue__c];
            Id returnUserId = AccountQueueServices.getQueueOwnerByMarketTerritoryOrRegion(new List<String>{'Consumer'}, String.valueOf(lstMarkets[1].Id), 'Consumer');
            System.assertEquals( testuser01.Id, returnUserId);             
        }
        /************************************************************************************************************************************
        	Author				:	Pragalbha Mahajan
            Description 		:	This method is used to Queue Owner By Market For Mid Market
            Last Modified Date  :	02 Feb 2017
        **************************************************************************************************************************************/        
        static testMethod void testQueueOwnerByMarketForMidMarket(){
            User testuser02=[Select Id,Name From User Where Username='testweworkuser2@example.com'];
            List<Market__c> lstMarkets = [SELECT Id, Name, Portfolio__c, TerritoryID__c, TerritoryID__r.RegionID__c, Mid_Market_Assignment_Override__c, Enterprise_Assignment_Override__c FROM Market__c]; 
            Id returnUserId = AccountQueueServices.getQueueOwnerByMarket(new List<String>{'Mid Market'},String.valueOf(lstMarkets[0].Id));
            System.assertEquals( testuser02.Id, returnUserId);    
            AccountQueueServices.updateAccountQueues();//This is added to increase coverage
        }
    }