objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <description>This is Picklist which Contains three values
1. Org : It is Main account in hierarchy which is Parent Account of Sales And Bill.
2. Sales: One Sales Account may contain multiple Bill Or Sales Account and It is Under Org Account in hierarchy
3. Bill: Bill Account is under Sales or Org. It never child of Bill Account.
4. ' '(Blank) : It is like Bill type which is under Sales or Org.</description>
        <inlineHelpText>This Picklist is used to determine the account type.</inlineHelpText>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Org</fullName>
                    <default>true</default>
                    <label>Org</label>
                </value>
                <value>
                    <fullName>Sales</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Parent_Account__c</fullName>
        <formula>CASESAFEID(ParentId)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Parent Account(Pipeline Reporting)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Org_Name__c</fullName>
        <description>Shows the name of the Ultimate Org when we have the multi-level hierarchy.</description>
        <formula>IF( OR( ISPICKVAL(Account_Type__c, 'Org'),ISBLANK(Parent.Id)),Name,IF(OR(ISPICKVAL(Parent.Account_Type__c, 'Org'),ISBLANK(Parent.Parent.Id)),Parent.Name,IF(OR(ISPICKVAL(Parent.Parent.Account_Type__c, 'Org'),ISBLANK(Parent.Parent.Parent.Id)), Parent.Parent.Name,IF(OR(ISPICKVAL(Parent.Parent.Parent.Account_Type__c, 'Org'),ISBLANK(Parent.Parent.Parent.Parent.Id)), Parent.Parent.Parent.Name,IF(OR(ISPICKVAL(Parent.Parent.Parent.Parent.Account_Type__c, 'Org'),ISBLANK(Parent.Parent.Parent.Parent.Parent.Id)), Parent.Parent.Parent.Parent.Name,Parent.Parent.Parent.Parent.Parent.Name)))))</formula>
        <inlineHelpText>Shows the name of the Ultimate Org when we have the multi-level hierarchy.</inlineHelpText>
        <label>Org Account Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Paperwork will be sent to the primary member on the ACCOUNT</inlineHelpText>
        <label>Main Contact</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.Account.Id</field>
                <operation>equals</operation>
                <valueField>$Source.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UUID__c</fullName>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Billing_Account__c.object
<CustomObject>
    <fields>
        <fullName>ID_Status__c</fullName>
        <description>This field determine whether or not the company is active in WeWork spaces</description>
        <inlineHelpText>This field determine whether or not the company is active in WeWork spaces</inlineHelpText>
        <label>ID Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Member</fullName>
                </value>
                <value>
                    <fullName>Potential</fullName>
                </value>
                <value>
                    <fullName>Past Member</fullName>
                </value>
                <value>
                    <fullName>active</fullName>
                </value>
                <value>
                    <fullName>inactive</fullName>
                    <default>true</default>
                    <label>inactive</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Parent_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is lookup to the Parent Account</description>
        <inlineHelpText>This is lookup to the Parent Account</inlineHelpText>
        <label>Parent Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the main point of contact for the Billing Account.</description>
        <inlineHelpText>Person at the member company responsible for managing the membership: invoices, key card replacements, MENA account manager tab. Responsible for signing legal agreement (unless an authorized signatory is designated).</inlineHelpText>
        <label>Primary Member</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UUID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>This is unique,case sensitive auto generated field used to identify Billing Account record.</description>
        <externalId>true</externalId>
        <inlineHelpText>This is unique,case sensitive auto generated field used to identify Billing Account record.</inlineHelpText>
        <label>UUID</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Ultimate_Parent_Org__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Shows the Ultimate Org when we have the multi-level hierarchy.</description>
        <inlineHelpText>Shows the Ultimate Org when we have the multi-level hierarchy.</inlineHelpText>
        <label>Ultimate Parent Org</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts (Ultimate Parent Org Name)</relationshipLabel>
        <relationshipName>Billing_Accounts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>All Billing account is moved to this Billing Account object it help Sales people to identify Org and Sales account easily and reduce the clutter of 100s of Accounts with same name.</description>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <formula>text(Account.Type)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Actual_Start_Date__c</fullName>
        <formula>Account.Start_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Actual Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Members</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Member__c</fullName>
        <formula>if( Billing_Account__r.Primary_Member__r.Id =  Id , "Yes","No")</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Primary Member</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UUID__c</fullName>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Checking</fullName>
                </value>
                <value>
                    <fullName>Savings</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Actual_Start_Date__c</fullName>
        <inlineHelpText>This is the Expected Start Date until Closed Won</inlineHelpText>
        <label>Actual Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field relates the opportunity to the billing account. The billing account is used in the space station for sending contracts.</description>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Building_uuid__c</fullName>
        <formula>Building__r.UUID__c</formula>
        <label>Building uuid</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contract_Stage__c</fullName>
        <label>Contract Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Contract Sent</fullName>
                </value>
                <value>
                    <fullName>Contract Voided</fullName>
                </value>
                <value>
                    <fullName>Contract Discarded</fullName>
                </value>
                <value>
                    <fullName>Contract Signed</fullName>
                </value>
                <value>
                    <fullName>Contract Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Encoded_ID__c</fullName>
        <label>Encoded ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Member__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>This is the Main Contact of the Opportunity</inlineHelpText>
        <label>Main Contact</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Setting__c.object
<CustomObject>
    <fields>
        <fullName>Data__c</fullName>
        <description>This should contain JSON formatted data for each setting record. The JSON object will vary from setting to setting.</description>
        <label>Data</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <description>We are creating object for Settings instead of using Custom Object because we need to store larger size of data which Custom Setting does not support. e.g. Mapping of Fields from Contact to Lead etc. which may go beyond 255 characters. 

It will not use caching but give more flexibility for coding.</description>
    <label>Sales Console Setting</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Console Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AssociateBillingAccountController.cls
/************************************************************************************************************************************
    Author      :   Dipak Pawar
    Description :   This class contain all aura methods related to AssignToAccount.
    ----------------------------------------------------------------------------------------------------------------------------------
    VERSION     DATE                AUTHOR                  DETAIL
    1           18 July 2018        Dipak Pawar      		Initial Developement
**************************************************************************************************************************************/
global without sharing class AssociateBillingAccountController {
    public class AssociateBillingAccountControllerException extends Exception{}
    public static Boolean isInvoker = false;
    public static Savepoint sp {get;set;}
    static {
        isInvoker = ApexDebugLog.registerRootInvoker(ApexDebugLog.InvokerType.AURA, 'AssociateBillingAccountController' + 'getsObjectPrefix', ApexDebugLog.InvokerType.AURA);        
    }
    
    /************************************************************************************************************************************
        Author              : Dipak Pawar
        Description         : This method brings the opportunity data, ultimateParentOrgId, billingAccounts, TourReservableAPI apiSetting .
        Created Date        : 18 July 2018 
		Last Modified Date  : 25 September 2018
    	Last Modified By    : Pragalbha Mahajan
    **************************************************************************************************************************************/	
    @AuraEnabled
    public static DatabaseResult getOpportunityData(Id opportunityId){
        try{
            AssignToAccountData objAssignToAccountData = new AssignToAccountData();
            objAssignToAccountData.opportunityRecord = (Opportunity)[SELECT Id, Name, AccountId, Account.Parent_Org_Name__c, Account.OwnerId, Billing_Account__c, Billing_Account__r.UUID__c, Primary_Member__c, Encoded_ID__c, Building_uuid__c, Actual_Start_Date__c, OwnerId, StageName, Contract_Stage__c, RecordType.Name FROM Opportunity WHERE Id =:opportunityId LIMIT 1];
            objAssignToAccountData.opportunityRecord.Encoded_ID__c = EncodingUtil.base64Encode(Blob.valueOf(opportunityId));
            DatabaseResult orgData = LightningComponentController.getOrg(objAssignToAccountData.opportunityRecord.AccountId);
            if(orgData != null && orgData.data != null){
             objAssignToAccountData.ultimateParentOrgId = Id.valueOf((String)JSON.deserialize(JSON.serialize(LightningComponentController.getOrg(objAssignToAccountData.opportunityRecord.AccountId).data), String.class));   
            }
            objAssignToAccountData.billingAccounts = new List<Billing_Account__c>([SELECT Id, OwnerId, ID_Status__c, Owner.Name, Parent_Account__r.Name, Parent_Account__r.Account_Type__c, Parent_Account__c, Name, Primary_Member__c, Primary_Member__r.Name, Primary_Member__r.Email, Primary_Member__r.Id, UUID__c FROM Billing_Account__c WHERE Ultimate_Parent_Org__c =:objAssignToAccountData.ultimateParentOrgId]);
            objAssignToAccountData.apiSetting = [SELECT Id, Name, Data__c FROM Setting__c WHERE Name = 'TourReservableAPI'];
            Boolean isValid = false;
            if(objAssignToAccountData.opportunityRecord.OwnerId == UserInfo.getUserId()){
                isValid = true;  
            }else{
                List<CustomPermission> lstCustomPermissions = [SELECT Id, DeveloperName, (SELECT Id, Parent.Name, Parent.Profile.Name FROM SetupEntityAccessItems WHERE Parent.Profile.Id =: UserInfo.getProfileId()) FROM CustomPermission WHERE DeveloperName = 'Can_Reparent_Billing_Account'];
                if(lstCustomPermissions != null && lstCustomPermissions.size() > 0 && lstCustomPermissions[0].SetupEntityAccessItems != null && lstCustomPermissions[0].SetupEntityAccessItems.size() > 0){
                    isValid = true;
                }
            }
            boolean isStageValid = false;
            if(isValid){
                String oppStageName = String.isBlank(objAssignToAccountData.opportunityRecord.StageName) ? '' : objAssignToAccountData.opportunityRecord.StageName.toLowerCase();
                String oppContractStage = String.isBlank(objAssignToAccountData.opportunityRecord.Contract_Stage__c) ? '' : objAssignToAccountData.opportunityRecord.Contract_Stage__c.toLowerCase();
                Setting__c manageBillingAccountSetting = Settings.get('ManageBillingAccountSetting');
                if(manageBillingAccountSetting != null && manageBillingAccountSetting.Data__c != null){
                    Map<String,object> mapSettingData = (Map<String, Object>) JSON.deserializeUntyped(manageBillingAccountSetting.Data__c.toLowerCase());
                    Map<String, Map<String, Set<String>>> billingAccSetting = (Map<String, Map<String, Set<String>>>) JSON.deserialize(JSON.serialize(mapSettingData.get('associatebillingaccount')),Map<String, Map<String, Set<String>>>.class);
                    if(objAssignToAccountData.opportunityRecord.Billing_Account__c != Null && billingAccSetting.get('withbillingaccount').get('allowedstages').contains(oppStageName) && (billingAccSetting.get('withbillingaccount').get('allowedcontractstages').contains(oppContractStage) || String.isBlank(oppContractStage))){
                        isStageValid = true;
                    } else if(objAssignToAccountData.opportunityRecord.Billing_Account__c == Null && billingAccSetting.get('withoutbillingaccount').get('allowedstages').contains(oppStageName) && (billingAccSetting.get('withoutbillingaccount').get('allowedcontractstages').contains(oppContractStage) || String.isBlank(oppContractStage))){
                        isStageValid = true;
                    }
                }else{
                    return new DatabaseResult(false,'null','Sales Console Setting (ManageBillingAccountSetting) not found.');
                }
            }
            objAssignToAccountData.isValidStage = isStageValid;
            objAssignToAccountData.isValidForAssociation = isValid;
            return new DatabaseResult(JSON.serialize(objAssignToAccountData));
        }catch(Exception pEx){
            ApexDebugLog.logException(pEx,'opportunityId---'+opportunityId, 'AssociateBillingAccountController', 'getOpportunityData');            
            return (new DatabaseResult(pEx));
        }
    }
    
     /************************************************************************************************************************************
        Author              : Pragalbha Mahajan
        Description         : This method inserts new billing account and Contact or update the exixting ,if exists.
        Created Date        : 20 July 2018 
        Issue No            : 
    **************************************************************************************************************************************/	
     @AuraEnabled
    public static DatabaseResult createNewBillingAccount(Map<String,String> mapNewObject){
        try{ 
            List<Billing_Account__c> lstBillAccounts = [Select Id, UUID__c From Billing_Account__c Where UUID__c =: mapNewObject.get('billingAccountUUID')];
            Debug.log('lstBillAccounts---'+lstBillAccounts);
            if(lstBillAccounts.size()>0){
                return new DatabaseResult(lstBillAccounts[0]);
            }else{
                Billing_Account__c billingAccountRec = (Billing_Account__c)FieldMappingsHelper.getMappings(mapNewObject.get('parentId'), 'FieldMappings:AccountToBillingAccount');
                billingAccountRec.Name = mapNewObject.get('billingAccountName');
                billingAccountRec.UUID__c = mapNewObject.get('billingAccountUUID');                
                billingAccountRec.Parent_Account__c = mapNewObject.get('parentId');
                Contact objContact;
                Opportunity objOpp;
                if(mapNewObject.get('contactId') != null){
                    billingAccountRec.Primary_Member__c  = mapNewObject.get('contactId');
                    insert billingAccountRec;
                    objContact = new Contact(Id=mapNewObject.get('contactId'),UUID__c = mapNewObject.get('primaryMemberUUID'),Billing_Account__c=billingAccountRec.Id);
                    if(mapNewObject.containsKey('contactAccountId') && mapNewObject.get('contactAccountId') != null){
                        objContact.AccountId = (mapNewObject.containsKey('contactAccountId') && mapNewObject.get('contactAccountId')!= null ? mapNewObject.get('contactAccountId') : null);
                    }
                    UPDATE objContact;
                }else{
                    insert billingAccountRec;
                    List<String> lstNames = mapNewObject.get('contactName').split(' ');
                    String strFirstName = '',strLastName = '';
                    if(lstNames.size()>1){
                        strFirstName = lstNames[0];
                        lstNames.remove(0);
                        strLastName = String.join(lstNames,' ');
                    }else{
                        strLastName = String.join(lstNames,' ');
                    }
                    objContact = new Contact(FirstName=strFirstName,LastName=strLastName,Billing_Account__c=billingAccountRec.Id,AccountId=(mapNewObject.containsKey('parentId') && mapNewObject.get('parentId')!= null ? mapNewObject.get('parentId') : null),Email=mapNewObject.get('Email'),Phone=mapNewObject.get('phone'),UUID__c=mapNewObject.get('primaryMemberUUID'));
                    insert objContact;
                    billingAccountRec.Primary_Member__c = objContact.Id;
                    update billingAccountRec;
                }
                if(mapNewObject.get('oppId') != null){
                    objOpp = new Opportunity(Id=mapNewObject.get('oppId'),Billing_Account__c=billingAccountRec.Id);
                    update objOpp;
                }
                billingAccountRec = [SELECT Id, Name, UUID__c FROM Billing_Account__c WHERE Id=:billingAccountRec.Id];
                return new DatabaseResult(billingAccountRec);
            }
        }catch(Exception pEx){
            ApexDebugLog.logException(pEx,'', 'AssociateBillingAccountController', 'insertNewAccountForSendPaperwork');            
            return (new DatabaseResult(pEx)); 
        }
    } 
    
     /************************************************************************************************************************************
        Author              : Pragalbha Mahajan
        Description         : This method checks is opportunity is valid for SendPaperWork.
        Created Date        : 23 July 2018 
        Issue No            : 
    **************************************************************************************************************************************/	
    @AuraEnabled
    public static DatabaseResult isValidOppforSendPaperwork(Id oppId){
        return new DatabaseResult(SendPaperWorkController.isValidOppforSendPaperwork(oppId));
    }
    
	/**************************************************************************************************************************************************
    Author              : Dipak Pawar
    Description         : This is a Class to hold AssignToAccountData Details.
    Created Date        : 18 July 2018 
    ***************************************************************************************************************************************************/
    public class AssignToAccountData {
        public Opportunity opportunityRecord{get;set;}
        public Id ultimateParentOrgId{get;set;}
        public List<Billing_Account__c> billingAccounts{get;set;}
        public Setting__c apiSetting{get;set;}
        public Boolean isValidForAssociation{get;set;}
        public Boolean isValidStage{get;set;}
    }
}