objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <description>This is Picklist which Contains three values
1. Org : It is Main account in hierarchy which is Parent Account of Sales And Bill.
2. Sales: One Sales Account may contain multiple Bill Or Sales Account and It is Under Org Account in hierarchy
3. Bill: Bill Account is under Sales or Org. It never child of Bill Account.
4. ' '(Blank) : It is like Bill type which is under Sales or Org.</description>
        <inlineHelpText>This Picklist is used to determine the account type.</inlineHelpText>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Org</fullName>
                    <default>true</default>
                    <label>Org</label>
                </value>
                <value>
                    <fullName>Sales</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Lead_Source__c</fullName>
        <label>Lead Source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unomy_Company_ID__c</fullName>
        <externalId>true</externalId>
        <label>Unomy Company ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unomy_Location_Address__c</fullName>
        <label>Unomy Location Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unomy_Location_City__c</fullName>
        <label>Unomy Location City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unomy_Location_Country__c</fullName>
        <label>Unomy Location Country</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unomy_Location_State__c</fullName>
        <label>Unomy Location State</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unomy_Updated_DateTime__c</fullName>
        <description>The date/time a record was updated from Unomy</description>
        <label>Unomy Updated DateTime</label>
        <type>DateTime</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/BatchToUpdateOrInsertSObjectsTest.cls
/************************************************************************************************************************************
	Author		: 	Nikhil Mehta
	Description	:   This class used to test BatchToUpdateSobjects.
	----------------------------------------------------------------------------------------------------------------------------------
	VERSION		DATE	        		AUTHOR                     	DETAIL
	1	    	22 February 2019		Nikhil Mehta             	Initial Developement
**************************************************************************************************************************************/
@isTest
public class BatchToUpdateOrInsertSObjectsTest {
    @TestSetup
    public static void initData(){
        SalesConsoleSettings.createSettings();
    }
    
    @isTest
    public static void verifyBatchToUpdateSOBjects(){
        List<Account> lstAccounts = new List<Account>();
        Integer iIndex;
        for(iIndex = 0; iIndex < 5; iIndex++){
            lstAccounts.add(new Account(Name='Master Account'+iIndex, Unomy_Company_ID__c = 123456+iIndex, Unomy_Updated_DateTime__c = Date.today(), Lead_Source__c = 'Test'+iIndex, Account_Type__c = 'Org', Unomy_Location_Address__c = 'USA', Unomy_Location_City__c = 'Seattle', Unomy_Location_State__c = 'Washington', Unomy_Location_Country__c = 'USA', BillingStreet = 'Washington', BillingCity = 'Seattle', BillingState = 'Washington', BillingCountry = 'USA')); 
        }
        Database.insert(lstAccounts, false);
        iIndex = 0;
        for(Account objAccount : lstAccounts){
            objAccount.Name = 'Account'+iIndex;
            iIndex++;
        }
        Test.startTest();
        Database.executeBatch(new BatchToUpdateOrInsertSObjects(lstAccounts));
        Test.stopTest();
        iIndex = 0;
        for(Account objAccount : [SELECT Id, Name FROM Account WHERE Id IN :lstAccounts]){
            System.assertEquals('Account'+iIndex, objAccount.Name);
            iIndex++;
        }
    }
}