objects/Account.object
<CustomObject>
    <fields>
        <fullName>Lead_Source__c</fullName>
        <label>Lead Source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Event_Email_Opt_Out__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Please check if this event should not receive automated email cadences from Marketing Cloud</description>
        <label>Event Email Opt Out</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Lead_Source_Detail__c</fullName>
        <description>This field captures the information from where the lead is coming.</description>
        <inlineHelpText>This field captures the information from where the lead is coming.</inlineHelpText>
        <label>Lead Source Detail</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This is the latest status coming from Space systems through Jitterbunny of the individual member. This tells us if the user is active or not.</description>
        <inlineHelpText>This is accurate status of a contact if it is an active member of our products or not.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>active</fullName>
                </value>
                <value>
                    <fullName>inactive</fullName>
                    <default>true</default>
                    <label>inactive</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Journey__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <description>If Primary_Lead is exists, will return Primary Lead's Email otherwise It will check for Primary_Contact, If contact exists will return Email of Contact.</description>
        <formula>IF( Primary_Lead__c != NULL , Primary_Lead__r.Email , IF( Primary_Contact__c != NULL, Primary_Contact__r.Email , "" ))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Email(old)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Source_Detail__c</fullName>
        <description>Details of Lead Source from where Tour was booked. e.g. specific form of the website.</description>
        <label>Lead Source Detail</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Source__c</fullName>
        <description>Source of the Tour, how it was booked.</description>
        <label>Lead Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>42 Floors</fullName>
                </value>
                <value>
                    <fullName>ads-twitter</fullName>
                </value>
                <value>
                    <fullName>Adwords</fullName>
                </value>
                <value>
                    <fullName>Affiliate Referral</fullName>
                </value>
                <value>
                    <fullName>Broker Referral</fullName>
                </value>
                <value>
                    <fullName>Cold Call</fullName>
                </value>
                <value>
                    <fullName>Cold Email</fullName>
                </value>
                <value>
                    <fullName>Community Team Referral</fullName>
                </value>
                <value>
                    <fullName>Craigslist Ad</fullName>
                </value>
                <value>
                    <fullName>Employee Referral</fullName>
                </value>
                <value>
                    <fullName>Event</fullName>
                </value>
                <value>
                    <fullName>Facebook</fullName>
                </value>
                <value>
                    <fullName>Google</fullName>
                </value>
                <value>
                    <fullName>Guest</fullName>
                </value>
                <value>
                    <fullName>Guest Wifi</fullName>
                </value>
                <value>
                    <fullName>Id</fullName>
                </value>
                <value>
                    <fullName>Inbound Call</fullName>
                </value>
                <value>
                    <fullName>Inbound Email</fullName>
                </value>
                <value>
                    <fullName>Landing Page Campaign</fullName>
                </value>
                <value>
                    <fullName>LinkedIn Paid</fullName>
                </value>
                <value>
                    <fullName>Member Referral</fullName>
                </value>
                <value>
                    <fullName>Newsletter</fullName>
                </value>
                <value>
                    <fullName>Newsletter Campaign</fullName>
                </value>
                <value>
                    <fullName>Olark Chat</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Other Referral</fullName>
                </value>
                <value>
                    <fullName>Outbound Email/Cold Call</fullName>
                </value>
                <value>
                    <fullName>Partner Referral</fullName>
                </value>
                <value>
                    <fullName>Phone Call</fullName>
                </value>
                <value>
                    <fullName>Press Campaign</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>NMD_Next_Contact_Date__c</fullName>
        <description>Date on which Journey Primary Member should be next contacted on.

This is key to manage the reminders for the Journey.</description>
        <label>Next Contact Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Primary Contact of the Journey</description>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Journeys</relationshipLabel>
        <relationshipName>Journeys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>If journey is for a Lead this will be the Primary Lead. Only Primary Contact or Primary Lead can be specified not both.</description>
        <label>Primary Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Journeys</relationshipLabel>
        <relationshipName>Journeys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>New Field to Capture Journey Status</description>
        <label>Journey Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Started</fullName>
                    <default>true</default>
                    <label>Started</label>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Trying to Reach</fullName>
                </value>
                <value>
                    <fullName>In Contact</fullName>
                </value>
                <value>
                    <fullName>Nurture</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Transferred</fullName>
                </value>
                <value>
                    <fullName>Unresponsive</fullName>
                </value>
                <value>
                    <fullName>No Contact</fullName>
                </value>
                <value>
                    <fullName>Unqualified</fullName>
                </value>
                <value>
                    <fullName>Auto-Complete/Expiration</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>We are going to use this object as Sales Journey of the user. Which begins when a person shows interest in one of our products or we decide to reach out to show our products.</description>
    <label>Journey</label>
    <nameField>
        <label>Customer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Journeys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Lead_Source_Detail__c</fullName>
        <label>Lead Source Detail</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/UpdateJourneyOnCampaignMemberBatchTest.cls
@isTest
public class UpdateJourneyOnCampaignMemberBatchTest {
/*    @testSetup static void setup() {
        SalesConsoleSettings.createSettings(); 
        List<Campaign>lstCampaign =new List<Campaign>();           
        for(Integer index=1;index<7;index++) {
            lstCampaign.add(new Campaign(Name = 'TestCamp'+index, Type='Event', Status='Active', Event_Email_Opt_Out__c=true, StartDate=Date.today()));
        }
        insert lstCampaign;
        
        List<Lead>lstLead =new List<Lead>();           
        for(Integer index=1;index<11;index++) {
            if(index<=5){
                lstLead.add(new Lead(FirstName='Test',LastName = 'Lead'+index,LeadSource='Event',Lead_Source_Detail__c='Book A Tour Availability',Phone='8888888888',Email='testlead'+index+'@example.com',Company='TestAccount'));
            }else{
                lstLead.add(new Lead(FirstName='Test',LastName = 'Lead'+index,Phone='1234567890',LeadSource='Event',Lead_Source_Detail__c='Book A Tour Form',Email='testlead'+index+'@example.com',Company = 'TestAccount')); 
            }           
        }
        insert lstLead;
        
        Account objAccount = new Account(Name = 'Test Account001');
        insert objAccount; 
        
        List<Contact>lstContact =new List<Contact>(); 
        for(Integer index=1;index<11;index++) {          
            lstContact.add(new Contact(AccountId=objAccount.Id,FirstName='Test',LastName = 'Contact_'+index,Email='testcontact_'+index+'_c@example.com', LeadSource ='Event'));           
        }
        insert lstContact; 
        
        List<Journey__c>lstJorneys =new List<Journey__c>();
        for(Integer index=0;index<5;index++) {          
            lstJorneys.add(new Journey__c(Name = lstLead.get(index).LastName, Status__c = 'Started', Lead_Source__c='Event', Primary_Lead__c=lstLead.get(index).Id, NMD_Next_Contact_Date__c = Date.today()));
        }
        
        for(Integer index=0;index<5;index++) {          
            lstJorneys.add(new Journey__c(Name = lstContact.get(index).LastName,Status__c = 'Started', Lead_Source__c='Event' ,Primary_Contact__c=lstContact.get(index).Id, NMD_Next_Contact_Date__c = Date.today()));
        }
        insert lstJorneys;
        
        List<CampaignMember> lstCM = new List<CampaignMember>();
        for(Integer index=0; index<5; index++) {          
            lstCM.add(new CampaignMember(CampaignId = lstCampaign.get(index).Id, LeadId = lstLead.get(index).Id ));
        }
        for(Integer index=0; index<5; index++) {  
            lstCM.add(new CampaignMember(CampaignId = lstCampaign.get(index).Id, ContactId = lstContact.get(index).Id ));
        }
        insert lstCM;
    }
    
    static testmethod void testUpdateJourneyBasedCM() {
        List<Campaign>lstCamp = [SELECT Id,Name,StartDate FROM Campaign];
        System.assertEquals(lstCamp.size(), 6);
        List<CampaignMember> lstCM = [SELECT Id,Contact.Name,Lead.Name,CreatedDate FROM CampaignMember];
        System.assertEquals(lstCM.size(), 10);
        List<Lead>lstleads=[SELECT Id,Name,LeadSource,Company,Phone,Email FROM Lead];
        System.assertEquals(lstleads.size(), 10);
        List<Account>lstAccounts=[SELECT Id,Name FROM Account];
        System.assertEquals(lstAccounts.size(), 2, 'It creates two accounts first is Org and second is under that org');
        List<Contact>lstContacts=[SELECT Id,Name,Email,Account.Name FROM Contact];
        System.assertEquals(lstContacts.size(), 10);
        List<Journey__c>lstJourneys=[SELECT Id,Name,Email__c,Status__c,CreatedDate FROM Journey__c];
        System.assertEquals(10, lstJourneys.size());
        Test.startTest();
        Id batchId = Database.executeBatch(new UpdateJourneyOnCampaignMemberBatch(),100);
        System.assertNotEquals(batchId, null);
        Test.stopTest();
        List<Journey__c>lstResultJourneys = [SELECT Id,Name,Email__c,Status__c,Primary_Contact__c,Primary_Lead__c,CreatedDate FROM Journey__c WHERE Status__c='Completed'];
        System.debug('lstResultJourneys==>'+lstResultJourneys.size());
        System.assertEquals(10,lstResultJourneys.size());
        
    }
*/    
    
}