objects/Account.object
<CustomObject>
    <fields>
        <fullName>Geography__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to store the geography record which is created when we find the market for account. Created for ST-3198</description>
        <inlineHelpText>Store the geography record which is created when we find the market for account.</inlineHelpText>
        <label>Geography</label>
        <referenceTo>Geography__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Paperwork will be sent to the primary member on the ACCOUNT</inlineHelpText>
        <label>Main Contact</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.Account.Id</field>
                <operation>equals</operation>
                <valueField>$Source.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Geography__c.object
<CustomObject>
    <description>This object will represent Google Maps Location so that we can reuse same location as and when required within multiple objects.</description>
    <label>Geography</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Geographies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Geography__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will show the location where the lead is interested to find the spaces.</description>
        <inlineHelpText>Search for the relevant geographic location</inlineHelpText>
        <label>Geography</label>
        <referenceTo>Geography__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Member__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>This is the Main Contact of the Opportunity</inlineHelpText>
        <label>Main Contact</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/UtilOpportunity.cls
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Name:            Opportunity.cls
Description:    Opportunity Object Utility for testing and general functions .        
Date            Author          Summary of Changes 
7-OCT-2018     Rashad Saeed  Initial Implementation 
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
public class UtilOpportunity {
    
    Private Static Map <String,Id>ActiveRecordTypes = UtilRecordType.GetSobjectActiveRecordTypes('Opportunity');    
    Private Static Map<String,Object> StMapFields = new Map<String,Object> ();
   
    public static List<Opportunity>GetNewOpportunity(Integer NumberOfRecords,Account Acc,Boolean DoInsert){
        List<Map<String,Object>> ListOfMapFields = new List<Map<String,Object>>();
        for (Integer i = 1, j = NumberOfRecords; i <= j; i++){
            Map<String,Object> OppFieldsMap = new Map<String,Object>(StMapFields);
            OppFieldsMap.put ('AccountId',Acc.id);
            OppFieldsMap.put ('StageName','New');
            String OppName = Acc.Name+'_'+i;
            OppFieldsMap.Put ('Name',OppName);
            OppFieldsMap.Put ('CloseDate',System.today().addDays(5));
            OppFieldsMap.Put ('LeadSource','WeWork.com');
            ListOfMapFields.add(OppFieldsMap);
        }
        return UtilGeneral.createTestRecords(Opportunity.sObjectType, ListOfMapFields, DoInsert); 
    }  
    
    public Static List <Opportunity> GetOppByRecordType (Integer NumberOfRecords,String RecordTypeName,Account Acc,Boolean DoInsert){
        RecordTypeName = RecordTypeName.toLowerCase();
        if (ActiveRecordTypes.containsKey(RecordTypeName))
            StMapFields.put('RecordTypeId',ActiveRecordTypes.get(RecordTypeName));
        else
            return null;
        return GetNewOpportunity (NumberOfRecords,Acc,DoInsert);
    }

    public static Opportunity createOppWithGeoAndContact(integer NumberOfRecords, Account acc, Id contactId, Id geo, boolean doInsert)
    {
    	StMapFields.put('Primary_Member__c',contactId);
    	StMapFields.put('Geography__c',geo);

    	return GetNewOpportunity (NumberOfRecords, Acc, DoInsert)[0];
    }
}