objects/Account.object
<CustomObject>
    <fields>
        <fullName>Primary_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Paperwork will be sent to the primary member on the ACCOUNT</inlineHelpText>
        <label>Main Contact</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.Account.Id</field>
                <operation>equals</operation>
                <valueField>$Source.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UUID__c</fullName>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Building__c.object
<CustomObject>
    <fields>
        <fullName>UUID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Building</label>
    <nameField>
        <label>Building</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Actual_Start_Date__c</fullName>
        <formula>Account.Start_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Actual Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Building__c</fullName>
        <description>Pulls Building Location without 3 character city reference</description>
        <formula>Location__r.Location_No_City__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Building</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Member__c</fullName>
        <formula>if( Billing_Account__r.Primary_Member__r.Id =  Id , "Yes","No")</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Primary Member</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Licensee</fullName>
                </value>
                <value>
                    <fullName>Employee</fullName>
                </value>
                <value>
                    <fullName>Member</fullName>
                </value>
                <value>
                    <fullName>Broker</fullName>
                </value>
                <value>
                    <fullName>Affiliate</fullName>
                </value>
                <value>
                    <fullName>Potential</fullName>
                </value>
                <value>
                    <fullName>Lead</fullName>
                </value>
                <value>
                    <fullName>Unqualified Broker</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UUID__c</fullName>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Actual_Start_Date__c</fullName>
        <inlineHelpText>This is the Expected Start Date until Closed Won</inlineHelpText>
        <label>Actual Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Building__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Enter the specific building for which opportunity is associated</description>
        <inlineHelpText>This is the building / Nearest building to the geography entered by customer</inlineHelpText>
        <label>Building/Nearest Building</label>
        <referenceTo>Building__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Locations_Interested__c</fullName>
        <label>Locations Interested</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AMS-Labs</fullName>
                </value>
                <value>
                    <fullName>AMS-Metropool</fullName>
                </value>
                <value>
                    <fullName>AMS-Strawinskylaan</fullName>
                </value>
                <value>
                    <fullName>AMS-Weteringschans</fullName>
                </value>
                <value>
                    <fullName>ARC-Andres Arguibel 2860</fullName>
                </value>
                <value>
                    <fullName>ARC-Avenida Corrientes 800</fullName>
                </value>
                <value>
                    <fullName>ARC-Ing. Enrique Butty 275</fullName>
                </value>
                <value>
                    <fullName>ARC-Libertador 1000</fullName>
                </value>
                <value>
                    <fullName>ARC- Torre Bellini</fullName>
                </value>
                <value>
                    <fullName>ARG- Torre Bellini</fullName>
                </value>
                <value>
                    <fullName>ARN-Urban Escape</fullName>
                </value>
                <value>
                    <fullName>ATL-1372 Peachtree</fullName>
                </value>
                <value>
                    <fullName>ATL-3280 Peachtree Road NE</fullName>
                </value>
                <value>
                    <fullName>ATL-Colony Square</fullName>
                </value>
                <value>
                    <fullName>ATL-Tower Place</fullName>
                </value>
                <value>
                    <fullName>AUS-Congress</fullName>
                </value>
                <value>
                    <fullName>AUS-Domain</fullName>
                </value>
                <value>
                    <fullName>AUS-Labs</fullName>
                </value>
                <value>
                    <fullName>AUS-University Park</fullName>
                </value>
                <value>
                    <fullName>AUS-Westview</fullName>
                </value>
                <value>
                    <fullName>AUS-WeWork 801 Barton Springs</fullName>
                </value>
                <value>
                    <fullName>BCN-Diagonal 444</fullName>
                </value>
                <value>
                    <fullName>BHZ-Boulevard Shopping</fullName>
                </value>
                <value>
                    <fullName>BKK-Asia Centre</fullName>
                </value>
                <value>
                    <fullName>BKN-109 S 5th St</fullName>
                </value>
                <value>
                    <fullName>BKN-Brooklyn Heights</fullName>
                </value>
                <value>
                    <fullName>BKN-Dumbo Heights (Prospect)</fullName>
                </value>
                <value>
                    <fullName>BKN-Dumbo Heights (Sands)</fullName>
                </value>
                <value>
                    <fullName>BKN-Montague St.</fullName>
                </value>
                <value>
                    <fullName>BKN-Williamsburg</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_Member__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>This is the Main Contact of the Opportunity</inlineHelpText>
        <label>Main Contact</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Event Space</fullName>
                </value>
                <value>
                    <fullName>Internal Transfer</fullName>
                </value>
                <value>
                    <fullName>Partnership</fullName>
                </value>
                <value>
                    <fullName>PxWe</fullName>
                </value>
                <value>
                    <fullName>Mixed</fullName>
                </value>
                <value>
                    <fullName>Global Access</fullName>
                </value>
                <value>
                    <fullName>WeWork</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/RESTWaitlistTest.cls
@isTest
private class RESTWaitlistTest {
    static {
        SalesConsoleSettings.createSettings();
    }
	@isTest static void test_post_success_1_new_opportunity() {
		//pre-context
			Account a = new Account(
				name = 'Test Account'
			);
			insert a;

			Contact c = new Contact(
				lastname 	= 'TestContact',
				AccountId = a.Id,
				email 		= 'john@doe.com'
			);
			insert c;
			
			a.Primary_Member__c = c.Id;
			update a;

			Building__c b1 = new Building__c(
				name='b1',
				uuid__c = 'abc123'
			);
			insert b1;

			Building__c b2 = new Building__c(
				name='b2',
				uuid__c = 'def456'
			);
			insert b2;
						
			Opportunity o = new Opportunity(
				type__c 							= 'Network Membership',
				AccountID 						= a.Id,
				stagename 						= 'Qualifying',
				closeDate 						= system.today(),
				Building__c 					= b1.Id,
				actual_start_date__c 	= Date.today(),
				name 									= 'Test Opportunity',
				Primary_Member__c 		= c.id
			);
			insert o;

		//test
		Test.startTest();
		RestRequest req 	= new RestRequest(); 
	    RestResponse res 	= new RestResponse();
      
      // pass the req and resp objects to the method		 
      req.requestURI = 'https://cs8.salesforce.com/services/apexrest/Waitlist';  
      req.httpMethod = 'POST';

	 		//assign rest context
	 		RestContext.request 	= req;
	 		RestContext.response 	= res;
	 		
	 		//define container and set request Company and Reservable UUIDs
	 		WWTypes.Waitlist j 						= new WWTypes.Waitlist();	 		
	 		j.actual_start_date 					= system.today().addDays(10);
	 		j.notes 								= 'Some notes';
	 		j.email 								= 'john@doe.com';
	 		j.buildings_interested_uuids 	= new String[]{'abc123', 'def456'};
			
			//submit post
			RESTWaitlist.Response response = RESTWaitlist.doPost(j);		

			system.assertEquals(
				true,
				response.success,
				'the response should be successfully processed'
			);

			Opportunity[] Os = [	SELECT id, stagename, Primary_Member__r.email, AccountId, locations_interested__c 
														FROM Opportunity 
														WHERE stagename = 'Negotiating'															
												 ];

       		Debug.log('Opportunity Os 81==>'+Os);
			system.assertEquals(
				1,
				Os.size(),
				'One opportunity in waitlist should exist'
			);								

			system.assertEquals(
				j.email,
				Os[0].Primary_Member__r.email,
				'The primary member should have the same email address as specified on waitlist'
			);

			system.assertEquals(
				a.id,
				Os[0].AccountId,
				'The same account of the primary member should be used for the opportunity'
			);

			system.assertNotEquals(
				null,
				Os[0].locations_interested__c,
				'locations should be set'
			);

			system.assertEquals(
				true,
				(Os[0].locations_interested__c.contains(b1.name)|| Os[0].locations_interested__c.contains('B1')),
				'locations should be set'
			);

			system.assertEquals(
				true,
				Os[0].locations_interested__c.contains(b2.name),
				'locations should be set'
			);

			system.assertEquals(
				true,
				Os[0].locations_interested__c.contains(';'),
				'locations separator should be set'
			);

		Test.stopTest();
	}
    
    
    
    

	@isTest static void test_post_success_1_update_opportunity() {
		//pre-context
			Account a = new Account(
				name = 'Test Account'
			);
			insert a;

			Contact c = new Contact(
				lastname 	= 'TestContact',
				AccountId = a.Id,
				email 		= 'john@doe.com'
			);
			insert c;
			
			a.Primary_Member__c = c.Id;
			update a;

			Building__c b1 = new Building__c(
				name='b1',
				uuid__c = 'abc123'
			);
			insert b1;

			Building__c b2 = new Building__c(
				name='b2',
				uuid__c = 'def456'
			);
			insert b2;
						
			Opportunity o = new Opportunity(
				type__c 							= 'Network Membership',
				AccountID 						= a.Id,
				stagename 						= 'Negotiating',
				closeDate 						= system.today(),
				Building__c 					= b1.Id,
				actual_start_date__c 	= Date.today(),
				name 									= 'Test Opportunity',
				Primary_Member__c 		= c.id,
				locations_interested__c = 'b1'
			);
			insert o;

		//test
		Test.startTest();
			RestRequest req 	= new RestRequest(); 
	    RestResponse res 	= new RestResponse();
      
      // pass the req and resp objects to the method		 
      req.requestURI = 'https://cs8.salesforce.com/services/apexrest/Waitlist';  
      req.httpMethod = 'POST';

	 		//assign rest context
	 		RestContext.request 	= req;
	 		RestContext.response 	= res;
	 		
	 		//define container and set request Company and Reservable UUIDs
	 		WWTypes.Waitlist j 						= new WWTypes.Waitlist();	 		
	 		j.actual_start_date 					= system.today();
	 		j.notes 											= 'Some notes';
	 		j.email 											= 'john@doe.com';
	 		j.buildings_interested_uuids 	= new String[]{'abc123', 'def456'};
			
			//submit post
			RESTWaitlist.Response response = RESTWaitlist.doPost(j);		

			Opportunity[] Os = [	SELECT id, locations_interested__c 
														FROM Opportunity 
														WHERE stagename = 'Negotiating'															
												 ];
        	

			system.assertEquals(
				1,
				Os.size(),
				'One opportunity in waitlist should exist'
			);

        	debug.log('Os==>'+Os);
        system.assertEquals(
            true,
            (Os[0].locations_interested__c.contains(b1.name)|| Os[0].locations_interested__c.contains('B1')) &&
            Os[0].locations_interested__c.contains('b2') &&
            Os[0].locations_interested__c.contains(';'),
            'locations_interested__c should be merged'
        );		

		Test.stopTest();
	}

	@isTest static void test_post_success_2_update_opportunity() {
		//pre-context
			Account a = new Account(
				name = 'Test Account'
			);
			insert a;

			Contact c = new Contact(
				lastname 	= 'TestContact',
				AccountId = a.Id,
				email 		= 'john@doe.com'
			);
			insert c;
			
			a.Primary_Member__c = c.Id;
			update a;

			Building__c b1 = new Building__c(
				name='b1',
				uuid__c = 'abc123'
			);
			insert b1;

			Building__c b2 = new Building__c(
				name='b2',
				uuid__c = 'def456'
			);
			insert b2;
						
			Opportunity o = new Opportunity(
				type__c 							= 'Network Membership',
				AccountID 						= a.Id,
				stagename 						= 'Negotiating',
				closeDate 						= system.today(),
				Building__c 					= b1.Id,
				actual_start_date__c 	= Date.today(),
				name 									= 'Test Opportunity',
				Primary_Member__c 		= c.id,
				locations_interested__c = null
			);
			insert o;

		//test
		Test.startTest();
			RestRequest req 	= new RestRequest(); 
	    RestResponse res 	= new RestResponse();
      
      // pass the req and resp objects to the method		 
      req.requestURI = 'https://cs8.salesforce.com/services/apexrest/Waitlist';  
      req.httpMethod = 'POST';

	 		//assign rest context
	 		RestContext.request 	= req;
	 		RestContext.response 	= res;
	 		
	 		//define container and set request Company and Reservable UUIDs
	 		WWTypes.Waitlist j 						= new WWTypes.Waitlist();	 		
	 		j.actual_start_date 					= system.today();
	 		j.notes 											= 'Some notes';
	 		j.email 											= 'john@doe.com';
	 		j.buildings_interested_uuids 	= new String[]{'abc123', 'def456'};
			
			//submit post
			RESTWaitlist.Response response = RESTWaitlist.doPost(j);		

			Opportunity[] Os = [	SELECT id, locations_interested__c 
														FROM Opportunity 
														WHERE stagename = 'Negotiating'															
												 ];

			system.assertEquals(
				1,
				Os.size(),
				'One opportunity in waitlist should exist'
			);

			system.assertEquals(
				true,
				(Os[0].locations_interested__c.contains(b1.name)|| Os[0].locations_interested__c.contains('B1')) &&
				Os[0].locations_interested__c.contains('b2') &&
				Os[0].locations_interested__c.contains(';'),
				'locations_interested__c should be merged'
			);		

		Test.stopTest();
	}

	@isTest static void test_post_success_3_update_opportunity() {
		//pre-context
			Account a = new Account(
				name = 'Test Account'
			);
			insert a;

			Contact c = new Contact(
				lastname 	= 'TestContact',
				AccountId = a.Id,
				email 		= 'john@doe.com'
			);
			insert c;
			
			a.Primary_Member__c = c.Id;
			update a;

			Building__c b1 = new Building__c(
				name='b1',
				uuid__c = 'abc123'
			);
			insert b1;

			Building__c b2 = new Building__c(
				name='b2',
				uuid__c = 'def456'
			);
			insert b2;
						
			Opportunity o = new Opportunity(
				type__c 							= 'Network Membership',
				AccountID 						= a.Id,
				stagename 						= 'Negotiating',
				closeDate 						= system.today(),
				Building__c 					= b1.Id,
				actual_start_date__c 	= Date.today(),
				name 									= 'Test Opportunity',
				Primary_Member__c 		= c.id,
				locations_interested__c = 'b1'
			);
			insert o;

		//test
		Test.startTest();
			RestRequest req 	= new RestRequest(); 
	    RestResponse res 	= new RestResponse();
      
      // pass the req and resp objects to the method		 
      req.requestURI = 'https://cs8.salesforce.com/services/apexrest/Waitlist';  
      req.httpMethod = 'POST';

	 		//assign rest context
	 		RestContext.request 	= req;
	 		RestContext.response 	= res;
	 		
	 		//define container and set request Company and Reservable UUIDs
	 		WWTypes.Waitlist j 						= new WWTypes.Waitlist();	 		
	 		j.actual_start_date 					= system.today();
	 		j.notes 											= 'Some notes';
	 		j.email 											= 'john@doe.com';
	 		j.buildings_interested_uuids 	= null;
			
			//submit post
			RESTWaitlist.Response response = RESTWaitlist.doPost(j);		

			Opportunity[] Os = [	SELECT id, locations_interested__c 
														FROM Opportunity 
														WHERE stagename = 'Negotiating'															
												 ];

			system.assertEquals(
				1,
				Os.size(),
				'One opportunity in waitlist should exist'
			);

			system.assertEquals(
				true,
				(Os[0].locations_interested__c.contains(b1.name)|| Os[0].locations_interested__c.contains('B1')),
				'locations_interested__c should be merged'
			);		

		Test.stopTest();
	}

	@isTest static void test_post_success_4_update_opportunity() {
		//pre-context
			Account a = new Account(
				name = 'Test Account'
			);
			insert a;

			Contact c = new Contact(
				lastname 	= 'TestContact',
				AccountId = a.Id,
				email 		= 'john@doe.com'
			);
			insert c;
			
			a.Primary_Member__c = c.Id;
			update a;

			Building__c b1 = new Building__c(
				name='b1',
				uuid__c = 'abc123'
			);
			insert b1;

			Building__c b2 = new Building__c(
				name='b2',
				uuid__c = 'def456'
			);
			insert b2;
						
			Opportunity o = new Opportunity(
				type__c 							= 'Network Membership',
				AccountID 						= a.Id,
				stagename 						= 'Negotiating',
				closeDate 						= system.today(),
				Building__c 					= b1.Id,
				actual_start_date__c 	= Date.today(),
				name 									= 'Test Opportunity',
				Primary_Member__c 		= c.id,
				locations_interested__c = null
			);
			insert o;

		//test
		Test.startTest();
			RestRequest req 	= new RestRequest(); 
	    RestResponse res 	= new RestResponse();
      
      // pass the req and resp objects to the method		 
      req.requestURI = 'https://cs8.salesforce.com/services/apexrest/Waitlist';  
      req.httpMethod = 'POST';

	 		//assign rest context
	 		RestContext.request 	= req;
	 		RestContext.response 	= res;
	 		
	 		//define container and set request Company and Reservable UUIDs
	 		WWTypes.Waitlist j 						= new WWTypes.Waitlist();	 		
	 		j.actual_start_date 					= system.today();
	 		j.notes 											= 'Some notes';
	 		j.email 											= 'john@doe.com';
	 		j.buildings_interested_uuids 	= null;
			
			//submit post
			RESTWaitlist.Response response = RESTWaitlist.doPost(j);		

			Opportunity[] Os = [	SELECT id, locations_interested__c 
														FROM Opportunity 
														WHERE stagename = 'Negotiating'															
												 ];

			system.assertEquals(
				1,
				Os.size(),
				'One opportunity in waitlist should exist'
			);

			system.assertEquals(
				null,
				Os[0].locations_interested__c ,
				'locations_interested__c should be empty'
			);		

		Test.stopTest();
	}

	@isTest static void test_post_failure_1_email_doesnt_exist() {
		//pre-context
			//...	

		//test
		Test.startTest();
			RestRequest req 	= new RestRequest(); 
	    RestResponse res 	= new RestResponse();
      
      // pass the req and resp objects to the method		 
      req.requestURI = 'https://cs8.salesforce.com/services/apexrest/Waitlist';  
      req.httpMethod = 'POST';

	 		//assign rest context
	 		RestContext.request 	= req;
	 		RestContext.response 	= res;
	 		
	 		//define container and set request Company and Reservable UUIDs
	 		WWTypes.Waitlist j 						= new WWTypes.Waitlist();	 		
	 		j.actual_start_date 					= system.today();
	 		j.notes 											= 'Some notes';
	 		j.email 											= 'unexisting_email@doe.com';
	 		j.buildings_interested_uuids 	= new String[]{'abc123', 'def456'};
			
			//submit post
			RESTWaitlist.Response response = RESTWaitlist.doPost(j);		

			system.assertEquals(
				false,
				response.success,
				'an exception should be catched when the email is not found'
			);

		Test.stopTest();
	}
}