objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <description>This is Picklist which Contains three values
1. Org : It is Main account in hierarchy which is Parent Account of Sales And Bill.
2. Sales: One Sales Account may contain multiple Bill Or Sales Account and It is Under Org Account in hierarchy
3. Bill: Bill Account is under Sales or Org. It never child of Bill Account.
4. ' '(Blank) : It is like Bill type which is under Sales or Org.</description>
        <inlineHelpText>This Picklist is used to determine the account type.</inlineHelpText>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Org</fullName>
                    <default>true</default>
                    <label>Org</label>
                </value>
                <value>
                    <fullName>Sales</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Parent_Account__c</fullName>
        <formula>CASESAFEID(ParentId)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Parent Account(Pipeline Reporting)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Paperwork will be sent to the primary member on the ACCOUNT</inlineHelpText>
        <label>Main Contact</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.Account.Id</field>
                <operation>equals</operation>
                <valueField>$Source.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UUID__c</fullName>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Unomy_Company_ID__c</fullName>
        <externalId>true</externalId>
        <label>Unomy Company ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unomy_Company_Name__c</fullName>
        <label>Unomy Company Name</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Referral</fullName>
        <active>true</active>
        <label>Referral</label>
    </recordTypes>
</CustomObject>

objects/Billing_Account__c.object
<CustomObject>
    <fields>
        <fullName>Parent_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is lookup to the Parent Account</description>
        <inlineHelpText>This is lookup to the Parent Account</inlineHelpText>
        <label>Parent Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the main point of contact for the Billing Account.</description>
        <inlineHelpText>Person at the member company responsible for managing the membership: invoices, key card replacements, MENA account manager tab. Responsible for signing legal agreement (unless an authorized signatory is designated).</inlineHelpText>
        <label>Primary Member</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UUID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>This is unique,case sensitive auto generated field used to identify Billing Account record.</description>
        <externalId>true</externalId>
        <inlineHelpText>This is unique,case sensitive auto generated field used to identify Billing Account record.</inlineHelpText>
        <label>UUID</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Unomy_Company_ID__c</fullName>
        <externalId>true</externalId>
        <label>Unomy Company ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unomy_Company_Name__c</fullName>
        <label>Unomy Company Name</label>
        <type>TextArea</type>
    </fields>
    <description>All Billing account is moved to this Billing Account object it help Sales people to identify Org and Sales account easily and reduce the clutter of 100s of Accounts with same name.</description>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Building__c.object
<CustomObject>
    <fields>
        <fullName>UUID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Building</label>
    <nameField>
        <label>Building</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <formula>text(Account.Type)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Members</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Building__c</fullName>
        <description>Pulls Building Location without 3 character city reference</description>
        <formula>Location__r.Location_No_City__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Building</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Member__c</fullName>
        <formula>if( Billing_Account__r.Primary_Member__r.Id =  Id , "Yes","No")</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Primary Member</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Licensee</fullName>
                </value>
                <value>
                    <fullName>Employee</fullName>
                </value>
                <value>
                    <fullName>Member</fullName>
                </value>
                <value>
                    <fullName>Broker</fullName>
                </value>
                <value>
                    <fullName>Affiliate</fullName>
                </value>
                <value>
                    <fullName>Potential</fullName>
                </value>
                <value>
                    <fullName>Lead</fullName>
                </value>
                <value>
                    <fullName>Unqualified Broker</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UUID__c</fullName>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Unomy_Company_ID__c</fullName>
        <label>Unomy Company ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unomy_Company_Name__c</fullName>
        <label>Unomy Company Name</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Referral</fullName>
        <active>true</active>
        <label>Referral</label>
    </recordTypes>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Checking</fullName>
                </value>
                <value>
                    <fullName>Savings</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field relates the opportunity to the billing account. The billing account is used in the space station for sending contracts.</description>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Building__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Enter the specific building for which opportunity is associated</description>
        <inlineHelpText>This is the building / Nearest building to the geography entered by customer</inlineHelpText>
        <label>Building/Nearest Building</label>
        <referenceTo>Building__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract_Signed_On__c</fullName>
        <description>Capture date when Contract get Signed on</description>
        <inlineHelpText>Capture date when Contract get Signed on</inlineHelpText>
        <label>Contract Signed On</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Primary_Member__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>This is the Main Contact of the Opportunity</inlineHelpText>
        <label>Main Contact</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Referral_Status__c</fullName>
        <description>This will store Referral Status. Default value is Pending. Issue ST-2823</description>
        <inlineHelpText>This will store Referral Status.</inlineHelpText>
        <label>Referral Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Event Space</fullName>
                </value>
                <value>
                    <fullName>Internal Transfer</fullName>
                </value>
                <value>
                    <fullName>Partnership</fullName>
                </value>
                <value>
                    <fullName>PxWe</fullName>
                </value>
                <value>
                    <fullName>Mixed</fullName>
                </value>
                <value>
                    <fullName>Global Access</fullName>
                </value>
                <value>
                    <fullName>WeWork</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Setting__c.object
<CustomObject>
    <fields>
        <fullName>Data__c</fullName>
        <description>This should contain JSON formatted data for each setting record. The JSON object will vary from setting to setting.</description>
        <label>Data</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type of the Settings, if it is Field Mappings, it will contain mapping of source object to destination object in JSON format.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Field Mappings</fullName>
                </value>
                <value>
                    <fullName>Custom</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>We are creating object for Settings instead of using Custom Object because we need to store larger size of data which Custom Setting does not support. e.g. Mapping of Fields from Contact to Lead etc. which may go beyond 255 characters. 

It will not use caching but give more flexibility for coding.</description>
    <label>Sales Console Setting</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Console Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/RetroactiveReferralControllerTest.cls
/************************************************************************************************************************************
    Author      :  Nikhil Mehta    
    Description :  This class contain all test methods related to aura methods in RetroactiveReferralControllerTest.
    ----------------------------------------------------------------------------------------------------------------------------------
    VERSION     DATE                AUTHOR          		DETAIL
     1          18 Oct 2018       	Nikhil Mehta    	    Initial Developement
**************************************************************************************************************************************/
@isTest
public class RetroactiveReferralControllerTest {
    @testSetup
    static void setup(){
        SalesConsoleSettings.createSettings();
        List<Account> lstAccounts = new List<Account>();
        List<Contact> lstContacts = new List<Contact>();
        List<Opportunity> lstOpportunities = new List<Opportunity>();
        List<User> lstUsers = new List<User>();
        List<Billing_Account__c> lstBillingAccount = new List<Billing_Account__c>();
        
        List<Profile> lstProfile = [SELECT Id FROM Profile WHERE Name IN ('WeWork System Administrator', 'WeWork NMD User')]; 
        Map<String, Object> mapUserValues = TestingUtility.getUserMapValues('Admin');
        lstUsers.add((User)TestingUtility.insertUserWithAssert(lstProfile[0].Id, mapUserValues, false));
        
        Map<String, Object> mapUserValues1 = TestingUtility.getUserMapValues('NMDUser');
        lstUsers.add((User)TestingUtility.insertUserWithAssert(lstProfile[1].Id, mapUserValues1, false));
        TestingUtility.insertListWithAssert(lstUsers);
        
        lstAccounts.add(new Account(Name = 'tesAccount1'));
        lstAccounts.add(new Account(Name = 'testAccountSaveConAccRecords2', Account_Type__c = 'Org', Unomy_Company_ID__c = 123456789,Unomy_Company_Name__c = 'Enzigma123'));
        TestingUtility.insertListWithAssert(lstAccounts);
        
        lstContacts.add(new Contact(firstName = 'John', lastName = 'Rambo', email = 'john@example.com', Type__c = 'Employee'));
        TestingUtility.insertListWithAssert(lstContacts);
        
        lstBillingAccount.add(new Billing_Account__c(Name = 'Test Billing Account1', Parent_Account__c = lstAccounts[0].Id, UUID__c = 'testAccountUUID1', Primary_Member__c = lstContacts[0].Id));
        TestingUtility.insertListWithAssert(lstBillingAccount);
        
        lstOpportunities.add(new Opportunity(name = 'test oppty1', AccountId = lstAccounts[0].Id, Billing_Account__c = lstBillingAccount[0].Id, Primary_Member__c = lstContacts[0].Id, stageName = 'Selling' ,closeDate = System.today()));
        lstOpportunities.add(new Opportunity(name = 'test oppty2', AccountId = lstAccounts[0].Id, Primary_Member__c = lstContacts[0].Id, stageName = 'Qualifying', closeDate = System.today()));
        lstOpportunities.add(new Opportunity(name = 'test oppty3', AccountId = lstAccounts[0].Id, Primary_Member__c = lstContacts[0].Id, stageName = 'Closed Lost', closeDate = System.today()));
        lstOpportunities.add(new Opportunity(name = 'test oppty4', AccountId = lstAccounts[0].Id, Primary_Member__c = lstContacts[0].Id, Referral_Status__c = 'Approved', stageName = 'Closed Won', closeDate = System.today()));
        
        TestingUtility.insertListWithAssert(lstOpportunities);        
    }
    /*****************************************************************************************************************************************
        Author              :   Pragalbha Mahajan
        Description         :   This method tests UpdateReferrerOnOpportunity method
        Created Date        :   01 November 2018
        Issue No            :   ST-2858
    ******************************************************************************************************************************************/
    public static testMethod void verifycheckValidation(){
        List<Opportunity> lstOpportunity = [SELECT Id, Name, StageName FROM Opportunity WHERE StageName = 'Selling' OR StageName = 'Qualifying' OR StageName = 'Closed Lost' OR StageName = 'Closed Won'];
        List<Contact> lstContact = [SELECT Id, Type__c FROM Contact];
        List<Account> lstAccounts = [SELECT id FROM Account];
        List<User> lstUsers = [SELECT id, Name FROM User WHERE Email = 'testUser_NMDUser@example.com'];
        
        List<Billing_Account__c> lstBillingAccount = [SELECT Id, Primary_Member__c FROM Billing_Account__c];
        String oppResultNull = RetroactiveReferralController.isValidForWebService(null);
        Debug.log('oppResultNull'+oppResultNull);
        System.assertEquals(null, (Map<String, Object>) JSON.deserializeUntyped(oppResultNull));
        
        String oppResult = RetroactiveReferralController.isValidForWebService(lstOpportunity[0].Id);
        System.assertEquals(true, Boolean.valueOf(((Map<String, Object>) JSON.deserializeUntyped(oppResult)).get('isValid')));
        
        DatabaseResult oppRecord = RetroactiveReferralController.initialize(lstOpportunity[0].Id);
        System.assertEquals(true, Boolean.valueOf(((Map<String, Object>) JSON.deserializeUntyped(String.valueOf(oppRecord.data))).get('isValid')));
        
        oppRecord = RetroactiveReferralController.initialize(null);
        System.assertEquals(true, Boolean.valueOf(((Map<String, Object>) JSON.deserializeUntyped(String.valueOf(oppRecord.data))).get('isValid')));
      
        System.runAs(lstUsers[0]){
            String oppResult1 = RetroactiveReferralController.isValidForWebService(lstOpportunity[1].Id);
            System.assertEquals(false, Boolean.valueOf(((Map<String, Object>) JSON.deserializeUntyped(oppResult1)).get('isValid')));
            
            oppRecord = RetroactiveReferralController.initialize(null);
            System.assertEquals(false, Boolean.valueOf(((Map<String, Object>) JSON.deserializeUntyped(String.valueOf(oppRecord.data))).get('isValid')));
        }
        
        System.runAs(lstUsers[0]){
            Setting__c retroactiveSetting = Settings.get('RetroactiveReferralSettings');
            retroactiveSetting.Data__c ='{"RetroactiveReferralApi":{"url":"https://sales-api-staging.wework.com/v1/retroactive_referrals","Headers":{"Authorization":"Token token=dIc0nYcdaPvmFzUq3e0-CQ"}},"RetroactiveReferralType":["Retroactive Referral","Confidential Referral"],"ContactRecordType":"0120G000001K6d4","AccountRecordType":"0120G000001K6d3","APIUser":"005F0000003Kmbw","AllowedStages":["Closed Won"],"AllowedUsersId":["'+lstUsers[0].Id+'"],"AllowedProfileId":["00eF0000000aice"],"RetroactiveReferrType":["Employee","Member","Affiliate","Broker"],"RestrictOppStages":["Closed Lost","Merged"],"RestrictCriteria":{"excludeReferralStatus":["Approved"],"allowedOppStages":["Qualifying","Selling","Negotiating","Closing","Closed Won","Licensee"],"excludedContractStages":["Contract Sent","Contract Signed"],"excludedOppStages":["Closed Lost","Merged"]}}';
            update retroactiveSetting;    
            
            oppRecord = RetroactiveReferralController.initialize(null);
            System.assertEquals(true, Boolean.valueOf(((Map<String, Object>) JSON.deserializeUntyped(String.valueOf(oppRecord.data))).get('isValid')));
        
            String oppResult1 = RetroactiveReferralController.isValidForWebService(lstOpportunity[1].Id);
            String oppResult2 = RetroactiveReferralController.isValidForWebService(lstOpportunity[2].Id);
            String oppResult3 = RetroactiveReferralController.isValidForWebService(lstOpportunity[3].Id);
            
            System.assertEquals(true, Boolean.valueOf(((Map<String, Object>) JSON.deserializeUntyped(oppResult1)).get('isValid')));
            System.assertEquals(false, Boolean.valueOf(((Map<String, Object>) JSON.deserializeUntyped(oppResult2)).get('isValid')));
            System.assertEquals(false, Boolean.valueOf(((Map<String, Object>) JSON.deserializeUntyped(oppResult3)).get('isValid')));
        }
    }
    
    /*****************************************************************************************************************************************
        Author              :   Pragalbha Mahajan
        Description         :   This method tests UpdateReferrerOnOpportunity method
        Created Date        :   01 November 2018
        Issue No            :   ST-2858
    ******************************************************************************************************************************************/
    public static testMethod void testUpdateReferrerOnOpportunity(){
        List<Opportunity> lstOpportunity = [SELECT Id FROM Opportunity];
        List<Contact> lstContact = [SELECT Id, Type__c FROM Contact];
        List<Account> lstAccounts = [SELECT id FROM Account];
        List<Billing_Account__c> lstBillingAccount = [SELECT Id, Primary_Member__c FROM Billing_Account__c];
        
        DatabaseResult oppRecord = RetroactiveReferralController.updateReferrerOnOpportunity(lstOpportunity[0].Id, lstContact[0], lstBillingAccount[0].Id, lstAccounts[0].Id, 'Confidential Referral');
        Opportunity UpdatedOpp = [SELECT Id, Name, Billing_Account__c, Contract_Signed_On__c, Building__r.UUID__c, RecordType.Name, LeadSource, Referral_Type__c, Referrer__r.Name ,Referrer__r.Email ,Referrer__r.Phone ,Referrer__r.Type__c, Primary_Member__r.Email, Primary_Member__r.Name, Referrer__c FROM Opportunity WHERE Id =: lstOpportunity[0].Id];         
        System.assertEquals(lstBillingAccount[0].Id, UpdatedOpp.Billing_Account__c);
        System.assertEquals(lstBillingAccount[0].Primary_Member__c, UpdatedOpp.Primary_Member__c);
        System.assertEquals(lstContact[0].Id, UpdatedOpp.Referrer__c);
        System.assertEquals('Referral', UpdatedOpp.LeadSource);
    }
    
    /*****************************************************************************************************************************************
        Author              :   Pragalbha Mahajan
        Description         :   This method tests UpdateReferrerOnOpportunity method
        Created Date        :   01 November 2018
        Issue No            :   ST-2858
    ******************************************************************************************************************************************/
    public static testMethod void testNullConditionInUpdateReferrerOnOpportunity(){
        try{
            List<Opportunity> lstOpportunity = [SELECT Id FROM Opportunity];
            List<Contact> lstContact = [SELECT Id, Type__c FROM Contact];
            List<Account> lstAccounts = [SELECT id FROM Account];
            List<Billing_Account__c> lstBillingAccount = [SELECT Id, Primary_Member__c FROM Billing_Account__c];
            
            DatabaseResult oppRecordNull = RetroactiveReferralController.updateReferrerOnOpportunity(null, lstContact[0], lstBillingAccount[0].Id, lstAccounts[0].Id, 'Confidential Referral');
        }catch(Exception pEx) {
            System.assertEquals('Opportunity Id is not present', pEx.getMessage());
        }
    }
    
    /*****************************************************************************************************************************************
        Author              :   Pragalbha Mahajan
        Description         :   This method tests SaveConAccRecords method
        Created Date        :   01 November 2018
        Issue No            :   ST-2858
    ******************************************************************************************************************************************/
    public static testMethod void testSaveConAccRecords(){
        List<Billing_Account__c> lstBillingAccount = new List<Billing_Account__c>();
        boolean createReferral = true;
        List<sObject> lstSobject = new List<sObject>();
        List<Account> lstAccount = [SELECT Id, Name FROM Account];
        List<Contact> lstContact = [SELECT Id, FirstName, LastName, Email, Billing_Account__c, AccountId FROM Contact];
        lstBillingAccount.add(new Billing_Account__c(Name = 'Test Billing Account1'));
        //In Update Context 
        lstSobject.add(lstContact[0]);
        lstSobject.add(lstAccount[0]);
        lstSobject.add(lstBillingAccount[0]);
        DatabaseResult response = RetroactiveReferralController.saveConAccRecords(lstSobject);
        Map<String, sObject> response1 = (Map<String, sObject>)JSON.deserializeStrict(JSON.serialize(response.data), Map<String, sObject>.class);
        System.assert(String.isNotBlank(response1.get('billAcc').Id));
        System.assert(String.isNotBlank(response1.get('contact').Id));
        lstBillingAccount.clear();
        lstSobject.clear();
        Contact con = new Contact(LastName = 'tstContact', AccountId = lstAccount[0].Id);
        lstBillingAccount.add(new Billing_Account__c(Name = 'Test Billing Account2'));
        lstSobject.add(con);
        lstSobject.add(lstAccount[0]);
        lstSobject.add(lstBillingAccount[0]);
        DatabaseResult response2 = RetroactiveReferralController.saveConAccRecords(lstSobject);
        Map<String, sObject> response3 = (Map<String, sObject>)JSON.deserializeStrict(JSON.serialize(response2.data), Map<String, sObject>.class);
        System.assert(String.isNotBlank(response3.get('billAcc').Id));
        System.assert(String.isNotBlank(response3.get('contact').Id));
    }
}