objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <description>This is Picklist which Contains three values
1. Org : It is Main account in hierarchy which is Parent Account of Sales And Bill.
2. Sales: One Sales Account may contain multiple Bill Or Sales Account and It is Under Org Account in hierarchy
3. Bill: Bill Account is under Sales or Org. It never child of Bill Account.
4. ' '(Blank) : It is like Bill type which is under Sales or Org.</description>
        <inlineHelpText>This Picklist is used to determine the account type.</inlineHelpText>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Org</fullName>
                    <default>true</default>
                    <label>Org</label>
                </value>
                <value>
                    <fullName>Sales</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Interested_in_Number_of_Desks__c</fullName>
        <label>Interested in Number of Desk(s)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Full_Time_Employees__c</fullName>
        <label>Number of Full Time Employees</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Parent_Account__c</fullName>
        <formula>CASESAFEID(ParentId)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Parent Account(Pipeline Reporting)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Paperwork will be sent to the primary member on the ACCOUNT</inlineHelpText>
        <label>Main Contact</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.Account.Id</field>
                <operation>equals</operation>
                <valueField>$Source.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Billing_Account__c.object
<CustomObject>
    <fields>
        <fullName>Number_of_Full_Time_Employees__c</fullName>
        <label>Number of Full Time Employees</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Parent_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is lookup to the Parent Account</description>
        <inlineHelpText>This is lookup to the Parent Account</inlineHelpText>
        <label>Parent Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the main point of contact for the Billing Account.</description>
        <inlineHelpText>Person at the member company responsible for managing the membership: invoices, key card replacements, MENA account manager tab. Responsible for signing legal agreement (unless an authorized signatory is designated).</inlineHelpText>
        <label>Primary Member</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>All Billing account is moved to this Billing Account object it help Sales people to identify Org and Sales account easily and reduce the clutter of 100s of Accounts with same name.</description>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <formula>text(Account.Type)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Members</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Interested_in_Number_of_Desks__c</fullName>
        <label>Interested in Number of Desk(s)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Full_Time_Employees__c</fullName>
        <label>Number of Full Time Employees</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Primary_Member__c</fullName>
        <formula>if( Billing_Account__r.Primary_Member__r.Id =  Id , "Yes","No")</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Primary Member</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This is the latest status coming from Space systems through Jitterbunny of the individual member. This tells us if the user is active or not.</description>
        <inlineHelpText>This is accurate status of a contact if it is an active member of our products or not.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>active</fullName>
                </value>
                <value>
                    <fullName>inactive</fullName>
                    <default>true</default>
                    <label>inactive</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/NewOrganizationControllerTest.cls
/************************************************************************************************************************************
    Author      :  Pragalbha Mahajan    
    Description :  This class contain all aura methods related new Account flow.
    
    History     :
    ----------------------------------------------------------------------------------------------------------------------------------
    VERSION     DATE                AUTHOR          		DETAIL
     1          3 Sept 2018       	Pragalbha Mahajan    	Initial Developement
**************************************************************************************************************************************/

@isTest
public class NewOrganizationControllerTest {
    @TestSetup
    static void initData(){
        SalesConsoleSettings.createSettings();
        Profile testProfile = [SELECT Id FROM Profile WHERE Name='System Administrator'];	
        Profile testProfile1 = [SELECT Id FROM Profile WHERE Name='WeWork Enterprise Solutions'];
        List<User> lstUsers = new List<User>();
        User tstUser = new user(alias = 'test123', email='test123@noemail.com', 
                                emailencodingkey='UTF-8', firstName='Chris', lastname='Bonapart', languagelocalekey='en_US',
                                localesidkey='en_IN', profileid = testProfile.Id, country='India',
                                timezonesidkey='Asia/Kolkata', username='testchris_g@noemail.com'); 
        lstUsers.add(tstUser);
        
        User tstUser1 = new user(alias = 'test111', email='test111@noemail.com', 
                                emailencodingkey='UTF-8', firstName='John', lastname='Bonapart', languagelocalekey='en_US',
                                localesidkey='en_IN', profileid = testProfile1.Id, country='India',
                                timezonesidkey='Asia/Kolkata', username='johnBonapart_g@noemail.com'); 
        lstUsers.add(tstUser1);
        TestingUtility.insertListWithAssert(lstUsers);
        
        Contact contactRec = new Contact(FirstName = 'John1', LastName = 'Smith1', Email = 'testContact1@example.com', Status__c = 'active');
        TestingUtility.insertWithAssert(contactRec);
        Account accRec = new Account(Name = 'strAccount', Number_of_Full_Time_Employees__c = 1000, Website = 'testaccount.in', Interested_in_Number_of_Desks__c = 100, Phone = '9845623584');
        TestingUtility.insertWithAssert(accRec);
        Billing_Account__c billingAcc = new Billing_Account__c(Name = 'tstBillingAcc');
        TestingUtility.insertWithAssert(billingAcc);
    }
    /************************************************************************************************************************************
        Author              :   Pragalbha Mahajan
        Description         :   This method tests Account flow for user without permission set.
        Last Modified Date  :   4 Sept 2018
		Issue No			:   ST-2731
    **************************************************************************************************************************************/
    public static testMethod void verifyAccountFlowForUserWithOutPermission(){
        List<User> lstUser = [SELECT Id, Name, UserName, ProfileId, Profile.Name  FROM User WHERE UserName = 'johnBonapart_g@noemail.com'];
        System.runAs(lstUser[0]){
			DatabaseResult result = NewOrganizationController.getNewOrganizationData();  
            NewOrganizationController.NewOrganizationSettingWrapper permission = (NewOrganizationController.NewOrganizationSettingWrapper) result.data;
            System.assertEquals(false, permission.isUserCreateEnterpriseOrg);
            System.assertEquals(false, permission.isUserCreateOrg);
        }
    }
    /************************************************************************************************************************************
        Author              :   Pragalbha Mahajan
        Description         :   This method tests Account flow for user with permission set.
        Last Modified Date  :   4 Sept 2018
		Issue No			:   ST-2731
    **************************************************************************************************************************************/
    public static testMethod void verifyAccountFlowForUserWithPermissionSet(){
        List<User> lstUser = [SELECT Id,Name,UserName  FROM User WHERE UserName = 'testchris_g@noemail.com'];
        PermissionSet objPermission = [SELECT Id, Name, ProfileId FROM PermissionSet WHERE Name = 'Can_Create_Organization'];
        insert new PermissionSetAssignment(AssigneeId = lstUser[0].id, PermissionSetId = objPermission.Id);
        System.runAs(lstUser[0]){
			DatabaseResult result = NewOrganizationController.getNewOrganizationData();  
            NewOrganizationController.NewOrganizationSettingWrapper permission = (NewOrganizationController.NewOrganizationSettingWrapper) result.data;
            System.assertEquals(true, permission.isUserCreateEnterpriseOrg);
            System.assertEquals(true, permission.isUserCreateOrg);
        }
    }
    /************************************************************************************************************************************
        Author              :   Pragalbha Mahajan
        Description         :   This method tests CreateNewOrgAndContact.
        Last Modified Date  :   4 Sept 2018
		Issue No			: 	ST-2729
    **************************************************************************************************************************************/
    public static testMethod void verifyCreateNewOrgAndContact(){
        Account accRec = new Account(Name = 'strAccount1', Number_of_Full_Time_Employees__c = 1000, Website = 'testaccount1.in', Interested_in_Number_of_Desks__c = 100, Phone = '98456235644');
        Contact contactRec = new Contact(FirstName = 'John2', LastName = 'Smith2', Email = 'testContact2@example.com', Status__c = 'active');
        
        DatabaseResult result = NewOrganizationController.createNewOrganization(new List<sObject>{accRec, contactRec});
        List<Contact> lstContacts = [SELECT Id, Name, Email FROM Contact WHERE Email = 'testContact2@example.com'];
        System.assertNotEquals(lstContacts[0].Id, null);
        List<Account> lstAccounts = [SELECT Id, Name, RecordType.Name, Primary_Member__c, Account_Type__c FROM Account WHERE Website = 'testaccount1.in'];
        System.assertNotEquals(lstAccounts[0].Id, null);
        System.assertEquals(lstAccounts[0].Primary_Member__c, lstContacts[0].Id);
    }
    
    /************************************************************************************************************************************
        Author              :   Pragalbha Mahajan
        Description         :   This method tests CreateNewOrg with existing contact.
        Last Modified Date  :   4 Sept 2018
		Issue No			: 	ST-2729
    **************************************************************************************************************************************/
    public static testMethod void verifyCreateNewOrgWithExistingContact(){
        try{
            Account accRec = new Account(Name = 'strAccount1', Number_of_Full_Time_Employees__c = 1000, Website = 'testaccount1.in', Interested_in_Number_of_Desks__c = 100, Phone = '9845623645');
            List<Contact> lstContacts = [SELECT Id, Name, Email, AccountId FROM Contact WHERE Email = 'testContact1@example.com'];
            List<Billing_Account__c> lstBillingAccount = [SELECT Id, Name, Primary_Member__c, Parent_Account__c FROM Billing_Account__c];
            DatabaseResult result = NewOrganizationController.createNewOrganization(new List<sObject>{accRec, lstContacts[0], lstBillingAccount[0]});
            List<Account> lstAccounts = [SELECT Id, Name, RecordType.Name, Primary_Member__c, Account_Type__c FROM Account WHERE Website = 'testaccount1.in'];
            System.assertEquals(lstContacts[0].AccountId, lstAccounts[0].Id);
            
            DatabaseResult result1 = NewOrganizationController.createNewOrganization(new List<sObject>{lstContacts[0]});
            Account acc = (Account) result1.data;
            System.assertEquals(acc, null);
        }catch(Exception exc){
            System.assertNotEquals(null, exc);
        }
    }
    /************************************************************************************************************************************
        Author              :   Pragalbha Mahajan
        Description         :   This method tests CreateNewOrg with existing contact and billing account.
        Last Modified Date  :   4 Sept 2018
		Issue No			: 	ST-2729
    **************************************************************************************************************************************/
    public static testMethod void verifyCreateNewOrgWithExistingContactAndBillingAccount(){
        try{
            Account accRec = new Account(Name = 'strAccount1', Number_of_Full_Time_Employees__c = 1000, Website = 'testaccount1.in', Interested_in_Number_of_Desks__c = 100, Phone = '9845623645');
            List<Contact> lstContacts = [SELECT Id, Name, Email, AccountId FROM Contact];
            List<Billing_Account__c> lstBillingAccount = [SELECT Id, Name, Primary_Member__c, Parent_Account__c FROM Billing_Account__c];
            DatabaseResult result = NewOrganizationController.createNewOrganization(new List<sObject>{accRec, lstContacts[0]});
            List<Account> lstAccounts1 = [SELECT Id, Name, RecordType.Name, Primary_Member__c, Account_Type__c FROM Account WHERE Website = 'testaccount1.in'];
            System.assertEquals(lstContacts[0].AccountId, lstAccounts1[0].Id);
        }catch(Exception exc){
            System.assertNotEquals(null, exc);
        }
    }
    
    /************************************************************************************************************************************
        Author              :   Pragalbha Mahajan
        Description         :   This method tests send organization request.
        Last Modified Date  :   4 Sept 2018
		Issue No			: 	ST-2729
    **************************************************************************************************************************************/
    public static testMethod void verifySendOrgRequest(){
        try{
            Test.startTest();
            Contact contactRec = new Contact(FirstName = 'John', LastName = 'Bonapart', Email = 'testBonapart@example.com', Status__c = 'active');
            Account accRec = new Account(Name = 'TestOrg', Number_of_Full_Time_Employees__c = 1000, Website = 'www.testorg.com', Interested_in_Number_of_Desks__c = 100, Phone = '9845623645');
            System.assertEquals(false, RequestNewOrganizationController.sendNewOrganizationRequest(new Account()).data, 'when account is null');
            System.assertEquals(true, NewOrganizationController.sendNewOrganizationRequest(new List<sObject>{accRec, contactRec}).data);
            System.assertEquals(1,Limits.getEmailInvocations(), 'email count');
            Test.stopTest();
            System.assertEquals(null, NewOrganizationController.sendNewOrganizationRequest(new List<sObject>{contactRec}).data);
        } catch(Exception exc){
            System.assertNotEquals(null, exc);
        }
    }
}