objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <description>This is Picklist which Contains three values
1. Org : It is Main account in hierarchy which is Parent Account of Sales And Bill.
2. Sales: One Sales Account may contain multiple Bill Or Sales Account and It is Under Org Account in hierarchy
3. Bill: Bill Account is under Sales or Org. It never child of Bill Account.
4. ' '(Blank) : It is like Bill type which is under Sales or Org.</description>
        <inlineHelpText>This Picklist is used to determine the account type.</inlineHelpText>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Org</fullName>
                    <default>true</default>
                    <label>Org</label>
                </value>
                <value>
                    <fullName>Sales</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Parent_Org__c</fullName>
        <description>Shows the ID of the first Org found in the multi-level hierarchy.</description>
        <formula>IF( OR( ISPICKVAL(Account_Type__c, 'Org'),ISBLANK(Parent.Id)),Id,IF(OR(ISPICKVAL(Parent.Account_Type__c, 'Org'),ISBLANK(Parent.Parent.Id)),Parent.Id,IF(OR(ISPICKVAL(Parent.Parent.Account_Type__c, 'Org'),ISBLANK(Parent.Parent.Parent.Id)), Parent.Parent.Id,IF(OR(ISPICKVAL(Parent.Parent.Parent.Account_Type__c, 'Org'),ISBLANK(Parent.Parent.Parent.Parent.Id)), Parent.Parent.Parent.Id,IF(OR(ISPICKVAL(Parent.Parent.Parent.Parent.Account_Type__c, 'Org'),ISBLANK(Parent.Parent.Parent.Parent.Parent.Id)), Parent.Parent.Parent.Parent.Id,Parent.Parent.Parent.Parent.Parent.Id)))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Shows the ID of the first Org found in the multi-level hierarchy.</inlineHelpText>
        <label>Parent Org</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/AccountTypeConversionController.cls
/************************************************************************************************************************************
    Author      :   Prashant Mane
    Description :   This controller class for Account Type Conversion functionality.
    ----------------------------------------------------------------------------------------------------------------------------------
    VERSION     DATE                AUTHOR                  DETAIL
    1           28 Aug 2018         Prashant Mane           Initial Developement
**************************************************************************************************************************************/
public without sharing class AccountTypeConversionController {
    public static Boolean isInvoker = false;
    static {
        isInvoker = ApexDebugLog.registerRootInvoker(ApexDebugLog.InvokerType.AURA, 'AccountTypeConversionController' + 'getsObjectPrefix', ApexDebugLog.InvokerType.AURA);    	
    }
    
	/************************************************************************************************************************************
        Author        	:   Prashant Mane
		Description   	:   This method is used to get AccountTypeConversion data
        Created Date  	:   28 Aug 2018
        Issue No    	:   ST-2715
    **************************************************************************************************************************************/
    @AuraEnabled
    public static DatabaseResult changeAccountType(Account objAccount) {
        Savepoint sp = Database.setSavepoint(); 
        try {
            List<Account> lstAccountsToUpdate = new List<Account>();
            lstAccountsToUpdate.add(objAccount);
            for(Account objChildAccount : [SELECT Id, Name, ParentId, Parent_Org__c FROM Account WHERE Account_Type__c = 'Org' AND ParentId =: objAccount.Id]) {
                if(objAccount.Account_Type__c == 'Sales') {
                    objChildAccount.ParentId = objAccount.ParentId;
                    lstAccountsToUpdate.add(objChildAccount);
                }
            }
            Database.update(lstAccountsToUpdate);
            return new DatabaseResult(JSON.serialize(objAccount));
        }catch(Exception pEx){
            if(sp != null){
                Database.rollback(sp);
            }
            ApexDebugLog.logException(pEx, JSON.serialize(objAccount), 'AccountTypeConversionController', 'changeAccountType');                      
            return new DatabaseResult(pEx);  
        } 
    }    
}