objects/Apex_Debug_Log__c.object
<CustomObject>
    <fields>
        <fullName>ApexLogId__c</fullName>
        <label>ApexLogId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Apex_Class__c</fullName>
        <label>Apex Class</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ErrorLineNumber__c</fullName>
        <label>ErrorLineNumber</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ExceptionTypeName__c</fullName>
        <label>ExceptionTypeName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Login_UserId__c</fullName>
        <label>Login UserId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Login_User_ProfileId__c</fullName>
        <label>Login User ProfileId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Method__c</fullName>
        <label>Method</label>
        <length>180</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Id__c</fullName>
        <label>Record</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ReplayId__c</fullName>
        <label>ReplayId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stack_Trace__c</fullName>
        <label>Stack Trace</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Apex Debug Log</label>
    <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Apex Debug Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Debug Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/LogException__e.object
<CustomObject>
    <fields>
        <fullName>Apex_Class__c</fullName>
        <label>Apex Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ErrorLineNumber__c</fullName>
        <label>ErrorLineNumber</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ExceptionTypeName__c</fullName>
        <label>ExceptionTypeName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Exception_Type__c</fullName>
        <label>Exception Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Login_UserId__c</fullName>
        <label>Login UserId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Login_User_ProfileId__c</fullName>
        <label>Login User ProfileId</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Method__c</fullName>
        <label>Method</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record__c</fullName>
        <label>Record</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Stack_Trace__c</fullName>
        <label>Stack Trace</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>LogException</label>
    <pluralLabel>LogExceptions</pluralLabel>
</CustomObject>

classes/LogExceptionTriggerHandlerTest.cls
/************************************************************************************************************************************
    Author 		: Krishana Tupe
    Description : This class is used to test LogExceptionTriggerHandler

    History:
	----------------------------------------------------------------------------------------------------------------------------------
	VERSION		DATE				AUTHOR					DETAIL
    1.0			02 May 2018			Krishana Tupe			Initial Developement.
**************************************************************************************************************************************/
@isTest
public class LogExceptionTriggerHandlerTest { 
        
    /************************************************************************************************************************************
        Author 				: 	Krishana Tupe
        Description 		: 	This method is used verify the functionality of insert platform event and get apex debug log record.
        Created Date		:	03 May 2018
        Last Modified By 	: 	Krishana Tupe
        Last Modified Date  : 	03 May 2018
    **********************************************************************************************************************************************/
    public testmethod static void verifyApexDebugLogsExceptionUsingPlatformEvent(){   
        try{
            Test.startTest();
            LogException__e newEvent = new LogException__e(
                Apex_Class__c = 'strClassName',
                ErrorLineNumber__c = 5,
                Exception_Type__c = 'Error',
                ExceptionTypeName__c = 'ex.getTypeName()', 
                Message__c = 'ex.getMessage()',
                Method__c = 'strMethodName',
                Record__c = 'listRecordIds',
                Login_User_ProfileId__c =  UserInfo.getProfileId(),
                Login_UserId__c         =  UserInfo.getUserId(),            
                Stack_Trace__c = 'ex.getStackTraceString()'            
            );
            // Call method to publish events
            Database.SaveResult sr = EventBus.publish(newEvent);
            Debug.log('Result of publish Event==>'+sr); 
            Test.stopTest();
            
            List<Apex_Debug_Log__c> lstApexDebugLogs = [Select Id,Apex_Class__c,ApexLogId__c,Message__c,Method__c,Record_Id__c,	Stack_Trace__c,Login_UserId__c,Login_User_ProfileId__c From Apex_Debug_Log__c];
            Debug.log('lstApexDebugLogs==>'+lstApexDebugLogs);
            System.assert(lstApexDebugLogs != null);
            System.assertEquals('strClassName',lstApexDebugLogs[0].Apex_Class__c);
            System.assertEquals('ex.getMessage()',lstApexDebugLogs[0].Message__c	);
            System.assertEquals('ex.getStackTraceString()',lstApexDebugLogs[0].Stack_Trace__c);
            System.assertEquals('strMethodName',lstApexDebugLogs[0].Method__c);
            System.assertEquals(UserInfo.getUserId(),lstApexDebugLogs[0].Login_UserId__c);
            System.assertEquals(UserInfo.getProfileId(),lstApexDebugLogs[0].Login_User_ProfileId__c); 
            
        }catch(Exception pEx) { 
            ApexDebugLog.logException(pEx,'Test Exception', 'LogExceptionTriggerHandlerTest', 'verifyApexDebugLogsExceptionUsingPlatformEvent');            
            throw new ApexDebugLog.ApexLogCustomException('Exception thrown from LogExceptionTriggerHandlerTest.verifyApexDebugLogsExceptionUsingPlatformEvent() : '+pEx);
        }
    }  
 /************************************************************************************************************************************
        Author 				: 	Krishana Tupe
        Description 		: 	This method is used to create custom exception.
        Created Date		:	29 May 2018
        Last Modified By 	: 	Krishana Tupe
        Last Modified Date  : 	29 May 2018
    **********************************************************************************************************************************************/ 
    public static void getException(){
        try{
            insert new Lead();
        }catch(Exception pEx){           
            Test.startTest();
            ApexDebugLog.logException(pEx,'Test Exception', 'LogExceptionTriggerHandlerTest', 'getException');
            List<Apex_Debug_Log__c> lstApexDebugLogs = [Select Id,ReplayId__c,Apex_Class__c,ApexLogId__c,Message__c,Method__c,Record_Id__c,	Stack_Trace__c,Login_UserId__c,Login_User_ProfileId__c From Apex_Debug_Log__c ORDER BY CreatedDate DESC];            
            Test.stopTest();
            throw new ApexDebugLog.ApexLogCustomException('Exception thrown from LogExceptionTriggerHandlerTest.getException() : '+pEx);  
        }
    }
    
   /************************************************************************************************************************************
        Author 				: 	Krishana Tupe
        Description 		: 	This method is used verify the log exception functionality.
        Created Date		:	29 May 2018
        Last Modified By 	: 	Krishana Tupe
        Last Modified Date  : 	29 May 2018
    **********************************************************************************************************************************************/ 
    public testmethod static void verifyApexDebugLogsException(){
        try{
            getException();
        }catch(Exception pEx){
            Debug.log('pEx in verifyApexDebugLogsException==>'+pEx);             
           List<Apex_Debug_Log__c> lstApexDebugLogs = [Select Id,ReplayId__c,Apex_Class__c,ApexLogId__c,Message__c,Method__c,Record_Id__c,	Stack_Trace__c,Login_UserId__c,Login_User_ProfileId__c From Apex_Debug_Log__c ORDER BY CreatedDate DESC];
            Debug.log('lstApexDebugLogs==>'+lstApexDebugLogs);
            System.assert(lstApexDebugLogs != null);
            //System.assert(String.isNotBlank(String.valueOf(lstApexDebugLogs[0].ReplayId__c)));
            System.assertEquals('LogExceptionTriggerHandlerTest',lstApexDebugLogs[0].Apex_Class__c);            
            System.assertEquals(pEx.getMessage(),'Exception thrown from LogExceptionTriggerHandlerTest.getException() : System.DmlException: '+lstApexDebugLogs[0].Message__c	);
            System.assertEquals('getException',lstApexDebugLogs[0].Method__c);
            System.assertEquals(UserInfo.getUserId(),lstApexDebugLogs[0].Login_UserId__c);
            System.assertEquals(UserInfo.getProfileId(),lstApexDebugLogs[0].Login_User_ProfileId__c); 
        }
    }
    
}