objects/Apex_Debug_Log__c.object
<CustomObject>
    <fields>
        <fullName>ApexLogId__c</fullName>
        <label>ApexLogId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Apex_Class__c</fullName>
        <label>Apex Class</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ErrorLineNumber__c</fullName>
        <label>ErrorLineNumber</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ExceptionTypeName__c</fullName>
        <label>ExceptionTypeName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>InstanceName__c</fullName>
        <label>InstanceName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Login_UserId__c</fullName>
        <label>Login UserId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Login_User_ProfileId__c</fullName>
        <label>Login User ProfileId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Method__c</fullName>
        <label>Method</label>
        <length>180</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Id__c</fullName>
        <label>Record</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ReplayId__c</fullName>
        <label>ReplayId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RollBar_Integration_status__c</fullName>
        <label>RollBar Integration status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>200</fullName>
                    <color>#33CC00</color>
                    <label>Operation was completed successfully</label>
                </value>
                <value>
                    <fullName>400</fullName>
                    <color>#78C953</color>
                    <label>The request was malformed and could not be parsed.</label>
                </value>
                <value>
                    <fullName>403</fullName>
                    <color>#E27001</color>
                    <label>Access token was missing, invalid, or does not have the necessary permissions.</label>
                </value>
                <value>
                    <fullName>404</fullName>
                    <color>#A845DC</color>
                    <label>The requested resource was not found. This response will be returned if the URL is entirely invalid (i.e. /asdf), or if it is a URL that could be valid but is referencing something that does not exist (i.e. /item/12345).</label>
                </value>
                <value>
                    <fullName>413</fullName>
                    <color>#F3D904</color>
                    <label>The request exceeded the maximum size of 128KB.</label>
                </value>
                <value>
                    <fullName>422</fullName>
                    <color>#A53711</color>
                    <label>The request was parseable (i.e. valid JSON), but some parameters were missing or otherwise invalid.</label>
                </value>
                <value>
                    <fullName>429</fullName>
                    <color>#66E9BD</color>
                    <label>If rate limiting is enabled for your access token, this return code signifies that the rate limit has been reached and the item was not processed.</label>
                </value>
                <value>
                    <fullName>401</fullName>
                    <color>#0B24BE</color>
                    <label>Bad Token</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stack_Trace__c</fullName>
        <label>Stack Trace</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Fixed, Pending Deployment</fullName>
                </value>
                <value>
                    <fullName>Investigated</fullName>
                    <label>Investigation Complete</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <label>Investigation In Progress</label>
                </value>
                <value>
                    <fullName>No Fix Required</fullName>
                </value>
                <value>
                    <fullName>Resolved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Exception Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Warning</fullName>
                </value>
                <value>
                    <fullName>Info</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Apex Debug Log</label>
    <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Apex Debug Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Debug Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Integration_Data__mdt.object
<CustomObject>
    <fields>
        <fullName>HoursFilter__c</fullName>
        <label>HoursFilter</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Method__c</fullName>
        <label>Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>POST</fullName>
                    <default>true</default>
                    <label>POST</label>
                </value>
                <value>
                    <fullName>Delete</fullName>
                </value>
                <value>
                    <fullName>GET</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Integration Data</label>
    <pluralLabel>Integrations Data</pluralLabel>
</CustomObject>

classes/QueueRollbarItemSubmit.cls
/******************************************************************************************************************** 
Name              : QueueRollbarItemSubmit.cls 
Description       : Future class for posting requst to rollbar.

Revision History  :-
Created/Modified by         Created/Modified Date       Requested by         Technical Design Proposal
---------------------------------------------------------------------------------------------------------------------
1. Rashad Saeed (Creator)      31 DEC 2018              WeWork                 SF - Rollbar Integration  Google Doc  
---------------------------------------------------------------------------------------------------------------------
*********************************************************************************************************************/
public class QueueRollbarItemSubmit implements Queueable, Database.AllowsCallouts {
   private RollbarItem item;
    private String project;
    Private List <Apex_Debug_Log__c >Alog;
    Private Apex_Debug_Log__c apexLog;
    public QueueRollbarItemSubmit() {
        List <AsyncApexJob> AsyncApexJob  = [SELECT  Id , Status  FROM AsyncApexJob WHERE ApexClassId IN
                                 (SELECT Id from ApexClass WHERE NamespacePrefix = null
                                  AND Name = 'QueueRollbarItemSubmit') and Status ='Queued' ]; 
        if (!AsyncApexJob.isEmpty())
            System.abortJob(AsyncApexJob[0].id);
        Integer HoursFilter = (Integer)[SELECT HoursFilter__c FROM Integration_Data__mdt WHERE DeveloperName = :'RollBar' LIMIT 1].HoursFilter__c; 
        if (HoursFilter == null)
            HoursFilter = 1; 
        DateTime LastNHours = System.Now().addHours(-HoursFilter);
        this.Alog = [select Id ,Name,Apex_Class__c ,
                     ApexLogId__c ,ErrorLineNumber__c ,
                     Type__c ,ExceptionTypeName__c ,
                     InstanceName__c ,Login_UserId__c ,
                     Login_User_ProfileId__c ,Message__c ,
                     Method__c ,Record_Id__c ,ReplayId__c ,
                     Stack_Trace__c ,Status__c 
                     from Apex_Debug_Log__c
                     where RollBar_Integration_status__c  = NULL
                     and CreatedDate >=: LastNHours
                     limit 1
                    ];
        if (!Alog.isEmpty()) {
            this.item = new RollbarItem(Alog[0]);
            this.project = 'RollBar';
            this.apexLog =Alog[0]; 
        }
    }
    public void execute(QueueableContext qc) {
        if (!Alog.isEmpty()){
        	apexLog.RollBar_Integration_status__c = String.ValueOf (Rollbar.submitItem(item, project).getStatusCode());
            Update apexLog;
            system.enqueueJob(new QueueRollbarItemSubmit());
        }
    }
}