objects/Apex_Debug_Log__c.object
<CustomObject>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Fixed, Pending Deployment</fullName>
                </value>
                <value>
                    <fullName>Investigated</fullName>
                    <label>Investigation Complete</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <label>Investigation In Progress</label>
                </value>
                <value>
                    <fullName>No Fix Required</fullName>
                </value>
                <value>
                    <fullName>Resolved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Apex Debug Log</label>
    <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Apex Debug Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Debug Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Setting__c.object
<CustomObject>
    <fields>
        <fullName>Data__c</fullName>
        <description>This should contain JSON formatted data for each setting record. The JSON object will vary from setting to setting.</description>
        <label>Data</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <description>We are creating object for Settings instead of using Custom Object because we need to store larger size of data which Custom Setting does not support. e.g. Mapping of Fields from Contact to Lead etc. which may go beyond 255 characters. 

It will not use caching but give more flexibility for coding.</description>
    <label>Sales Console Setting</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Console Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PurgeResolvedExceptionBatch.cls
/* Created By : Krishana Tupe
* Date : 21-Dec-2017
* Issue : ST-1737
* Comment : Delete all "Resolved" exception that are created before 30 days.
*/
global class PurgeResolvedExceptionBatch  implements Database.Batchable<SObject>,Schedulable,Database.Stateful {    
    Setting__c purgeResolvedExceptionSetting = Settings.get('PurgeResolvedException');
    purgeResolvedExceptionSettings objSetting = new purgeResolvedExceptionSettings();
    Map<String,String> mapPurgeSetting = new Map<String,String>();
    List<String> lstEmailAddresses = new List<String>();
    static Set<String> setMessages = new Set<String>();
    static String Status;
    static String query;
    global PurgeResolvedExceptionBatch(){  
        if(purgeResolvedExceptionSetting!=null){
            objSetting = (purgeResolvedExceptionSettings)JSON.deserialize(purgeResolvedExceptionSetting.Data__c.toLowerCase(),purgeResolvedExceptionSettings.class);  
            mapPurgeSetting = objSetting.criterias;
            lstEmailAddresses = objSetting.emails;
            if(objSetting.messages!=null){
                setMessages = objSetting.messages;
            }
            Status = mapPurgeSetting.get('status') != null ? mapPurgeSetting.get('status') : 'resolved';
        } 
    }
    global void execute(SchedulableContext SC) {
        PurgeResolvedExceptionBatch purgeExceptionBatch = new PurgeResolvedExceptionBatch();
        //For daily 11:59 PM
        String CRON_EXP = '0 59 23 * * ? *';
        String jobId = System.schedule('Purge Resolved Exception Batch',CRON_EXP,purgeExceptionBatch);       
    } 
    
    global Database.QueryLocator start(Database.BatchableContext context) {        
        Integer days = mapPurgeSetting.get('no of days before') != null ? Integer.valueOf(mapPurgeSetting.get('no of days before')) : 30;
        DateTime lastDate = System.now().addDays(-days);
        Debug.log('lastDate==>'+lastDate);
        Debug.log('days==>'+days);
        Debug.log('Status==>'+Status);
        debug.log('objSetting==>'+objSetting);
        if(!setMessages.isEmpty()){
            query = 'SELECT Id,Name,Status__c,CreatedDate,Message__c FROM Apex_Debug_Log__c WHERE Message__c IN : setMessages AND createdDate < : lastDate AND Status__c =: Status ORDER BY CreatedDate DESC';  
        }else{
            query = 'SELECT Id,Name,Status__c,CreatedDate,Message__c FROM Apex_Debug_Log__c WHERE createdDate < : lastDate AND Status__c =: Status ORDER BY CreatedDate DESC'; 
        }        
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext context, List<Apex_Debug_Log__c> records) {
        debug.log('Records==>'+records);
        List<Id> lstApexDebugLogIds = new List<Id>();        
        for(Apex_Debug_Log__c logRecord :records){  
            debug.log('logRecord status==>'+(String)logRecord.Status__c.toLowerCase());
            debug.log('Setting status==>'+Status);
            if(!setMessages.isEmpty()){
                if((String)logRecord.Status__c.toLowerCase() == Status && setMessages.contains(((String)logRecord.Message__c.toLowerCase()))){                
                    lstApexDebugLogIds.add(logRecord.Id);
                }    
            }else{
                if((String)logRecord.Status__c.toLowerCase() == Status ){                
                    lstApexDebugLogIds.add(logRecord.Id);
                }   
            }           
        }
        debug.log('lstApexDebugLogIds To Delete==>'+lstApexDebugLogIds);
        if(lstApexDebugLogIds.size() > 0){
            Database.delete(lstApexDebugLogIds,FALSE);            
        }
    }	
    global void finish(Database.BatchableContext context){
       if(lstEmailAddresses.size()>0){
            AsyncApexJob a = [SELECT Id, Status,ExtendedStatus,NumberOfErrors, JobItemsProcessed,TotalJobItems, CreatedBy.Email FROM AsyncApexJob WHERE Id =:context.getJobId()];
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            String[] toAddresses =lstEmailAddresses;
            mail.setToAddresses(toAddresses);
            mail.setSubject('Purge Resolved Exception Batch Status :: ' + a.Status);
            mail.setPlainTextBody('Records Processed ' + a.TotalJobItems +   ' With '+ a.NumberOfErrors + ' Failures.');
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });   
        }
    }
    global class purgeResolvedExceptionSettings{
        List<String> emails;
        Map<String,String> criterias;
        set<String> messages;
    }
}