objects/Apex_Debug_Log__c.object
<CustomObject>
    <fields>
        <fullName>ApexLogId__c</fullName>
        <label>ApexLogId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Apex_Class__c</fullName>
        <label>Apex Class</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>InstanceName__c</fullName>
        <label>InstanceName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Login_UserId__c</fullName>
        <label>Login UserId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Login_User_ProfileId__c</fullName>
        <label>Login User ProfileId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Method__c</fullName>
        <label>Method</label>
        <length>180</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Id__c</fullName>
        <label>Record</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ReplayId__c</fullName>
        <label>ReplayId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stack_Trace__c</fullName>
        <label>Stack Trace</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Apex Debug Log</label>
    <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Apex Debug Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Debug Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/QueueableForRollbarExceptionLogTest.cls
/************************************************************************************************************************************
    Author 		: 	Krishana Tupe	
    Description : 	This class verify the insertion of exception into rollbar.
    
    History		:
    ----------------------------------------------------------------------------------------------------------------------------------
    VERSION		DATE				AUTHOR					DETAIL
    1			23 April 2018		Krishana Tupe			Initial Developement
    2			03 May 2018 		Krishana Tupe			Changes for exception logging.
   	3			06 Aug 2018 		Krishana Tupe			Changes for exception logging.
**************************************************************************************************************************************/
@isTest
public class QueueableForRollbarExceptionLogTest {

  /************************************************************************************************************************************
	Author 				: 	Krishana Tupe
	Description 		: 	This method is used to setup the settings data.
	Created Date		:	01 Aug 2018 	
 **************************************************************************************************************************************/
    @TestSetup
    public static void testSetup(){
        SalesConsoleSettings.createSettings();  
    }  
       
  /************************************************************************************************************************************
	Author 				: 	Krishana Tupe
	Description 		: 	This method is used to verify exception log in rollbar functionality.
	Created Date		:	01 Aug 2018 	
**************************************************************************************************************************************/   
    public static testmethod void verifyRollbarExceptionInsertion(){
        try{
            LogExceptionTriggerHandlerTest.getException();
        }catch(Exception pEx){
            List<Apex_Debug_Log__c> lstLogsTobeCreated = [Select Id,ReplayId__c,Apex_Class__c,ApexLogId__c,Message__c,Method__c,Record_Id__c,Stack_Trace__c,Login_UserId__c,Login_User_ProfileId__c,InstanceName__c From Apex_Debug_Log__c ORDER BY CreatedDate DESC];
            Debug.log('lstLogsTobeCreatedIn Rollbar ==>'+lstLogsTobeCreated);
            Test.setMock(HttpCalloutMock.class, new MockResponseForApexDebugLog());           
            ID jobID = System.enqueueJob(new QueueableForRollbarExceptionLog(lstLogsTobeCreated));            
            debug.log('QueueableForRollbarExceptionLog Job Information==>'+jobID); 
            System.assert(jobID != null);  
             new QueueableForRollbarExceptionLog();
            new QueueableForRollbarExceptionLog(pEx,'123456789101115','QueueableForRollbarExceptionLogTest','verifyRollbarExceptionInsertion');
        }        
    }
}