objects/Billing_Account__c.object
<CustomObject>
    <fields>
        <fullName>Primary_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the main point of contact for the Billing Account.</description>
        <inlineHelpText>Person at the member company responsible for managing the membership: invoices, key card replacements, MENA account manager tab. Responsible for signing legal agreement (unless an authorized signatory is designated).</inlineHelpText>
        <label>Primary Member</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UUID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>This is unique,case sensitive auto generated field used to identify Billing Account record.</description>
        <externalId>true</externalId>
        <inlineHelpText>This is unique,case sensitive auto generated field used to identify Billing Account record.</inlineHelpText>
        <label>UUID</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <description>All Billing account is moved to this Billing Account object it help Sales people to identify Org and Sales account easily and reduce the clutter of 100s of Accounts with same name.</description>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Building__c.object
<CustomObject>
    <fields>
        <fullName>Market__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Portfolio</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Buildings</relationshipLabel>
        <relationshipName>Buildings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UUID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Building</label>
    <nameField>
        <label>Building</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Members</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Building__c</fullName>
        <description>Pulls Building Location without 3 character city reference</description>
        <formula>Location__r.Location_No_City__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Building</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Broker__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Contact Broker</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alexandria</fullName>
                </value>
                <value>
                    <fullName>Alpharetta</fullName>
                </value>
                <value>
                    <fullName>Amsterdam</fullName>
                </value>
                <value>
                    <fullName>Ann Arbor</fullName>
                </value>
                <value>
                    <fullName>Atlanta</fullName>
                </value>
                <value>
                    <fullName>Austin</fullName>
                </value>
                <value>
                    <fullName>Balston</fullName>
                </value>
                <value>
                    <fullName>Baltimore</fullName>
                </value>
                <value>
                    <fullName>Bangkok</fullName>
                </value>
                <value>
                    <fullName>Barranquilla</fullName>
                </value>
                <value>
                    <fullName>Be'er Sheva</fullName>
                </value>
                <value>
                    <fullName>Beijing</fullName>
                </value>
                <value>
                    <fullName>Bengaluru</fullName>
                </value>
                <value>
                    <fullName>Berkeley</fullName>
                </value>
                <value>
                    <fullName>Berlin</fullName>
                </value>
                <value>
                    <fullName>Bethesda</fullName>
                </value>
                <value>
                    <fullName>Bogota</fullName>
                </value>
                <value>
                    <fullName>Bogotá</fullName>
                </value>
                <value>
                    <fullName>Boston</fullName>
                </value>
                <value>
                    <fullName>Boulder</fullName>
                </value>
                <value>
                    <fullName>Brooklyn</fullName>
                </value>
                <value>
                    <fullName>Budapest</fullName>
                </value>
                <value>
                    <fullName>Buenos Aires</fullName>
                </value>
                <value>
                    <fullName>Charlotte</fullName>
                </value>
                <value>
                    <fullName>Chicago</fullName>
                </value>
                <value>
                    <fullName>Cincinnati</fullName>
                </value>
                <value>
                    <fullName>Cleveland</fullName>
                </value>
                <value>
                    <fullName>Columbus</fullName>
                </value>
                <value>
                    <fullName>Dallas</fullName>
                </value>
                <value>
                    <fullName>Dallas - Fort Worth</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_Member__c</fullName>
        <formula>if( Billing_Account__r.Primary_Member__r.Id =  Id , "Yes","No")</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Primary Member</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Referrer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referrer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UUID__c</fullName>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Referral</fullName>
        <active>true</active>
        <label>Referral</label>
    </recordTypes>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field relates the opportunity to the billing account. The billing account is used in the space station for sending contracts.</description>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Building__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Enter the specific building for which opportunity is associated</description>
        <inlineHelpText>This is the building / Nearest building to the geography entered by customer</inlineHelpText>
        <label>Building/Nearest Building</label>
        <referenceTo>Building__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Broker__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to identify whether lead to be contacted  by the Broker</description>
        <inlineHelpText>Flag to identify whether lead to be contacted  by the Broker</inlineHelpText>
        <label>Contact Broker</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contract_Signed_On_Date__c</fullName>
        <description>New field to capture the Signed on date from payload sent in contract event</description>
        <label>Contract Signed On (Date)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <description>Enter the market value from which the lead is coming</description>
        <inlineHelpText>Enter the market value from which the lead is coming</inlineHelpText>
        <label>Market [old]</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Amsterdam</fullName>
                </value>
                <value>
                    <fullName>Arlington</fullName>
                </value>
                <value>
                    <fullName>Atlanta</fullName>
                </value>
                <value>
                    <fullName>Austin</fullName>
                </value>
                <value>
                    <fullName>Baltimore</fullName>
                </value>
                <value>
                    <fullName>Bangalore</fullName>
                </value>
                <value>
                    <fullName>Bangkok</fullName>
                </value>
                <value>
                    <fullName>Be'er Sheva</fullName>
                </value>
                <value>
                    <fullName>Beijing</fullName>
                </value>
                <value>
                    <fullName>Bellevue</fullName>
                </value>
                <value>
                    <fullName>Bengaluru</fullName>
                </value>
                <value>
                    <fullName>Berkeley</fullName>
                </value>
                <value>
                    <fullName>Berlin</fullName>
                </value>
                <value>
                    <fullName>Bogota</fullName>
                </value>
                <value>
                    <fullName>Boston</fullName>
                </value>
                <value>
                    <fullName>Boulder</fullName>
                </value>
                <value>
                    <fullName>Bronx</fullName>
                </value>
                <value>
                    <fullName>Brooklyn</fullName>
                </value>
                <value>
                    <fullName>Budapest</fullName>
                </value>
                <value>
                    <fullName>Buenos Aires</fullName>
                </value>
                <value>
                    <fullName>Cambridge</fullName>
                </value>
                <value>
                    <fullName>Cartagena</fullName>
                </value>
                <value>
                    <fullName>Charlotte</fullName>
                </value>
                <value>
                    <fullName>Chicago</fullName>
                </value>
                <value>
                    <fullName>Condesa / Hipodromo</fullName>
                </value>
                <value>
                    <fullName>Dallas</fullName>
                </value>
                <value>
                    <fullName>Delhi</fullName>
                </value>
                <value>
                    <fullName>Denver</fullName>
                </value>
                <value>
                    <fullName>Detroit</fullName>
                </value>
                <value>
                    <fullName>Dubai</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_Member__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>This is the Main Contact of the Opportunity</inlineHelpText>
        <label>Main Contact</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Referral_Status__c</fullName>
        <description>This will store Referral Status. Default value is Pending. Issue ST-2823</description>
        <inlineHelpText>This will store Referral Status.</inlineHelpText>
        <label>Referral Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/OpportunityReferralStatusController.cls
/************************************************************************************************************************************
    Author      :  Nikhil Mehta    
    Description :  This class contain all methods related to aura methods in OpportunityReferralStatusController.
    ----------------------------------------------------------------------------------------------------------------------------------
    VERSION     DATE                AUTHOR          		DETAIL
     1          1 Nov 2018       	Nikhil Mehta    	    Initial Developement
**************************************************************************************************************************************/
public without sharing  class OpportunityReferralStatusController {
    public class OpportunityReferralStatusControllerException extends Exception{}
    public static Boolean isInvoker = false;
    static {
        isInvoker = ApexDebugLog.registerRootInvoker(ApexDebugLog.InvokerType.AURA, 'OpportunityReferralStatusControllerException' + 'getsObjectPrefix', ApexDebugLog.InvokerType.AURA);        
    }
     /****************************************************************************************************************************
        Author              : Nikhil Mehta
        Description         : This method is used to getOpprtunityData.
        Created Date        : 29 Oct 2018
		Issue No			: ST-2858
   *****************************************************************************************************************************/  
    @AuraEnabled
    public static DatabaseResult getOpprtunityData(Id opportunityId){
        Map<String, sObject> mapData = new Map<String, sObject>();
        if(opportunityId != null){
           List<Opportunity> lstOpportunities = new List<Opportunity>([Select Id, Referral_Status__c, Contract_Signed_On_Date__c, RecordType.Id, RecordType.Name, Contact_Broker__c, Billing_Account__c, Billing_Account__r.Name, Billing_Account__r.UUID__c, Building__r.Id, Building__r.Name, Building__r.UUID__c, Building__r.Market__r.UUID__c, Primary_Member__r.Id, Primary_Member__r.Name, Primary_Member__r.Email, Referrer__r.Id, Referrer__r.Name, Referrer__r.Email, Referrer__r.Type__c,  Referrer__r.Phone, CreatedDate FROM Opportunity WHERE Id = :opportunityId]);
            Opportunity objOpportunity;
            if(!lstOpportunities.isEmpty()){
                objOpportunity = lstOpportunities[0];
                mapData.put('opp', objOpportunity);
            }
            Setting__c settingRecord = Settings.get('RetroactiveReferralSettings');
            if(settingRecord != null){
               mapData.put('referralSetting', settingRecord);
            }
            settingRecord = Settings.get('ReferenceSettings');
            if(settingRecord != null){
                Map<String, Object> mapReferral = (Map<String, Object>)JSON.deserializeUntyped(settingRecord.Data__c);
                mapData.put('referralRec', new Referral__c(Expires_On__c = System.today().addDays(Integer.valueOf(mapReferral.get('expireafter'))), Start_Date__c = System.today(), Referral_Source__c = 'Retroactive Referral'));
            }
            if(objOpportunity != null && String.isNotEmpty(objOpportunity.Primary_Member__c) && String.isNotEmpty(objOpportunity.Primary_Member__r.Email)){
                List<Referral__c> lstReferrals = [SELECT Id, CreatedDate, Referral_Email__c FROM Referral__c WHERE Referral_Email__c =: objOpportunity.Primary_Member__r.Email ORDER BY CreatedDate];
                if(!lstReferrals.isEmpty()){
                    mapData.put('existingReferral', lstReferrals[0]);
                }
            }
        }
        return new DatabaseResult(mapData);
    }
}