objects/Billing_Account__c.object
<CustomObject>
    <fields>
        <fullName>UUID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>This is unique,case sensitive auto generated field used to identify Billing Account record.</description>
        <externalId>true</externalId>
        <inlineHelpText>This is unique,case sensitive auto generated field used to identify Billing Account record.</inlineHelpText>
        <label>UUID</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <description>All Billing account is moved to this Billing Account object it help Sales people to identify Org and Sales account easily and reduce the clutter of 100s of Accounts with same name.</description>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Building__c.object
<CustomObject>
    <fields>
        <fullName>UUID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Building</label>
    <nameField>
        <label>Building</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Actual_Start_Date__c</fullName>
        <formula>Account.Start_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Actual Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Members</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Building__c</fullName>
        <description>Pulls Building Location without 3 character city reference</description>
        <formula>Location__r.Location_No_City__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Building</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reservable__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reservable</label>
        <referenceTo>Reservable__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This is the latest status coming from Space systems through Jitterbunny of the individual member. This tells us if the user is active or not.</description>
        <inlineHelpText>This is accurate status of a contact if it is an active member of our products or not.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>active</fullName>
                </value>
                <value>
                    <fullName>inactive</fullName>
                    <default>true</default>
                    <label>inactive</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Licensee</fullName>
                </value>
                <value>
                    <fullName>Employee</fullName>
                </value>
                <value>
                    <fullName>Member</fullName>
                </value>
                <value>
                    <fullName>Broker</fullName>
                </value>
                <value>
                    <fullName>Affiliate</fullName>
                </value>
                <value>
                    <fullName>Potential</fullName>
                </value>
                <value>
                    <fullName>Lead</fullName>
                </value>
                <value>
                    <fullName>Unqualified Broker</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UUID__c</fullName>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Actual_Start_Date__c</fullName>
        <inlineHelpText>This is the Expected Start Date until Closed Won</inlineHelpText>
        <label>Actual Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field relates the opportunity to the billing account. The billing account is used in the space station for sending contracts.</description>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Building__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Enter the specific building for which opportunity is associated</description>
        <inlineHelpText>This is the building / Nearest building to the geography entered by customer</inlineHelpText>
        <label>Building/Nearest Building</label>
        <referenceTo>Building__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Commitment_Term_in_months__c</fullName>
        <defaultValue>1</defaultValue>
        <inlineHelpText>Months in the commitment term</inlineHelpText>
        <label>Weighted Avg Commitment Term (in months)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Send_Paperwork_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Paperwork Sent By</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Send Paperwork By)</relationshipLabel>
        <relationshipName>Send_Paperwork_By</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Event Space</fullName>
                </value>
                <value>
                    <fullName>Internal Transfer</fullName>
                </value>
                <value>
                    <fullName>Partnership</fullName>
                </value>
                <value>
                    <fullName>PxWe</fullName>
                </value>
                <value>
                    <fullName>Mixed</fullName>
                </value>
                <value>
                    <fullName>Global Access</fullName>
                </value>
                <value>
                    <fullName>WeWork</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity_Move_Outs__c.object
<CustomObject>
    <fields>
        <fullName>Building__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>When we get building uuid insted of reservable uuid in Contract event payload map here.</description>
        <inlineHelpText>When we get building uuid insted of reservable uuid in Contract event payload map here.</inlineHelpText>
        <label>Sellable Building</label>
        <referenceTo>Building__c</referenceTo>
        <relationshipLabel>Opportunity Move Outs</relationshipLabel>
        <relationshipName>Opportunity_Move_Outs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Monthly_Price__c</fullName>
        <label>Monthly Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Move Outs (from "there")</relationshipLabel>
        <relationshipName>Opportunity_Move_Outs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reservable__c</fullName>
        <label>Reservable</label>
        <referenceTo>Reservable__c</referenceTo>
        <relationshipLabel>Opportunity Move Outs</relationshipLabel>
        <relationshipName>Opportunity_Move_Outs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Cancel</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>We will capture  Move Outs of opportunity which are coming from Contract event</description>
    <label>Opportunity Move Out</label>
    <nameField>
        <displayFormat>MO-{0000000}</displayFormat>
        <label>Opportunity Move Outs Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Move Outs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity_Reservable__c.object
<CustomObject>
    <fields>
        <fullName>Building__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>When we get building uuid insted of reservable uuid in Contract event payload map here.</description>
        <inlineHelpText>When we get building uuid insted of reservable uuid in Contract event payload map here.</inlineHelpText>
        <label>Sellable Building</label>
        <referenceTo>Building__c</referenceTo>
        <relationshipLabel>Opportunity Reservables</relationshipLabel>
        <relationshipName>Opportunity_Reservables</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Monthly_Price__c</fullName>
        <label>Monthly Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Reservables</relationshipLabel>
        <relationshipName>Opportunity_Offices</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reservable__c</fullName>
        <label>Reservable</label>
        <referenceTo>Reservable__c</referenceTo>
        <relationshipLabel>Opportunity Reservables</relationshipLabel>
        <relationshipName>Opportunity_Offices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Value of start date from Contract Event endpoint</description>
        <inlineHelpText>Value of start date from Contract Event endpoint</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Opportunity Reservable</label>
    <nameField>
        <displayFormat>OO-{0000}</displayFormat>
        <label>Office ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Reservables</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Building__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is filled from contract event in the pay of products.</description>
        <inlineHelpText>Enter the relevant building. If 'Geography' was selected previously, the nearest building will appear.</inlineHelpText>
        <label>Building</label>
        <referenceTo>Building__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>This is filled from contract event payload in product for sellable feature</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

objects/Reservable__c.object
<CustomObject>
    <fields>
        <fullName>Building__c</fullName>
        <label>Building</label>
        <referenceTo>Building__c</referenceTo>
        <relationshipLabel>Reservables</relationshipLabel>
        <relationshipName>Offices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Monthly_Price__c</fullName>
        <label>Monthly Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Available</fullName>
                </value>
                <value>
                    <fullName>Unavailable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UUID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Reservable</label>
    <nameField>
        <label>Reservable Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reservables</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ContractEventSentTest.cls
/**
* Name			:	ContractEventSentTest	 
* Issue No.		: 	
* Purpose		:	This is contains the test methods 'Contract Sent' event.
* History		
Version			Author				Date			Detail						Feature			IssueNumber
1.0				Shobhit Gahlot		16/1/2018		Initial Development		
***********************************************************************************************************************************************************
*/
@isTest 
public with sharing class ContractEventSentTest {
    @TestSetup 
    static void testDataSetUp(){
        ContractEventTestingUtility.getContractDataForAllEvents();
    }
    
    static testMethod void testContractEventSentNewOpportunity(){
        List<Opportunity> lstOpportunities = [SELECT Id, Name, Billing_Account__r.UUID__c,Type__c, (SELECT Id, Status__c,Reservable__r.UUID__c FROM Opportunity_Move_Outs__r), (Select Id, Reservable__c, Start_Date__c, Opportunity__c, Monthly_Price__c From Opportunity_Offices__r) FROM Opportunity order by createdDate LIMIT 1];        
        debug.log('lstOpportunities: '+lstOpportunities);
        List<Reservable__c> lstReservable = [SELECT Id, uuid__c, Building__c FROM Reservable__c WHERE UUID__c != null];
        system.assert(lstReservable.size() > 0);
        Set<Id> setBuildingIds = new Set<Id>();
        for(Reservable__c obj : lstReservable){
            setBuildingIds.add(obj.Building__c);
        }
        List<Building__c> lstBuilding = [SELECT Id, uuid__c FROM Building__c WHERE UUID__c != null AND Id In : setBuildingIds];
        system.assert(lstBuilding.size() > 0);
        
        
        List<Billing_Account__c> lstBillingAccount = [SELECT Id, uuid__c FROM Billing_Account__c WHERE UUID__c != null];
        system.assert(lstBillingAccount.size() > 0);
        
        List<Contact> lstContacts = [SELECT Id, uuid__c, Email FROM Contact WHERE UUID__c != null];
        system.assert(lstContacts.size() > 0);
        
        Map<String,Object> mapPayLoadValues = new Map<String,Object>();
        
        List<WWTypes.commitmentTerms> lstcommitmentTerms  = ContractEventTestingUtility.getCommitmentsForPayload(lstBuilding);
        
        List<WWTypes.Discounts> lstDiscounts = ContractEventTestingUtility.getDiscountsForPayload(lstBuilding);
        
        List<WWTypes.move_insVal> lstmove_insVal = ContractEventTestingUtility.getMoveInsForPayload(lstBuilding, lstReservable);        
        
        List<WWTypes.move_outssVal> lstmove_outssVal = ContractEventTestingUtility.getMoveOutsforPayload(lstBuilding, lstReservable);
        
        List<WWTypes.products> lstproductss = ContractEventTestingUtility.getProductsforPayload(lstBuilding, lstReservable);
        debug.log('lstproductss: '+lstproductss);
        String strContractExpiration = '2018-03-06 08:37:30';
        Long longContractExpiration = DateTime.valueOf(strContractExpiration).getTime();
        WWTypes.ContractEvent ObjContractEvent = ContractEventTestingUtility.getCompletePayloadForContract('Contract Sent', lstBillingAccount[0].UUID__c, lstContacts[0].Email, 'New opportunity', 'USD', 'www.test.com,www.test1.com', '2018-10-14', 'Commitment', String.valueOf(lstOpportunities[0].Id), lstContacts[0].uuid__c, String.valueOf(strContractExpiration), null, lstcommitmentTerms, lstDiscounts, lstproductss, lstmove_insVal, lstmove_outssVal);
        RESTContractEvent.Response response = ContractEventTestingUtility.callOutToContractEventEndPoint(ObjContractEvent);
        Debug.log('response testContractEventSentSearchCriteriaNewOpportunity ::'+response);
        System.assertEquals(true, response.success);
        System.assert(response.result.startsWith('"New Opportunity :'));
        Id OpportunityId;
        if(response.result != null && response.result != ''){
            Debug.Log('response.result--'+response.result);
        	OpportunityId = ContractEventTestingUtility.extractIdFromResultInContractEvent(response.result);
            Debug.Log('OpportunityId--'+OpportunityId);
        }
        Map<Id,OpportunityLineItem> mapOpportunityLineItem = new Map<Id,OpportunityLineItem>();
        Debug.Log('ContractEvenetSentTest OpportunityId--'+OpportunityId);
        Opportunity opp = ContractEventTestingUtility.getOpportunityAfterContractRequest(OpportunityId);
        debug.log('ContractEvenetSentTest opp-----:'+opp);
        System.assertEquals(12.00, opp.Commitment_Term_in_months__c);
        ContractEventTestingUtility.payloadAssertion(ObjContractEvent, opp, null);
        System.assertEquals(Date.ValueOf(lstmove_insVal[2].start_date), opp.Actual_Start_Date__c);//Latest date on movein
        System.assertEquals(lstContacts[0].Id, opp.Send_Paperwork_By__c);
        System.assertEquals(lstContacts[0].UUID__c, opp.Community_Manager_UUID__c);
        System.assertEquals(lstContacts[0].Id, opp.Community_User__c);
        System.assertEquals(lstContacts[0].Id, opp.Primary_Member__c);
        System.assertEquals('Mixed', opp.Type__c);
        System.assertEquals(opp.Billing_Account__c, lstBillingAccount[0].id);
        
    }
    
    static testMethod void testContractEventSentUpdateOpportunity(){
        List<Opportunity> lstOpportunities = [SELECT Id, Name, Billing_Account__r.UUID__c,(SELECT Id,ProductCode FROM OpportunityLineItems), (SELECT Id, Status__c,Reservable__r.UUID__c FROM Opportunity_Move_Outs__r), (Select Id, Reservable__c, Start_Date__c, Opportunity__c, Monthly_Price__c From Opportunity_Offices__r) FROM Opportunity order by createdDate desc];        
        
        List<Reservable__c> lstReservable = [SELECT Id, uuid__c, Building__c FROM Reservable__c WHERE UUID__c != null];
        system.assert(lstReservable.size() > 0);
        Set<Id> setBuildingIds = new Set<Id>();
        for(Reservable__c obj : lstReservable){
            setBuildingIds.add(obj.Building__c);
        }
        List<Building__c> lstBuilding = [SELECT Id, uuid__c FROM Building__c WHERE UUID__c != null AND Id In : setBuildingIds];
        system.assert(lstBuilding.size() > 0);
        
        
        List<Billing_Account__c> lstBillingAccount = [SELECT Id, uuid__c FROM Billing_Account__c WHERE UUID__c != null];
        system.assert(lstBillingAccount.size() > 0);
        
        List<Contact> lstContacts = [SELECT Id, uuid__c, Email FROM Contact WHERE UUID__c != null];
        system.assert(lstContacts.size() > 0);
        
        Map<String,Object> mapPayLoadValues = new Map<String,Object>();
        
        List<WWTypes.commitmentTerms> lstcommitmentTerms  = ContractEventTestingUtility.getCommitmentsForPayload(lstBuilding);
        
        List<WWTypes.Discounts> lstDiscounts = ContractEventTestingUtility.getDiscountsForPayload(lstBuilding);
        
        List<WWTypes.move_insVal> lstmove_insVal = ContractEventTestingUtility.getMoveInsForPayload(lstBuilding, lstReservable);        
        
        List<WWTypes.move_outssVal> lstmove_outssVal = ContractEventTestingUtility.getMoveOutsforPayload(lstBuilding, lstReservable);
        
        List<WWTypes.products> lstproductss = ContractEventTestingUtility.getProductsforPayload(lstBuilding, lstReservable);
        
        String strContractExpiration = '2018-03-06 08:37:30';
        Long longContractExpiration = DateTime.valueOf(strContractExpiration).getTime();
        
        WWTypes.ContractEvent ObjContractEvent = ContractEventTestingUtility.getCompletePayloadForContract('Contract Sent', lstOpportunities[0].Billing_Account__r.UUID__c, lstContacts[0].Email, 'New opportunity', 'USD', 'www.test.com,www.test1.com', '2018-10-14', 'Commitment', null, lstContacts[0].uuid__c, String.valueOf(strContractExpiration), String.ValueOf(lstOpportunities[0].Id), lstcommitmentTerms, lstDiscounts, lstproductss, lstmove_insVal, lstmove_outssVal);
        Debug.Log('ObjContractEvent==>'+ObjContractEvent);
        
        RESTContractEvent.Response response = ContractEventTestingUtility.callOutToContractEventEndPoint(ObjContractEvent);
        Debug.log('response testContractEventSentSearchCriteriaNewOpportunity ::'+response);
        System.assertEquals(true, response.success);
        System.assert(response.result.startsWith('"Update Opportunity :'));
        Id OpportunityId;
        if(response.result != null && response.result != '')
            OpportunityId = ContractEventTestingUtility.extractIdFromResultInContractEvent(response.result);
        System.assertEquals(String.valueOf(lstOpportunities[0].Id), OpportunityId);
        Opportunity opp = ContractEventTestingUtility.getOpportunityAfterContractRequest(OpportunityId);
        
        System.assertEquals(12.00, opp.Commitment_Term_in_months__c);
        ContractEventTestingUtility.payloadAssertion(ObjContractEvent, opp, null);
        System.assertEquals(Date.ValueOf(lstmove_insVal[2].start_date), opp.Actual_Start_Date__c);//Latest date on movein
        System.assertEquals(lstContacts[0].Id, opp.Send_Paperwork_By__c);
        System.assertEquals(lstContacts[0].UUID__c, opp.Community_Manager_UUID__c);
        System.assertEquals(lstContacts[0].Id, opp.Community_User__c);
        System.assertEquals(lstContacts[0].Id, opp.Primary_Member__c);
        System.assertEquals('Mixed', opp.Type__c);
        System.assertEquals(opp.Billing_Account__c, lstBillingAccount[0].id);
    }
    
    static testMethod void testCurrencyChangeWithOpportunity_Id(){
        
        List<Opportunity> lstOpportunities = [SELECT Id, Name, Billing_Account__r.UUID__c, CurrencyIsoCode, (SELECT Id,ProductCode FROM OpportunityLineItems), (SELECT Id, Status__c,Reservable__r.UUID__c FROM Opportunity_Move_Outs__r), (Select Id, Reservable__c, Start_Date__c, Opportunity__c, Monthly_Price__c From Opportunity_Offices__r) FROM Opportunity order by createdDate LIMIT 1];        
        
        List<PriceBookEntry> lstpricebook = [SELECT ID FROM PriceBookEntry WHERE ProductCode = 'Not Considered' AND CurrencyIsoCode =: lstOpportunities[0].CurrencyIsoCode];
        
        OpportunityLineItem objLineItem = new OpportunityLineItem(
            PriceBookEntryId = lstpricebook[0].Id,
            UnitPrice = 56,
            quantity = 20,
            OpportunityId = lstOpportunities[0].Id
        );
        TestingUtility.insertWithAssert(objLineItem);
        
        
        List<Reservable__c> lstReservable = [SELECT Id, uuid__c, Building__c FROM Reservable__c WHERE UUID__c != null];
        system.assert(lstReservable.size() > 0);
        Set<Id> setBuildingIds = new Set<Id>();
        for(Reservable__c obj : lstReservable){
            setBuildingIds.add(obj.Building__c);
        }
        List<Building__c> lstBuilding = [SELECT Id, uuid__c FROM Building__c WHERE UUID__c != null AND Id In : setBuildingIds];
        system.assert(lstBuilding.size() > 0);
        
        
        List<Billing_Account__c> lstBillingAccount = [SELECT Id, uuid__c FROM Billing_Account__c WHERE UUID__c =: lstOpportunities[0].Billing_Account__r.UUID__c];
        system.assert(lstBillingAccount.size() > 0);
        
        List<Contact> lstContacts = [SELECT Id, uuid__c, Email FROM Contact WHERE UUID__c != null];
        system.assert(lstContacts.size() > 0);
        
        Map<String,Object> mapPayLoadValues = new Map<String,Object>();
        
        List<WWTypes.commitmentTerms> lstcommitmentTerms  = ContractEventTestingUtility.getCommitmentsForPayload(lstBuilding);
        
        List<WWTypes.Discounts> lstDiscounts = ContractEventTestingUtility.getDiscountsForPayload(lstBuilding);
        
        List<WWTypes.move_insVal> lstmove_insVal = ContractEventTestingUtility.getMoveInsForPayload(lstBuilding, lstReservable);        
        
        List<WWTypes.move_outssVal> lstmove_outssVal = ContractEventTestingUtility.getMoveOutsforPayload(lstBuilding, lstReservable);
        
        List<WWTypes.products> lstproductss = ContractEventTestingUtility.getProductsforPayload(lstBuilding, lstReservable);
        
        String strContractExpiration = '2018-03-06 08:37:30';
        Long longContractExpiration = DateTime.valueOf(strContractExpiration).getTime();
        
        WWTypes.ContractEvent ObjContractEvent = ContractEventTestingUtility.getCompletePayloadForContract('Contract Sent', lstOpportunities[0].Billing_Account__r.UUID__c, lstContacts[0].Email, 'Update opportunity', 'EUR', 'www.test.com,www.test1.com', '2018-10-14', 'Commitment', null, lstContacts[0].uuid__c, String.valueOf(strContractExpiration), String.ValueOf(lstOpportunities[0].Id), lstcommitmentTerms, lstDiscounts, lstproductss, lstmove_insVal, lstmove_outssVal);
        Debug.Log('ObjContractEvent==>'+ObjContractEvent);
        
        RESTContractEvent.Response response = ContractEventTestingUtility.callOutToContractEventEndPoint(ObjContractEvent);
        Debug.log('response testContractEventSentSearchCriteriaNewOpportunity ::'+response);
        System.assertEquals(true, response.success);
        System.assert(response.result.startsWith('"Update Opportunity :'));
        Id OpportunityId;
        if(response.result != null && response.result != ''){
            OpportunityId = ContractEventTestingUtility.extractIdFromResultInContractEvent(response.result);
        }  
        System.assertEquals(String.valueOf(lstOpportunities[0].Id), OpportunityId);
        Opportunity opp = ContractEventTestingUtility.getOpportunityAfterContractRequest(OpportunityId);
        
        System.assertEquals(12.00, opp.Commitment_Term_in_months__c);
        ContractEventTestingUtility.payloadAssertion(ObjContractEvent, opp, 'INR');
        System.assertEquals(Date.ValueOf(lstmove_insVal[2].start_date), opp.Actual_Start_Date__c);//Latest date on movein
        System.assertEquals(lstContacts[0].Id, opp.Send_Paperwork_By__c);
        System.assertEquals(lstContacts[0].UUID__c, opp.Community_Manager_UUID__c);
        System.assertEquals(lstContacts[0].Id, opp.Community_User__c);
        System.assertEquals(lstContacts[0].Id, opp.Primary_Member__c);
        System.assertEquals('Mixed', opp.Type__c);
        System.assertEquals(opp.Billing_Account__c, lstBillingAccount[0].id);
        
        debug.log('result testContractEventSentSearchCriteria update ::' + response);
        System.assertEquals(true, response.success);
        debug.log('response.result::' + response.result);
        System.assert(response.result.startsWith('"Update Opportunity :'));
        
    }
    
    
    static testMethod void testContractEventSentDealUpdateOpportunity(){
        List<Opportunity> lstOpportunities = [SELECT Id, Name, Billing_Account__r.UUID__c, CurrencyIsoCode FROM Opportunity order by createdDate];        
        
        List<Reservable__c> lstReservable = [SELECT Id, uuid__c, Building__c FROM Reservable__c WHERE UUID__c != null];
        system.assert(lstReservable.size() > 0);
        Set<Id> setBuildingIds = new Set<Id>();
        for(Reservable__c obj : lstReservable){
            setBuildingIds.add(obj.Building__c);
        }
        List<Building__c> lstBuilding = [SELECT Id, uuid__c FROM Building__c WHERE UUID__c != null AND Id In : setBuildingIds];
        system.assert(lstBuilding.size() > 0);
        
        List<Billing_Account__c> lstBillingAccount = [SELECT Id, uuid__c FROM Billing_Account__c WHERE UUID__c =: lstOpportunities[0].Billing_Account__r.UUID__c];
        system.assert(lstBillingAccount.size() > 0);
        
        List<Contact> lstContacts = [SELECT Id, uuid__c, Email FROM Contact WHERE UUID__c != null];
        system.assert(lstContacts.size() > 0);
        
        Map<String,Object> mapPayLoadValues = new Map<String,Object>();
        
        List<WWTypes.move_insVal> lstmove_insVal = ContractEventTestingUtility.getMoveInsForPayload(lstBuilding, lstReservable);        
        
        List<WWTypes.products> lstproductss = ContractEventTestingUtility.getProductsforPayload(lstBuilding, lstReservable);
        for(WWTypes.products objProduct : lstproductss){
            objProduct.product_code = 'PRDL-000001';
            break;
        }
        
        String strContractExpiration = '2018-03-06 08:37:30';
        Long longContractExpiration = DateTime.valueOf(strContractExpiration).getTime();
        
        WWTypes.ContractEvent ObjContractEvent = ContractEventTestingUtility.getCompletePayloadForContract('Contract Sent', lstOpportunities[0].Billing_Account__r.UUID__c, lstContacts[0].Email, 'Update opportunity', 'INR', 'www.test.com,www.test1.com', '2018-10-14', 'Commitment', null, lstContacts[0].uuid__c, String.valueOf(strContractExpiration), String.ValueOf(lstOpportunities[0].Id), null, null, lstproductss, lstmove_insVal, null);
        Debug.Log('ObjContractEvent==>'+ObjContractEvent);
        
        RESTContractEvent.Response response = ContractEventTestingUtility.callOutToContractEventEndPoint(ObjContractEvent);
        Debug.log('response testContractEventSentSearchCriteriaNewOpportunity ::'+response);
        System.assertEquals(true, response.success);
        System.assert(response.result.startsWith('"Update Opportunity :'));
        Id OpportunityId;
        if(response.result != null && response.result != ''){
            OpportunityId = ContractEventTestingUtility.extractIdFromResultInContractEvent(response.result);
        }  
        System.assertEquals(String.valueOf(lstOpportunities[0].Id), OpportunityId);
        Opportunity opp = ContractEventTestingUtility.getOpportunityAfterContractRequest(OpportunityId);
        
        
        ContractEventTestingUtility.payloadAssertion(ObjContractEvent, opp, null);
        System.assertEquals(Date.ValueOf(lstmove_insVal[2].start_date), opp.Actual_Start_Date__c);//Latest date on movein
        System.assertEquals(lstContacts[0].Id, opp.Send_Paperwork_By__c);
        System.assertEquals(lstContacts[0].UUID__c, opp.Community_Manager_UUID__c);
        System.assertEquals(lstContacts[0].Id, opp.Community_User__c);
        System.assertEquals(lstContacts[0].Id, opp.Primary_Member__c);
        System.assertEquals(opp.Billing_Account__c, lstBillingAccount[0].id);
    }
    
    static testMethod void testContractEventSentCreateNewDeal(){
        
        List<Opportunity> lstOpportunities = [SELECT Id, Name, Billing_Account__r.UUID__c, CurrencyIsoCode FROM Opportunity order by createdDate];        
        List<Reservable__c> lstReservable = [SELECT Id, uuid__c, Building__c FROM Reservable__c WHERE UUID__c != null];
        system.assert(lstReservable.size() > 0);
        Set<Id> setBuildingIds = new Set<Id>();
        for(Reservable__c obj : lstReservable){
            setBuildingIds.add(obj.Building__c);
        }
        List<Building__c> lstBuilding = [SELECT Id, uuid__c FROM Building__c WHERE UUID__c != null AND Id In : setBuildingIds];
        system.assert(lstBuilding.size() > 0);
        
        List<Billing_Account__c> lstBillingAccount = [SELECT Id, uuid__c FROM Billing_Account__c WHERE UUID__c =: lstOpportunities[0].Billing_Account__r.UUID__c];
        system.assert(lstBillingAccount.size() > 0);
        
        List<Contact> lstContacts = [SELECT Id, uuid__c, Email FROM Contact WHERE UUID__c != null];
        system.assert(lstContacts.size() > 0);
        
        Map<String,Object> mapPayLoadValues = new Map<String,Object>();
        
        List<WWTypes.move_insVal> lstmove_insVal = ContractEventTestingUtility.getMoveInsForPayload(lstBuilding, lstReservable);        
        
        List<WWTypes.products> lstproductss = ContractEventTestingUtility.getProductsforPayload(lstBuilding, lstReservable);
        for(WWTypes.products objProduct : lstproductss){
            objProduct.product_code = 'PRDL-000001';
            break;
        }
        
        String strContractExpiration = '2018-03-06 08:37:30';
        Long longContractExpiration = DateTime.valueOf(strContractExpiration).getTime();
        
        WWTypes.ContractEvent ObjContractEvent = ContractEventTestingUtility.getCompletePayloadForContract('Contract Sent', lstOpportunities[0].Billing_Account__r.UUID__c, lstContacts[0].Email, 'Update opportunity', 'INR', 'www.test.com,www.test1.com', '2018-10-14', 'Commitment', null, lstContacts[0].uuid__c, String.valueOf(strContractExpiration), null, null, null, lstproductss, lstmove_insVal, null);
        Debug.Log('ObjContractEvent==>'+ObjContractEvent);
        
        RESTContractEvent.Response response = ContractEventTestingUtility.callOutToContractEventEndPoint(ObjContractEvent);
        Debug.log('response testContractEventSentSearchCriteriaNewOpportunity ::'+response);
        System.assertEquals(true, response.success);
        System.assert(response.result.startsWith('"New Opportunity :'));
        Id OpportunityId;
        if(response.result != null && response.result != ''){
            OpportunityId = ContractEventTestingUtility.extractIdFromResultInContractEvent(response.result);
        }
        
        Opportunity opp = ContractEventTestingUtility.getOpportunityAfterContractRequest(OpportunityId);
        
        ContractEventTestingUtility.payloadAssertion(ObjContractEvent, opp, null);
        System.assertEquals(Date.ValueOf(lstmove_insVal[2].start_date), opp.Actual_Start_Date__c);//Latest date on movein
        System.assertEquals(lstContacts[0].Id, opp.Send_Paperwork_By__c);
        System.assertEquals(lstContacts[0].UUID__c, opp.Community_Manager_UUID__c);
        System.assertEquals(lstContacts[0].Id, opp.Community_User__c);
        System.assertEquals(lstContacts[0].Id, opp.Primary_Member__c);
        System.assertEquals(opp.Billing_Account__c, lstBillingAccount[0].id);
    }
}