objects/Billing_Account__c.object
<CustomObject>
    <fields>
        <fullName>Primary_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the main point of contact for the Billing Account.</description>
        <inlineHelpText>Person at the member company responsible for managing the membership: invoices, key card replacements, MENA account manager tab. Responsible for signing legal agreement (unless an authorized signatory is designated).</inlineHelpText>
        <label>Primary Member</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UUID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>This is unique,case sensitive auto generated field used to identify Billing Account record.</description>
        <externalId>true</externalId>
        <inlineHelpText>This is unique,case sensitive auto generated field used to identify Billing Account record.</inlineHelpText>
        <label>UUID</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <description>All Billing account is moved to this Billing Account object it help Sales people to identify Org and Sales account easily and reduce the clutter of 100s of Accounts with same name.</description>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Building__c.object
<CustomObject>
    <fields>
        <fullName>UUID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Building</label>
    <nameField>
        <label>Building</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Members</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Building__c</fullName>
        <description>Pulls Building Location without 3 character city reference</description>
        <formula>Location__r.Location_No_City__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Building</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Member__c</fullName>
        <formula>if( Billing_Account__r.Primary_Member__r.Id =  Id , "Yes","No")</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Primary Member</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reservable__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reservable</label>
        <referenceTo>Reservable__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This is the latest status coming from Space systems through Jitterbunny of the individual member. This tells us if the user is active or not.</description>
        <inlineHelpText>This is accurate status of a contact if it is an active member of our products or not.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>active</fullName>
                </value>
                <value>
                    <fullName>inactive</fullName>
                    <default>true</default>
                    <label>inactive</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UUID__c</fullName>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field relates the opportunity to the billing account. The billing account is used in the space station for sending contracts.</description>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Building__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Enter the specific building for which opportunity is associated</description>
        <inlineHelpText>This is the building / Nearest building to the geography entered by customer</inlineHelpText>
        <label>Building/Nearest Building</label>
        <referenceTo>Building__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Building_uuid__c</fullName>
        <formula>Building__r.UUID__c</formula>
        <label>Building uuid</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contract_Signed_On_Date__c</fullName>
        <description>New field to capture the Signed on date from payload sent in contract event</description>
        <label>Contract Signed On (Date)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contract_Stage__c</fullName>
        <label>Contract Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Contract Sent</fullName>
                </value>
                <value>
                    <fullName>Contract Voided</fullName>
                </value>
                <value>
                    <fullName>Contract Discarded</fullName>
                </value>
                <value>
                    <fullName>Contract Signed</fullName>
                </value>
                <value>
                    <fullName>Contract Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract_UUID__c</fullName>
        <description>contractEvent Endpoint will contain 'Contract UUID' to search Opportunity</description>
        <externalId>true</externalId>
        <inlineHelpText>contractEvent Endpoint will contain 'Contract UUID' to search Opportunity</inlineHelpText>
        <label>Contract UUID</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Primary_Member__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>This is the Main Contact of the Opportunity</inlineHelpText>
        <label>Main Contact</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity_Move_Outs__c.object
<CustomObject>
    <fields>
        <fullName>Building__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>When we get building uuid insted of reservable uuid in Contract event payload map here.</description>
        <inlineHelpText>When we get building uuid insted of reservable uuid in Contract event payload map here.</inlineHelpText>
        <label>Sellable Building</label>
        <referenceTo>Building__c</referenceTo>
        <relationshipLabel>Opportunity Move Outs</relationshipLabel>
        <relationshipName>Opportunity_Move_Outs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Monthly_Price__c</fullName>
        <label>Monthly Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Move Outs (from "there")</relationshipLabel>
        <relationshipName>Opportunity_Move_Outs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reservable__c</fullName>
        <label>Reservable</label>
        <referenceTo>Reservable__c</referenceTo>
        <relationshipLabel>Opportunity Move Outs</relationshipLabel>
        <relationshipName>Opportunity_Move_Outs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Cancel</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>We will capture  Move Outs of opportunity which are coming from Contract event</description>
    <label>Opportunity Move Out</label>
    <nameField>
        <displayFormat>MO-{0000000}</displayFormat>
        <label>Opportunity Move Outs Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Move Outs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity_Reservable__c.object
<CustomObject>
    <fields>
        <fullName>Building__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>When we get building uuid insted of reservable uuid in Contract event payload map here.</description>
        <inlineHelpText>When we get building uuid insted of reservable uuid in Contract event payload map here.</inlineHelpText>
        <label>Sellable Building</label>
        <referenceTo>Building__c</referenceTo>
        <relationshipLabel>Opportunity Reservables</relationshipLabel>
        <relationshipName>Opportunity_Reservables</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Monthly_Price__c</fullName>
        <label>Monthly Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Reservables</relationshipLabel>
        <relationshipName>Opportunity_Offices</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reservable__c</fullName>
        <label>Reservable</label>
        <referenceTo>Reservable__c</referenceTo>
        <relationshipLabel>Opportunity Reservables</relationshipLabel>
        <relationshipName>Opportunity_Offices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Value of start date from Contract Event endpoint</description>
        <inlineHelpText>Value of start date from Contract Event endpoint</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Opportunity Reservable</label>
    <nameField>
        <displayFormat>OO-{0000}</displayFormat>
        <label>Office ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Reservables</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Reservable__c.object
<CustomObject>
    <fields>
        <fullName>Building_UUID__c</fullName>
        <formula>Building__r.UUID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Building UUID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Building__c</fullName>
        <label>Building</label>
        <referenceTo>Building__c</referenceTo>
        <relationshipLabel>Reservables</relationshipLabel>
        <relationshipName>Offices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Monthly_Price__c</fullName>
        <label>Monthly Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Available</fullName>
                </value>
                <value>
                    <fullName>Unavailable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UUID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Reservable</label>
    <nameField>
        <label>Reservable Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reservables</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ContractEventSignedTest.cls
/**
* Name			:	ContractEventSignedTest	 
* Issue No.		: 	
* Purpose		:	This contains the test methods of 'Contract Signed' event.
* History		
	Version			Author				Date			Detail						Feature			IssueNumber
	1.0				Rupesh Patil		1/31/2018		Initial Development							
***********************************************************************************************************************************************************
*/
@isTest 
public class ContractEventSignedTest {
    @TestSetup 
    static void testDataSetUp(){
     ContractEventTestingUtility.getContractDataForAllEvents();      
    }
    public static testMethod void testDealProductsCreateNewOpportunity(){
        List<Opportunity> lstOpportunities = [SELECT Id, Name, Billing_Account__r.UUID__c, Primary_Member__r.Email, (SELECT Id, Status__c, Reservable__r.UUID__c FROM Opportunity_Move_Outs__r), (Select Id, Reservable__c, Start_Date__c, Opportunity__c, Monthly_Price__c From Opportunity_Offices__r) FROM Opportunity order by createdDate];        
        List<Reservable__c> lstReservable = [SELECT Id, uuid__c, Building__c FROM Reservable__c WHERE UUID__c != null];
        system.assert(lstReservable.size() > 0);
        Set<Id> setBuildingIds = new Set<Id>();
        for(Reservable__c obj : lstReservable){
            setBuildingIds.add(obj.Building__c);
        }
        List<Building__c> lstBuilding = [SELECT Id, uuid__c FROM Building__c WHERE UUID__c != null AND Id In : setBuildingIds];
        system.assert(lstBuilding.size() > 0);
        List<Billing_Account__c> lstBillingAccount = [SELECT Id, uuid__c FROM Billing_Account__c WHERE UUID__c != null];
        system.assert(lstBillingAccount.size() > 0);
        List<Contact> lstContacts = [SELECT Id, uuid__c, Email FROM Contact WHERE UUID__c != null];
        system.assert(lstContacts.size() > 0);
        List<WWTypes.move_insVal> lstmove_insVal = ContractEventTestingUtility.getMoveInsForPayload(lstBuilding, lstReservable);        
        List<WWTypes.products> lstproducts = ContractEventTestingUtility.getProductsforPayload(lstBuilding, lstReservable);     
        WWTypes.ContractEvent ObjContractEventSigned = ContractEventTestingUtility.getCompletePayloadForContract('Contract Signed', lstBillingAccount[2].UUID__c, lstOpportunities[0].Primary_Member__r.Email, 'abc123jnk', 'INR', '', '2018-11-06', 'New Business', '', lstContacts[1].UUID__c, '', '', null, null, lstproducts, lstmove_insVal, null);
        RESTContractEvent.Response response = ContractEventTestingUtility.callOutToContractEventEndPoint(objContractEventSigned);
        Debug.log('Response From REST API :::'+response);
        String oppoId;
        if(response.result != null && response.result != '')
            oppoId = ContractEventTestingUtility.extractIdFromResultInContractEvent(response.result);
        System.assertEquals(true, response.success);
        System.assert(response.result.startsWith('"New Opportunity :'));
        List<Opportunity> lstOpp = [SELECT Id, Billing_Account__c, StageName, CurrencyIsoCode, Contract_Signed_On_Date__c, Contract_UUID__c, Building__c, Contract_Stage__c,(select Id, Quantity, UnitPrice, Building_UUID__c, Building__c, CurrencyIsoCode From OpportunityLineItems) FROM Opportunity WHERE ID =:oppoId];
        System.assertEquals(3, lstopp[0].OpportunityLineItems.size());
        System.assertEquals(lstOpp[0].Id, oppoId);
        System.assertEquals(lstBuilding[0].Id, lstOpp[0].Building__c);
		System.assertEquals(lstOpp[0].Billing_Account__c, lstBillingAccount[2].id);		
        
    }
    public static testMethod void testContractEventSigned_SearchWithOpportunityId(){
        List<Opportunity> lstOpportunities = [SELECT Id, Name, Billing_Account__r.UUID__c, Primary_Member__r.Email, (SELECT Id, Status__c, Reservable__r.UUID__c FROM Opportunity_Move_Outs__r), (Select Id, Reservable__c, Start_Date__c, Opportunity__c, Monthly_Price__c From Opportunity_Offices__r) FROM Opportunity order by createdDate];        
        List<Reservable__c> lstReservable = [SELECT Id, uuid__c, Building__c FROM Reservable__c WHERE UUID__c != null];
        system.assert(lstReservable.size() > 0);
        Set<Id> setBuildingIds = new Set<Id>();
        for(Reservable__c obj : lstReservable){
            setBuildingIds.add(obj.Building__c);
        }
        List<Building__c> lstBuilding = [SELECT Id, uuid__c FROM Building__c WHERE UUID__c != null AND Id In : setBuildingIds];
        system.assert(lstBuilding.size() > 0);
        List<Billing_Account__c> lstBillingAccount = [SELECT Id, uuid__c FROM Billing_Account__c WHERE UUID__c != null];
        system.assert(lstBillingAccount.size() > 0);
        List<Contact> lstContacts = [SELECT Id, uuid__c, Email FROM Contact WHERE UUID__c != null];
        system.assert(lstContacts.size() > 0);
        List<WWTypes.move_insVal> lstmove_insVal = ContractEventTestingUtility.getMoveInsForPayload(lstBuilding, lstReservable);        
        List<WWTypes.products> lstproducts = ContractEventTestingUtility.getProductsforPayload(lstBuilding, lstReservable);     
        WWTypes.ContractEvent ObjContractEventSigned = ContractEventTestingUtility.getCompletePayloadForContract('Contract Signed', lstBillingAccount[1].UUID__c, lstOpportunities[2].Primary_Member__r.Email, 'abc123jnk', 'INR', '', '2018-11-06', 'Upgrade', '', lstContacts[2].UUID__c, '', string.valueof(lstOpportunities[2].Id), null, null, lstproducts, lstmove_insVal, null);
        RESTContractEvent.Response response = ContractEventTestingUtility.callOutToContractEventEndPoint(objContractEventSigned);
        Debug.log('Response From REST API :::'+response);
        String oppoId;
        if(response.result != null && response.result != '')
            oppoId = ContractEventTestingUtility.extractIdFromResultInContractEvent(response.result);
        System.assertEquals(true, response.success);
        System.assert(response.result.startsWith('"Update Opportunity :'));
        List<Opportunity> lstOpp = [SELECT Id, Billing_Account__c, StageName, CurrencyIsoCode, Contract_Signed_On_Date__c, Contract_UUID__c, Contract_Stage__c, Type__c,(select Id, Quantity, UnitPrice, Building_UUID__c, Building__c, CurrencyIsoCode From OpportunityLineItems) FROM Opportunity WHERE ID =:oppoId];
        system.assertEquals(3, lstopp[0].OpportunityLineItems.size());//Only deal
        System.assertEquals(lstOpp[0].Id, oppoId);
        System.assertEquals('Closed Won', lstOpp[0].StageName);
        System.assertEquals('INR', lstOpp[0].CurrencyIsoCode);//To check currency value change from AUD to INR
        System.assertEquals(Date.valueOf(objContractEventSigned.contract_date), lstOpp[0].Contract_Signed_On_Date__c);
        System.assertEquals('Mixed', lstOpp[0].Type__c);
        System.assertEquals(lstOpp[0].Billing_Account__c, lstBillingAccount[1].id);
        List<Opportunity_Reservable__c> lstOpportunityReservable = [SELECT Id, Building__c, Start_Date__c, Pending_Desks__c, Monthly_Price__c, Reservable__r.UUID__c, Commitment_Terms_End_Date__c FROM Opportunity_Reservable__c WHERE opportunity__c =: oppoId];
        System.assertEquals(3, lstOpportunityReservable.size());
        List<Opportunity_Move_Outs__c> lstOpportunityMoveOut = [SELECT Id, Building__c, Move_Out_Date__c, Pending_Desks__c, Monthly_Price__c FROM Opportunity_Move_Outs__c WHERE opportunity__c =: oppoId ];
        System.assertEquals(0, lstOpportunityMoveOut.size());       
    }
    static testMethod void testDiscardContractEventMethod(){ 
        List<Opportunity> lstOpportunities = [SELECT Id, Name, Billing_Account__r.UUID__c, Primary_Member__r.Email, contract_UUId__c, (SELECT Id, Status__c, Reservable__r.UUID__c FROM Opportunity_Move_Outs__r), (Select Id, Reservable__c, Start_Date__c, Opportunity__c, Monthly_Price__c From Opportunity_Offices__r) FROM Opportunity order by createdDate];        
        Debug.log('lstOpportunities'+ lstOpportunities);
        lstOpportunities[1].contract_UUId__c = 'abcdef123';
        lstOpportunities[1].StageName = 'Closing';
        lstOpportunities[1].Contract_Stage__c = 'Contract Sent';
        TestingUtility.updateListWithAssert(lstOpportunities);
        Test.setMock(HttpCalloutMock.class, new ContractEventMockHttpResponseGenerator());
        String result = ContractEventServices.updateOppContractDiscard(lstOpportunities[0].contract_UUId__c);
        system.assertEquals('true', result);
        Test.startTest();
            String result1  = ContractEventServices.discardContractEvent(lstOpportunities[1].contract_UUId__c);
            string result2  = ContractEventServices.discardContractEvent(lstOpportunities[2].contract_UUId__c);
        Test.stopTest();
    }
    
    static testMethod void testResendpaperwork(){      
        List<Opportunity> lstOpportunities = [SELECT Id, Name, Billing_Account__r.UUID__c, Primary_Member__r.Email, contract_UUId__c, (SELECT Id, Status__c, Reservable__r.UUID__c FROM Opportunity_Move_Outs__r), (Select Id, Reservable__c, Start_Date__c, Opportunity__c, Monthly_Price__c From Opportunity_Offices__r) FROM Opportunity order by createdDate];        
        Debug.log('lstOpportunities'+ lstOpportunities);
        lstOpportunities[0].contract_UUId__c = 'abcdef123';
        TestingUtility.updateListWithAssert(lstOpportunities);
        Test.setMock(HttpCalloutMock.class, new ContractEventMockHttpResponseGenerator());
        Test.startTest();
        	String result = ContractEventServices.resendPaperworkLightning(lstOpportunities[0].contract_UUId__c);
        Test.stopTest();
        Opportunity opp = ContractEventServices.getOppData(lstOpportunities[0].Id);
        System.assertNotEquals(null, opp);
}
}