objects/Billing_Account__c.object
<CustomObject>
    <description>All Billing account is moved to this Billing Account object it help Sales people to identify Org and Sales account easily and reduce the clutter of 100s of Accounts with same name.</description>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Building__c.object
<CustomObject>
    <fields>
        <fullName>Geography__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is a lookup of Geography object which is used to represent Google Maps Location so that we can reuse the same location as and when required within multiple objects.</description>
        <inlineHelpText>This field provides the exact or nearest google location where the building is located.</inlineHelpText>
        <label>Geography</label>
        <referenceTo>Geography__c</referenceTo>
        <relationshipLabel>Buildings</relationshipLabel>
        <relationshipName>Buildings_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Building</label>
    <nameField>
        <label>Building</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Geography__c.object
<CustomObject>
    <description>This object will represent Google Maps Location so that we can reuse same location as and when required within multiple objects.</description>
    <label>Geography</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Geographies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field relates the opportunity to the billing account. The billing account is used in the space station for sending contracts.</description>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Building__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Enter the specific building for which opportunity is associated</description>
        <inlineHelpText>This is the building / Nearest building to the geography entered by customer</inlineHelpText>
        <label>Building/Nearest Building</label>
        <referenceTo>Building__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Building_uuid__c</fullName>
        <formula>Building__r.UUID__c</formula>
        <label>Building uuid</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_Size__c</fullName>
        <label>Company Size</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1-5</fullName>
                </value>
                <value>
                    <fullName>6-20</fullName>
                </value>
                <value>
                    <fullName>21-50</fullName>
                </value>
                <value>
                    <fullName>51-100</fullName>
                </value>
                <value>
                    <fullName>101-200</fullName>
                </value>
                <value>
                    <fullName>201+</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Geography__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will show the location where the lead is interested to find the spaces.</description>
        <inlineHelpText>Search for the relevant geographic location</inlineHelpText>
        <label>Geography</label>
        <referenceTo>Geography__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Interested_in_Number_of_Desks__c</fullName>
        <label>Interested in Number of Desk(s)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Building_UUID__c</fullName>
        <description>This is populated from the payload of product in contract event</description>
        <externalId>true</externalId>
        <label>Building_UUID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Building__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is filled from contract event in the pay of products.</description>
        <inlineHelpText>Enter the relevant building. If 'Geography' was selected previously, the nearest building will appear.</inlineHelpText>
        <label>Building</label>
        <referenceTo>Building__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Family__c</fullName>
        <label>Product Family</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Membership</fullName>
                </value>
                <value>
                    <fullName>WeWork Off the Shelf Office</fullName>
                </value>
                <value>
                    <fullName>WeWork Customized Office</fullName>
                </value>
                <value>
                    <fullName>Envision</fullName>
                </value>
                <value>
                    <fullName>Design/Build</fullName>
                </value>
                <value>
                    <fullName>Operate</fullName>
                </value>
                <value>
                    <fullName>Custom</fullName>
                </value>
                <value>
                    <fullName>WeWork</fullName>
                </value>
                <value>
                    <fullName>Technology</fullName>
                </value>
                <value>
                    <fullName>Global Access</fullName>
                </value>
                <value>
                    <fullName>PxWe</fullName>
                </value>
                <value>
                    <fullName>Enterprise Solutions</fullName>
                </value>
                <value>
                    <fullName>Partnership</fullName>
                </value>
                <value>
                    <fullName>Mid Market</fullName>
                </value>
                <value>
                    <fullName>Standard Product</fullName>
                </value>
                <value>
                    <fullName>Powered by We</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Geography__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Enter a relevant geographical location no building can be specified.</inlineHelpText>
        <label>Geography</label>
        <referenceTo>Geography__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Primary_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This Field is used to identify primary product on opportunity.</description>
        <label>Is Primary Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PxWe</fullName>
                </value>
                <value>
                    <fullName>Global Access</fullName>
                </value>
                <value>
                    <fullName>Hot Desk</fullName>
                </value>
                <value>
                    <fullName>WeMembership</fullName>
                </value>
                <value>
                    <fullName>Dedicated Desk</fullName>
                </value>
                <value>
                    <fullName>Standard Office</fullName>
                </value>
                <value>
                    <fullName>Custom Office</fullName>
                </value>
                <value>
                    <fullName>Large Office(WWLO)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

objects/OpportunityStagesSetting__mdt.object
<CustomObject>
    <fields>
        <fullName>DefaultProductCode__c</fullName>
        <description>This field contains default product code.</description>
        <inlineHelpText>This field contains default product code.</inlineHelpText>
        <label>DefaultProductCode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stages__c</fullName>
        <description>This field will store the stages of the opportunity object</description>
        <inlineHelpText>Enter the opportunity stage here</inlineHelpText>
        <label>Stages</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <description>This custom metadata will be used to store the stages as per the scenarios like allowed stages to create products etc</description>
    <label>OpportunityStagesSetting</label>
    <pluralLabel>OpportunityStagesSettings</pluralLabel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Default_Product_Category__c</fullName>
        <label>Default Product Category</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Standard Office</fullName>
                </value>
                <value>
                    <fullName>Large Office(WWLO)</fullName>
                </value>
                <value>
                    <fullName>Custom Office</fullName>
                </value>
                <value>
                    <fullName>PxWe</fullName>
                </value>
                <value>
                    <fullName>Global Access</fullName>
                </value>
                <value>
                    <fullName>Dedicated Desk</fullName>
                </value>
                <value>
                    <fullName>Hot Desk</fullName>
                </value>
                <value>
                    <fullName>WeMembership</fullName>
                </value>
                <value>
                    <fullName>Desk</fullName>
                </value>
                <value>
                    <fullName>Private Office</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <label>Product Category</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Standard Office</fullName>
                </value>
                <value>
                    <fullName>Custom Office</fullName>
                </value>
                <value>
                    <fullName>Large Office(WWLO)</fullName>
                    <label>Large Office (WWLO)</label>
                </value>
                <value>
                    <fullName>PxWe</fullName>
                </value>
                <value>
                    <fullName>Global Access</fullName>
                </value>
                <value>
                    <fullName>Dedicated Desk</fullName>
                </value>
                <value>
                    <fullName>Hot Desk</fullName>
                </value>
                <value>
                    <fullName>WeMembership</fullName>
                </value>
                <value>
                    <fullName>TEEM</fullName>
                </value>
                <value>
                    <fullName>Desk</fullName>
                </value>
                <value>
                    <fullName>WeWork</fullName>
                    <isActive>false</isActive>
                    <label>WeWork</label>
                </value>
                <value>
                    <fullName>WeWork Desks</fullName>
                    <isActive>false</isActive>
                    <label>WeWork Desks</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TrOpportunityCreateOppProduct.cls
/************************************************************************************************************************************
    Author 		: 	Pragalbha Mahajan
    Description : 	This class contains the business logic of createOpportunityProduct Trigger.
    History		:
	----------------------------------------------------------------------------------------------------------------------------------
	VERSION		DATE				AUTHOR					DETAIL
	1			15 November 2018	Pragalbha Mahajan     	Initial Development	 
**************************************************************************************************************************************/
public class TrOpportunityCreateOppProduct implements IProcessHandler{
    public static String defaultProductCode ;
    
    public void handle(List<sObject> triggerNew, Map<Id, sObject> triggerOldMap){
        createOpportunityProduct((list<Opportunity>)triggerNew);
    }
    
    /************************************************************************************************************************************
    Author 				: 	Pragalbha Mahajan
    Description 		: 	This method is used to create Opportunity Line Item. 
    Issue No.			:	ST-3076
	Created Date		:	15 November 2018
    **************************************************************************************************************************************/ 
    public static void createOpportunityProduct(list<Opportunity> lstNewOpportunity){
        Set<String> setAllowedStages = new Set<String>();
        getInitialSettingData(setAllowedStages);
        Set<Id> setAccountIds = new Set<Id>();
        Set<Id> setBillingAccount = new Set<Id>();
        Set<String> setCurrencies = new Set<String>();
        for(Opportunity opp : lstNewOpportunity){
            if(String.isNotBlank(opp.StageName) && setAllowedStages.contains(opp.StageName.toLowerCase())){
                setCurrencies.add(opp.CurrencyISOCode);
                setAccountIds.add(opp.AccountId);
                setBillingAccount.add(opp.Billing_Account__c);
            }
        }
        if(setCurrencies.size() > 0){
            List<OpportunityLineItem> lstOpportunityProduct = getProducts(lstNewOpportunity, setCurrencies, setAllowedStages);
            if(lstOpportunityProduct.size() > 0){
                mapProductFamilyAndCategory(lstOpportunityProduct);
                Database.insert(lstOpportunityProduct);
            }
        }
    }
    
    /************************************************************************************************************************************
    Author 				: 	Milanjeet Singh
    Description 		: 	This helper method is used to get the quantity of Products by Interested in Number of Desks and Company Size 
    Issue No.			:	-
	Created Date		:	16 November 2018
    **************************************************************************************************************************************/ 
    public static Map<Id, Integer> getQuantityMap(List<Opportunity> lstOpportunity){
        Map<Id, Integer> mapQuantity = new Map<Id, Integer>();
        for(Opportunity objOpportunity : lstOpportunity){
            if(String.isEmpty(String.valueOf(objOpportunity.Interested_in_Number_of_Desks__c))){
                String strCompanySize = (String.isBlank(objOpportunity.Company_Size__c) ? '1' : (objOpportunity.Company_Size__c.contains('-') ? (objOpportunity.Company_Size__c.split('-')[0]) : (objOpportunity.Company_Size__c.contains('+') ? (objOpportunity.Company_Size__c.substring(0, objOpportunity.Company_Size__c.indexOf('+'))) : (objOpportunity.Company_Size__c.split(' ')[0]))));
                if(String.isNotBlank(strCompanySize) && strCompanySize.contains(',')){
                    strCompanySize = strCompanySize.remove(',');
                }
                strCompanySize = strCompanySize.trim();
                mapQuantity.put(objOpportunity.Id, Integer.valueOf(strCompanySize));
            }else{
                mapQuantity.put(objOpportunity.Id, Integer.valueOf(objOpportunity.Interested_in_Number_of_Desks__c));
            }
        }
        return mapQuantity;
    }
    
    /************************************************************************************************************************************
    Author 				: 	Milanjeet Singh
    Description 		: 	This helper method is used to get the Products by quantity
    Issue No.			:	-
	Created Date		:	16 November 2018
    **************************************************************************************************************************************/ 
    public static List<OpportunityLineItem> getProducts(List<Opportunity> lstOpportunity, Set<String> setCurrencies, Set<String> setAllowedStages){
        List<OpportunityLineItem> lstOpportunityProduct = new List<OpportunityLineItem>();
        Map<Id, Integer> mapQuantity = getQuantityMap(lstOpportunity);
        Map<String, PricebookEntry> mapEntries = getPriceBookEntryByProductCode(defaultProductCode, setCurrencies);
        for(Opportunity objOpportunity : lstOpportunity){
            if(String.isNotBlank(objOpportunity.StageName) && setAllowedStages.contains(objOpportunity.StageName.toLowerCase()) && mapEntries.size() > 0){ 
                if(mapEntries.containsKey(objOpportunity.CurrencyISOCode) && mapEntries.get(objOpportunity.CurrencyISOCode) != null && mapQuantity.get(objOpportunity.Id) > 0){
                    lstOpportunityProduct.add(new OpportunityLineItem(PricebookEntryId = mapEntries.get(objOpportunity.CurrencyISOCode).Id, OpportunityId = objOpportunity.Id, Quantity = mapQuantity.get(objOpportunity.Id), UnitPrice = 450, Building__c = objOpportunity.Building__c, Geography__c = objOpportunity.Geography__c, Building_UUID__c = objOpportunity.Building_uuid__c, Is_Primary_Product__c = true));
                }
            }
        }
        return lstOpportunityProduct;
    }
    
    /************************************************************************************************************************************
    Author 				: 	Milanjeet Singh
    Description 		: 	This helper method is used to get pricebook entries by currencies and product code.
    Issue No.			:	-
	Created Date		:	16 November 2018
    **************************************************************************************************************************************/ 
    public static Map<String, PricebookEntry> getPriceBookEntryByProductCode(String productCode, Set<String> setCurrencies){
        Map<String, PricebookEntry> mapPricebookEntries = new Map<String,PricebookEntry>();
        for(PricebookEntry entry:[SELECT Id, Name, CurrencyIsoCode, UnitPrice FROM PricebookEntry WHERE ProductCode =: productCode AND CurrencyIsoCode IN:setCurrencies]){
            mapPricebookEntries.put(entry.CurrencyISOCode, entry);
        }
        return mapPricebookEntries;
    }
    
    /************************************************************************************************************************************
    Author 				: 	Milanjeet Singh
    Description 		: 	This helper method is used to map the product family and category
    Issue No.			:	-
	Created Date		:	16 November 2018
    **************************************************************************************************************************************/ 
    public static void mapProductFamilyAndCategory(List<OpportunityLineItem> lstOpportunityProduct){
        List<Product2> lstProducts = Settings.getProductsByProductCode(defaultProductCode);
        Product2 objDefaultProduct = lstProducts != null ? lstProducts[0] : null;
        for(OpportunityLineItem oppLineItem : lstOpportunityProduct){
            if(objDefaultProduct != null && objDefaultProduct.Default_Product_Category__c != null){
                oppLineItem.Product_Category__c = objDefaultProduct.Default_Product_Category__c;
            }
            if(objDefaultProduct != null && objDefaultProduct.Family != null){
                oppLineItem.Family__c = objDefaultProduct.Family;
            }
        }
    }
    
	/************************************************************************************************************************************
    Author 				: 	Pragalbha Mahajan
    Description 		: 	This method is used to get InitialSettingData
    Issue No.			:	ST-3076
	Created Date		:	20 November 2018
    **************************************************************************************************************************************/     
    public static Set<String> getInitialSettingData(Set<String> setAllowedStages){
        Set<String> setFields = new Set<String>();
        setFields.add('Stages__c');
        setFields.add('DefaultProductCode__c'); 
        List<OpportunityStagesSetting__mdt> oppStageSettings = (List<OpportunityStagesSetting__mdt>)Settings.getFieldsFromMDT('OpportunityStagesSetting__mdt', 'AllowedStagesForOppProduct', setFields);
        if(oppStageSettings != null && !oppStageSettings.isEmpty()){
            if(String.isNotEmpty(oppStageSettings[0].Stages__c)){
                setAllowedStages.addAll(Settings.splitStringToSet(oppStageSettings[0].Stages__c, ';'));
            }
            defaultProductCode = oppStageSettings[0].DefaultProductCode__c;
        }
        return setAllowedStages;
    }
}