objects/Billing_Account__c.object
<CustomObject>
    <fields>
        <fullName>UUID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>This is unique,case sensitive auto generated field used to identify Billing Account record.</description>
        <externalId>true</externalId>
        <inlineHelpText>This is unique,case sensitive auto generated field used to identify Billing Account record.</inlineHelpText>
        <label>UUID</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <description>All Billing account is moved to this Billing Account object it help Sales people to identify Org and Sales account easily and reduce the clutter of 100s of Accounts with same name.</description>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Building__c.object
<CustomObject>
    <fields>
        <fullName>UUID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Building</label>
    <nameField>
        <label>Building</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Members</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Building__c</fullName>
        <description>Pulls Building Location without 3 character city reference</description>
        <formula>Location__r.Location_No_City__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Building</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reservable__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reservable</label>
        <referenceTo>Reservable__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This is the latest status coming from Space systems through Jitterbunny of the individual member. This tells us if the user is active or not.</description>
        <inlineHelpText>This is accurate status of a contact if it is an active member of our products or not.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>active</fullName>
                </value>
                <value>
                    <fullName>inactive</fullName>
                    <default>true</default>
                    <label>inactive</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UUID__c</fullName>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field relates the opportunity to the billing account. The billing account is used in the space station for sending contracts.</description>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Building__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Enter the specific building for which opportunity is associated</description>
        <inlineHelpText>This is the building / Nearest building to the geography entered by customer</inlineHelpText>
        <label>Building/Nearest Building</label>
        <referenceTo>Building__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract_UUID__c</fullName>
        <description>contractEvent Endpoint will contain 'Contract UUID' to search Opportunity</description>
        <externalId>true</externalId>
        <inlineHelpText>contractEvent Endpoint will contain 'Contract UUID' to search Opportunity</inlineHelpText>
        <label>Contract UUID</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity_Move_Outs__c.object
<CustomObject>
    <fields>
        <fullName>Building__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>When we get building uuid insted of reservable uuid in Contract event payload map here.</description>
        <inlineHelpText>When we get building uuid insted of reservable uuid in Contract event payload map here.</inlineHelpText>
        <label>Sellable Building</label>
        <referenceTo>Building__c</referenceTo>
        <relationshipLabel>Opportunity Move Outs</relationshipLabel>
        <relationshipName>Opportunity_Move_Outs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Monthly_Price__c</fullName>
        <label>Monthly Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Move Outs (from "there")</relationshipLabel>
        <relationshipName>Opportunity_Move_Outs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reservable__c</fullName>
        <label>Reservable</label>
        <referenceTo>Reservable__c</referenceTo>
        <relationshipLabel>Opportunity Move Outs</relationshipLabel>
        <relationshipName>Opportunity_Move_Outs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Cancel</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>We will capture  Move Outs of opportunity which are coming from Contract event</description>
    <label>Opportunity Move Out</label>
    <nameField>
        <displayFormat>MO-{0000000}</displayFormat>
        <label>Opportunity Move Outs Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Move Outs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity_Reservable__c.object
<CustomObject>
    <fields>
        <fullName>Building__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>When we get building uuid insted of reservable uuid in Contract event payload map here.</description>
        <inlineHelpText>When we get building uuid insted of reservable uuid in Contract event payload map here.</inlineHelpText>
        <label>Sellable Building</label>
        <referenceTo>Building__c</referenceTo>
        <relationshipLabel>Opportunity Reservables</relationshipLabel>
        <relationshipName>Opportunity_Reservables</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Monthly_Price__c</fullName>
        <label>Monthly Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Reservables</relationshipLabel>
        <relationshipName>Opportunity_Offices</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reservable__c</fullName>
        <label>Reservable</label>
        <referenceTo>Reservable__c</referenceTo>
        <relationshipLabel>Opportunity Reservables</relationshipLabel>
        <relationshipName>Opportunity_Offices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Value of start date from Contract Event endpoint</description>
        <inlineHelpText>Value of start date from Contract Event endpoint</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Opportunity Reservable</label>
    <nameField>
        <displayFormat>OO-{0000}</displayFormat>
        <label>Office ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Reservables</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Reservable__c.object
<CustomObject>
    <fields>
        <fullName>Building__c</fullName>
        <label>Building</label>
        <referenceTo>Building__c</referenceTo>
        <relationshipLabel>Reservables</relationshipLabel>
        <relationshipName>Offices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Monthly_Price__c</fullName>
        <label>Monthly Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Available</fullName>
                </value>
                <value>
                    <fullName>Unavailable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UUID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Reservable</label>
    <nameField>
        <label>Reservable Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reservables</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ContractEventHotDeskTest.cls
/**
* Name			:	ContractEventHotDeskTest	 
* Issue No.		: 	CSI-441 
* Purpose		:	Test Methods for ContractEventHotDesk
	Version			Author				Date			Detail				Feature
	1.0				Samadhan Kadam		22/01/2018		Initial Development	
***********************************************************************************************************************************************************
*/ 

@isTest
public class ContractEventHotDeskTest { 
   @TestSetup 
    static void testDataSetUp(){
        TriggerSettings.mappedField.Billing_Account_mapParentAccount = false;
        ContractEventTestingUtility.getContractDataForAllEvents();
        //TriggerSettings.mappedField.Billing_Account_mapParentAccount = true;
    }
    static testMethod void verifyHotDeskCancellationExistingOpportunity(){
        List<Reservable__c> lstReservable = [SELECT Id, uuid__c, Building__c FROM Reservable__c WHERE UUID__c != null];
        system.assert(lstReservable.size() > 0);
        Set<Id> setBuildingIds = new Set<Id>();
        for(Reservable__c obj : lstReservable){
            setBuildingIds.add(obj.Building__c);
        }
        List<Opportunity> lstOpportunities = [SELECT Id, Name, contract_uuid__c, Billing_Account__r.UUID__c, (SELECT Id, Status__c,Reservable__r.UUID__c FROM Opportunity_Move_Outs__r), (Select Id, Reservable__c, Start_Date__c, Opportunity__c, Monthly_Price__c From Opportunity_Offices__r) FROM Opportunity order by createdDate LIMIT 1];        
        String company_uuid = lstOpportunities[0].Billing_Account__r.UUID__c;
        Opportunity opportunity= lstOpportunities[0];
        opportunity.Billing_Account__c = null;
        update opportunity;
        List<Billing_Account__c> lstBillingAccount = [SELECT Id, uuid__c FROM Billing_Account__c WHERE UUID__c != null];
        system.assert(lstBillingAccount.size() > 0);
        List<Contact> lstContacts = [SELECT Id, uuid__c, Email FROM Contact WHERE UUID__c != null];
        system.assert(lstContacts.size() > 0);
        List<Building__c> lstBuilding = [SELECT Id, uuid__c FROM Building__c WHERE UUID__c != null AND Id In : setBuildingIds];
        system.assert(lstBuilding.size() > 0);
        List<WWTypes.move_insVal> lstmove_insVal = ContractEventTestingUtility.getMoveInsForPayload(lstBuilding, lstReservable); 
        List<WWTypes.move_outssVal> lstmove_outssVal = ContractEventTestingUtility.getMoveOutsforPayload(lstBuilding, lstReservable);
        List<WWTypes.products> lstproductss = ContractEventTestingUtility.getProductsforPayload(lstBuilding, lstReservable);
        WWTypes.ContractEvent ObjContractEvent = ContractEventTestingUtility.getCompletePayloadForContract('Contract Canceled', company_uuid, lstContacts[0].Email, 'test', 'USD', 'www.test.com,www.test1.com', String.valueOf(Date.today().addDays(-2)), null, null, null, null, opportunity.Id, null, null, lstproductss, lstmove_insVal, lstmove_outssVal);
        ObjContractEvent.reservation_uuid = 'reservationuuid' ;
        ObjContractEvent.lead_source = 'lead_source';
        ObjContractEvent.lead_source_detail = 'lead_source_detail';
        Debug.log('ObjContractEventObjContractEvent'+ObjContractEvent);
        RESTContractEvent.Response response = ContractEventTestingUtility.callOutToContractEventEndPoint(ObjContractEvent);
        Debug.log('responseresponse123'+response);		
        System.assertEquals(true, response.success);
        Id OpportunityId; 
        if(response.result != null && response.result != '')
            OpportunityId = ContractEventTestingUtility.extractIdFromResultInContractEvent(response.result);
        Opportunity opp = ContractEventTestingUtility.getOpportunityAfterContractRequest(OpportunityId);
        ContractEventTestingUtility.payloadAssertion(ObjContractEvent, opp, null);
        
    }
    
    static testMethod void verifyHotDeskCancellationNewOpportunityCreation(){
        List<Reservable__c> lstReservable = [SELECT Id, uuid__c, Building__c FROM Reservable__c WHERE UUID__c != null];
        system.assert(lstReservable.size() > 0);
        Set<Id> setBuildingIds = new Set<Id>();
        for(Reservable__c obj : lstReservable){
            setBuildingIds.add(obj.Building__c);
        }
        List<Opportunity> lstOpportunities = [SELECT Id, Name, contract_uuid__c, Billing_Account__r.UUID__c, (SELECT Id, Status__c,Reservable__r.UUID__c FROM Opportunity_Move_Outs__r), (Select Id, Reservable__c, Start_Date__c, Opportunity__c, Monthly_Price__c From Opportunity_Offices__r) FROM Opportunity order by createdDate LIMIT 1];        
        List<Billing_Account__c> lstBillingAccount = [SELECT Id, uuid__c FROM Billing_Account__c WHERE UUID__c != null];
        system.assert(lstBillingAccount.size() > 0);
        List<Contact> lstContacts = [SELECT Id, uuid__c, Email FROM Contact WHERE UUID__c != null];
        system.assert(lstContacts.size() > 0);
        List<Building__c> lstBuilding = [SELECT Id, uuid__c FROM Building__c WHERE UUID__c != null AND Id In : setBuildingIds];
        system.assert(lstBuilding.size() > 0);
        List<WWTypes.move_insVal> lstmove_insVal = ContractEventTestingUtility.getMoveInsForPayload(lstBuilding, lstReservable); 
        List<WWTypes.move_outssVal> lstmove_outssVal = ContractEventTestingUtility.getMoveOutsforPayload(lstBuilding, lstReservable);
        List<WWTypes.products> lstproductss = ContractEventTestingUtility.getProductsforPayload(lstBuilding, lstReservable);
        WWTypes.ContractEvent ObjContractEvent = ContractEventTestingUtility.getCompletePayloadForContract('Contract Canceled', lstBillingAccount[0].UUID__c, lstContacts[0].Email, 'test', 'USD', 'www.test.com,www.test1.com', String.valueOf(Date.today().addDays(-2)), null, null, null, null, null, null,null, lstproductss, lstmove_insVal, lstmove_outssVal);
        Debug.log('ObjContractEventObjContractEvent'+ObjContractEvent);
        ObjContractEvent.reservation_uuid = 'reservationuuid' ;
        ObjContractEvent.lead_source = 'lead_source';
        ObjContractEvent.lead_source_detail = 'lead_source_detail';
        RESTContractEvent.Response response = ContractEventTestingUtility.callOutToContractEventEndPoint(ObjContractEvent);
        Debug.log('responseresponse123'+response);		
        System.assertEquals(true, response.success);
        Id OpportunityId; 
        if(response.result != null && response.result != '')
            OpportunityId = ContractEventTestingUtility.extractIdFromResultInContractEvent(response.result);
        Opportunity opp = ContractEventTestingUtility.getOpportunityAfterContractRequest(OpportunityId);
        ContractEventTestingUtility.payloadAssertion(ObjContractEvent, opp, null);
    }
    
    static testMethod void verifyHotDeskOpportunityUpdate(){
        List<Opportunity> lstOpportunities = [SELECT Id, Name, contract_uuid__c, Billing_Account__r.UUID__c, (SELECT Id, Status__c,Reservable__r.UUID__c FROM Opportunity_Move_Outs__r), (Select Id, Reservable__c, Start_Date__c, Opportunity__c, Monthly_Price__c From Opportunity_Offices__r) FROM Opportunity order by createdDate LIMIT 1];        
        List<Reservable__c> lstReservable = [SELECT Id, uuid__c, Building__c FROM Reservable__c WHERE UUID__c != null];
        system.assert(lstReservable.size() > 0);
        Set<Id> setBuildingIds = new Set<Id>();
        for(Reservable__c obj : lstReservable){
            setBuildingIds.add(obj.Building__c);
        }
        List<Billing_Account__c> lstBillingAccount = [SELECT Id, uuid__c FROM Billing_Account__c WHERE UUID__c != null];
        system.assert(lstBillingAccount.size() > 0);
        List<Contact> lstContacts = [SELECT Id, uuid__c, Email FROM Contact WHERE UUID__c != null];
        system.assert(lstContacts.size() > 0);
        List<Building__c> lstBuilding = [SELECT Id, uuid__c FROM Building__c WHERE UUID__c != null AND Id In : setBuildingIds];
        system.assert(lstBuilding.size() > 0);
        List<WWTypes.move_insVal> lstmove_insVal = ContractEventTestingUtility.getMoveInsForPayload(lstBuilding, lstReservable); 
        List<WWTypes.move_outssVal> lstmove_outssVal = ContractEventTestingUtility.getMoveOutsforPayload(lstBuilding, lstReservable);
        List<WWTypes.products> lstproductss = ContractEventTestingUtility.getProductsforPayload(lstBuilding, lstReservable);
        WWTypes.ContractEvent ObjContractEvent = ContractEventTestingUtility.getCompletePayloadForContract('Contract Signed', lstBillingAccount[0].UUID__c, lstContacts[0].Email, 'test', 'USD', 'www.test.com,www.test1.com', String.valueOf(Date.today().addDays(-2)), null, null, null, null, String.valueOf(lstOpportunities[0].Id),'testOppReservation', null, null,  lstproductss, lstmove_insVal, lstmove_outssVal);
        Debug.log('ObjContractEventObjContractEvent'+ObjContractEvent);
        ObjContractEvent.reservation_uuid = 'reservationuuid' ;
        ObjContractEvent.lead_source = 'lead_source';
        ObjContractEvent.lead_source_detail = 'lead_source_detail';
        RESTContractEvent.Response response = ContractEventTestingUtility.callOutToContractEventEndPoint(ObjContractEvent);
        Debug.log('responseresponse123'+response);		
        System.assertEquals(true, response.success);
        Id OpportunityId; 
        if(response.result != null && response.result != '')
            OpportunityId = ContractEventTestingUtility.extractIdFromResultInContractEvent(response.result);
        Opportunity opp = ContractEventTestingUtility.getOpportunityAfterContractRequest(OpportunityId);
        ContractEventTestingUtility.payloadAssertion(ObjContractEvent, opp, null);
    }
}