objects/Building__c.object
<CustomObject>
    <fields>
        <fullName>UUID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Building</label>
    <nameField>
        <label>Building</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Reservable__c.object
<CustomObject>
    <fields>
        <fullName>Building__c</fullName>
        <label>Building</label>
        <referenceTo>Building__c</referenceTo>
        <relationshipLabel>Reservables</relationshipLabel>
        <relationshipName>Offices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>UUID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Reservable</label>
    <nameField>
        <label>Reservable Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reservables</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ContractEventValidationsTest.cls
/**
* Name			:	ContractEventValidationsTest	 
* Issue No.		: 	
* Purpose		:	This contains the test methods of all the custom validations in contract event.
* History		
	Version			Author				Date			Detail						Feature			IssueNumber
	1.0				Rupesh Patil		1/31/2018		Initial Development							
***********************************************************************************************************************************************************
*/
@isTest
public class ContractEventValidationsTest {
    
    @TestSetup 
    static void testDataSetup(){
        ContractEventTestingUtility.getContractDataForAllEvents();
    }
    public static testMethod void testContractReservableNotFoundError(){
        List<Reservable__c> lstReservable = [SELECT Id, uuid__c, Building__c FROM Reservable__c WHERE UUID__c != null];
        system.assert(lstReservable.size() > 0);
        Set<Id> setBuildingIds = new Set<Id>();
        for(Reservable__c obj : lstReservable){
            setBuildingIds.add(obj.Building__c);
        }
        List<Building__c> lstBuilding = [SELECT Id, uuid__c FROM Building__c WHERE UUID__c != null AND Id In : setBuildingIds];
        system.assert(lstBuilding.size() > 0);
        List<WWTypes.move_insVal> lstmove_insVal = ContractEventTestingUtility.getMoveInsForPayload(lstBuilding, lstReservable);        
        List<WWTypes.move_outssVal> lstmove_outssVal = ContractEventTestingUtility.getMoveOutsforPayload(lstBuilding, lstReservable);
        for(WWTypes.move_insVal moveIn: lstmove_insVal){
            moveIn.reservable_uuid = 'objreservable_uuid_not_found';
            break;
        }
        TestingUtility.updateListWithAssert(lstReservable);
        WWTypes.ContractEvent ObjContractEvent = ContractEventTestingUtility.getCompletePayloadForContract('Contract Sent', 'testBilingAccountUUID1', 'testcontact1RestCon@example.com', 'FailedMembership', 'AUD', 'www.test.com,www.test1.com', '', '', '', '', '', null, null, null, null, lstmove_insVal, lstmove_outssVal);
        RESTContractEvent.Response response = ContractEventTestingUtility.callOutToContractEventEndPoint(ObjContractEvent);
        Debug.log('response pEx message---'+response);
        System.assertEquals(false, response.success);
        system.assertEquals(response.message.contains('objreservable_uuid_not_found,'), true);
    } 
}