objects/Building__c.object
<CustomObject>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Buildings</relationshipLabel>
        <relationshipName>Buildings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Community_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>&gt;&gt;&gt;used for assignment of transactional deal type</inlineHelpText>
        <label>Community Lead</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Buildings3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Portfolio</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Buildings</relationshipLabel>
        <relationshipName>Buildings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Building</label>
    <nameField>
        <label>Building</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/City__c.object
<CustomObject>
    <fields>
        <fullName>Portfolio__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Portfolio</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Cities</relationshipLabel>
        <relationshipName>Cities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Cluster__c.object
<CustomObject>
    <fields>
        <fullName>Cluster_Sales_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cluster Sales Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Clusters1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>&gt;&gt;&gt;used for ROE assignment</inlineHelpText>
        <label>Sales Lead</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Clusters</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Cluster</label>
    <nameField>
        <label>Cluster</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Country__c.object
<CustomObject>
    <fields>
        <fullName>Portfolio__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Portfolio</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Countries</relationshipLabel>
        <relationshipName>Countries</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alexandria</fullName>
                </value>
                <value>
                    <fullName>Alpharetta</fullName>
                </value>
                <value>
                    <fullName>Amsterdam</fullName>
                </value>
                <value>
                    <fullName>Ann Arbor</fullName>
                </value>
                <value>
                    <fullName>Arlington</fullName>
                </value>
                <value>
                    <fullName>Atlanta</fullName>
                </value>
                <value>
                    <fullName>Austin</fullName>
                </value>
                <value>
                    <fullName>Balston</fullName>
                </value>
                <value>
                    <fullName>Baltimore</fullName>
                </value>
                <value>
                    <fullName>Bangalore</fullName>
                </value>
                <value>
                    <fullName>Bangkok</fullName>
                </value>
                <value>
                    <fullName>Barcelona</fullName>
                </value>
                <value>
                    <fullName>Barranquilla</fullName>
                </value>
                <value>
                    <fullName>Be'er Sheva</fullName>
                </value>
                <value>
                    <fullName>Beijing</fullName>
                </value>
                <value>
                    <fullName>Bellevue</fullName>
                </value>
                <value>
                    <fullName>Belo Horizonte</fullName>
                </value>
                <value>
                    <fullName>Bengaluru</fullName>
                </value>
                <value>
                    <fullName>Berkeley</fullName>
                </value>
                <value>
                    <fullName>Berlin</fullName>
                </value>
                <value>
                    <fullName>Bethesda</fullName>
                </value>
                <value>
                    <fullName>Bogota</fullName>
                </value>
                <value>
                    <fullName>Bogotá</fullName>
                </value>
                <value>
                    <fullName>Boston</fullName>
                </value>
                <value>
                    <fullName>Boulder</fullName>
                </value>
                <value>
                    <fullName>Brasilia</fullName>
                </value>
                <value>
                    <fullName>Brisbane</fullName>
                </value>
                <value>
                    <fullName>Bronx</fullName>
                </value>
                <value>
                    <fullName>Brooklyn</fullName>
                </value>
                <value>
                    <fullName>Brussels</fullName>
                </value>
                <value>
                    <fullName>Frankfurt</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Market__c.object
<CustomObject>
    <fields>
        <fullName>Portfolio_Sales_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Senior Sales Exec of Portfolio</inlineHelpText>
        <label>Portfolio Sales Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Markets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Portfolio__c</fullName>
        <description>Display name for portfolio, something user friendly to end users</description>
        <inlineHelpText>Display name (text)</inlineHelpText>
        <label>Portfolio Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <formula>TerritoryID__r.RegionID__r.Region__c</formula>
        <inlineHelpText>Display name (text)</inlineHelpText>
        <label>Region Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TerritoryID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Territory</label>
        <referenceTo>Territory__c</referenceTo>
        <relationshipLabel>Portfolios</relationshipLabel>
        <relationshipName>Portfolio</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <formula>TerritoryID__r.Territory__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Display name (text)</inlineHelpText>
        <label>Territory Name</label>
        <type>Text</type>
    </fields>
    <description>We are introducing new object Market so that same building can fall under multiple Markets as per Marketing department requirement.</description>
    <label>Portfolio</label>
    <nameField>
        <label>Portfolio</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portfolios</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Region__c.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <description>Display name for region</description>
        <inlineHelpText>Display name (text)</inlineHelpText>
        <label>Region Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Regional_Sales_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Senior Sales Exec of Region</inlineHelpText>
        <label>Regional Sales Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Regions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Region</label>
    <nameField>
        <label>Region</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Territory__c.object
<CustomObject>
    <fields>
        <fullName>RegionID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Region</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Territories</relationshipLabel>
        <relationshipName>Territories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <formula>RegionID__r.Region__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Display name (text)</inlineHelpText>
        <label>Region Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory_Sales_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Senior Sales Exec of Territory</inlineHelpText>
        <label>Territory Sales Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <description>Display Name for Territory, something user friendly to user</description>
        <inlineHelpText>Display name (text)</inlineHelpText>
        <label>Territory Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Territory</label>
    <nameField>
        <label>Territory</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Building__c</fullName>
        <label>Building</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AMS-Metropool</fullName>
                </value>
                <value>
                    <fullName>AMS-Labs</fullName>
                </value>
                <value>
                    <fullName>AMS-Weteringschans</fullName>
                </value>
                <value>
                    <fullName>ATX-Congress</fullName>
                </value>
                <value>
                    <fullName>ATX-Labs</fullName>
                </value>
                <value>
                    <fullName>BKN-Dumbo Heights</fullName>
                </value>
                <value>
                    <fullName>BK-Williamsburg</fullName>
                </value>
                <value>
                    <fullName>BOS-Fort Point</fullName>
                </value>
                <value>
                    <fullName>BOS-Labs</fullName>
                </value>
                <value>
                    <fullName>BOS-South Station</fullName>
                </value>
                <value>
                    <fullName>CHI-Fulton Market</fullName>
                </value>
                <value>
                    <fullName>CHI-Labs</fullName>
                </value>
                <value>
                    <fullName>CHI-RiverNorth</fullName>
                </value>
                <value>
                    <fullName>DC-Chinatown</fullName>
                </value>
                <value>
                    <fullName>DC-DuPont Circle</fullName>
                </value>
                <value>
                    <fullName>DC-Labs</fullName>
                </value>
                <value>
                    <fullName>DC-Wonder Bread Factory</fullName>
                </value>
                <value>
                    <fullName>ISR-Labs</fullName>
                </value>
                <value>
                    <fullName>LA-Fine Arts</fullName>
                </value>
                <value>
                    <fullName>LA-Fine Arts Building</fullName>
                </value>
                <value>
                    <fullName>LA-Hollywood</fullName>
                </value>
                <value>
                    <fullName>LA-Labs</fullName>
                </value>
                <value>
                    <fullName>LA-Promenade</fullName>
                </value>
                <value>
                    <fullName>LA-Santa Monica</fullName>
                </value>
                <value>
                    <fullName>LON-Devonshire</fullName>
                </value>
                <value>
                    <fullName>LON-East London</fullName>
                </value>
                <value>
                    <fullName>LON-Labs</fullName>
                </value>
                <value>
                    <fullName>LON-Moorgate</fullName>
                </value>
                <value>
                    <fullName>LON-South Bank</fullName>
                </value>
                <value>
                    <fullName>LON-Soho London</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/BuildingTriggerHandlerTests.cls
/***********************************************************************************************************************
    Author 		: Ajaysinh Chauhan
    Description : ---
    History		: --

----------------------------------------------------------------------------------------------------------------------------------
	VERSION					DATE					AUTHOR							DETAIL
	1						--		                Ajaysinh Chauhan	            Initial Developement
****************************************************************************************************************************/

@isTest
public class BuildingTriggerHandlerTests {
/****************************************************************************************************************************
		Author 				: Ajaysinh Chauhan
        Description 		: This method used to verify Teritory Structure.
        Created Date		: --
        Last Modified Date	: 02 Feb, 2018
        Last Modified By	: Prashant Mane
****************************************************************************************************************************/
    public static testMethod void verifySetTerritoryStructure(){
        
        Profile weworkSystemAdmin = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];
        
        Map<String, Object> mapRegionSalesManager = new Map<String, Object>();
        mapRegionSalesManager.put('LastName', 'TestRegionSalesManager');
        mapRegionSalesManager.put('Username', 'TestRegionSalesManager@weworkexample.com');
        mapRegionSalesManager.put('Email', 'testregionsalesmanager@weworkexample.com');
        User RegionSalesManager = TestingUtility.insertUserWithAssert(weworkSystemAdmin.Id, mapRegionSalesManager, true);
        
        Map<String, Object> mapTerritorySalesManager = new Map<String, Object>();
        mapTerritorySalesManager.put('LastName', 'TestTerritorySalesManager');
        mapTerritorySalesManager.put('Username', 'TestTerritorySalesManager@weworkexample.com');
        mapTerritorySalesManager.put('Email', 'testterritorysalesmanager@weworkexample.com');
        User TerritorySalesManager = TestingUtility.insertUserWithAssert(weworkSystemAdmin.Id, mapTerritorySalesManager, true);
        
        Map<String, Object> mapPortfolioSalesManager = new Map<String, Object>();
        mapPortfolioSalesManager.put('LastName', 'TestPortfolioSalesManager');
        mapPortfolioSalesManager.put('Username', 'TestPortfolioSalesManager@weworkexample.com');
        mapPortfolioSalesManager.put('Email', 'testportfoliosalesmanager@weworkexample.com');
        User PortfolioSalesManager = TestingUtility.insertUserWithAssert(weworkSystemAdmin.Id, mapPortfolioSalesManager, true);
        
        Map<String, Object> mapClusterSalesManager = new Map<String, Object>();
        mapClusterSalesManager.put('LastName', 'TestClusterSalesManager');
        mapClusterSalesManager.put('Username', 'TestClusterSalesManager@weworkexample.com');
        mapClusterSalesManager.put('Email', 'testclustersalesmanager@weworkexample.com');
        User ClusterSalesManager = TestingUtility.insertUserWithAssert(weworkSystemAdmin.Id, mapClusterSalesManager, true);
        
        Map<String, Object> mapClusterSalesLead = new Map<String, Object>();
        mapClusterSalesLead.put('LastName', 'TestClusterSalesLead');
        mapClusterSalesLead.put('Username', 'TestClusterSalesLead@weworkexample.com');
        mapClusterSalesLead.put('Email', 'testclustersaleslead@weworkexample.com');
        User ClusterSalesLead = TestingUtility.insertUserWithAssert(weworkSystemAdmin.Id, mapClusterSalesLead, true);
        
        Map<String, Object> mapCommunityManager = new Map<String, Object>();
        mapCommunityManager.put('LastName', 'TestCommunityManager');
        mapCommunityManager.put('Username', 'TestCommunityManager@weworkexample.com');
        mapCommunityManager.put('Email', 'testcommunitymanager@weworkexample.com');
        User CommunityManager = TestingUtility.insertUserWithAssert(weworkSystemAdmin.Id, mapCommunityManager, true);
      
        Map<String, Object> mapCommunityLead = new Map<String, Object>();
        mapCommunityLead.put('LastName', 'TestCommunityLead');
        mapCommunityLead.put('Username', 'TestCommunityLead@weworkexample.com');
        mapCommunityLead.put('Email', 'testcommunitylead@weworkexample.com');
        User CommunityLead = TestingUtility.insertUserWithAssert(weworkSystemAdmin.Id, mapCommunityLead, true);
       
        Region__c objRegion = new Region__c(Name = 'Test Region', Region__c = 'Test Region', Regional_Sales_Manager__c = RegionSalesManager.Id);
        TestingUtility.insertWithAssert(objRegion, 'Region not inserted');
            
        Territory__c objTerritory = new Territory__c(Name = 'Test Territory', Territory__c =' Test Territory', RegionID__c = objRegion.Id, Territory_Sales_Manager__c = TerritorySalesManager.Id);
        TestingUtility.insertWithAssert(objTerritory, 'Territory not inserted');
            
        Market__c objMarket = new Market__c(Name = 'Test Portfolio', Portfolio__c = 'Test Portfolio', TerritoryId__c = objTerritory.Id, Portfolio_Sales_Manager__c = PortfolioSalesManager.Id);
        TestingUtility.insertWithAssert(objMarket, 'Portfolio not inserted');
    
        Cluster__c objCluster = new Cluster__c(Name = 'Test Cluster', Cluster_Sales_Manager__c = ClusterSalesManager.Id, Sales_Lead__c = ClusterSalesLead.Id);
        TestingUtility.insertWithAssert(objCluster,'Cluster not inserted');
        
        List<Building__C> lstBuilding =new List<Building__C>();
        lstBuilding.addAll(TestingUtility.createBuildings(new Map<String,Object>{'Cluster__c' => objCluster.Id}, 9));
        lstBuilding.addAll(TestingUtility.createBuildings(new Map<String,Object>{'Market__c' => objMarket.Id}, 9));
        lstBuilding.addAll(TestingUtility.createBuildings(new Map<String,Object>{'Community_Lead__c' => CommunityLead.Id}, 1));
        lstBuilding.addAll(TestingUtility.createBuildings(new Map<String,Object>{'Responsible_CM__c' => CommunityManager.Id}, 1));
        
        TestingUtility.insertListWithAssert(lstBuilding);
        
        List<Building__c> lstInsertedBuilding =   [SELECT Id,Name,
                   Cluster_Name__c,
                   Portfolio_Name__c,
                   Territory_Name__c,
                   Region_Name__c,
                   Cluster_Sales_Manager_Name__c,
                   Cluster_Sales_Lead_Name__c,
                   Portfolio_Sales_Manager_Name__c,
                   Territory_Sales_Manager_Name__c,
                   Regional_Sales_Manager_Name__c, 
                   Cluster_Sales_Manager_Email__c,
                   Cluster_Sales_Lead_Email__c,
                   Portfolio_Sales_Manager_Email__c,
                   Territory_Sales_Manager_Email__c,
                   Regional_Sales_Manager_Email__c,
                   Community_Lead__c,
                   Responsible_CM__c,
                   Community_Lead__r.Name,
                   Responsible_CM__r.Name FROM Building__c ORDER BY createdDate];
        
        system.assertEquals(20, lstInsertedBuilding.size(),'Building Not Inserted Properly');
        
        for(Integer Index = 0; Index < lstInsertedBuilding.size(); Index++){
            if(Index <= 8){
                System.assertEquals('Test Cluster', lstInsertedBuilding[Index].Cluster_Name__c, 'Cluster Name not Populated');
                System.assertEquals('TestClusterSalesManager', lstInsertedBuilding[Index].Cluster_Sales_Manager_Name__c, 'Cluster Sales Manager Name not Populated');
                System.assertEquals('TestClusterSalesLead', lstInsertedBuilding[Index].Cluster_Sales_Lead_Name__c, 'Cluster Sales Lead Name not Populated');
                System.assertEquals('testclustersalesmanager@weworkexample.com', lstInsertedBuilding[Index].Cluster_Sales_Manager_Email__c, 'Cluster Sales Manager Email not Populated');
                System.assertEquals('testclustersaleslead@weworkexample.com', lstInsertedBuilding[Index].Cluster_Sales_Lead_Email__c, 'Cluster Sales Lead Email not Populated');
            }else if(Index <= 17){
                System.assertEquals('Test Portfolio', lstInsertedBuilding[Index].Portfolio_Name__c, 'Portfolio Name not Populated');
                System.assertEquals('Test Territory', lstInsertedBuilding[Index].Territory_Name__c, 'Territory Name not Populated');
                System.assertEquals('Test Region', lstInsertedBuilding[Index].Region_Name__c, 'Region Name not Populated');
                System.assertEquals('TestPortfolioSalesManager', lstInsertedBuilding[Index].Portfolio_Sales_Manager_Name__c, 'Portfolio Sales Manager Name not Populated');
                System.assertEquals('TestTerritorySalesManager', lstInsertedBuilding[Index].Territory_Sales_Manager_Name__c, 'Territory Sales Manager Name not Populated');
                System.assertEquals('TestRegionSalesManager', lstInsertedBuilding[Index].Regional_Sales_Manager_Name__c, 'Region Sales Manager Name not Populated');
                System.assertEquals('testportfoliosalesmanager@weworkexample.com', lstInsertedBuilding[Index].Portfolio_Sales_Manager_Email__c, 'Portfolio Sales Manager Email not Populated');
                System.assertEquals('testterritorysalesmanager@weworkexample.com', lstInsertedBuilding[Index].Territory_Sales_Manager_Email__c, 'Territory Sales Manager Email not Populated');
                System.assertEquals('testregionsalesmanager@weworkexample.com', lstInsertedBuilding[Index].Regional_Sales_Manager_Email__c, 'Region Sales Manager Email not Populated');
            }else if(Index == 18){
                System.assertEquals('TestCommunityLead', lstInsertedBuilding[Index].Community_Lead__r.Name, 'Community Lead Name Not Populated');
            }else if(Index == 19){
                System.assertEquals('TestCommunityManager', lstInsertedBuilding[Index].Responsible_CM__r.Name,'Community Manager Name Not Populated');
            }
        }
    }
    
/*************************************************************************************************
        Author              : Nikhil Mehta
        Description         : This method is used to test manageBuildingRelatedGeographies.
        Created Date        : 14 May, 2018
		Issue No			: ST-2267
****************************************************************************************************/
    public static testMethod void testManageBuildingRelatedGeographies(){
        SalesConsoleSettings.createSettings();
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new QueueInsertGeoForBuildingMockRes());
        Building__c objBuilding = new Building__c(City__c = 'Frankfurt', Country__c = 'Germany',Name = 'HE-Goetheplatz', CurrencyIsoCode = 'USD',Time_Zone__c = 'Europe/Amsterdam');
        TestingUtility.insertWithAssert(objBuilding);
        insert new Building__c();
        Test.stopTest();
    }
}