objects/Building__c.object
<CustomObject>
    <fields>
        <fullName>UUID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Building</label>
    <nameField>
        <label>Building</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Building__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Enter the specific building for which opportunity is associated</description>
        <inlineHelpText>This is the building / Nearest building to the geography entered by customer</inlineHelpText>
        <label>Building/Nearest Building</label>
        <referenceTo>Building__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Encoded_ID__c</fullName>
        <label>Encoded ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Source_Detail__c</fullName>
        <inlineHelpText>Enter the appropriate details regarding the source of the lead</inlineHelpText>
        <label>Lead Source Detail</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>utm_campaign__c</fullName>
        <label>utm_campaign</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>utm_campaign_id__c</fullName>
        <label>utm_campaign_id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>utm_content__c</fullName>
        <label>utm_content</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>utm_medium__c</fullName>
        <label>utm_medium</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>utm_source__c</fullName>
        <label>utm_source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>utm_term__c</fullName>
        <label>utm_term</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Setting__c.object
<CustomObject>
    <fields>
        <fullName>Data__c</fullName>
        <description>This should contain JSON formatted data for each setting record. The JSON object will vary from setting to setting.</description>
        <label>Data</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <description>We are creating object for Settings instead of using Custom Object because we need to store larger size of data which Custom Setting does not support. e.g. Mapping of Fields from Contact to Lead etc. which may go beyond 255 characters. 

It will not use caching but give more flexibility for coding.</description>
    <label>Sales Console Setting</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Console Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Triggers__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity_Upate_Encoded_ID__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Opportunity_Upate_Encoded_ID</label>
        <type>Checkbox</type>
    </fields>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>We are going to use this object to activate or deactivate various triggers we will be writing so we can easily deactivate triggers in case of errors or mass upload if required.</description>
    <label>Triggers</label>
</CustomObject>

classes/TestOpportunityEncodedIDTrigger.cls
@isTest
private class TestOpportunityEncodedIDTrigger {
	//We should delete this test class as we already deleted OpportunityStageToTour trigger.
	//Test code moved to OpportunityTriggerHandlerTest class.
	//Commmented By : Anant Kumar
	//Date : 23/June/2016
	/*
	@isTest static void test_x() {
		//pre-context
			Setting__c testSettings = new Setting__c();
	       	testSettings.Name = 'OpportunityFromLatestOpportunity';
	       	testSettings.Data__c = '{"LeadSource":{"name":"LeadSource","overwrite":false},"Lead_Source_Detail__c":{"name":"Lead_Source_Detail__c","overwrite":true},"utm_campaign__c":{"name":"utm_campaign__c","overwrite":true},"utm_campaign_id__c":{"name":"utm_campaign_id__c","overwrite":false},"utm_content__c":{"name":"utm_content__c","overwrite":false},"utm_medium__c":{"name":"utm_medium__c","overwrite":true},"utm_source__c":{"name":"utm_source__c","overwrite":false},"utm_term__c":{"name":"utm_term__c","overwrite":false}}';
	       	TestingUtility.insertWithAssert(testSettings);
       		
       		Triggers__c triggers = new Triggers__c(Name= 'Triggers');
         	triggers.Opportunity_Upate_Encoded_ID__c= true;
       		TestingUtility.insertWithAssert(triggers);
       		
			Building__c b = new Building__c(
				Name='b1',
				uuid__c = 'abc123'
			);
			insert b;

			Opportunity o = new Opportunity(				
				CloseDate 	= system.today(),
				StageName 	= 'Qualifying',
				Name 				= 'test Opoortunity',
				Building__c	= b.Id
			);
			insert o;		//test

		Test.startTest();
			o = [SELECT Encoded_Id__c FROM Opportunity WHERE id = :o.Id LIMIT 1];
			system.assertEquals(
				EncodingHandler.encode(o.Id),
				o.Encoded_Id__c,
				'The Opportunity was not correctly encoded.'
			);
			
		Test.stopTest();
	}
	*/
}