objects/Building__c.object
<CustomObject>
    <fields>
        <fullName>Market__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Portfolio</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Buildings</relationshipLabel>
        <relationshipName>Buildings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UUID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Building</label>
    <nameField>
        <label>Building</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Building__c</fullName>
        <description>Pulls Building Location without 3 character city reference</description>
        <formula>Location__r.Location_No_City__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Building</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alexandria</fullName>
                </value>
                <value>
                    <fullName>Alpharetta</fullName>
                </value>
                <value>
                    <fullName>Amsterdam</fullName>
                </value>
                <value>
                    <fullName>Ann Arbor</fullName>
                </value>
                <value>
                    <fullName>Atlanta</fullName>
                </value>
                <value>
                    <fullName>Austin</fullName>
                </value>
                <value>
                    <fullName>Balston</fullName>
                </value>
                <value>
                    <fullName>Baltimore</fullName>
                </value>
                <value>
                    <fullName>Bangkok</fullName>
                </value>
                <value>
                    <fullName>Barranquilla</fullName>
                </value>
                <value>
                    <fullName>Be'er Sheva</fullName>
                </value>
                <value>
                    <fullName>Beijing</fullName>
                </value>
                <value>
                    <fullName>Bengaluru</fullName>
                </value>
                <value>
                    <fullName>Berkeley</fullName>
                </value>
                <value>
                    <fullName>Berlin</fullName>
                </value>
                <value>
                    <fullName>Bethesda</fullName>
                </value>
                <value>
                    <fullName>Bogota</fullName>
                </value>
                <value>
                    <fullName>Bogotá</fullName>
                </value>
                <value>
                    <fullName>Boston</fullName>
                </value>
                <value>
                    <fullName>Boulder</fullName>
                </value>
                <value>
                    <fullName>Brooklyn</fullName>
                </value>
                <value>
                    <fullName>Budapest</fullName>
                </value>
                <value>
                    <fullName>Buenos Aires</fullName>
                </value>
                <value>
                    <fullName>Charlotte</fullName>
                </value>
                <value>
                    <fullName>Chicago</fullName>
                </value>
                <value>
                    <fullName>Cincinnati</fullName>
                </value>
                <value>
                    <fullName>Cleveland</fullName>
                </value>
                <value>
                    <fullName>Columbus</fullName>
                </value>
                <value>
                    <fullName>Dallas</fullName>
                </value>
                <value>
                    <fullName>Dallas - Fort Worth</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_Member__c</fullName>
        <formula>if( Billing_Account__r.Primary_Member__r.Id =  Id , "Yes","No")</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Primary Member</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Referrer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referrer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UUID__c</fullName>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Referral</fullName>
        <active>true</active>
        <label>Referral</label>
    </recordTypes>
</CustomObject>

objects/Market__c.object
<CustomObject>
    <fields>
        <fullName>Portfolio__c</fullName>
        <description>Display name for portfolio, something user friendly to end users</description>
        <inlineHelpText>Display name (text)</inlineHelpText>
        <label>Portfolio Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <formula>TerritoryID__r.RegionID__r.Region__c</formula>
        <inlineHelpText>Display name (text)</inlineHelpText>
        <label>Region Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TerritoryID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Territory</label>
        <referenceTo>Territory__c</referenceTo>
        <relationshipLabel>Portfolios</relationshipLabel>
        <relationshipName>Portfolio</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <formula>TerritoryID__r.Territory__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Display name (text)</inlineHelpText>
        <label>Territory Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UUID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <description>We are introducing new object Market so that same building can fall under multiple Markets as per Marketing department requirement.</description>
    <label>Portfolio</label>
    <nameField>
        <label>Portfolio</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portfolios</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Building__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Enter the specific building for which opportunity is associated</description>
        <inlineHelpText>This is the building / Nearest building to the geography entered by customer</inlineHelpText>
        <label>Building/Nearest Building</label>
        <referenceTo>Building__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <description>Enter the market value from which the lead is coming</description>
        <inlineHelpText>Enter the market value from which the lead is coming</inlineHelpText>
        <label>Market [old]</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Amsterdam</fullName>
                </value>
                <value>
                    <fullName>Arlington</fullName>
                </value>
                <value>
                    <fullName>Atlanta</fullName>
                </value>
                <value>
                    <fullName>Austin</fullName>
                </value>
                <value>
                    <fullName>Baltimore</fullName>
                </value>
                <value>
                    <fullName>Bangalore</fullName>
                </value>
                <value>
                    <fullName>Bangkok</fullName>
                </value>
                <value>
                    <fullName>Be'er Sheva</fullName>
                </value>
                <value>
                    <fullName>Beijing</fullName>
                </value>
                <value>
                    <fullName>Bellevue</fullName>
                </value>
                <value>
                    <fullName>Bengaluru</fullName>
                </value>
                <value>
                    <fullName>Berkeley</fullName>
                </value>
                <value>
                    <fullName>Berlin</fullName>
                </value>
                <value>
                    <fullName>Bogota</fullName>
                </value>
                <value>
                    <fullName>Boston</fullName>
                </value>
                <value>
                    <fullName>Boulder</fullName>
                </value>
                <value>
                    <fullName>Bronx</fullName>
                </value>
                <value>
                    <fullName>Brooklyn</fullName>
                </value>
                <value>
                    <fullName>Budapest</fullName>
                </value>
                <value>
                    <fullName>Buenos Aires</fullName>
                </value>
                <value>
                    <fullName>Cambridge</fullName>
                </value>
                <value>
                    <fullName>Cartagena</fullName>
                </value>
                <value>
                    <fullName>Charlotte</fullName>
                </value>
                <value>
                    <fullName>Chicago</fullName>
                </value>
                <value>
                    <fullName>Condesa / Hipodromo</fullName>
                </value>
                <value>
                    <fullName>Dallas</fullName>
                </value>
                <value>
                    <fullName>Delhi</fullName>
                </value>
                <value>
                    <fullName>Denver</fullName>
                </value>
                <value>
                    <fullName>Detroit</fullName>
                </value>
                <value>
                    <fullName>Dubai</fullName>
                </value>
                <value>
                    <fullName>India</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_Member__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>This is the Main Contact of the Opportunity</inlineHelpText>
        <label>Main Contact</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Referrer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referrer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Referrer)</relationshipLabel>
        <relationshipName>Opportunities3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <description>Formula reference through building/portfolio to territory table</description>
        <formula>Building__r.Market__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Portfolio</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Region__c.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <description>Display name for region</description>
        <inlineHelpText>Display name (text)</inlineHelpText>
        <label>Region Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Region</label>
    <nameField>
        <label>Region</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Territory__c.object
<CustomObject>
    <fields>
        <fullName>RegionID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Region</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Territories</relationshipLabel>
        <relationshipName>Territories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <formula>RegionID__r.Region__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Display name (text)</inlineHelpText>
        <label>Region Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <description>Display Name for Territory, something user friendly to user</description>
        <inlineHelpText>Display name (text)</inlineHelpText>
        <label>Territory Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Territory</label>
    <nameField>
        <label>Territory</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Trigger_Configuration__mdt.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Record_Types_API_Names__c</fullName>
        <label>Record Types API Names</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Trigger Configuration</label>
    <pluralLabel>Trigger Configurations</pluralLabel>
</CustomObject>

classes/TrOpportunityEmailAlertForBrokerInTest.cls
/************************************************************************************************************************************
    Author      :   Jitesh Adwani   
    Description :   This class will contain all the test method of TrOpportunityEmailAlertForBrokerInvolved.
    Issue No    :   ST-3276
    History     :
    ----------------------------------------------------------------------------------------------------------------------------------
    VERSION     DATE                AUTHOR                  DETAIL
    1          2 Jan 2019           Jitesh             Initial Developement
**************************************************************************************************************************************/
@isTest
public class TrOpportunityEmailAlertForBrokerInTest {   
    static Boolean isTriggerActive = false;
    
    @testSetup
    Static void initData() {
        Integer count = 0;
        Set<String> setTriggerConfig = new Set<String>{'OpportunityEmailAlertForBrokerOnInsert', 'OpportunityEmailAlertForBrokerOnUpdate'};
        List<Trigger_Configuration__mdt> config = [SELECT Active__c, Record_Types_API_Names__c FROM Trigger_Configuration__mdt WHERE Active__c = true AND DeveloperName IN :setTriggerConfig];
        if(config.size() > 0){
            isTriggerActive = true;
        }
        SalesConsoleSettings.createSettings();
        List<Region__c> lstRegion = new List<Region__c>();
        lstRegion.add(new Region__c(Name = 'India', Region__c = 'India'));
        lstRegion.add(new Region__c(Name = 'China', Region__c = 'China'));
        TestingUtility.insertListWithAssert(lstRegion);
        Territory__c objTerritory = new Territory__c(Name = 'Test Territory 1', Territory__c = 'Test Terriotory 1', RegionID__c = lstRegion[0].Id);
        TestingUtility.insertWithAssert(objTerritory, 'Territory inserted');
        Market__c objMarket = new Market__c(Name = 'Test Portfolio', Portfolio__c = 'Test Portfolio', TerritoryId__c = objTerritory.Id);
        TestingUtility.insertWithAssert(objMarket, 'Portfolio inserted');
        Building__c objBuilding = new Building__c(Name = 'Test1', UUID__c = '12544114441111', Market__c = objMarket.Id);
        TestingUtility.insertWithAssert(objBuilding);
        
        TestingUtility.getRecords(new Map<String, Object>{'objName'=>'contact','numberOfRecords'=>3});
        List<Contact> lstContacts = new List<Contact>([SELECT Id, LastName FROM Contact]);
        System.assertEquals(lstContacts.size(), 3);
        
        Map<String, Object> mapData = new Map<String, Object>();
        Map<String, List<Object>> mapFieldForOpportunity = new Map<String, List<Object>>();
        mapFieldForOpportunity.put('Primary_Member__c', new List<Object>{lstContacts[0].Id, lstContacts[1].Id, lstContacts[2].Id});
        mapFieldForOpportunity.put('LeadSource', new List<Object>{'Event', 'Event', 'Event'});
        mapFieldForOpportunity.put('Referrer__c', new List<Object>{lstContacts[0].Id, lstContacts[0].Id, lstContacts[0].Id});
        mapFieldForOpportunity.put('Building__c', new List<Object>{objBuilding.Id, objBuilding.Id, objBuilding.Id});
        mapFieldForOpportunity.put('Broker_Involvement_Indicated__c', new List<Object>{'Yes', 'No', 'Yes'});
        mapData.put('objName', 'Opportunity');
        mapData.put('numberOfRecords', 3);
        mapData.put('doInsert', true);
        mapData.put('mapFieldValues', mapFieldForOpportunity);
        List<Opportunity> lstOpportunities = TestingUtility.getRecords(mapData);
        System.assertEquals(lstOpportunities.size(), 3);
    }
    
    /************************************************************************************************************************************
        Author         : Jitesh Adwani
        Description    : This method is used check email is sent or not.
        Created Date   : 03 Jan 2019 
        Issue No       : ST-3276
    **************************************************************************************************************************************/
    public static testMethod void verifyEmailAlertForBrokerInvolved(){
        if(!isTriggerActive){
            return;
        }
        //Insert        
        Integer invocations = Limits.getEmailInvocations();
        System.assertEquals(1, invocations, 'An Email has not been sent');
        //Update
        List<Territory__c> lstUpdateTerritory = new List<Territory__c>();
        List<Region__c> lstRegions = new List<Region__c>([SELECT Id, Name FROM Region__c]);
        List<Territory__c> lstTerritory = new List<Territory__c>([SELECT Id FROM Territory__c]);
        for(Territory__c objTerritory : lstTerritory){
            objTerritory.RegionID__c = lstRegions[1].Id;
            lstUpdateTerritory.add(objTerritory);
        }
        TestingUtility.updateListWithAssert(lstUpdateTerritory);
        List<Building__c> lstBuilding = new List<Building__c>([SELECT Id, Name, Region_Name__c FROM Building__c]);
        System.assertEquals(lstBuilding[0].Region_Name__c, lstRegions[1].Name, 'Region didn\'t Updated');
        List<Opportunity> lstOpportunity = new List<Opportunity>([SELECT Id, Name, Broker_Involvement_Indicated__c FROM Opportunity]); 
        lstOpportunity[1].Broker_Involvement_Indicated__c = 'Yes';
        TestingUtility.updateListWithAssert(lstOpportunity);
        Integer invocations1 = Limits.getEmailInvocations();
        System.assertEquals(2, invocations1, 'An Email has not been sent');
        
        //Negative scenario mail didn't send.
        List<Opportunity> lstOpportunities = new List<Opportunity>([SELECT Id, Name, Broker_Involvement_Indicated__c FROM Opportunity]);
        lstOpportunities[1].LeadSource = 'Broker Referral';
        TestingUtility.updateListWithAssert(lstOpportunities);     
        Integer invocations2 = Limits.getEmailInvocations();
        System.assertEquals(2, invocations2, 'An Email has not been sent');
    }
}