objects/Building__c.object
<CustomObject>
    <fields>
        <fullName>Market__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Portfolio</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Buildings</relationshipLabel>
        <relationshipName>Buildings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Portfolio_Name__c</fullName>
        <label>Portfolio Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Portfolio_Sales_Manager_Email__c</fullName>
        <label>Portfolio Sales Manager Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Portfolio_Sales_Manager_Name__c</fullName>
        <label>Portfolio Sales Manager Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Portfolio_Standard_Name__c</fullName>
        <label>Portfolio Standard Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region_Name__c</fullName>
        <label>Region Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Regional_Sales_Manager_Email__c</fullName>
        <label>Regional Sales Manager Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Regional_Sales_Manager_Name__c</fullName>
        <label>Regional Sales Manager Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory_Name__c</fullName>
        <label>Territory Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory_Sales_Manager_Email__c</fullName>
        <label>Territory Sales Manager Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Territory_Sales_Manager_Name__c</fullName>
        <label>Territory Sales Manager Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Building</label>
    <nameField>
        <label>Building</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Market__c.object
<CustomObject>
    <fields>
        <fullName>Portfolio_Sales_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Senior Sales Exec of Portfolio</inlineHelpText>
        <label>Portfolio Sales Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Markets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Portfolio__c</fullName>
        <description>Display name for portfolio, something user friendly to end users</description>
        <inlineHelpText>Display name (text)</inlineHelpText>
        <label>Portfolio Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <formula>TerritoryID__r.RegionID__r.Region__c</formula>
        <inlineHelpText>Display name (text)</inlineHelpText>
        <label>Region Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TerritoryID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Territory</label>
        <referenceTo>Territory__c</referenceTo>
        <relationshipLabel>Portfolios</relationshipLabel>
        <relationshipName>Portfolio</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <formula>TerritoryID__r.Territory__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Display name (text)</inlineHelpText>
        <label>Territory Name</label>
        <type>Text</type>
    </fields>
    <description>We are introducing new object Market so that same building can fall under multiple Markets as per Marketing department requirement.</description>
    <label>Portfolio</label>
    <nameField>
        <label>Portfolio</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portfolios</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Region__c.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <description>Display name for region</description>
        <inlineHelpText>Display name (text)</inlineHelpText>
        <label>Region Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Regional_Sales_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Senior Sales Exec of Region</inlineHelpText>
        <label>Regional Sales Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Regions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Region</label>
    <nameField>
        <label>Region</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Territory__c.object
<CustomObject>
    <fields>
        <fullName>RegionID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Region</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Territories</relationshipLabel>
        <relationshipName>Territories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <formula>RegionID__r.Region__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Display name (text)</inlineHelpText>
        <label>Region Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory_Sales_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Senior Sales Exec of Territory</inlineHelpText>
        <label>Territory Sales Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <description>Display Name for Territory, something user friendly to user</description>
        <inlineHelpText>Display name (text)</inlineHelpText>
        <label>Territory Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Territory</label>
    <nameField>
        <label>Territory</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Building__c</fullName>
        <label>Building</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AMS-Metropool</fullName>
                </value>
                <value>
                    <fullName>AMS-Labs</fullName>
                </value>
                <value>
                    <fullName>AMS-Weteringschans</fullName>
                </value>
                <value>
                    <fullName>ATX-Congress</fullName>
                </value>
                <value>
                    <fullName>ATX-Labs</fullName>
                </value>
                <value>
                    <fullName>BKN-Dumbo Heights</fullName>
                </value>
                <value>
                    <fullName>BK-Williamsburg</fullName>
                </value>
                <value>
                    <fullName>BOS-Fort Point</fullName>
                </value>
                <value>
                    <fullName>BOS-Labs</fullName>
                </value>
                <value>
                    <fullName>BOS-South Station</fullName>
                </value>
                <value>
                    <fullName>CHI-Fulton Market</fullName>
                </value>
                <value>
                    <fullName>CHI-Labs</fullName>
                </value>
                <value>
                    <fullName>CHI-RiverNorth</fullName>
                </value>
                <value>
                    <fullName>DC-Chinatown</fullName>
                </value>
                <value>
                    <fullName>DC-DuPont Circle</fullName>
                </value>
                <value>
                    <fullName>DC-Labs</fullName>
                </value>
                <value>
                    <fullName>DC-Wonder Bread Factory</fullName>
                </value>
                <value>
                    <fullName>ISR-Labs</fullName>
                </value>
                <value>
                    <fullName>LA-Fine Arts</fullName>
                </value>
                <value>
                    <fullName>LA-Fine Arts Building</fullName>
                </value>
                <value>
                    <fullName>LA-Hollywood</fullName>
                </value>
                <value>
                    <fullName>LA-Labs</fullName>
                </value>
                <value>
                    <fullName>LA-Promenade</fullName>
                </value>
                <value>
                    <fullName>LA-Santa Monica</fullName>
                </value>
                <value>
                    <fullName>LON-Devonshire</fullName>
                </value>
                <value>
                    <fullName>LON-East London</fullName>
                </value>
                <value>
                    <fullName>LON-Labs</fullName>
                </value>
                <value>
                    <fullName>LON-Moorgate</fullName>
                </value>
                <value>
                    <fullName>LON-South Bank</fullName>
                </value>
                <value>
                    <fullName>LON-Soho London</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/PortfolioTriggersHandler.cls
/************************************************************************************************************************************
   	Author 		: Milanjeet
   	Description : This class contains Logic of PortfolioTrigger

   	History		:
	----------------------------------------------------------------------------------------------------------------------------------
	VERSION		DATE			AUTHOR				DETAIL
	1			9 Nov 2017		Milanjeet 			Initial Developement
**************************************************************************************************************************************/

public class PortfolioTriggersHandler extends ITriggerHandler {
    public PortfolioTriggersHandler(){
        super('Market__c');
    }
    
    /************************************************************************************************************************************
         Author 			: Pragalbha Mahajan
         Description 		: This method overrides after update method from ITriggerHander which will control the execution flow.
         Last Modified Date	: 02 February 2018
         Last Modified By	: Pragalbha Mahajan (added Comment)
	**************************************************************************************************************************************/
    public override void AfterUpdate(List<SObject> listNewItems, Map<Id, SObject> mapNewItems, List<SObject> listOldItems, Map<Id, SObject> mapOldItems){
        updatePortfolioInfoOnBuilding(listNewItems, mapNewItems, listOldItems, mapOldItems);
    }

    /************************************************************************************************************************************
        Author 				: Milanjeet
        Description 		: This method is used to update portfolio info on Building
        Last Modified Date	: 10-Nov-2017
        Last Modified By	: Milanjeet
        Issue No 			: ST-1652
	**************************************************************************************************************************************/
    public static void updatePortfolioInfoOnBuilding(List<SObject> listNewItems, Map<Id, SObject> mapNewItems, List<SObject> listOldItems, Map<Id, SObject> mapOldItems){     
        if(TriggerSettings.mappedField.Portfolio_UpdatePortfolioInfoOnBuilding){
            Set<Id> setPortfolioIds = new Set<Id>();   
            try{
                for(Market__c mrkt:(List<Market__c>)listNewItems){
                    if((mrkt.Portfolio__c==null || !mrkt.Portfolio__c.equalsIgnoreCase(String.valueOf(mapOldItems.get(mrkt.Id).get('Portfolio__c')))) || mrkt.Portfolio_Sales_Manager__c!=mapOldItems.get(mrkt.Id).get('Portfolio_Sales_Manager__c') || mrkt.TerritoryID__c !=mapOldItems.get(mrkt.Id).get('TerritoryID__c') || mrkt.Name !=mapOldItems.get(mrkt.Id).get('Name')){
                        setPortfolioIds.add(mrkt.Id);
                    }
                }
                if(setPortfolioIds.size()>0){
                    List<Building__c> lstBuildings = [Select Id,Market__r.Name,Market__r.Portfolio__c,Market__r.Portfolio_Sales_Manager__r.Name,Market__r.Portfolio_Sales_Manager__r.Email,Market__r.TerritoryId__r.Territory__c,Market__r.TerritoryId__r.Territory_Sales_Manager__r.Name,Market__r.TerritoryId__r.Territory_Sales_Manager__r.Email,Market__r.TerritoryId__r.RegionId__r.Region__c,Market__r.TerritoryId__r.RegionId__r.Regional_Sales_Manager__r.Name,Market__r.TerritoryId__r.RegionId__r.Regional_Sales_Manager__r.Email From Building__c Where Market__c IN:setPortfolioIds];
                    List<Building__c> lstBuildingsToUpdate = new List<Building__c>();
                    for(Building__c bldng:lstBuildings){
                        Building__c b = new Building__c(Id=bldng.Id);
                        b.Portfolio_Name__c = bldng.Market__r.Portfolio__c;
                        b.Portfolio_Standard_Name__c = bldng.Market__r.Name;
                        b.Portfolio_Sales_Manager_Name__c = bldng.Market__r.Portfolio_Sales_Manager__r!=null?bldng.Market__r.Portfolio_Sales_Manager__r.Name:'';
                        b.Territory_Name__c = bldng.Market__r.TerritoryId__r.Territory__c;
                        b.Territory_Sales_Manager_Name__c = bldng.Market__r.TerritoryId__r.Territory_Sales_Manager__r!=null?bldng.Market__r.TerritoryId__r.Territory_Sales_Manager__r.Name:'';
                        b.Region_Name__c = bldng.Market__r.TerritoryId__r.RegionId__r.Region__c;
                        b.Regional_Sales_Manager_Name__c = bldng.Market__r.TerritoryId__r.RegionId__r.Regional_Sales_Manager__r!=null?bldng.Market__r.TerritoryId__r.RegionId__r.Regional_Sales_Manager__r.Name:'';
                        
                        b.Portfolio_Sales_Manager_Email__c = bldng.Market__r.Portfolio_Sales_Manager__r!=null?bldng.Market__r.Portfolio_Sales_Manager__r.Email:'';
                        b.Territory_Sales_Manager_Email__c = bldng.Market__r.TerritoryId__r.Territory_Sales_Manager__r!=null?bldng.Market__r.TerritoryId__r.Territory_Sales_Manager__r.Email:'';
                        b.Regional_Sales_Manager_Email__c = bldng.Market__r.TerritoryId__r.RegionId__r.Regional_Sales_Manager__r!=null?bldng.Market__r.TerritoryId__r.RegionId__r.Regional_Sales_Manager__r.Email:'';
                        lstBuildingsToUpdate.add(b);
                    }
                    update lstBuildingsToUpdate;
                }  
            }catch(Exception pEx) { 
                List<Id> ids = New List<Id>();
                if(mapOldItems.keyset()!=null)
                    ids.addAll(mapOldItems.keyset());
                new ApexDebugLog().createLog( 
                    new ApexDebugLog.Error('PortfolioTriggersHandler','updatePortfolioInfoOnBuilding',String.join(ids,','),pEx)
                );
                throw new PortfolioTriggersHandlerException(pEx.getMessage());
            }    
            
        }
    }
    
    /************************************************************************************************************************************
        Author 				: Milanjeet
        Description 		: This is custom exception used for Portfolio Triggers Handler
        Last Modified Date	: 9 Nov 2017
        Last Modified By	: Milanjeet
	**************************************************************************************************************************************/
    public class PortfolioTriggersHandlerException extends Exception{}
}