objects/Building__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Aland Islands</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia, Plurinational State of</fullName>
                </value>
                <value>
                    <fullName>Bonaire, Sint Eustatius and Saba</fullName>
                </value>
                <value>
                    <fullName>Bosnia and Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Bouvet Island</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Geography__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is a lookup of Geography object which is used to represent Google Maps Location so that we can reuse the same location as and when required within multiple objects.</description>
        <inlineHelpText>This field provides the exact or nearest google location where the building is located.</inlineHelpText>
        <label>Geography</label>
        <referenceTo>Geography__c</referenceTo>
        <relationshipLabel>Buildings</relationshipLabel>
        <relationshipName>Buildings_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Building</label>
    <nameField>
        <label>Building</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/City__c.object
<CustomObject>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <referenceTo>State__c</referenceTo>
        <relationshipLabel>Cities</relationshipLabel>
        <relationshipName>Cities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Country__c.object
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Geography__c.object
<CustomObject>
    <fields>
        <fullName>Building_Updated_Date__c</fullName>
        <description>This field store the date when batch update the building on geography.</description>
        <label>Building Updated Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>administrative_area_level_3 or locality should be saved here in City field.</description>
        <label>City</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Country of the Google Location</description>
        <label>Country</label>
        <length>120</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nearest_Building__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field contains the value of nearest building which is included in buildings object.</description>
        <inlineHelpText>The value in this field comes from buildings available for the user.</inlineHelpText>
        <label>Nearest Building</label>
        <referenceTo>Building__c</referenceTo>
        <relationshipLabel>Geographies</relationshipLabel>
        <relationshipName>Geographies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Previous_Building__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Previous Building</label>
        <referenceTo>Building__c</referenceTo>
        <relationshipLabel>Geographies (Previous Building)</relationshipLabel>
        <relationshipName>previousGeographies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>Google Places returns administrative_area_level_1 which is generally a State or Province which will be stored here.</description>
        <label>State/Provience</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <description>This object will represent Google Maps Location so that we can reuse same location as and when required within multiple objects.</description>
    <label>Geography</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Geographies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/State__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>States</relationshipLabel>
        <relationshipName>States</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/QueueInsertGeographyForBuilding.cls
/************************************************************************************************************************************
	Author		: 	Nikhil Mehta
	Description	: 	This Queueable class insert Geography to related to Building.
	----------------------------------------------------------------------------------------------------------------------------------
	VERSION		DATE	        	AUTHOR                     DETAIL
	1	    	4 December 2018		Nikhil Mehta            Initial Developement
**************************************************************************************************************************************/
public class QueueInsertGeographyForBuilding implements Queueable, Database.AllowsCallouts{
    public List<Building__c> lstNewBuildings;
    public Integer maxCallouts;
    private Integer counter = 0;
    public GeographyHandler.GoogleGeolocationAPI googleGeolocationAPISetting;
    
    public QueueInsertGeographyForBuilding(List<Building__c> lstNewBuildings,GeographyHandler.GoogleGeolocationAPI googleGeolocationAPISetting){
        this.lstNewBuildings = lstNewBuildings;
        this.maxCallouts = lstNewBuildings.size();
        this.googleGeolocationAPISetting = googleGeolocationAPISetting;
    }
    /************************************************************************************************************************************
        Author              :   Nikhil Mehta
        Description         :   This method insert geography record for Building.
		Last Modified By	:	Nikhil Mehta
        Last Modified Date  :   04 December 2018
    **************************************************************************************************************************************/    
    public void execute(QueueableContext context) {
        try{
            if(googleGeolocationAPISetting != null && lstNewBuildings != null && lstNewBuildings.size()>0){
                Building__c building = lstNewBuildings[counter];
                Map<String, String> mapAddress = new Map<String, String>();
                mapAddress.put('address', building.Address__c);
                mapAddress.put('city', building.City__c);
                mapAddress.put('state', building.State__c);
                mapAddress.put('country', building.Country__c);
                Geography__c geographyRec = GeographyHandler.getGeography(mapAddress);
                if(String.isEmpty(geographyRec.Id)){
                    geographyRec.Nearest_Building__c = building.Id;
                    Database.insert(geographyRec, false);
                }
                if(geographyRec.Id != null){
                    Building__c newBuilding = new Building__c(Id = building.Id, Geography__c = geographyRec.Id);
                    update newBuilding;
                    List<Geography__c> lstGeographies = new List<Geography__c>([SELECT Id, Name, Geocode__Latitude__s, Geocode__Longitude__s, Nearest_Building__r.Name, Nearest_Building__r.Geography__c, Nearest_Building__r.Geography__r.Name, Nearest_Building__r.Geography__r.Geocode__Latitude__s, Nearest_Building__r.Geography__r.Geocode__Longitude__s, Nearest_Building__r.Geography__r.Nearest_Building__c FROM Geography__c WHERE Id =: geographyRec.Id]);
                    if(lstGeographies.size() > 0){
                        Geography__c newGeographyRec = lstGeographies[0];
                        Geography__c nearestGeographyRec = newGeographyRec.Nearest_Building__r.Geography__r;
                        if(building != null && nearestGeographyRec != null){
                            List<Geography__c> lstNearestBuildingGeographies = [SELECT Id, Name, Geocode__Latitude__s, Geocode__Longitude__s FROM Geography__c WHERE Nearest_Building__c =: nearestGeographyRec.Nearest_Building__c];
                            if(lstNearestBuildingGeographies.size() > 0){
                                List<Geography__c> lstGeographysToUpdate = new List<Geography__c>();
                                System.Location newGeographyRecLocation = System.Location.newInstance(newGeographyRec.Geocode__Latitude__s, newGeographyRec.Geocode__Longitude__s);
                                System.Location nearestGeographyRecLocation = System.Location.newInstance(nearestGeographyRec.Geocode__Latitude__s, nearestGeographyRec.Geocode__Longitude__s);
                                System.Location geographyLocation;
                                for(Geography__c nearestBuildingGeographyRec : lstNearestBuildingGeographies){
                                    geographyLocation = System.Location.newInstance(nearestBuildingGeographyRec.Geocode__Latitude__s, nearestBuildingGeographyRec.Geocode__Longitude__s);
                                    if(System.Location.getDistance(geographyLocation, newGeographyRecLocation, 'mi') < System.Location.getDistance(geographyLocation, nearestGeographyRecLocation, 'mi')){
                                        nearestBuildingGeographyRec.Building_Updated_Date__c = System.now();
                                        nearestBuildingGeographyRec.Previous_Building__c = nearestGeographyRec.Nearest_Building__c;
                                        nearestBuildingGeographyRec.Nearest_Building__c = building.Id;
                                        lstGeographysToUpdate.add(nearestBuildingGeographyRec);
                                    }
                                }
                                if(lstGeographysToUpdate.size() > 0){
                                    Database.update(lstGeographysToUpdate, false);
                                }
                            }
                        }
                    }
                }
                counter += 1;
                if(maxCallouts > counter){
                    QueueInsertGeographyForBuilding jobQueueInsertGeographyForBuilding = new QueueInsertGeographyForBuilding(lstNewBuildings, googleGeolocationAPISetting);
                    jobQueueInsertGeographyForBuilding.counter = counter;
                    System.enqueueJob(jobQueueInsertGeographyForBuilding);
                }
            }
        } catch(Exception pEx) { 
            new ApexDebugLog().createLog( 
                new ApexDebugLog.Error('QueueInsertGeographyForBuilding','execute',null,pEx)
            );
            throw new QueueInsertGeographyForBuildingException(pEx.getMessage());
        }
    }
    
    public class QueueInsertGeographyForBuildingException extends Exception{}
}