objects/Building__c.object
<CustomObject>
    <fields>
        <fullName>UUID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Building</label>
    <nameField>
        <label>Building</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Building__c</fullName>
        <description>Pulls Building Location without 3 character city reference</description>
        <formula>Location__r.Location_No_City__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Building</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Member__c</fullName>
        <formula>if( Billing_Account__r.Primary_Member__r.Id =  Id , "Yes","No")</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Primary Member</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This is the latest status coming from Space systems through Jitterbunny of the individual member. This tells us if the user is active or not.</description>
        <inlineHelpText>This is accurate status of a contact if it is an active member of our products or not.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>active</fullName>
                </value>
                <value>
                    <fullName>inactive</fullName>
                    <default>true</default>
                    <label>inactive</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UUID__c</fullName>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Tour_Outcome__c.object
<CustomObject>
    <fields>
        <fullName>Interested_Buildings__c</fullName>
        <inlineHelpText>Interested buildings as per SpaceStation</inlineHelpText>
        <label>Interested Buildings</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>32 Village</fullName>
                </value>
                <value>
                    <fullName>AMS-Metropool</fullName>
                </value>
                <value>
                    <fullName>AMS-Strawinskylaan</fullName>
                </value>
                <value>
                    <fullName>AMS-Weteringschans</fullName>
                </value>
                <value>
                    <fullName>ARC-Andres Arguibel 2860</fullName>
                </value>
                <value>
                    <fullName>ARC-Avenida Corrientes 800</fullName>
                </value>
                <value>
                    <fullName>ARC-Libertador 1000</fullName>
                </value>
                <value>
                    <fullName>ARC-Torre Bellini</fullName>
                </value>
                <value>
                    <fullName>ARN-Urban Escape</fullName>
                </value>
                <value>
                    <fullName>ATL-1372 Peachtree</fullName>
                </value>
                <value>
                    <fullName>ATL-3280 Peachtree Road NE</fullName>
                </value>
                <value>
                    <fullName>ATL-Colony Square</fullName>
                </value>
                <value>
                    <fullName>ATL-Tower Place</fullName>
                </value>
                <value>
                    <fullName>AUS-Congress</fullName>
                </value>
                <value>
                    <fullName>AUS-Domain</fullName>
                </value>
                <value>
                    <fullName>AUS-University Park</fullName>
                </value>
                <value>
                    <fullName>AUS-West 6th</fullName>
                </value>
                <value>
                    <fullName>AUS-Westview</fullName>
                </value>
                <value>
                    <fullName>AUS-WeWork 801 Barton Springs</fullName>
                </value>
                <value>
                    <fullName>BCN-Diagonal 444</fullName>
                </value>
                <value>
                    <fullName>BHZ-Boulevard Shopping</fullName>
                </value>
                <value>
                    <fullName>BKK-Asia Centre</fullName>
                </value>
                <value>
                    <fullName>BKK-T-One Building</fullName>
                </value>
                <value>
                    <fullName>BKN-109 S 5th St</fullName>
                </value>
                <value>
                    <fullName>BKN-Brooklyn Navy Yard</fullName>
                </value>
                <value>
                    <fullName>BKN-Dumbo Heights (Prospect)</fullName>
                </value>
                <value>
                    <fullName>BKN-Dumbo Heights (Sands)</fullName>
                </value>
                <value>
                    <fullName>BKN-Montague St.</fullName>
                </value>
                <value>
                    <fullName>BKN-Williamsburg</fullName>
                </value>
                <value>
                    <fullName>BL-Alexanderstraße</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Move_In_Date__c</fullName>
        <label>Move In Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Office_Capacity__c</fullName>
        <description>Captures the size of office in which the prospect is interested</description>
        <inlineHelpText>Captures the size of office in which the prospect is interested
&gt;&gt;&gt;only populated when Office Type is "Office"</inlineHelpText>
        <label>Office Capacity</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Member</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Tours (Primary Member)</relationshipLabel>
        <relationshipName>Tours3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Scheduled_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Scheduled With</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Tours</relationshipLabel>
        <relationshipName>Tours</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Overall Status from SpaceStation</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>No Show</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Rescheduled</fullName>
                </value>
                <value>
                    <fullName>Not Rescheduled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tour_Date__c</fullName>
        <label>Tour Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Tour_Outcome_Notes__c</fullName>
        <inlineHelpText>Notes field from SpaceStation Outcome form</inlineHelpText>
        <label>Tour Outcome Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Tour_Outcome__c</fullName>
        <inlineHelpText>Outcome Status from SpaceStation</inlineHelpText>
        <label>Tour Outcome</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Ready to sign now</fullName>
                </value>
                <value>
                    <fullName>Interested</fullName>
                    <label>Tour Interested</label>
                </value>
                <value>
                    <fullName>Did not show up</fullName>
                    <label>No Show</label>
                </value>
                <value>
                    <fullName>Not Interested</fullName>
                    <label>Does not want Membership</label>
                </value>
                <value>
                    <fullName>Tour Reschedule</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unit_Type__c</fullName>
        <description>This field captures the information about the unit type in which the prospect is interested in. This information is captured during the Tour Outcome Form.</description>
        <inlineHelpText>This field captures the information about the unit type in which the prospect is interested in.</inlineHelpText>
        <label>Unit Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Daily Desk</fullName>
                </value>
                <value>
                    <fullName>Dedicated Desk</fullName>
                </value>
                <value>
                    <fullName>Hot Desk</fullName>
                </value>
                <value>
                    <fullName>Labs Desk</fullName>
                </value>
                <value>
                    <fullName>Lounge Membership</fullName>
                </value>
                <value>
                    <fullName>Office</fullName>
                </value>
                <value>
                    <fullName>Shared Desk</fullName>
                </value>
                <value>
                    <fullName>We Membership</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>uuid__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Tour</label>
    <nameField>
        <displayFormat>TRO-{0000}</displayFormat>
        <label>Tour Outcome ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tours</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Building__c</fullName>
        <label>Building</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AMS-Metropool</fullName>
                </value>
                <value>
                    <fullName>AMS-Labs</fullName>
                </value>
                <value>
                    <fullName>AMS-Weteringschans</fullName>
                </value>
                <value>
                    <fullName>ATX-Congress</fullName>
                </value>
                <value>
                    <fullName>ATX-Labs</fullName>
                </value>
                <value>
                    <fullName>BKN-Dumbo Heights</fullName>
                </value>
                <value>
                    <fullName>BK-Williamsburg</fullName>
                </value>
                <value>
                    <fullName>BOS-Fort Point</fullName>
                </value>
                <value>
                    <fullName>BOS-Labs</fullName>
                </value>
                <value>
                    <fullName>BOS-South Station</fullName>
                </value>
                <value>
                    <fullName>CHI-Fulton Market</fullName>
                </value>
                <value>
                    <fullName>CHI-Labs</fullName>
                </value>
                <value>
                    <fullName>CHI-RiverNorth</fullName>
                </value>
                <value>
                    <fullName>DC-Chinatown</fullName>
                </value>
                <value>
                    <fullName>DC-DuPont Circle</fullName>
                </value>
                <value>
                    <fullName>DC-Labs</fullName>
                </value>
                <value>
                    <fullName>DC-Wonder Bread Factory</fullName>
                </value>
                <value>
                    <fullName>ISR-Labs</fullName>
                </value>
                <value>
                    <fullName>LA-Fine Arts</fullName>
                </value>
                <value>
                    <fullName>LA-Fine Arts Building</fullName>
                </value>
                <value>
                    <fullName>LA-Hollywood</fullName>
                </value>
                <value>
                    <fullName>LA-Labs</fullName>
                </value>
                <value>
                    <fullName>LA-Promenade</fullName>
                </value>
                <value>
                    <fullName>LA-Santa Monica</fullName>
                </value>
                <value>
                    <fullName>LON-Devonshire</fullName>
                </value>
                <value>
                    <fullName>LON-East London</fullName>
                </value>
                <value>
                    <fullName>LON-Labs</fullName>
                </value>
                <value>
                    <fullName>LON-Moorgate</fullName>
                </value>
                <value>
                    <fullName>LON-South Bank</fullName>
                </value>
                <value>
                    <fullName>LON-Soho London</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/TourOutcomeFormControllerTest.cls
@isTest
public class TourOutcomeFormControllerTest{
    @TestSetup 
    static void testDataSetup() {
        SalesConsoleSettings.createSettings(); 
        Map<String, Object> mapContactFieldValues = new Map<String, Object>();
        List<Contact> lstContacts = new List<Contact>();
        mapContactFieldValues.put('firstname', 'test');
        mapContactFieldValues.put('lastname', 'Contact');
        mapContactFieldValues.put('email', 'joinus@wework.com');
        mapContactFieldValues.put('Status__c', 'active');
        mapContactFieldValues.put('UUID__c', 'UUID1');
        lstContacts.add((Contact)TestingUtility.createTestRecords(Contact.sObjectType,mapContactFieldValues,false));
        mapContactFieldValues.put('firstname', 'test');
        mapContactFieldValues.put('lastname', 'Contact1');
        mapContactFieldValues.put('email', 'testUser@wework.com');
        mapContactFieldValues.put('Status__c', 'active');
        mapContactFieldValues.put('UUID__c', 'UUID2');
        lstContacts.add((Contact)TestingUtility.createTestRecords(Contact.sObjectType, mapContactFieldValues, false));
        TestingUtility.insertListWithAssert(lstContacts);
        
        List<Building__c> lstBuildings = new List<Building__c>();
        Map<String, Object> mapBuildingFieldValues = new Map<String, Object>();
        mapBuildingFieldValues.put('Name', 'building1');
        mapBuildingFieldValues.put('uuid__c', 'UUID3');
        lstBuildings.add((Building__c)TestingUtility.createTestRecords(Building__c.sObjectType, mapBuildingFieldValues, false));
        TestingUtility.insertListWithAssert(lstBuildings); 
        
        List<Tour_Outcome__c> lstTourOutcomes = new List<Tour_Outcome__c>();
        Map<String, Object> mapTourOutcomeFieldValues = new Map<String, Object>();
        mapTourOutcomeFieldValues.put('Primary_Member__c', lstContacts[0].Id);
        mapTourOutcomeFieldValues.put('Scheduled_By__c', lstContacts[1].Id);
        mapTourOutcomeFieldValues.put('Status__c', 'Inquiry');
        mapTourOutcomeFieldValues.put('Tour_Date__c', system.today().addDays(3));
        mapTourOutcomeFieldValues.put('Tour_Outcome__c', 'Interested');
        mapTourOutcomeFieldValues.put('Move_In_Date__c', system.today().addDays(4));
        mapTourOutcomeFieldValues.put('Interested_Buildings__c', lstBuildings[0].Name+';Test Building');
        mapTourOutcomeFieldValues.put('Unit_Type__c', 'Office;HotDesk');
        mapTourOutcomeFieldValues.put('Office_Capacity__c', '11;12;13;14;15');
        mapTourOutcomeFieldValues.put('Tour_Outcome_Notes__c', 'Test Notes');
        mapTourOutcomeFieldValues.put('Objections__c', 'Too Expensive;Other');
        lstTourOutcomes.add((Tour_Outcome__c)TestingUtility.createTestRecords(Tour_Outcome__c.sObjectType, mapTourOutcomeFieldValues, false));
        TestingUtility.insertListWithAssert(lstTourOutcomes);
        
        Profile weworkSystemAdmin = [SELECT Id FROM Profile WHERE Name = 'WeWork System Administrator'];        
        Map<String,Object> userRecordMap = new Map<String,Object>();
        userRecordMap.put('LastName', 'Last Name');
        userRecordMap.put('Username', TestingUtility.createStringValue()+'username@user.com');
        userRecordMap.put('Email', 'testUser@wework.com');
        User testUser = TestingUtility.insertUserWithAssert(weworkSystemAdmin.Id, userRecordMap, true);   
        
        TourOutcomeFormController.Headers headers = new TourOutcomeFormController.Headers();
        headers.Authorization = 'Token token=dIc0nYcdaPvmFzUq3e0-CQ';
        
        TourOutcomeFormController.ReservableAvailabilityAPI reservAvailApi = new TourOutcomeFormController.ReservableAvailabilityAPI();
        reservAvailApi.headers = headers;
        reservAvailApi.url = 'https://sales-api-staging.wework.com/v2/office_availabilities/search';
        
        TourOutcomeFormController.CreateTourOutcomes tourOutcomes = new TourOutcomeFormController.CreateTourOutcomes();
        tourOutcomes.headers = headers;
        tourOutcomes.url = 'https://sales-api-staging.wework.com/v1/tour_outcomes';
        
        TourOutcomeFormController.NoShow noShow = new TourOutcomeFormController.NoShow();
        noShow.headers = headers;
        noShow.url = 'https://sales-api-staging.wework.com/v1/tours/tour_uuid/no_show';
        
        TourOutcomeFormController.Reasons reasons = new TourOutcomeFormController.Reasons();
        reasons.headers = headers;
        reasons.url = 'https://sales-api-staging.wework.com/v1/reasons';
        
        TourOutcomeFormController.HowHeards howHeards = new TourOutcomeFormController.HowHeards();
        howHeards.headers = headers;
        howHeards.url = 'https://sales-api-staging.wework.com/v2/how_heards';
        
        TourOutcomeFormController.Urgencies urgencies = new TourOutcomeFormController.Urgencies();
        urgencies.headers = headers;
        urgencies.url = 'https://sales-api-staging.wework.com/v2/urgencies';
        
        TourOutcomeFormController.ReservableTourBuildingAvailabilitiesAPI reservTour = new TourOutcomeFormController.ReservableTourBuildingAvailabilitiesAPI();
        reservTour.headers = headers;
        reservTour.url = 'https://sales-api-staging.wework.com/v2/available_tour_times';
        
        TourOutcomeFormController.ReservableRescheduleAPI reservReschedule = new TourOutcomeFormController.ReservableRescheduleAPI();
        reservReschedule.headers = headers;
        reservReschedule.url = 'https://sales-api-staging.wework.com/v1/tours/:id/reschedule';
        
        TourOutcomeFormController.TourOutcomeFormSettings tourOutcomeFormSetting = new TourOutcomeFormController.TourOutcomeFormSettings();
        tourOutcomeFormSetting.RestrictedProfiles = new set<String>{'WeWork NMD Admin', 'WeWork NMD User', 'WeWork NMD User - Beta', 'WeWork NMD User - Outbound'};
        tourOutcomeFormSetting.reservableAvailabilityAPI = reservAvailApi;
        tourOutcomeFormSetting.createTourOutcomes = tourOutcomes;
        tourOutcomeFormSetting.howHeards = howHeards;
        tourOutcomeFormSetting.noShow = noShow;
        tourOutcomeFormSetting.reasons = reasons;
        tourOutcomeFormSetting.reservableRescheduleAPI = reservReschedule;
        tourOutcomeFormSetting.reservableTourBuildingAvailabilitiesAPI = reservTour;
        tourOutcomeFormSetting.urgencies = urgencies;
    }
    
    @isTest 
    static void getFormDataTest(){
        List<Tour_Outcome__c> lstTourOutcomes = [SELECT Id, Name FROM Tour_Outcome__c];
        List<User> lstUsers = [SELECT Id, Name,Email FROM User Where Email = 'testUser@wework.com'];
        List<Contact> lstContacts = [SELECT Id, Name, email, UUID__c FROM Contact];        
        Map<String, Object> parameters = new Map<String, Object>{'IdOrUUID' => lstTourOutcomes[0].Id, 'label' => 'TourDetails'};
        String result = (String)TourOutcomeFormController.getFormData(parameters).data;
        Map<String, Object> formData = (Map<String, Object>)JSON.deserializeUntyped(result);
        
        List<object> tourRecord = (List<object>)formData.get('tourRecord');
        Map<String, Object> tourCompletedBy = (Map<String, Object>)formData.get('tourCompletedBy');
        Map<String, Object> setting = (Map<String, Object>)formData.get('setting');
        Map<String, Object> urgenciesSetting = (Map<String, Object>)setting.get('urgencies');
        TourOutcomeFormController.Urgencies urgencies = new TourOutcomeFormController.Urgencies();
        urgencies.url = 'https://sales-api-staging.wework.com/v2/urgencies';
        System.assertNotEquals(null, formData);
        Map<String, Object> mapResult = (Map<String, object>)tourRecord[0];       
        System.assertEquals(lstTourOutcomes[0].Id, mapResult.get('Id'));
        System.assertEquals(userInfo.getUserId(), formData.get('loggedInUser'));
        System.assertEquals(urgencies.url, urgenciesSetting.get('url'));
        System.assertEquals(lstContacts[0].Id, tourCompletedBy.get('Id'));
        System.runAs(lstUsers[0]){
            string userContextData = (string)TourOutcomeFormController.getFormData(parameters).data;
            Map<String, Object> userContextFormData = (Map<String, Object>)JSON.deserializeUntyped(userContextData);
            Map<String, Object> userContextTourCompletedBy = (Map<String, Object>)userContextFormData.get('tourCompletedBy'); 
            System.assertEquals(lstContacts[1].Id, userContextTourCompletedBy.get('Id'));
        }
        TestingUtility.deleteListWithAssert(lstContacts);
        System.runAs(lstUsers[0]){
            String userContextData = (String)TourOutcomeFormController.getFormData(parameters).data;
            Map<String, Object> userContextFormData = (Map<String, Object>)JSON.deserializeUntyped(userContextData);
            Map<String, Object> userContextTourCompletedBy = (Map<String, Object>)userContextFormData.get('tourCompletedBy');
            System.assertEquals(null, userContextTourCompletedBy.get('Id'));
        }
        try{
            DatabaseResult result1  = TourOutcomeFormController.getFormData(null);
        } catch(Exception exc){
            System.assertNotEquals(null, exc);
        } 
    }  
    
    @isTest 
    static void getUserContactInfoTest(){
        List<User> lstUsers = [SELECT Id, Name FROM User Where Email = 'testUser@wework.com'];
        List<Contact> lstContacts = [SELECT Id, Name, email, UUID__c FROM Contact];
        System.runAs(lstUsers[0]){
        String contact = TourOutcomeFormController.getUserContactInfo();
        Map<String, Object> contactMap = (Map<String, Object>)JSON.deserializeUntyped(contact.substringBetween('[', ']'));
        System.assertEquals(lstContacts[1].Id, contactMap.get('Id'));
        }
    }
    
    
}