objects/Building__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Aland Islands</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia, Plurinational State of</fullName>
                </value>
                <value>
                    <fullName>Bonaire, Sint Eustatius and Saba</fullName>
                </value>
                <value>
                    <fullName>Bosnia and Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Bouvet Island</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>India</fullName>
                </value>
                <value>
                    <fullName>Netherlands</fullName>
                </value>
                <value>
                    <fullName>UK</fullName>
                </value>
                <value>
                    <fullName>USA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Geography__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is a lookup of Geography object which is used to represent Google Maps Location so that we can reuse the same location as and when required within multiple objects.</description>
        <inlineHelpText>This field provides the exact or nearest google location where the building is located.</inlineHelpText>
        <label>Geography</label>
        <referenceTo>Geography__c</referenceTo>
        <relationshipLabel>Buildings</relationshipLabel>
        <relationshipName>Buildings_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Time_Zone__c</fullName>
        <label>Time Zone</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Africa/Algiers</fullName>
                </value>
                <value>
                    <fullName>Africa/Cairo</fullName>
                </value>
                <value>
                    <fullName>Africa/Casablanca</fullName>
                </value>
                <value>
                    <fullName>Africa/Johannesburg</fullName>
                </value>
                <value>
                    <fullName>Africa/Nairobi</fullName>
                </value>
                <value>
                    <fullName>America/Adak</fullName>
                </value>
                <value>
                    <fullName>America/Anchorage</fullName>
                </value>
                <value>
                    <fullName>America/Argentina/Buenos_Aires</fullName>
                </value>
                <value>
                    <fullName>America/Bogota</fullName>
                </value>
                <value>
                    <fullName>America/Caracas</fullName>
                </value>
                <value>
                    <fullName>America/Chicago</fullName>
                </value>
                <value>
                    <fullName>America/Denver</fullName>
                </value>
                <value>
                    <fullName>America/El_Salvador</fullName>
                </value>
                <value>
                    <fullName>America/Halifax</fullName>
                </value>
                <value>
                    <fullName>America/Indiana/Indianapolis</fullName>
                </value>
                <value>
                    <fullName>America/Lima</fullName>
                </value>
                <value>
                    <fullName>America/Los_Angeles</fullName>
                </value>
                <value>
                    <fullName>America/Mazatlan</fullName>
                </value>
                <value>
                    <fullName>America/Mexico_City</fullName>
                </value>
                <value>
                    <fullName>America/New_York</fullName>
                </value>
                <value>
                    <fullName>America/Panama</fullName>
                </value>
                <value>
                    <fullName>America/Phoenix</fullName>
                </value>
                <value>
                    <fullName>America/Puerto_Rico</fullName>
                </value>
                <value>
                    <fullName>America/Santiago</fullName>
                </value>
                <value>
                    <fullName>America/Sao_Paulo</fullName>
                </value>
                <value>
                    <fullName>America/Scoresbysund</fullName>
                </value>
                <value>
                    <fullName>America/St_Johns</fullName>
                </value>
                <value>
                    <fullName>America/Tijuana</fullName>
                </value>
                <value>
                    <fullName>Asia/Baghdad</fullName>
                </value>
                <value>
                    <fullName>Asia/Baku</fullName>
                </value>
                <value>
                    <fullName>Europe/Amsterdam</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UUID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Building</label>
    <nameField>
        <label>Building</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/City__c.object
<CustomObject>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <referenceTo>State__c</referenceTo>
        <relationshipLabel>Cities</relationshipLabel>
        <relationshipName>Cities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Country__c.object
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Geography__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <description>administrative_area_level_3 or locality should be saved here in City field.</description>
        <label>City</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Country of the Google Location</description>
        <label>Country</label>
        <length>120</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <description>This will be the administrative_area_level_2 value which generally represents County or District</description>
        <label>County/District</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Formatted_Address__c</fullName>
        <description>Formatted Address of the Location which will also be stored in Name field.</description>
        <label>Formatted Address</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>JSON__c</fullName>
        <description>Entire JSON retrieved from Google Maps should be saved here, so we can pull any additional information easily in future from Google if required.</description>
        <label>JSON</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Location_Type__c</fullName>
        <description>Location Type provided in the Google Location should be stored here.</description>
        <label>Location Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>APPROXIMATE</fullName>
                </value>
                <value>
                    <fullName>GEOMETRIC_CENTER</fullName>
                </value>
                <value>
                    <fullName>RANGE_INTERPOLATED</fullName>
                </value>
                <value>
                    <fullName>ROOFTOP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Nearest_Building__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field contains the value of nearest building which is included in buildings object.</description>
        <inlineHelpText>The value in this field comes from buildings available for the user.</inlineHelpText>
        <label>Nearest Building</label>
        <referenceTo>Building__c</referenceTo>
        <relationshipLabel>Geographies</relationshipLabel>
        <relationshipName>Geographies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Place_ID__c</fullName>
        <description>Google ID of the location. Google API calls is Place ID</description>
        <externalId>true</externalId>
        <label>Place ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>Google Places returns administrative_area_level_1 which is generally a State or Province which will be stored here.</description>
        <label>State/Provience</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <description>This object will represent Google Maps Location so that we can reuse same location as and when required within multiple objects.</description>
    <label>Geography</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Geographies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Setting__c.object
<CustomObject>
    <fields>
        <fullName>Data__c</fullName>
        <description>This should contain JSON formatted data for each setting record. The JSON object will vary from setting to setting.</description>
        <label>Data</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <description>We are creating object for Settings instead of using Custom Object because we need to store larger size of data which Custom Setting does not support. e.g. Mapping of Fields from Contact to Lead etc. which may go beyond 255 characters. 

It will not use caching but give more flexibility for coding.</description>
    <label>Sales Console Setting</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Console Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/State__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>States</relationshipLabel>
        <relationshipName>States</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/QueueInsertGeographyForBuildingTest.cls
@isTest
public class QueueInsertGeographyForBuildingTest {
    public static List<Geography__c> lstGeographies = new  List<Geography__c>();
    static{
         SalesConsoleSettings.createSettings();
        Geography__c objGeography1 = new Geography__c(
            Name='Baner1,Maharashtra',
            City__c='Pune',
            Country__c='Netherlands', District__c='Pune',
            Formatted_Address__c='Baner, Pune, Maharashtra, India', 
            Geocode__Latitude__s=18.5596581,
            Geocode__Longitude__s=73.7799374,
            JSON__c='{"address_components":[{"long_name":"Baner","short_name":"Baner","types":["","sublocality","sublocality_level_1"]},{"long_name":"Pune","short_name":"Pune","types":["locality","political"]},{"long_name":"Pune","short_name":"Pune","types":["administrative_area_level_2","political"]},{"long_name":"Maharashtra","short_name":"MH","types":["administrative_area_level_1","political"]},{"long_name":"India","short_name":"IN","types":["country","political"]}],"formatted_address":"Baner, Pune, Maharashtra, India","geometry":{"bounds":{"northeast":{"lat":18.5756111,"lng":73.8043045},"southwest":{"lat":18.544332,"lng":73.76332800000002}},"location":{"lat":18.5596581,"lng":73.7799374},"location_type":"APPROXIMATE","viewport":{"northeast":{"lat":18.5756111,"lng":73.8043045},"southwest":{"lat":18.544332,"lng":73.76332800000002}}},"place_id":"ChIJy9Nd8M--wjsRfat_-5cSkaE","types":["political","sublocality","sublocality_level_1"]}',
            Location_Type__c='APPROXIMATE', 
            Place_ID__c='ChIJy9Nd8M--wjsRfat_-5cSkaEvhj', 
            State__c='Maharashtra' 
        );  
        lstGeographies.add(objGeography1);
        Debug.log('objGeography1---'+objGeography1); 
        Geography__c objGeography2 = new Geography__c(
            Name='Sangamner, Maharashtra', City__c='Sangamner',
            Country__c='Indi2politicala', District__c='Ahmednagar',
            Formatted_Address__c='Sangamner, Maharashtra 422605, India', 
            Geocode__Latitude__s=19.5771387 ,
            Geocode__Longitude__s=74.2079648,
            JSON__c='{"address_components":[{"long_name":"Sangamner","short_name":"Sangamner","types":["locality","political"]},{"long_name":"Ahmednagar","short_name":"Ahmednagar","types":["administrative_area_level_2","political"]},{"long_name":"Maharashtra","short_name":"MH","types":["administrative_area_level_1","political"]},{"long_name":"India","short_name":"IN","types":["country","political"]},{"long_name":"422605","short_name":"422605","types":["postal_code"]}],"formatted_address":"Sangamner, Maharashtra 422605, India","geometry":{"bounds":{"northeast":{"lat":19.5954532,"lng":74.2273235},"southwest":{"lat":19.5567976,"lng":74.1888714}},"location":{"lat":19.5771387,"lng":74.2079648},"location_type":"APPROXIMATE","viewport":{"northeast":{"lat":19.5954532,"lng":74.2273235},"southwest":{"lat":19.5567976,"lng":74.1888714}}},"partial_match":true,"place_id":"ChIJeavrqdAB3TsRiL6oagFS3UY","types":["locality","political"]}',
            Location_Type__c='APPROXIMATE', 
            Place_ID__c='ChIJy9Nd8M--wjsRfat_-5cSkaEnjbhjg', 
            State__c='Maharashtra',
            CurrencyIsoCode='USD' 
        );  
        lstGeographies.add(objGeography2);
         Geography__c objGeography3 = new Geography__c(
            Name='Melbourne VIC, Victoria', City__c='Victoria',
            Country__c='Australia',
            Formatted_Address__c='Melbourne VIC, Australia', 
            Geocode__Latitude__s=-37.8136276,
            Geocode__Longitude__s=144.9630576,
            JSON__c='{"address_components":[{"long_name":"Melbourne","short_name":"Melbourne","types":["colloquial_area","locality","political"]},{"long_name":"Victoria","short_name":"VIC","types":["administrative_area_level_1","political"]},{"long_name":"Australia","short_name":"AU","types":["country","political"]}],"formatted_address":"Melbourne VIC, Australia","geometry":{"bounds":{"northeast":{"lat":-37.5112737,"lng":145.5125288},"southwest":{"lat":-38.4338593,"lng":144.5937418}},"location":{"lat":-37.8136276,"lng":144.9630576},"location_type":"APPROXIMATE","viewport":{"northeast":{"lat":-37.5112737,"lng":145.5125288},"southwest":{"lat":-38.4338593,"lng":144.5937418}}},"place_id":"ChIJ90260rVG1moRkM2MIXVWBAQ","types":["colloquial_area","locality","political"]}',
            Location_Type__c='APPROXIMATE', 
            Place_ID__c='ChIJ90260rVG1moRkM2MIXVWBAQ', 
            State__c='Victoria',
            CurrencyIsoCode='USD' 
        );
        lstGeographies.add(objGeography3);
        TestingUtility.insertListWithAssert(lstGeographies);
     }
    public static testMethod void testQueueInsertGeographyForBuilding(){
        Test.setMock(HttpCalloutMock.class, new QueueInsertGeoForBuildingMockRes());  
        Building__c building1 = new Building__c(City__c = 'Frankfurt', Country__c = 'Germany',Name = 'HE-Goetheplatz', CurrencyIsoCode = 'USD',Time_Zone__c = 'Europe/Amsterdam', Geography__c = lstGeographies[0].Id, UUID__c='11111');
        Building__c building2 = new Building__c(City__c = 'Brooklyn', Country__c = 'USA',Name = 'BKN-Williamsburg', CurrencyIsoCode = 'USD',Time_Zone__c = 'Europe/Amsterdam', Geography__c = lstGeographies[1].Id, UUID__c='22222');
        Building__c building3 = new Building__c(City__c = 'London', Country__c = 'UK',Name = 'LON-Kings Place', CurrencyIsoCode = 'USD',Time_Zone__c = 'Europe/Amsterdam', Geography__c = lstGeographies[2].Id, UUID__c='33333');
        Building__c building4 = new Building__c(City__c = 'Pune', Country__c = 'India',Name = 'Test', CurrencyIsoCode = 'USD',Time_Zone__c = 'Europe/Amsterdam', Geography__c = lstGeographies[2].Id);
		List<Building__c> lstBuildings = new List<Building__c>();
        lstBuildings.add(building1); 
        lstBuildings.add(building2);
        lstBuildings.add(building3);
        lstBuildings.add(building4);
        TestingUtility.insertListWithAssert(lstBuildings);
        
        List<Geography__c> lstGeographyUpdate = new List<Geography__c>(); 
        lstGeographies[0].Nearest_Building__c = lstBuildings[0].Id;
        lstGeographyUpdate.add(lstGeographies[0]);
        lstGeographies[1].Nearest_Building__c = lstBuildings[1].Id;
        lstGeographyUpdate.add(lstGeographies[1]);
        lstGeographies[2].Nearest_Building__c = lstBuildings[2].Id;
        lstGeographyUpdate.add(lstGeographies[2]);
        update lstGeographyUpdate;
        
        List<Geography__c> lstNewGeographys = new List<Geography__c>();
        Decimal latitude = 19.5771387 ;
        Decimal logitude = 74.2079648 ; 
        for(Integer index=1; index<10 ; index++){
            lstNewGeographys.add(new Geography__c(
                Name='Melbourne VIC, Victoria'+(index), City__c='Victoria'+(index),
                Country__c='Australia',
                Formatted_Address__c='Melbourne VIC, Australia', 
                Geocode__Latitude__s=(latitude+index),
                Geocode__Longitude__s=(logitude+index),
                JSON__c='{"address_components":[{"long_name":"Melbourne","short_name":"Melbourne","types":["colloquial_area","locality","political"]},{"long_name":"Victoria","short_name":"VIC","types":["administrative_area_level_1","political"]},{"long_name":"Australia","short_name":"AU","types":["country","political"]}],"formatted_address":"Melbourne VIC, Australia","geometry":{"bounds":{"northeast":{"lat":-37.5112737,"lng":145.5125288},"southwest":{"lat":-38.4338593,"lng":144.5937418}},"location":{"lat":-37.8136276,"lng":144.9630576},"location_type":"APPROXIMATE","viewport":{"northeast":{"lat":-37.5112737,"lng":145.5125288},"southwest":{"lat":-38.4338593,"lng":144.5937418}}},"place_id":"ChIJ90260rVG1moRkM2MIXVWBAQ","types":["colloquial_area","locality","political"]}',
                Location_Type__c='APPROXIMATE', 
                Place_ID__c= QueueInsertGeographyForBuildingTest.generateRandomString(30), 
                State__c='Victoria',
                CurrencyIsoCode='USD',
				Nearest_Building__c = lstBuildings[2].Id
            ));
            
        }
		TestingUtility.insertListWithAssert(lstNewGeographys);
        
        try{
            Test.startTest();
            Debug.log('In manageBuildingRelatedGeographies---'); 
            Setting__c googleGeolocationAPISetting = Settings.get('Google Geolocation API');
            if(googleGeolocationAPISetting != null){
                String googleGeolocationAPISettingData = googleGeolocationAPISetting.Data__c.replace('accept-encoding','acceptEncoding');
                Debug.log('googleGeolocationAPISettingData---'+googleGeolocationAPISettingData);
                GeographyHandler.GoogleGeolocationAPI googleGeolocationAPIRec = (GeographyHandler.GoogleGeolocationAPI)System.JSON.deserialize(googleGeolocationAPISettingData, GeographyHandler.GoogleGeolocationAPI.class);
                Debug.log('googleGeolocationAPIRec---'+googleGeolocationAPIRec);
                Debug.log('googleGeolocationAPIRec.geolocationAPI.url---'+googleGeolocationAPIRec.geolocationAPI.url);
                QueueInsertGeographyForBuilding jobQueueInsertGeographyForBuilding = new QueueInsertGeographyForBuilding(lstBuildings, googleGeolocationAPIRec);
                ID jobID = System.enqueueJob(jobQueueInsertGeographyForBuilding);
                Debug.Log('jobID---'+jobID);
             }
            Test.stopTest();
            for(Building__c buildingRec : [SELECT Name, Geography__c, Geography__r.Name, Geography__r.Nearest_Building__c FROM Building__c]){
                Debug.Log('buildingRec---'+buildingRec);
                System.assertNotEquals(null, buildingRec.Id);                
                if(buildingRec.Id == building1.Id){                    
                    System.assertNotEquals(null, building1.Geography__c);
                 }else if(buildingRec.Id == building2.Id){
                     System.assertNotEquals(null, building1.Geography__c);
                 }else if(buildingRec.Id == building3.Id){
                     System.assertNotEquals(null, building1.Geography__c);
                 }
             }
            
        }catch(Exception exc){
            Debug.log('exc :: '+exc);
        }
    }
    
    public static String generateRandomString(Integer len) {
        final String chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789abcdefghijklmnopqrstuvwxyz';
        String randStr = '';
        while (randStr.length() < len) {
            Integer idx = Math.mod(Math.abs(Crypto.getRandomInteger()), chars.length());
            randStr += chars.substring(idx, idx+1);
        }
        return randStr; 
    }
}