objects/Building__c.object
<CustomObject>
    <label>Building</label>
    <nameField>
        <label>Building</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Building__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Enter the specific building for which opportunity is associated</description>
        <inlineHelpText>This is the building / Nearest building to the geography entered by customer</inlineHelpText>
        <label>Building/Nearest Building</label>
        <referenceTo>Building__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Locations_Interested__c</fullName>
        <label>Locations Interested</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AMS-Labs</fullName>
                </value>
                <value>
                    <fullName>AMS-Metropool</fullName>
                </value>
                <value>
                    <fullName>AMS-Strawinskylaan</fullName>
                </value>
                <value>
                    <fullName>AMS-Weteringschans</fullName>
                </value>
                <value>
                    <fullName>ARC-Andres Arguibel 2860</fullName>
                </value>
                <value>
                    <fullName>ARC-Avenida Corrientes 800</fullName>
                </value>
                <value>
                    <fullName>ARC-Ing. Enrique Butty 275</fullName>
                </value>
                <value>
                    <fullName>ARC-Libertador 1000</fullName>
                </value>
                <value>
                    <fullName>ARC- Torre Bellini</fullName>
                </value>
                <value>
                    <fullName>ARG- Torre Bellini</fullName>
                </value>
                <value>
                    <fullName>ARN-Urban Escape</fullName>
                </value>
                <value>
                    <fullName>ATL-1372 Peachtree</fullName>
                </value>
                <value>
                    <fullName>ATL-3280 Peachtree Road NE</fullName>
                </value>
                <value>
                    <fullName>ATL-Colony Square</fullName>
                </value>
                <value>
                    <fullName>ATL-Tower Place</fullName>
                </value>
                <value>
                    <fullName>AUS-Congress</fullName>
                </value>
                <value>
                    <fullName>AUS-Domain</fullName>
                </value>
                <value>
                    <fullName>AUS-Labs</fullName>
                </value>
                <value>
                    <fullName>AUS-University Park</fullName>
                </value>
                <value>
                    <fullName>AUS-Westview</fullName>
                </value>
                <value>
                    <fullName>AUS-WeWork 801 Barton Springs</fullName>
                </value>
                <value>
                    <fullName>BCN-Diagonal 444</fullName>
                </value>
                <value>
                    <fullName>BHZ-Boulevard Shopping</fullName>
                </value>
                <value>
                    <fullName>BKK-Asia Centre</fullName>
                </value>
                <value>
                    <fullName>BKN-109 S 5th St</fullName>
                </value>
                <value>
                    <fullName>BKN-Brooklyn Heights</fullName>
                </value>
                <value>
                    <fullName>BKN-Dumbo Heights (Prospect)</fullName>
                </value>
                <value>
                    <fullName>BKN-Dumbo Heights (Sands)</fullName>
                </value>
                <value>
                    <fullName>BKN-Montague St.</fullName>
                </value>
                <value>
                    <fullName>BKN-Williamsburg</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/UpdateLocationInterestedOnOppQueueable.cls
public class UpdateLocationInterestedOnOppQueueable implements Queueable {
    public Opportunity objOpporturnity;
    public Id pAccountId;
    public Id pContactId;
    public String buildingName;
    public Id buildingId;
    public WWTypes.InboundLead pInboundLead;
    public UpdateLocationInterestedOnOppQueueable(Id AccountId, Id ContactId, WWTypes.InboundLead objInboundLead){
        this.pInboundLead = objInboundLead;
        this.pAccountId = AccountId;
        this.pContactId = ContactId;
    }
	public void execute(QueueableContext context) {
		sleep(8000);
        if(pInboundLead.tour_building_uuid != null || String.isNotBlank(pInboundLead.tour_building_uuid))
        	buildingName = BuildingHandler.getMultipicklistValuesFromUUID( new String[] { pInboundLead.tour_building_uuid });
        if(pInboundLead.opportunity_id != null || String.isNotBlank(pInboundLead.opportunity_id)){
        	this.objOpporturnity = OpportunityServices.getOpportunitybySFId(pInboundLead.opportunity_id);
            Debug.log('getOpportunitybySFId ==>> '+ this.objOpporturnity);
        } else {
			this.objOpporturnity = OpportunityServices.get_latest_open_opportunity_by_primary_member(pAccountId, pContactId, buildingName);
			Debug.log('get_latest_open_opportunity_by_primary_member ==>> '+ this.objOpporturnity);
		}
        
        if(pInboundLead.tour_building_uuid != null || String.isNotBlank(pInboundLead.tour_building_uuid))
			buildingId = BuildingHandler.getBuildingIdByUUID(pInboundLead.tour_building_uuid);
		
        if(this.objOpporturnity.locations_interested__c != null){ 
            debug.log('locations_interested__c of Opportunity != null ::'+ this.objOpporturnity.locations_interested__c);
            Set<String> location_Interested = new Set<String>(this.objOpporturnity.locations_interested__c.split(';'));
            location_Interested.add(buildingName);
            this.objOpporturnity.locations_interested__c = String.join(new List<String>(location_Interested),';');
            debug.log('updated locations_interested__c of Opportunity ::'+ this.objOpporturnity.locations_interested__c);
        } else {
            debug.log('locations_interested__c of Opportunity == null ::'+ buildingName);
            if(this.objOpporturnity != null)
            	this.objOpporturnity.locations_interested__c = buildingName;
        }		
        /*if(buildingId != null){
            //this.objOpporturnity.Building__c = buildingId;
        }*/
        if(this.objOpporturnity != null)
        	update this.objOpporturnity;
    }
	private static void sleep(Long milliSeconds){
		Long timeDiff = 0;
		DateTime firstTime = System.now();
		do
		{
			timeDiff = System.now().getTime() - firstTime.getTime();
		}
		while(timeDiff <= milliSeconds);
	}
}