objects/Building__c.object
<CustomObject>
    <fields>
        <fullName>Maximum_Tour_Days__c</fullName>
        <defaultValue>21</defaultValue>
        <label>Maximum Tour Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Tour_Spacing__c</fullName>
        <label>Tour Spacing</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Half Hour</fullName>
                </value>
                <value>
                    <fullName>Hour</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Building</label>
    <nameField>
        <label>Building</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Setting__c.object
<CustomObject>
    <fields>
        <fullName>Data__c</fullName>
        <description>This should contain JSON formatted data for each setting record. The JSON object will vary from setting to setting.</description>
        <label>Data</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <description>We are creating object for Settings instead of using Custom Object because we need to store larger size of data which Custom Setting does not support. e.g. Mapping of Fields from Contact to Lead etc. which may go beyond 255 characters. 

It will not use caching but give more flexibility for coding.</description>
    <label>Sales Console Setting</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Console Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Tour_Closed_Hour__c.object
<CustomObject>
    <fields>
        <fullName>Building__c</fullName>
        <label>Building</label>
        <referenceTo>Building__c</referenceTo>
        <relationshipLabel>Tours Closed Hours</relationshipLabel>
        <relationshipName>Tours_Closed_Hours</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <label>End Time</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>8:00AM</fullName>
                </value>
                <value>
                    <fullName>8:30AM</fullName>
                </value>
                <value>
                    <fullName>9:00AM</fullName>
                </value>
                <value>
                    <fullName>9:30AM</fullName>
                </value>
                <value>
                    <fullName>10:00AM</fullName>
                </value>
                <value>
                    <fullName>10:30AM</fullName>
                </value>
                <value>
                    <fullName>11:00AM</fullName>
                </value>
                <value>
                    <fullName>11:30AM</fullName>
                </value>
                <value>
                    <fullName>12:00PM</fullName>
                </value>
                <value>
                    <fullName>12:30PM</fullName>
                </value>
                <value>
                    <fullName>1:00PM</fullName>
                </value>
                <value>
                    <fullName>1:30PM</fullName>
                </value>
                <value>
                    <fullName>2:00PM</fullName>
                </value>
                <value>
                    <fullName>2:30PM</fullName>
                </value>
                <value>
                    <fullName>3:00PM</fullName>
                </value>
                <value>
                    <fullName>3:30PM</fullName>
                </value>
                <value>
                    <fullName>4:00PM</fullName>
                </value>
                <value>
                    <fullName>4:30PM</fullName>
                </value>
                <value>
                    <fullName>5:00PM</fullName>
                </value>
                <value>
                    <fullName>5:30PM</fullName>
                </value>
                <value>
                    <fullName>6:00PM</fullName>
                </value>
                <value>
                    <fullName>6:30PM</fullName>
                </value>
                <value>
                    <fullName>7:00PM</fullName>
                </value>
                <value>
                    <fullName>7:30PM</fullName>
                </value>
                <value>
                    <fullName>8:00PM</fullName>
                </value>
                <value>
                    <fullName>8:30PM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>8:00AM</fullName>
                </value>
                <value>
                    <fullName>8:30AM</fullName>
                </value>
                <value>
                    <fullName>9:00AM</fullName>
                </value>
                <value>
                    <fullName>9:30AM</fullName>
                </value>
                <value>
                    <fullName>10:00AM</fullName>
                </value>
                <value>
                    <fullName>10:30AM</fullName>
                </value>
                <value>
                    <fullName>11:00AM</fullName>
                </value>
                <value>
                    <fullName>11:30AM</fullName>
                </value>
                <value>
                    <fullName>12:00PM</fullName>
                </value>
                <value>
                    <fullName>12:30PM</fullName>
                </value>
                <value>
                    <fullName>1:00PM</fullName>
                </value>
                <value>
                    <fullName>1:30PM</fullName>
                </value>
                <value>
                    <fullName>2:00PM</fullName>
                </value>
                <value>
                    <fullName>2:30PM</fullName>
                </value>
                <value>
                    <fullName>3:00PM</fullName>
                </value>
                <value>
                    <fullName>3:30PM</fullName>
                </value>
                <value>
                    <fullName>4:00PM</fullName>
                </value>
                <value>
                    <fullName>4:30PM</fullName>
                </value>
                <value>
                    <fullName>5:00PM</fullName>
                </value>
                <value>
                    <fullName>5:30PM</fullName>
                </value>
                <value>
                    <fullName>6:00PM</fullName>
                </value>
                <value>
                    <fullName>6:30PM</fullName>
                </value>
                <value>
                    <fullName>7:00PM</fullName>
                </value>
                <value>
                    <fullName>7:30PM</fullName>
                </value>
                <value>
                    <fullName>8:00PM</fullName>
                </value>
                <value>
                    <fullName>8:30PM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tour_Schedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tour Schedule</label>
        <referenceTo>Tour_Schedule__c</referenceTo>
        <relationshipLabel>Tours Closed Hours</relationshipLabel>
        <relationshipName>Tours_Closed_Hours</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Tour Closed Hour</label>
    <nameField>
        <displayFormat>TCH-{0}</displayFormat>
        <label>Tour Closed Hour Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tours Closed Hours</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Tour_Schedule__c.object
<CustomObject>
    <fields>
        <fullName>Building__c</fullName>
        <label>Building</label>
        <referenceTo>Building__c</referenceTo>
        <relationshipLabel>Tour Schedules</relationshipLabel>
        <relationshipName>Tour_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Maximum_Tour_Days__c</fullName>
        <inlineHelpText>The number of days a tour can be booked in advance</inlineHelpText>
        <label>Maximum Tour Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <label>Product Line</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>WeWork</fullName>
                </value>
                <value>
                    <fullName>WeLive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <description>This field has all the available slot for Start Time of the Tour</description>
        <inlineHelpText>This field has all the available slot for Start Time of the Tour</inlineHelpText>
        <label>Start Time</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>8:00AM</fullName>
                </value>
                <value>
                    <fullName>8:30AM</fullName>
                </value>
                <value>
                    <fullName>9:00AM</fullName>
                </value>
                <value>
                    <fullName>9:30AM</fullName>
                </value>
                <value>
                    <fullName>10:00AM</fullName>
                </value>
                <value>
                    <fullName>10:30AM</fullName>
                </value>
                <value>
                    <fullName>11:00AM</fullName>
                </value>
                <value>
                    <fullName>11:30AM</fullName>
                </value>
                <value>
                    <fullName>12:00PM</fullName>
                </value>
                <value>
                    <fullName>12:30PM</fullName>
                </value>
                <value>
                    <fullName>1:00PM</fullName>
                </value>
                <value>
                    <fullName>1:30PM</fullName>
                </value>
                <value>
                    <fullName>2:00PM</fullName>
                </value>
                <value>
                    <fullName>2:30PM</fullName>
                </value>
                <value>
                    <fullName>3:00PM</fullName>
                </value>
                <value>
                    <fullName>3:30PM</fullName>
                </value>
                <value>
                    <fullName>4:00PM</fullName>
                </value>
                <value>
                    <fullName>4:30PM</fullName>
                </value>
                <value>
                    <fullName>5:00PM</fullName>
                </value>
                <value>
                    <fullName>5:30PM</fullName>
                </value>
                <value>
                    <fullName>6:00PM</fullName>
                </value>
                <value>
                    <fullName>6:30PM</fullName>
                </value>
                <value>
                    <fullName>7:00PM</fullName>
                </value>
                <value>
                    <fullName>7:30PM</fullName>
                </value>
                <value>
                    <fullName>8:00PM</fullName>
                </value>
                <value>
                    <fullName>8:30PM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tour_Spacing__c</fullName>
        <label>Tour Spacing</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Half Hour</fullName>
                </value>
                <value>
                    <fullName>Hour</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Tour Schedule</label>
    <nameField>
        <displayFormat>TS-{000}</displayFormat>
        <label>Tour Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tour Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TourCloseHourController.cls
/************************************************************************************************************************************
    Author      :   Dipak Pawar    
    Description :   This class contain methods that are used in TourCloseHourContoller
    
    History     :
    ----------------------------------------------------------------------------------------------------------------------------------
    VERSION     DATE                AUTHOR                  DETAIL
    1          25-10-2018         	Dipak Pawar        		Initial Developement
**************************************************************************************************************************************/
global with sharing class TourCloseHourController {      
    public static Boolean isInvoker = false;
    public static Savepoint sp {get; set;}
    public String mode {get; set;}
    
    static {
        isInvoker = ApexDebugLog.registerRootInvoker(ApexDebugLog.InvokerType.AURA, 'TourCloseHourController' + 'getsObjectPrefix', ApexDebugLog.InvokerType.AURA);        
    }
    
   /****************************************************************************************************************************
        Author              : Dipak Pawar
        Description         : This Method returns the pagedata
        Created Date        : 25/10/2018
       	Issue               : ST-2939
		LastModified Date   : 22/02/2019
		LastModified By		: Krishana Tupe
   *****************************************************************************************************************************/
    public TourCloseHourController(ApexPages.StandardController controller) {
        Map<String, String> mapParamerters = ApexPages.currentPage().getParameters();
        if(mapParamerters.containsKey('retURL')){
            String retURL = mapParamerters.get('retURL'); 
            mode = retURL.length() ==  3 ? 'NEW' : 'EDIT';
            //added for lightning view/edit 
            if(String.isNotBlank(retURL)){
                if(retURL.contains('actionName=view')){
                    mode = 'VIEW';
                } else if(retURL.contains('actionName=new')){
                    mode = 'EDIT'; 
                }  
            }            
        }else{
            mode = 'VIEW';
        }       
    }
    
    /****************************************************************************************************************************
        Author              : Dipak Pawar
        Description         : This Method returns the pagedata
        Created Date        : 25/10/2018
       	Issue               : ST-2939
   *****************************************************************************************************************************/
    @AuraEnabled
    public static DatabaseResult getPageData(String strSettingName, String tourScheduleId, String tourCloseHourId){
        try{
            Map<String, Object> mapPageData = new Map<String, Object>();
            
            String tourclosedHourPrefix = Tour_closed_hour__c.SObjectType.getDescribe().getKeyPrefix();
            mapPageData.put('objectPrefix', tourclosedHourPrefix);
            
            Setting__c objSettings = [SELECT Data__c FROM Setting__c WHERE Name =: strSettingName];
            SettingData objSettingData = (SettingData)JSON.deserialize(objSettings.Data__c, SettingData.class);
            mapPageData.put('instructions', objSettingData.Instructions);
            
            Id recordId = String.isNotBlank(tourCloseHourId) ? Id.valueOf(tourCloseHourId) : Id.valueOf(tourScheduleId);
            List<UserRecordAccess> lstUserRecordAccess = new List<UserRecordAccess>([SELECT RecordId, HasReadAccess, HasEditAccess, HasDeleteAccess FROM UserRecordAccess WHERE UserId =: UserInfo.getUserId() AND RecordId =: recordId ]);
            if(lstUserRecordAccess.size() > 0){
                UserRecordAccess objUserRecordAccess = lstUserRecordAccess[0];
                mapPageData.put('userHasReadAccess', objUserRecordAccess.HasReadAccess);
                mapPageData.put('userHasEditAccess', objUserRecordAccess.HasEditAccess);
                mapPageData.put('userHasDeleteAccess', objUserRecordAccess.HasDeleteAccess);
            }
            
            List<Tour_Schedule__c> lstTourSchedules = new List<Tour_Schedule__c>([SELECT Id, Name, CurrencyIsoCode, Building__c, Maximum_Tour_Days__c, Product_Line__c, Tour_Spacing__c, Start_Time__c, End_Time__c FROM Tour_Schedule__c WHERE Id =: tourScheduleId]);
            mapPageData.put('objTourSchedule', lstTourSchedules.isEmpty() ? null : lstTourSchedules[0]);            
            
            return new DatabaseResult(mapPageData);
        } catch(Exception pEx){
            ApexDebugLog.logException(pEx, strSettingName + ' ' + tourScheduleId, 'TourCloseHourController', 'getPageData');            
            return (new DatabaseResult(pEx));
        }
    }
    
    /****************************************************************************************************************************
        Author              : Dipak Pawar
        Description         : Wrapper class for Setting Data
        Created Date        : 26-10-2018
       	Issue               : ST-2939
   *****************************************************************************************************************************/
    public class SettingData {
        public List<String> Instructions {get;set;}        
    }
    
    public class TourCloseHourControllerException extends Exception{}
}