objects/Building__c.object
<CustomObject>
    <fields>
        <fullName>Cluster_Name__c</fullName>
        <label>Cluster Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cluster_Sales_Lead_Email__c</fullName>
        <label>Cluster Sales Lead Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Cluster_Sales_Lead_Name__c</fullName>
        <inlineHelpText>&gt;&gt;&gt;used for assignment of relational deal type</inlineHelpText>
        <label>Cluster Sales Lead Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cluster_Sales_Manager_Email__c</fullName>
        <label>Cluster Sales Manager Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Cluster_Sales_Manager_Name__c</fullName>
        <label>Cluster Sales Manager Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Buildings</relationshipLabel>
        <relationshipName>Buildings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Community_Lead_Name__c</fullName>
        <label>Community Lead Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Community_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>&gt;&gt;&gt;used for assignment of transactional deal type</inlineHelpText>
        <label>Community Lead</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Buildings3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Community_Manager_Name__c</fullName>
        <label>Community Manager Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Portfolio</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Buildings</relationshipLabel>
        <relationshipName>Buildings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Portfolio_Name__c</fullName>
        <label>Portfolio Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Portfolio_Sales_Manager_Email__c</fullName>
        <label>Portfolio Sales Manager Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Portfolio_Sales_Manager_Name__c</fullName>
        <label>Portfolio Sales Manager Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region_Name__c</fullName>
        <label>Region Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Regional_Sales_Manager_Email__c</fullName>
        <label>Regional Sales Manager Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Regional_Sales_Manager_Name__c</fullName>
        <label>Regional Sales Manager Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Responsible_CM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the Community Manager that is assigned Accounts for Consumer Deals</description>
        <inlineHelpText>Responsible CM of building
&gt;&gt;&gt;SFDC User lookup
&gt;&gt;&gt;in old assignment rules used for assignment of transactional deal type</inlineHelpText>
        <label>Community Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Buildings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Territory_Name__c</fullName>
        <label>Territory Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory_Sales_Manager_Email__c</fullName>
        <label>Territory Sales Manager Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Territory_Sales_Manager_Name__c</fullName>
        <label>Territory Sales Manager Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Building</label>
    <nameField>
        <label>Building</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Cluster__c.object
<CustomObject>
    <fields>
        <fullName>Cluster_Sales_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cluster Sales Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Clusters1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>&gt;&gt;&gt;used for ROE assignment</inlineHelpText>
        <label>Sales Lead</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Clusters</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Cluster</label>
    <nameField>
        <label>Cluster</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Market__c.object
<CustomObject>
    <fields>
        <fullName>Portfolio_Sales_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Senior Sales Exec of Portfolio</inlineHelpText>
        <label>Portfolio Sales Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Markets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <formula>TerritoryID__r.RegionID__r.Region__c</formula>
        <inlineHelpText>Display name (text)</inlineHelpText>
        <label>Region Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TerritoryID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Territory</label>
        <referenceTo>Territory__c</referenceTo>
        <relationshipLabel>Portfolios</relationshipLabel>
        <relationshipName>Portfolio</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <formula>TerritoryID__r.Territory__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Display name (text)</inlineHelpText>
        <label>Territory Name</label>
        <type>Text</type>
    </fields>
    <description>We are introducing new object Market so that same building can fall under multiple Markets as per Marketing department requirement.</description>
    <label>Portfolio</label>
    <nameField>
        <label>Portfolio</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portfolios</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Region__c.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <description>Display name for region</description>
        <inlineHelpText>Display name (text)</inlineHelpText>
        <label>Region Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Regional_Sales_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Senior Sales Exec of Region</inlineHelpText>
        <label>Regional Sales Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Regions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Region</label>
    <nameField>
        <label>Region</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Setting__c.object
<CustomObject>
    <fields>
        <fullName>Data__c</fullName>
        <description>This should contain JSON formatted data for each setting record. The JSON object will vary from setting to setting.</description>
        <label>Data</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <description>We are creating object for Settings instead of using Custom Object because we need to store larger size of data which Custom Setting does not support. e.g. Mapping of Fields from Contact to Lead etc. which may go beyond 255 characters. 

It will not use caching but give more flexibility for coding.</description>
    <label>Sales Console Setting</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Console Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Territory__c.object
<CustomObject>
    <fields>
        <fullName>RegionID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Region</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Territories</relationshipLabel>
        <relationshipName>Territories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <formula>RegionID__r.Region__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Display name (text)</inlineHelpText>
        <label>Region Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory_Sales_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Senior Sales Exec of Territory</inlineHelpText>
        <label>Territory Sales Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <description>Display Name for Territory, something user friendly to user</description>
        <inlineHelpText>Display name (text)</inlineHelpText>
        <label>Territory Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Territory</label>
    <nameField>
        <label>Territory</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Building__c</fullName>
        <label>Building</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AMS-Metropool</fullName>
                </value>
                <value>
                    <fullName>AMS-Labs</fullName>
                </value>
                <value>
                    <fullName>AMS-Weteringschans</fullName>
                </value>
                <value>
                    <fullName>ATX-Congress</fullName>
                </value>
                <value>
                    <fullName>ATX-Labs</fullName>
                </value>
                <value>
                    <fullName>BKN-Dumbo Heights</fullName>
                </value>
                <value>
                    <fullName>BK-Williamsburg</fullName>
                </value>
                <value>
                    <fullName>BOS-Fort Point</fullName>
                </value>
                <value>
                    <fullName>BOS-Labs</fullName>
                </value>
                <value>
                    <fullName>BOS-South Station</fullName>
                </value>
                <value>
                    <fullName>CHI-Fulton Market</fullName>
                </value>
                <value>
                    <fullName>CHI-Labs</fullName>
                </value>
                <value>
                    <fullName>CHI-RiverNorth</fullName>
                </value>
                <value>
                    <fullName>DC-Chinatown</fullName>
                </value>
                <value>
                    <fullName>DC-DuPont Circle</fullName>
                </value>
                <value>
                    <fullName>DC-Labs</fullName>
                </value>
                <value>
                    <fullName>DC-Wonder Bread Factory</fullName>
                </value>
                <value>
                    <fullName>ISR-Labs</fullName>
                </value>
                <value>
                    <fullName>LA-Fine Arts</fullName>
                </value>
                <value>
                    <fullName>LA-Fine Arts Building</fullName>
                </value>
                <value>
                    <fullName>LA-Hollywood</fullName>
                </value>
                <value>
                    <fullName>LA-Labs</fullName>
                </value>
                <value>
                    <fullName>LA-Promenade</fullName>
                </value>
                <value>
                    <fullName>LA-Santa Monica</fullName>
                </value>
                <value>
                    <fullName>LON-Devonshire</fullName>
                </value>
                <value>
                    <fullName>LON-East London</fullName>
                </value>
                <value>
                    <fullName>LON-Labs</fullName>
                </value>
                <value>
                    <fullName>LON-Moorgate</fullName>
                </value>
                <value>
                    <fullName>LON-South Bank</fullName>
                </value>
                <value>
                    <fullName>LON-Soho London</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Full_Name__c</fullName>
        <formula>FirstName &amp;" "&amp; LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Full Name</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/BuildingTriggerHandler.cls
/*******************************************************************************************************************************
    Author 		: Ajaysinh Chauhan
    Description : ---
    History		: --

----------------------------------------------------------------------------------------------------------------------------------
    VERSION					DATE					AUTHOR							DETAIL
    1						--		                Ajaysinh Chauhan	            Initial Developement
********************************************************************************************************************************/
public class BuildingTriggerHandler extends ITriggerHandler {
    public BuildingTriggerHandler(){
        super('Building__c');
    } 
    public static Map<Id, Cluster__c> mapClusters;
    public static Map<Id, Market__c> mapPortfolios;
    public static Map<Id, Building__c> mapBuildings;
    
/*******************************************************************************************************************************
    Author 				: Ajaysinh Chauhan
    Description 		: This method overrides before insert method from ITriggerHander which will control the execution flow.
    Created Date		:	--
    Last Modified Date	: 02 Feb, 2018
    Last Modified By	: Prashant Mane
********************************************************************************************************************************/
    public override void BeforeInsert(List<SObject> listNewItems){        
        if(TriggerSettings.mappedField.Building_SetTerritoryStructure)
            setTerritoryStructure((List<Building__c>)listNewItems, null, null, null);
    }
    
/******************************************************************************************************************************
    Author              : Nikhil Mehta
    Description         : This method overrides after Insert method from ITriggerHander which will control the execution flow.
    Created Date        : 16 May, 2018
*******************************************************************************************************************************/
    public override void AfterInsert(List<SObject> listNewItems, Map<Id, SObject> mapNewItems){
        if(TriggerSettings.mappedField.Building_ManageBuildingRelatedGeographies){
            manageBuildingRelatedGeographies((List<Building__c>)listNewItems,(Map<Id,Building__c>)mapNewItems);
        }
    }
    
/*******************************************************************************************************************************
    Author 				: Ajaysinh Chauhan
    Description 		: This method overrides before update method from ITriggerHander which will control the execution flow.
    Created Date		:	--
    Last Modified Date	: 02 Feb, 2018
    Last Modified By	: Prashant Mane
********************************************************************************************************************************/   
    public override void BeforeUpdate(List<SObject> listNewItems, Map<Id, SObject> mapNewItems, List<SObject> listOldItems, Map<Id, SObject> mapOldItems){
        if(TriggerSettings.mappedField.Building_SetTerritoryStructure)
            setTerritoryStructure((List<Building__c>) listNewItems, (Map<Id, Building__c>) mapNewItems, (List<Building__c>) listOldItems, (Map<Id, Building__c>) mapOldItems);
    }
    
/*******************************************************************************************************************************
    Author 				: Ajaysinh Chauhan
    Description 		: Method used to get Building Structures.
    Created Date		:	--
    Last Modified Date	: 02 Feb, 2018
    Last Modified By	: Prashant Mane
********************************************************************************************************************************/
    public static void getBuildingStructure(){
        mapClusters = new Map<Id, Cluster__c>([SELECT Id, Name, Cluster_Sales_Manager__r.Full_Name__c, Cluster_Sales_Manager__r.Email, Sales_Lead__r.Full_Name__c, Sales_Lead__r.Email FROM Cluster__c]);
        mapPortfolios = new Map<Id, Market__c>([SELECT Id, Name, Portfolio_Sales_Manager__r.Full_Name__c, Portfolio_Sales_Manager__r.Email, TerritoryID__r.Territory__c, TerritoryID__r.Territory_Sales_Manager__r.Full_Name__c, TerritoryID__r.Territory_Sales_Manager__r.Email, TerritoryID__r.RegionID__r.Region__c, TerritoryID__r.RegionID__r.Regional_Sales_Manager__r.Full_Name__c, TerritoryID__r.RegionID__r.Regional_Sales_Manager__r.Email FROM Market__c]); 
        mapBuildings = new Map<Id, Building__c>([SELECT Id, Name, Community_Lead__c, Community_Lead__r.Name, Responsible_CM__c, Responsible_CM__r.Name FROM Building__c]); 
    }
    
/*******************************************************************************************************************************
    Author 				: Ajaysinh Chauhan
    Description 	    : Method Used To Set Territory Structure in Both Before inserion And Before Updation of Building Record.
    Created Date		: --
    Last Modified Date	: 02 Feb, 2018
    Last Modified By	: Prashant Mane
********************************************************************************************************************************/
    public static void setTerritoryStructure(List<Building__c> listNewItems, Map<Id, Building__c> mapNewItems, List<Building__c> listOldItems, Map<Id, Building__c> mapOldItems){ 
        if(mapClusters == null || mapPortfolios == null ){
            BuildingTriggerHandler.getBuildingStructure();
        }
        for(Building__c objBuilding : listNewItems){
            if(objBuilding.Market__c != null){
                if(mapPortfolios != null && mapPortfolios.containsKey(objBuilding.Market__c) && (Trigger.isInsert || objBuilding.Market__c != mapOldItems.get(objBuilding.Id).get('Market__c'))){
                    objBuilding.Portfolio_Name__c = mapPortfolios.get(objBuilding.Market__c).Name;
                    objBuilding.Territory_Name__c = mapPortfolios.get(objBuilding.Market__c).TerritoryID__r.Territory__c;
                    objBuilding.Region_Name__c = mapPortfolios.get(objBuilding.Market__c).TerritoryID__r.RegionID__r.Region__c;
                    objBuilding.Portfolio_Sales_Manager_Name__c =  mapPortfolios.get(objBuilding.Market__c).Portfolio_Sales_Manager__r.Full_Name__c;
                    objBuilding.Territory_Sales_Manager_Name__c =  mapPortfolios.get(objBuilding.Market__c).TerritoryID__r.Territory_Sales_Manager__r.Full_Name__c;
                    objBuilding.Regional_Sales_Manager_Name__c =  mapPortfolios.get(objBuilding.Market__c).TerritoryID__r.RegionID__r.Regional_Sales_Manager__r.Full_Name__c;
                    objBuilding.Portfolio_Sales_Manager_Email__c = mapPortfolios.get(objBuilding.Market__c).Portfolio_Sales_Manager__r.Email;
                    objBuilding.Territory_Sales_Manager_Email__c = mapPortfolios.get(objBuilding.Market__c).TerritoryID__r.Territory_Sales_Manager__r.Email;
                    objBuilding.Regional_Sales_Manager_Email__c = mapPortfolios.get(objBuilding.Market__c).TerritoryID__r.RegionID__r.Regional_Sales_Manager__r.Email;
                }    
            } else {
                objBuilding.Portfolio_Name__c = null;
                objBuilding.Territory_Name__c = null;
                objBuilding.Region_Name__c = null; 
                objBuilding.Portfolio_Sales_Manager_Name__c = null;
                objBuilding.Territory_Sales_Manager_Name__c = null;
                objBuilding.Regional_Sales_Manager_Name__c = null;
                objBuilding.Portfolio_Sales_Manager_Email__c = null;
                objBuilding.Territory_Sales_Manager_Email__c = null;
                objBuilding.Regional_Sales_Manager_Email__c = null;
            }
            
            if(objBuilding.Cluster__c != null){
                if(mapClusters != null && mapClusters.containsKey(objBuilding.Cluster__c) && (Trigger.isInsert || objBuilding.Cluster__c != mapOldItems.get(objBuilding.Id).get('Cluster__c'))){
                    objBuilding.Cluster_Name__c = mapClusters.get(objBuilding.Cluster__c).Name;
                    objBuilding.Cluster_Sales_Manager_Name__c = mapClusters.get(objBuilding.Cluster__c).Cluster_Sales_Manager__r.Full_Name__c;
                    objBuilding.Cluster_Sales_Lead_Name__c = mapClusters.get(objBuilding.Cluster__c).Sales_Lead__r.Full_Name__c;
                    objBuilding.Cluster_Sales_Manager_Email__c = mapClusters.get(objBuilding.Cluster__c).Cluster_Sales_Manager__r.Email;
                    objBuilding.Cluster_Sales_Lead_Email__c = mapClusters.get(objBuilding.Cluster__c).Sales_Lead__r.Email;
                }                   
            }else{
                objBuilding.Cluster_Sales_Manager_Name__c = null;
                objBuilding.Cluster_Sales_Lead_Name__c = null;
                objBuilding.Cluster_Sales_Manager_Email__c = null;
                objBuilding.Cluster_Sales_Lead_Email__c = null;
            }  
            
            if( objBuilding.Community_Lead__c != null && mapBuildings != null && mapBuildings.get(objBuilding.Id) != null ){   
                
                objBuilding.Community_Lead_Name__c = mapBuildings.get(objBuilding.Id).Community_Lead__r.Name;
                objBuilding.Community_Manager_Name__c = mapBuildings.get(objBuilding.Id).Responsible_CM__r.Name;
            } else{
                objBuilding.Community_Lead_Name__c = null;
                objBuilding.Community_Manager_Name__c = null;
            } 
            
        }
    }
    
/*************************************************************************************************
    Author              : Nikhil Mehta
    Description         : This method is used to map new or existing geography on building
    Created Date        : 14 May, 2018
    Issue No			: ST-2267
****************************************************************************************************/
    public static void manageBuildingRelatedGeographies(List<Building__c> lstNewBuildings, Map<Id, Building__c> mapNewBuildings){
        Setting__c googleGeolocationAPISetting = Settings.get('Google Geolocation API');
        if(googleGeolocationAPISetting != null){
            String googleGeolocationAPISettingData = googleGeolocationAPISetting.Data__c.replace('accept-encoding','acceptEncoding');
            GeographyHandler.GoogleGeolocationAPI googleGeolocationAPIRec = (GeographyHandler.GoogleGeolocationAPI)System.JSON.deserialize(googleGeolocationAPISettingData, GeographyHandler.GoogleGeolocationAPI.class);
            if(!Test.isRunningTest()){
                QueueInsertGeographyForBuilding jobQueueInsertGeographyForBuilding = new QueueInsertGeographyForBuilding(lstNewBuildings,googleGeolocationAPIRec);
                ID jobID = System.enqueueJob(jobQueueInsertGeographyForBuilding);
            }
        }
    }
}