objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Event_Email_Opt_Out__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Please check if this event should not receive automated email cadences from Marketing Cloud</description>
        <label>Event Email Opt Out</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>This is the latest status coming from Space systems through Jitterbunny of the individual member. This tells us if the user is active or not.</description>
        <inlineHelpText>This is accurate status of a contact if it is an active member of our products or not.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>active</fullName>
                </value>
                <value>
                    <fullName>inactive</fullName>
                    <default>true</default>
                    <label>inactive</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Journey__c.object
<CustomObject>
    <fields>
        <fullName>Lead_Source__c</fullName>
        <description>Source of the Tour, how it was booked.</description>
        <label>Lead Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>42 Floors</fullName>
                </value>
                <value>
                    <fullName>ads-twitter</fullName>
                </value>
                <value>
                    <fullName>Adwords</fullName>
                </value>
                <value>
                    <fullName>Affiliate Referral</fullName>
                </value>
                <value>
                    <fullName>Broker Referral</fullName>
                </value>
                <value>
                    <fullName>Cold Call</fullName>
                </value>
                <value>
                    <fullName>Cold Email</fullName>
                </value>
                <value>
                    <fullName>Community Team Referral</fullName>
                </value>
                <value>
                    <fullName>Craigslist Ad</fullName>
                </value>
                <value>
                    <fullName>Employee Referral</fullName>
                </value>
                <value>
                    <fullName>Event</fullName>
                </value>
                <value>
                    <fullName>Facebook</fullName>
                </value>
                <value>
                    <fullName>Google</fullName>
                </value>
                <value>
                    <fullName>Guest</fullName>
                </value>
                <value>
                    <fullName>Guest Wifi</fullName>
                </value>
                <value>
                    <fullName>Id</fullName>
                </value>
                <value>
                    <fullName>Inbound Call</fullName>
                </value>
                <value>
                    <fullName>Inbound Email</fullName>
                </value>
                <value>
                    <fullName>Landing Page Campaign</fullName>
                </value>
                <value>
                    <fullName>LinkedIn Paid</fullName>
                </value>
                <value>
                    <fullName>Member Referral</fullName>
                </value>
                <value>
                    <fullName>Newsletter</fullName>
                </value>
                <value>
                    <fullName>Newsletter Campaign</fullName>
                </value>
                <value>
                    <fullName>Olark Chat</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Other Referral</fullName>
                </value>
                <value>
                    <fullName>Outbound Email/Cold Call</fullName>
                </value>
                <value>
                    <fullName>Partner Referral</fullName>
                </value>
                <value>
                    <fullName>Phone Call</fullName>
                </value>
                <value>
                    <fullName>Press Campaign</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Primary Contact of the Journey</description>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Journeys</relationshipLabel>
        <relationshipName>Journeys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>If journey is for a Lead this will be the Primary Lead. Only Primary Contact or Primary Lead can be specified not both.</description>
        <label>Primary Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Journeys</relationshipLabel>
        <relationshipName>Journeys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>New Field to Capture Journey Status</description>
        <label>Journey Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Started</fullName>
                    <default>true</default>
                    <label>Started</label>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Trying to Reach</fullName>
                </value>
                <value>
                    <fullName>In Contact</fullName>
                </value>
                <value>
                    <fullName>Nurture</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Transferred</fullName>
                </value>
                <value>
                    <fullName>Unresponsive</fullName>
                </value>
                <value>
                    <fullName>No Contact</fullName>
                </value>
                <value>
                    <fullName>Unqualified</fullName>
                </value>
                <value>
                    <fullName>Auto-Complete/Expiration</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>We are going to use this object as Sales Journey of the user. Which begins when a person shows interest in one of our products or we decide to reach out to show our products.</description>
    <label>Journey</label>
    <nameField>
        <label>Customer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Journeys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/UpdateJourneyOnCampaignMemberBatch.cls
global class UpdateJourneyOnCampaignMemberBatch implements Database.Batchable<sObject>,Schedulable  {
    List<Journey__c> lstJournyesToUpdate = new List<Journey__c>();
    Map<String,Set<String>> setting = (Map<String,Set<String>>)JSON.deserialize(Settings.get('UpdateJourneyOnCampaignMemberBatch').Data__c,Map<String,Set<String>>.class);
    global Database.QueryLocator start(Database.BatchableContext bc) {
        Date Dtoday = System.today();
        Set<String> CampaignType = setting.get('CampaignType');
        //return Database.getQueryLocator('SELECT Id,Name,StartDate,Type,(SELECT Id,Name,ContactId,LeadId,CreatedDate From CampaignMembers) From Campaign WHERE StartDate =: Dtoday AND Type IN : CampaignType');
        return Database.getQueryLocator('SELECT Id,Name,ContactId,LeadId,CreatedDate,CampaignId From CampaignMember WHERE Campaign.Event_Email_Opt_Out__c = true AND ( Campaign.StartDate =: Dtoday AND Campaign.Type IN : CampaignType)');
    }
    global void execute(SchedulableContext ctx) {
        UpdateJourneyOnCampaignMemberBatch batchSch = new UpdateJourneyOnCampaignMemberBatch();
        database.executebatch(batchSch,1);
    }
    global void execute(Database.BatchableContext bc, List<sObject> scope){
        Debug.log('In  execute : '+scope);
        set<string> Ids = new set<string>();
        map<String,CampaignMember> mapCampaignMembers = new map<String,CampaignMember>();
        map<String,String> mapLeadIdWithCampaignMembers = new map<String,String>();
        map<String,String> mapContactIdWithCampaignMembers = new map<String,String>();
        for(CampaignMember cmpMember : (List<CampaignMember>) scope){
            mapCampaignMembers.put(cmpMember.Id, cmpMember);
            if(cmpMember.LeadId != null){
                Ids.add(cmpMember.LeadId);
                mapLeadIdWithCampaignMembers.put(cmpMember.LeadId, cmpMember.Id);
            }
            if(cmpMember.ContactId != null){
                Ids.add(cmpMember.ContactId);
                mapContactIdWithCampaignMembers.put(cmpMember.ContactId, cmpMember.Id);
            } 
        }

        Set<String> JourneyLeadSource = setting.get('JourneyLeadSource');
        //List<Journey__c> lstJourneys = [SELECT Id,Name,Primary_Contact__c,Primary_Lead__c,CreatedDate From Journey__c Where Lead_Source__c IN : JourneyLeadSource AND (Primary_Contact__c IN :Ids OR Primary_Lead__c IN:Ids) ];
        //Debug.log('lstJourneys records ==>:  '+lstJourneys);
        //Debug.log('lstJourneys ==>:  '+lstJourneys.size());
        for(Journey__c objjourney : [ SELECT Id,Name,Primary_Contact__c,Primary_Lead__c,CreatedDate From Journey__c Where Status__c != 'Completed' AND (Lead_Source__c IN : JourneyLeadSource AND (Primary_Contact__c IN :Ids OR Primary_Lead__c IN:Ids)) ]){
            if(objjourney.Primary_Lead__c != null){
                if(mapLeadIdWithCampaignMembers.containsKey(objjourney.Primary_Lead__c)){
                    CampaignMember cmpMember = mapCampaignMembers.get(mapLeadIdWithCampaignMembers.get(objjourney.Primary_Lead__c));
                    if(date.newinstance(cmpMember.CreatedDate.year(),cmpMember.CreatedDate.month(),cmpMember.CreatedDate.day()) == date.newinstance(objjourney.CreatedDate.year(),objjourney.CreatedDate.month(),objjourney.CreatedDate.day())){
                        Debug.log('In Lead : '+objjourney.Id);
                        Journey__c objLJourney = new Journey__c();
                        objLJourney.Id = objjourney.Id;
                        objLJourney.Status__c = 'Completed';
                        lstJournyesToUpdate.add(objLJourney);
                    }
                }
            }
            if(objjourney.Primary_Contact__c != null){
                if(mapContactIdWithCampaignMembers.containsKey(objjourney.Primary_Contact__c)){
                    CampaignMember cmpMember = mapCampaignMembers.get(mapContactIdWithCampaignMembers.get(objjourney.Primary_Contact__c));
                    if(date.newinstance(cmpMember.CreatedDate.year(),cmpMember.CreatedDate.month(),cmpMember.CreatedDate.day()) == date.newinstance(objjourney.CreatedDate.year(),objjourney.CreatedDate.month(),objjourney.CreatedDate.day())){
                        Debug.log('In Contact : '+objjourney.Id);
                        Journey__c objCJourney = new Journey__c();
                        objCJourney.Id = objjourney.Id;
                        objCJourney.Status__c = 'Completed';
                        lstJournyesToUpdate.add(objCJourney);
                    }
                }
            }
        }
        Debug.log('lstJournyesToUpdate ==>.'+lstJournyesToUpdate);
        Database.update(lstJournyesToUpdate);
    }    
    
    global void finish(Database.BatchableContext bc){
        Set<String> emailtoAddr = setting.get('NotifyEmails');
        List<String> emails = new List<String>();
        emails.addAll(emailtoAddr);
        if(emailtoAddr.size() > 0){
            AsyncApexJob a = [SELECT Id, Status, NumberOfErrors, JobItemsProcessed, TotalJobItems, CreatedBy.Email FROM AsyncApexJob WHERE Id = :bc.getJobId()];        
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            mail.setToAddresses(emails);
            mail.setSubject('Journeys updated ' + a.Status);
            mail.setPlainTextBody('The UpdateJourneyOnCampaignMemberBatch batch Apex job processed ' + a.TotalJobItems + ' batches with '+ a.NumberOfErrors + ' failures.');
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail }); 
        }
    }    
    
}