objects/Case.object
<CustomObject>
    <fields>
        <fullName>Actual_Guardrail_Margin__c</fullName>
        <label>Actual Deal Guardrail Margin (%)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Case_Template_Name__c</fullName>
        <description>Name of the Task Template from which this Case was created, so trigger can easily identify the Task Template and assign the owner of the Case accordingly.</description>
        <externalId>true</externalId>
        <label>Case Template Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Case Template from which this Case was created, so trigger can easily identify the Case and assign the owner of the Case accordingly.</description>
        <label>Case Template</label>
        <referenceTo>Case_Template__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cash_Margin__c</fullName>
        <label>Cash Margin (%)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Commitment_Term_from_Model__c</fullName>
        <label>Commitment Term (months)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Deal_RSF__c</fullName>
        <label>Deal RSF</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Deal_USF__c</fullName>
        <label>Deal USF</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Incremental_Capex_Required_USD__c</fullName>
        <label>Incremental Capex Required (USD)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Opportunity to which this case is directly related to if any.</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Cases</relationshipLabel>
        <relationshipName>Opportunity_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requested_Type__c</fullName>
        <label>Request Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pricing</fullName>
                </value>
                <value>
                    <fullName>Proposal</fullName>
                </value>
                <value>
                    <fullName>Proposal &amp; Pricing</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Contract_Value__c</fullName>
        <label>TCV Excluding Configuration Fee (USD)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case_Template__c.object
<CustomObject>
    <description>This is a Task Template which will be used to generate Standard Tasks automatically or by manual event.</description>
    <label>Case Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/UtilCase.cls
/**
* @author Gad Sharon    
* @date 19/11/18
* @description Util class for the Case object.
*/

public class UtilCase {

    Private Static Map<String, Object> stMapFields = new Map<String, Object>();

    public static List <Case> createCases (Integer numberOfRecords, Boolean doInsert)
    {
        List<Map<String,Object>> ListOfMapFields = new List<Map<String,Object>>();

        for (Integer i = 0; i < numberOfRecords; i++)
        {
            Map <String, Object> mapCaseFields = new Map <String, Object>(StMapFields);
            ListOfMapFields.add(mapCaseFields);
        }

        return UtilGeneral.createTestRecords(Case.sObjectType, ListOfMapFields, doInsert); 
    }

    public static Case createCaseRelatedToOpp (Id oppId, Id ownerId, Id recordTypeId, boolean doInsert)
    {
        stMapFields.put('Opportunity__c', oppId);
        stMapFields.put('OwnerId', ownerId);
        stMapFields.put('Requested_Type__c', 'Other');
        if(recordTypeId != null)
            stMapFields.put('RecordTypeId', recordTypeId);
        
        return createCases(1, doInsert)[0];
    }

    public static Case createCaseReadyToBeClosed (Id AccountId, Id OppId, Id ownerId, Id caseTemplateId, Id RecordTypeId, string caseTemplateName, string requestedType, boolean doInsert)
    {
        stMapFields.put('AccountId', AccountId);
        stMapFields.put('Opportunity__c', oppId);
        if(ownerId != null)
            stMapFields.put('OwnerId', ownerId);
        stMapFields.put('Case_Template__c', caseTemplateId);
        stMapFields.put('RecordTypeId', recordTypeId);
        stMapFields.put('Case_Template_Name__c', caseTemplateName);
        stMapFields.put('Requested_Type__c', requestedType);
        stMapFields.put('Status', 'New');
        stMapFields.put('Actual_Guardrail_Margin__c', 10);
        stMapFields.put('Cash_Margin__c', 10);
        stMapFields.put('Commitment_Term_from_Model__c', 10);
        stMapFields.put('Total_Contract_Value__c', 1000000);
        stMapFields.put('Deal_RSF__c', 10);
        stMapFields.put('Deal_USF__c', 10);
        stMapFields.put('Incremental_Capex_Required_USD__c', 1000);

        
        return createCases(1, doInsert)[0];
    }

}