objects/City__c.object
<CustomObject>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <referenceTo>State__c</referenceTo>
        <relationshipLabel>Cities</relationshipLabel>
        <relationshipName>Cities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Country__c.object
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Geography__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <description>administrative_area_level_3 or locality should be saved here in City field.</description>
        <label>City</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Country of the Google Location</description>
        <label>Country</label>
        <length>120</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <description>This will be the administrative_area_level_2 value which generally represents County or District</description>
        <label>County/District</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Formatted_Address__c</fullName>
        <description>Formatted Address of the Location which will also be stored in Name field.</description>
        <label>Formatted Address</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>JSON__c</fullName>
        <description>Entire JSON retrieved from Google Maps should be saved here, so we can pull any additional information easily in future from Google if required.</description>
        <label>JSON</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Location_Type__c</fullName>
        <description>Location Type provided in the Google Location should be stored here.</description>
        <label>Location Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>APPROXIMATE</fullName>
                </value>
                <value>
                    <fullName>GEOMETRIC_CENTER</fullName>
                </value>
                <value>
                    <fullName>RANGE_INTERPOLATED</fullName>
                </value>
                <value>
                    <fullName>ROOFTOP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Nearest_Building__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field contains the value of nearest building which is included in buildings object.</description>
        <inlineHelpText>The value in this field comes from buildings available for the user.</inlineHelpText>
        <label>Nearest Building</label>
        <referenceTo>Building__c</referenceTo>
        <relationshipLabel>Geographies</relationshipLabel>
        <relationshipName>Geographies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Place_ID__c</fullName>
        <description>Google ID of the location. Google API calls is Place ID</description>
        <externalId>true</externalId>
        <label>Place ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>Google Places returns administrative_area_level_1 which is generally a State or Province which will be stored here.</description>
        <label>State/Provience</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <description>This object will represent Google Maps Location so that we can reuse same location as and when required within multiple objects.</description>
    <label>Geography</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Geographies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/State__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>States</relationshipLabel>
        <relationshipName>States</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/UtilGeography.cls
/**
* @author Gad Sharon    
* @date 01/10/18
* @description Util class for the Geography__c object.
*/

public class UtilGeography {

    Private Static Map<String, Object> stMapFields = new Map<String, Object>();

    public static List <Geography__c> createGeography (Integer numberOfRecords, Boolean doInsert)
    {
        List<Map<String,Object>> ListOfMapFields = new List<Map<String,Object>>();

        for (Integer i = 0; i < numberOfRecords; i++)
        {
            Map <String, Object> mapGeoFields = new Map <String, Object>(stMapFields);
            mapGeoFields.put('Location_Type__c', 'APPROXIMATE');
            mapGeoFields.put('CurrencyIsoCode', 'USD');
            ListOfMapFields.add(mapGeoFields);
        }

        return UtilGeneral.createTestRecords(Geography__c.sObjectType, ListOfMapFields, doInsert); 
    }

    public static Geography__c createGeography(string name, string city, string country, string district, string state, string address, string json, string placeId, Id nearestBuilding, Object latitude, Object longitude, boolean doInsert)
    {
        stMapFields.put('Name', name);
        stMapFields.put('City__c', city);
        stMapFields.put('Country__c', country);
        stMapFields.put('District__c', district);
        stMapFields.put('State__c', state);
        stMapFields.put('Formatted_Address__c', address);
        stMapFields.put('JSON__c', json);
        stMapFields.put('Place_ID__c', placeId);
        stMapFields.put('Nearest_Building__c', nearestBuilding);
        stMapFields.put('Geocode__Latitude__s', latitude);
        stMapFields.put('Geocode__Longitude__s', longitude);
     	
        return createGeography(1, doInsert)[0];
    }

}