objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>This is the latest status coming from Space systems through Jitterbunny of the individual member. This tells us if the user is active or not.</description>
        <inlineHelpText>This is accurate status of a contact if it is an active member of our products or not.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>active</fullName>
                </value>
                <value>
                    <fullName>inactive</fullName>
                    <default>true</default>
                    <label>inactive</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Journey__c.object
<CustomObject>
    <fields>
        <fullName>NMD_Next_Contact_Date__c</fullName>
        <description>Date on which Journey Primary Member should be next contacted on.

This is key to manage the reminders for the Journey.</description>
        <label>Next Contact Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Primary Contact of the Journey</description>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Journeys</relationshipLabel>
        <relationshipName>Journeys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>If journey is for a Lead this will be the Primary Lead. Only Primary Contact or Primary Lead can be specified not both.</description>
        <label>Primary Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Journeys</relationshipLabel>
        <relationshipName>Journeys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>New Field to Capture Journey Status</description>
        <label>Journey Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Started</fullName>
                    <default>true</default>
                    <label>Started</label>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Trying to Reach</fullName>
                </value>
                <value>
                    <fullName>In Contact</fullName>
                </value>
                <value>
                    <fullName>Nurture</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Transferred</fullName>
                </value>
                <value>
                    <fullName>Unresponsive</fullName>
                </value>
                <value>
                    <fullName>No Contact</fullName>
                </value>
                <value>
                    <fullName>Unqualified</fullName>
                </value>
                <value>
                    <fullName>Auto-Complete/Expiration</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>We are going to use this object as Sales Journey of the user. Which begins when a person shows interest in one of our products or we decide to reach out to show our products.</description>
    <label>Journey</label>
    <nameField>
        <label>Customer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Journeys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/JourneyBulkEmailControllerTest.cls
@isTest
private class JourneyBulkEmailControllerTest {
	/*static testMethod void TestJourneyDetailsController() {
		JourneyBulkEmailController testObject = new JourneyBulkEmailController();
        //Test Account created for testContact.
        Account testAccount = new Account();
        	testAccount.Name = 'Test Account';
		insert testAccount;
		//Test Contact created for testJourney.
        Contact testContact = new Contact();
    	 	testContact.AccountId = testAccount.Id;
    	 	testContact.firstname = 'TestFirstName';
    	 	testContact.lastname = 'TestLastName';
         	testContact.Email = 'Test111@example.com';
         	testContact.Status__c = 'active';
        insert testContact;
	    System.assertNotEquals(testContact.Id, null);
		     
	    Journey__c testJourney = new Journey__c();
            testJourney.Name = 'testJourneyName';
            testJourney.CurrencyIsoCode = 'USD';
            testJourney.Primary_Contact__c = testContact.Id;
            testJourney.NMD_Next_Contact_Date__c = Date.today();
	    TestingUtility.insertWithAssert(testJourney);
        
        EmailTemplate objEmailTemplate = new EmailTemplate();
        EmailTemplate objEmailTemplateFetch = new EmailTemplate();
        //objEmailTemplate = [select Id, HtmlValue, Body, Subject,TemplateType From EmailTemplate Limit 1];
        objEmailTemplate = [select Id, HtmlValue, Body, Subject,TemplateType From EmailTemplate where TemplateType ='visualforce' AND isActive = true Limit 1];
        
        objEmailTemplateFetch = JourneyBulkEmailController.fetchEmailTemplate(objEmailTemplate.Id);
        String resultContactEmail = JourneyBulkEmailController.sendEmail(objEmailTemplate.Id,testJourney.Id);
        debug.Log('resultContactEmail>>' + resultContactEmail);
        system.assertEquals('Email Send Successfully.',resultContactEmail);
        
        EmailTemplate objEmailTemplate2 = new EmailTemplate(); 
            
        objEmailTemplate2 = [select Id, HtmlValue, Body, Subject,TemplateType From EmailTemplate where TemplateType !='visualforce' AND isActive = true Limit 1];
        List<Lead> listLeads = new List<Lead>();
        Lead leadNew = new Lead();
            leadNew.LastName = 'lastName';
            leadNew.Company = 'company';
            leadNew.Email = 'email@example.com';
            leadNew.Phone = '9874563210';
        insert leadNew;
        
        testJourney.Primary_Contact__c = null;
        testJourney.Primary_Lead__c = leadNew.Id;
        update testJourney;
        String resultLeadEmail = JourneyBulkEmailController.sendEmail(objEmailTemplate2.Id,testJourney.Id);
        system.assertEquals('Email Send Successfully.',resultLeadEmail); 
        debug.Log('resultLeadEmail>>' + resultLeadEmail);
    }*/
}