objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>This is the latest status coming from Space systems through Jitterbunny of the individual member. This tells us if the user is active or not.</description>
        <inlineHelpText>This is accurate status of a contact if it is an active member of our products or not.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>active</fullName>
                </value>
                <value>
                    <fullName>inactive</fullName>
                    <default>true</default>
                    <label>inactive</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Journey__c.object
<CustomObject>
    <fields>
        <fullName>NMD_Next_Contact_Date__c</fullName>
        <description>Date on which Journey Primary Member should be next contacted on.

This is key to manage the reminders for the Journey.</description>
        <label>Next Contact Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Primary Contact of the Journey</description>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Journeys</relationshipLabel>
        <relationshipName>Journeys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>If journey is for a Lead this will be the Primary Lead. Only Primary Contact or Primary Lead can be specified not both.</description>
        <label>Primary Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Journeys</relationshipLabel>
        <relationshipName>Journeys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>New Field to Capture Journey Status</description>
        <label>Journey Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Started</fullName>
                    <default>true</default>
                    <label>Started</label>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Trying to Reach</fullName>
                </value>
                <value>
                    <fullName>In Contact</fullName>
                </value>
                <value>
                    <fullName>Nurture</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Transferred</fullName>
                </value>
                <value>
                    <fullName>Unresponsive</fullName>
                </value>
                <value>
                    <fullName>No Contact</fullName>
                </value>
                <value>
                    <fullName>Unqualified</fullName>
                </value>
                <value>
                    <fullName>Auto-Complete/Expiration</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>We are going to use this object as Sales Journey of the user. Which begins when a person shows interest in one of our products or we decide to reach out to show our products.</description>
    <label>Journey</label>
    <nameField>
        <label>Customer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Journeys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Generate_Journey__c</fullName>
        <defaultValue>true</defaultValue>
        <description>If this check box is checked , create journey for converted lead</description>
        <label>Generate Journey</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/TestJourneyDetailsController.cls
/**
 * This class should contain all the test methods related JourneyDetailsController 
 * 
 * @author  Dipak Pawar
 * @date    25/06/2016
 */

@isTest
public class TestJourneyDetailsController {
    /**
	 * ST-300 : Test method for JourneyDetailController Constructor
	 * @author  Dipak Pawar
	 * @date    21/June/2016
	 */
    static{
        SalesConsoleSettings.createSettings();
    }
    static testMethod void TestJourneyDetailsController() {
        Account testAccount = new Account();
        testAccount.Name = 'Test Account';
		insert testAccount;
		//Test Contact created for testJourney.
        Contact testContact = new Contact();
    	 	testContact.AccountId = testAccount.Id;
    	 	testContact.firstname = 'TestFirstName';
    	 	testContact.lastname = 'TestLastName';
         	testContact.Email = 'Test111@example.com';
         	testContact.Status__c = 'active';
        insert testContact;
	    System.assertNotEquals(testContact.Id, null);
		
		//Test Journey for JourneyDetailController.        
	    Journey__c testJourney = new Journey__c();
	    testJourney.Name = 'testJourneyName';
	    testJourney.CurrencyIsoCode = 'USD';
	    testJourney.Primary_Contact__c = testContact.Id;
        testJourney.NMD_Next_Contact_Date__c = Date.today();
	    TestingUtility.insertWithAssert(testJourney);
        System.debug(LoggingLevel.ERROR,'testJourney1 ::'+testJourney);
	    ApexPages.StandardController testStandardController = new ApexPages.StandardController(testJourney);
	    JourneyDetailController testObject = new JourneyDetailController(testStandardController);
        
        //JourneyDetails Page with journeyId as a parameter.
        PageReference testPageReference = new PageReference('/apex/JourneyDetails');
        testPageReference.getParameters().put('journeyId', testJourney.Id);
        Test.setCurrentPageReference(testPageReference);
    }
    
    static testMethod void TestJourneyDetailsController_ForLead() {
        Lead leadNew = new Lead(LastName = 'Test Lead Last Name', Company = 'Test Company', Email = 'test@example.com', Phone = '1212121125', Generate_Journey__c = false);
        insert leadNew;
		//Test Journey for JourneyDetailController.        
	    Journey__c testJourney = new Journey__c();
	    testJourney.Name = 'testJourney';
	    testJourney.CurrencyIsoCode = 'USD';
	    testJourney.Primary_Lead__c = leadNew.Id;
        testJourney.NMD_Next_Contact_Date__c = Date.today();
	    TestingUtility.insertWithAssert(testJourney);
	    ApexPages.StandardController testStandardController = new ApexPages.StandardController(testJourney);
	    JourneyDetailController testObject = new JourneyDetailController(testStandardController);
        
        //JourneyDetails Page with journeyId as a parameter.
        PageReference testPageReference = new PageReference('/apex/JourneyDetails');
        testPageReference.getParameters().put('journeyId', testJourney.Id);
        Test.setCurrentPageReference(testPageReference);
    }
    static testMethod void getStringMapTest(){
        Map<string,List<EmailTemplate>> getStringMap =JourneyDetailController.getStringMap(); 
        System.assert(getStringMap!=null);
        //Debug.log('getStringMap==>'+getStringMap);
    }
}