objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Building__c</referenceTo>
        <relationshipLabel>Members</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Member__c</fullName>
        <formula>if( Billing_Account__r.Primary_Member__r.Id =  Id , "Yes","No")</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Primary Member</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This is the latest status coming from Space systems through Jitterbunny of the individual member. This tells us if the user is active or not.</description>
        <inlineHelpText>This is accurate status of a contact if it is an active member of our products or not.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>active</fullName>
                </value>
                <value>
                    <fullName>inactive</fullName>
                    <default>true</default>
                    <label>inactive</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Journey__c.object
<CustomObject>
    <fields>
        <fullName>Building_Interested_In__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Building Interested In</label>
        <referenceTo>Building__c</referenceTo>
        <relationshipLabel>Journeys</relationshipLabel>
        <relationshipName>Journeys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Count_of_Desk__c</fullName>
        <description>This is a temporary field to capture the Number of Desk for the Journey</description>
        <label>Number of Desks</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Primary Contact of the Journey</description>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Journeys</relationshipLabel>
        <relationshipName>Journeys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>New Field to Capture Journey Status</description>
        <label>Journey Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Started</fullName>
                    <default>true</default>
                    <label>Started</label>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Trying to Reach</fullName>
                </value>
                <value>
                    <fullName>In Contact</fullName>
                </value>
                <value>
                    <fullName>Nurture</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Transferred</fullName>
                </value>
                <value>
                    <fullName>Unresponsive</fullName>
                </value>
                <value>
                    <fullName>No Contact</fullName>
                </value>
                <value>
                    <fullName>Unqualified</fullName>
                </value>
                <value>
                    <fullName>Auto-Complete/Expiration</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>We are going to use this object as Sales Journey of the user. Which begins when a person shows interest in one of our products or we decide to reach out to show our products.</description>
    <label>Journey</label>
    <nameField>
        <label>Customer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Journeys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Count_of_Desk__c</fullName>
        <description>This is a temporary field to capture the Number of Desk for the Opportunity whose source of truth will the Journey Record associated with the tour with which the Tour is associated</description>
        <label>Number of Desks (Count)</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Journey__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Journey</label>
        <referenceTo>Journey__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Primary Contact)</relationshipLabel>
        <relationshipName>Opportunities4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Member__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>This is the Main Contact of the Opportunity</inlineHelpText>
        <label>Main Contact</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tour_Outcome__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tour Outcome</label>
        <referenceTo>Tour_Outcome__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Tour_Outcome__c.object
<CustomObject>
    <fields>
        <fullName>Journey__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Journey</label>
        <referenceTo>Journey__c</referenceTo>
        <relationshipLabel>Tours</relationshipLabel>
        <relationshipName>Tours</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Building__c</referenceTo>
        <relationshipName>Tour_Outcome</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Tours</relationshipLabel>
        <relationshipName>Tour_Outcome</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Member</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Tours (Primary Member)</relationshipLabel>
        <relationshipName>Tours3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Overall Status from SpaceStation</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>No Show</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Rescheduled</fullName>
                </value>
                <value>
                    <fullName>Not Rescheduled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tour_Outcome__c</fullName>
        <inlineHelpText>Outcome Status from SpaceStation</inlineHelpText>
        <label>Tour Outcome</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Ready to sign now</fullName>
                </value>
                <value>
                    <fullName>Interested</fullName>
                    <label>Tour Interested</label>
                </value>
                <value>
                    <fullName>Did not show up</fullName>
                    <label>No Show</label>
                </value>
                <value>
                    <fullName>Not Interested</fullName>
                    <label>Does not want Membership</label>
                </value>
                <value>
                    <fullName>Tour Reschedule</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Tour</label>
    <nameField>
        <displayFormat>TRO-{0000}</displayFormat>
        <label>Tour Outcome ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tours</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/QueueUpdateCountOfDeskOnOpportunity.cls
/**
 * Created By : Mayuresh Ghodke
 * Created Date : 3 June 2017
 * Comment : Queueable class for ST-910 functionality. Which will call from Tour Trigger.
 			Change normal method to Queueable method as after updating Opportunities Count_of_Desk__c there is no any other operation to work.
 */
public class QueueUpdateCountOfDeskOnOpportunity implements Queueable {
	List<Tour_Outcome__c> triggerNew = new List<Tour_Outcome__c>();
	
	public QueueUpdateCountOfDeskOnOpportunity(List<Tour_Outcome__c> triggerNew){
		//this.triggerNew = triggerNew;
	}
	
	public void execute(QueueableContext context) {
		/*set<Id> setPrimaryContact = new set<Id>(); //Contains Primary contact of Tour triggerNew
        set<Id> setLastModifiedJourney = new set<Id>(); //Contains Last Modified Journey
        Map<Id, Tour_Outcome__c> mapTourWithJourneyId = new Map<Id, Tour_Outcome__c>();
        Map<Id, Opportunity> mapOpportunityToUpdate = new Map<Id, Opportunity>();
        Map<Id,Journey__c> mapJourneyToUpdate = new Map<Id,Journey__c>();
        Set<Id> setOpportunityIds = new Set<Id>();
        for(Tour_Outcome__c tourRec : triggerNew){
            if(tourRec.Primary_Member__c != null)    
                setPrimaryContact.add(tourRec.Primary_Member__c);
        }
        
        //List of Journey order by LastModifiedDate desc
        List<Journey__c> lstJourney = new List<Journey__c>();
       
        if(setPrimaryContact.size() > 0)
        	lstJourney = new List<Journey__c>([Select Id, Name, LastModifiedDate, Status__c, Primary_Contact__c, Building_Interested_In__c, Count_of_Desk__c From Journey__C Where Primary_Contact__c IN : setPrimaryContact order by LastModifiedDate desc]); //AND LastModifiedDate > :Datetime.now().addMinutes(-15)
        Debug.log('lstJourney :: '+lstJourney);
        
        Map<Id, Journey__c> mapOfJourneys = new Map<Id, Journey__c>(lstJourney);
        
        for(Journey__c journeyRec : lstJourney){
            Debug.log('journeyRec :: '+journeyRec);
            if(!setLastModifiedJourney.contains(journeyRec.Primary_Contact__c)){
                setLastModifiedJourney.add(journeyRec.Primary_Contact__c);
                mapJourneyToUpdate.put(journeyRec.Primary_Contact__c,journeyRec);
            } 
        }
        Debug.log('Test : setLastModifiedJourney ::: ' + setLastModifiedJourney);
        Debug.log('Test : mapJourneyToUpdate ::: ' + mapJourneyToUpdate);
        for(Tour_Outcome__c tourRec : triggerNew){
            Debug.log('Test : tourRec ::: ' + tourRec);
            if(tourRec.Opportunity__c != null)
                setOpportunityIds.add(tourRec.Opportunity__c);
            if(tourRec.Journey__c == null)
            {
                Journey__c journeyRec = mapJourneyToUpdate.get(tourRec.Primary_Member__c);
                Debug.log('Test : journeyRec ::: ' + journeyRec);
                if(journeyRec != null){
                    if((journeyRec.Primary_Contact__c == tourRec.Primary_Member__c) && 
                       (journeyRec.Building_Interested_In__c == tourRec.Location__c) 
                      ){
                          tourRec.Journey__c = journeyRec.Id;
                          mapTourWithJourneyId.put(journeyRec.Id, tourRec);
                      }
                    if((journeyRec.Primary_Contact__c == tourRec.Primary_Member__c) && 
                       (journeyRec.Building_Interested_In__c == null)                   
                      ){
                          tourRec.Journey__c = journeyRec.Id;
                          mapTourWithJourneyId.put(journeyRec.Id, tourRec);
                    }
                }
            }
        }
       //Map<Id, Opportunity> mapOpportunities = new Map<Id, Opportunity>([SELECT Id, Count_of_Desk__c FROM Opportunity Where Id in : setOpportunityIds]);
       Map<Id, Opportunity> mapOpportunities = new Map<Id, Opportunity>();
       if(setOpportunityIds.size() > 0){
           for(Opportunity oppRec : [SELECT Id, Count_of_Desk__c FROM Opportunity Where Id in : setOpportunityIds]){
               mapOpportunities.put(oppRec.Id, oppRec);    
           }
       } 
       Debug.log('Test : mapTourWithJourneyId ::: ' + mapTourWithJourneyId);
        //Changes to populate Count_of_Desks on Tour's Opportunity
        for(Journey__c journey : mapOfJourneys.values()){
            if(mapTourWithJourneyId.get(journey.Id) != null){
                Id oppId = mapTourWithJourneyId.get(journey.Id).Opportunity__c;
                if(oppId != null){
	                Opportunity getOpp = mapOpportunities.get(oppId);
	                Debug.log('Test : getOpp ::: ' + getOpp);
	                if(getOpp.Count_of_Desk__c == null && mapTourWithJourneyId.get(journey.Id) != null){
	                    Opportunity opp = new Opportunity();
	                    opp.Id = oppId;
	                    opp.Count_of_Desk__c = journey.Count_of_Desk__c;
	                    mapOpportunityToUpdate.put(opp.Id, opp);
	                }
                }
            }
        }
        Debug.log('Test : mapOpportunityToUpdate ::: ' + mapOpportunityToUpdate);
        
        if(mapOpportunityToUpdate.size() > 0)
        	update mapOpportunityToUpdate.values();*/
	}
	
    
}