objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Actual_Start_Date__c</fullName>
        <formula>Account.Start_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Actual Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Primary_Member__c</fullName>
        <formula>if( Billing_Account__r.Primary_Member__r.Id =  Id , "Yes","No")</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Primary Member</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Default</fullName>
        <active>true</active>
        <label>Default</label>
    </recordTypes>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Actual_Start_Date__c</fullName>
        <inlineHelpText>This is the Expected Start Date until Closed Won</inlineHelpText>
        <label>Actual Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Locations_Interested__c</fullName>
        <label>Locations Interested</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AMS-Labs</fullName>
                </value>
                <value>
                    <fullName>AMS-Metropool</fullName>
                </value>
                <value>
                    <fullName>AMS-Strawinskylaan</fullName>
                </value>
                <value>
                    <fullName>AMS-Weteringschans</fullName>
                </value>
                <value>
                    <fullName>ARC-Andres Arguibel 2860</fullName>
                </value>
                <value>
                    <fullName>ARC-Avenida Corrientes 800</fullName>
                </value>
                <value>
                    <fullName>ARC-Ing. Enrique Butty 275</fullName>
                </value>
                <value>
                    <fullName>ARC-Libertador 1000</fullName>
                </value>
                <value>
                    <fullName>ARC- Torre Bellini</fullName>
                </value>
                <value>
                    <fullName>ARG- Torre Bellini</fullName>
                </value>
                <value>
                    <fullName>ARN-Urban Escape</fullName>
                </value>
                <value>
                    <fullName>ATL-1372 Peachtree</fullName>
                </value>
                <value>
                    <fullName>ATL-3280 Peachtree Road NE</fullName>
                </value>
                <value>
                    <fullName>ATL-Colony Square</fullName>
                </value>
                <value>
                    <fullName>ATL-Tower Place</fullName>
                </value>
                <value>
                    <fullName>AUS-Congress</fullName>
                </value>
                <value>
                    <fullName>AUS-Domain</fullName>
                </value>
                <value>
                    <fullName>AUS-Labs</fullName>
                </value>
                <value>
                    <fullName>AUS-University Park</fullName>
                </value>
                <value>
                    <fullName>AUS-Westview</fullName>
                </value>
                <value>
                    <fullName>AUS-WeWork 801 Barton Springs</fullName>
                </value>
                <value>
                    <fullName>BCN-Diagonal 444</fullName>
                </value>
                <value>
                    <fullName>BHZ-Boulevard Shopping</fullName>
                </value>
                <value>
                    <fullName>BKK-Asia Centre</fullName>
                </value>
                <value>
                    <fullName>BKN-109 S 5th St</fullName>
                </value>
                <value>
                    <fullName>BKN-Brooklyn Heights</fullName>
                </value>
                <value>
                    <fullName>BKN-Dumbo Heights (Prospect)</fullName>
                </value>
                <value>
                    <fullName>BKN-Dumbo Heights (Sands)</fullName>
                </value>
                <value>
                    <fullName>BKN-Montague St.</fullName>
                </value>
                <value>
                    <fullName>BKN-Williamsburg</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_Member__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>This is the Main Contact of the Opportunity</inlineHelpText>
        <label>Main Contact</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Waitlist_Notes__c</fullName>
        <label>Waitlist Notes</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/WaitlistHandler.cls
public with sharing class WaitlistHandler {
	public static String process_waitlist(WWTypes.Waitlist pWaitlist) {
		//locate primary member's email
		Contact[] Cs = [	SELECT id, email, AccountId 
											FROM Contact 
											WHERE email = :pWaitlist.email 
											LIMIT 1
										];
		//check member exists
		if (Cs.size() == 0 ) throw new WaitlistHandlerException('Primary members email not found within system.');

		//assign contact
		Contact c = Cs[0];

		//search for duplicate opportunity
		Opportunity[] Os = [	SELECT id, Locations_Interested__c, waitlist_notes__c 
													FROM Opportunity 
													WHERE 
														Primary_Member__c = :c.id AND 
														stagename = 'Negotiating'
													ORDER BY createddate DESC
													LIMIT 1
												];
		
		//container
		Opportunity o;

		//if previous waitlisted opportunity exists, update it
		if (Os.size() == 1) {
			o = Os[0];

			//merge building interests
			o.Locations_Interested__c = WaitlistHandler.merge_building_interests(
				o.Locations_Interested__c,
				BuildingHandler.getMultipicklistValuesFromUUID(pWaitlist.buildings_interested_uuids)
			);
			
			//update notes
			o.waitlist_notes__c = WaitlistHandler.add_notes(o.waitlist_notes__c, pWaitlist.notes);

			//dml
			update o;
		}

		//if no previous waitlisted opportunity exists, create a new one
		if (Os.size() == 0) {
			o = new Opportunity(
				name  									= 'Inbound waitlist opportunity',
				stagename 							= 'Negotiating',
				closeDate             	= system.today(),
				Primary_member__c 			= c.id,
				AccountId 							= c.AccountId,
				actual_start_date__c 		= pWaitlist.actual_start_date,
				waitlist_notes__c 			= WaitlistHandler.add_notes(null, pWaitlist.notes),
				locations_interested__c	= BuildingHandler.getMultipicklistValuesFromUUID(pWaitlist.buildings_interested_uuids)
			);
			insert o;
		}

		return String.valueOf(o.id);
	}

	private static String add_notes(String pOriginal, String pNew) {
		String result;
		try {
			//code here
			String new_entry = String.format(
													'[{0}] {1} \n', 
													new String[]{
														Datetime.now().format('yyyy-MM-dd HH:mm:ss'),
														pNew
													}
												 );

			result = new_entry + (pOriginal != null? pOriginal : '');
		}
		catch(Exception pEx) {
			result = pOriginal; //default value
		}
		
		return result;
	}

	private static String merge_building_interests(String pOriginal, String pNew) {
		String result;
		
		if (pOriginal == null) result = pNew;
		if (pNew == null) result = pOriginal;
		if (pNew == null & pOriginal == null) result = null;

		if (pNew != null && pOriginal != null) {
			Set<String> Ss = new Set<String>();

			//join splitted
			Ss.addAll(pOriginal.split(';', -1));
			Ss.addAll(pNew.split(';', -1));

			String[] Bs = new String[]{};
			Bs.addAll(Ss);

			//
			result = String.join(Bs, ';');
		}

		return result;
	}

	public class WaitlistHandlerException extends Exception{}
}