objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Referrer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referrer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Referral__c.object
<CustomObject>
    <fields>
        <fullName>Expires_On__c</fullName>
        <description>Date on which this Reference Expires, every time reference needs to be extended this date should be updated to reflect the extension. Any Opportunity created while this reference is not expired, for the primary contact matching the email provided in this reference will be have Referrer set with Referrer in this record.</description>
        <label>Expires On</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <description>To check if the reference is a active reference or not ?</description>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Referral_Email__c</fullName>
        <description>Captures the email of the new lead coming to the system with reference of a referrer.</description>
        <label>Referral Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Referrer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contact who Referred the Person identified by given email address.</description>
        <label>Referrer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Referrals</relationshipLabel>
        <relationshipName>Referrals</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>This object will represent references made by either Member/Broker/Employee to certain person identified by email. 

This is generally valid for 60 days and may be extended by another 60 days based on certain events like if referred person books a tour, completes a tour or paperwork is sent to the person referred.</description>
    <label>Referral</label>
    <nameField>
        <label>Referral Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referrals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Setting__c.object
<CustomObject>
    <fields>
        <fullName>Data__c</fullName>
        <description>This should contain JSON formatted data for each setting record. The JSON object will vary from setting to setting.</description>
        <label>Data</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <description>We are creating object for Settings instead of using Custom Object because we need to store larger size of data which Custom Setting does not support. e.g. Mapping of Fields from Contact to Lead etc. which may go beyond 255 characters. 

It will not use caching but give more flexibility for coding.</description>
    <label>Sales Console Setting</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Console Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ReferenceHandlerTest.cls
/*
 * @ Created By : Anant Kumar
 * @ Created Date : 20 June 2016
 */
 
@isTest
private class ReferenceHandlerTest {
	static{
        SalesConsoleSettings.createSettings();
		/*ReferenceSettings settingsMy = new ReferenceSettings();
        settingsMy.expireafter = 10;

        Setting__c setting = new Setting__c( Name = 'ReferenceSettings', Data__c = JSON.serialize(settingsMy));
        insert setting;
        
        List<Setting__c> lstSettings = new List<Setting__c>();
        lstSettings.add(new Setting__c(Name = 'AccountCleansingSetting',Data__c = '{"starts_with":["The","An","A"],"ends_with":["pvt","ltd"],"specialCharacters":"@#^&*!():?/><"}'));
        insert lstSettings;*/
	}

    public static testMethod void checkSettings(){
	/*ReferenceSettings settingsNew;
		settingsNew = (ReferenceSettings) Settings.get('ReferenceSettings',ReferenceSettings.class);
        System.assert(settingsNew.expireafter == 10);*/
    }

    static testMethod void testReferenceHandler()
    {
        Account accRec = TestingUtility.createAccount('strAccountName', true);
        Contact referrer1 = new Contact();
        referrer1.LastName = 'referrer1';
        referrer1.Email = 'referrer1@example.com';
        TestingUtility.insertWithAssert(referrer1);
        
        Contact referrer2 = new Contact();
        referrer2.LastName = 'referrer1';
        referrer2.Email = 'referrer2@example.com';
        TestingUtility.insertWithAssert(referrer2);
        
        Referral__c reference1 = new Referral__c();
        reference1.Referral_Email__c= 'reference1@example.com';
        reference1.IsActive__c = true;
        reference1.Referrer__c = referrer1.Id;
        reference1.Expires_On__c = Date.today().addDays(10);
        TestingUtility.insertWithAssert(reference1);
        
        Referral__c reference2 = new Referral__c();
        reference2.Referral_Email__c= 'reference2@example.com';
        reference2.IsActive__c = false;
        reference2.Referrer__c = referrer1.Id;
        reference2.Expires_On__c = Date.today().addDays(10);
        TestingUtility.insertWithAssert(reference2);
        
        Set<String> setEmails = new Set<String>();
        setEmails.add(reference1.Referral_Email__c);
        
        ReferenceHandler.ExtendReference(setEmails);

        Referral__c existingReference = [SELECT Id, Name, Expires_On__c FROM Referral__c WHERE Id=:reference1.Id];
        Debug.Log('Test : reference1 ::: ' + existingReference);
        Time tNow = Time.newInstance(0, 0, 0, 0);
        DateTime todayTime = DateTime.newInstance(Date.today(), tNow);
        //System.assertEquals(todayTime.addDays(60), existingReference.Expires_On__c);

        ReferenceHandler.ExtendReference(reference1.Id,Date.today(), Date.today());

        Map <string,Id> mapReferrer = ReferenceHandler.getActiveReference(setEmails);
        System.assertEquals(referrer1.Id, mapReferrer.get(reference1.Referral_Email__c));
        
        System.assertEquals(referrer1.Id, ReferenceHandler.getActiveReference(reference1.Referral_Email__c));
        System.assertEquals(null, ReferenceHandler.getActiveReference(reference2.Referral_Email__c));
    }
    
    static testMethod void PreventDuplicateActiveReference()
    {
        Account accRec = TestingUtility.createAccount('strAccountName', true);
        Contact referrer1 = new Contact();
        referrer1.LastName = 'referrer1';
        referrer1.Email = 'referrer1@example.com';
        TestingUtility.insertWithAssert(referrer1);
        
        Contact referrer2 = new Contact();
        referrer2.LastName = 'referrer1';
        referrer2.Email = 'referrer2@example.com';
        TestingUtility.insertWithAssert(referrer2);
        
        Referral__c reference1 = new Referral__c();
        reference1.Referral_Email__c= 'referenced1@example.com';
        reference1.IsActive__c = true;
        reference1.Referrer__c = referrer1.Id;
        reference1.Expires_On__c = Date.today().addDays(60);
        TestingUtility.insertWithAssert(reference1);
       
       try{ 
        reference1 = new Referral__c();
        reference1.Referral_Email__c= 'referenced123@example.com';
        reference1.IsActive__c = true;
        reference1.Referrer__c = referrer1.Id;
        reference1.Expires_On__c = Date.today().addDays(60);
        TestingUtility.insertWithAssert(reference1);
       }
       catch(Exception ex){
       	 Debug.log('Exception::'+ex);
       }
    }

	public class ReferenceSettings {
		public Integer expireafter{get;Set;}
	}
}