objects/Deal__c.object
<CustomObject>
    <fields>
        <fullName>Adam_Actions__c</fullName>
        <label>Adam Actions</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Approver_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver 1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Deals_1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <label>Group</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Corporate/Finance</fullName>
                </value>
                <value>
                    <fullName>Real Estate</fullName>
                </value>
                <value>
                    <fullName>Development</fullName>
                </value>
                <value>
                    <fullName>Services/Partnership</fullName>
                </value>
                <value>
                    <fullName>Physical Product</fullName>
                </value>
                <value>
                    <fullName>Digital Product</fullName>
                </value>
                <value>
                    <fullName>Operations</fullName>
                </value>
                <value>
                    <fullName>Brand Marketing</fullName>
                </value>
                <value>
                    <fullName>Community/Expansion</fullName>
                </value>
                <value>
                    <fullName>Enterprise Solution</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <description>User can put notes in this field.</description>
        <label>Notes</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Phase__c</fullName>
        <label>Gate</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>B</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
                <value>
                    <fullName>D</fullName>
                </value>
                <value>
                    <fullName>E</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>I/U</fullName>
                    <color>#FF0000</color>
                    <label>I/U</label>
                </value>
                <value>
                    <fullName>I/NU</fullName>
                    <color>#FF6600</color>
                    <label>I/NU</label>
                </value>
                <value>
                    <fullName>NI/U</fullName>
                    <color>#FFFF66</color>
                    <label>NI/U</label>
                </value>
                <value>
                    <fullName>NI/NU</fullName>
                    <color>#3366FF</color>
                    <label>NI/NU</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Pencils Down</fullName>
                </value>
                <value>
                    <fullName>Dead</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Timing__c</fullName>
        <label>Next Deadline</label>
        <type>Date</type>
    </fields>
    <label>Deal</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Triggers__c.object
<CustomObject>
    <fields>
        <fullName>Deals_Set_Closed_Deal_Status_To_Blank__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Deals_Set_Closed_Deal_Status_To_Blank</label>
        <type>Checkbox</type>
    </fields>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>We are going to use this object to activate or deactivate various triggers we will be writing so we can easily deactivate triggers in case of errors or mass upload if required.</description>
    <label>Triggers</label>
</CustomObject>

classes/DealsTriggerHandlerTest.cls
/************************************************************************************************************************************
Author : Amol Darekar  
Description : This class should contain all test methods related to DealsTriggerHandler class.

History:
----------------------------------------------------------------------------------------------------------------------------------
VERSION					DATE					AUTHOR							DETAIL
1						13 May 2016		   	Amol Darekar             		Initial Developement
**************************************************************************************************************************************/
@isTest
public class DealsTriggerHandlerTest {
    
/************************************************************************************************************************************
	Author 				: Amol Darekar
	Description 		: This test method is used to verify DealsHandler.
	Created Date		: 13 May 2016	
**************************************************************************************************************************************/ 
    static testMethod void testDealsHandler(){  	    
        Triggers__c triggers = new Triggers__c(Deals_Set_Closed_Deal_Status_To_Blank__c= true);
        insert triggers;
        
        Profile weworkSystemAdmin = [SELECT Id FROM Profile WHERE Name='WeWork Standard User'];
        Map<String,Object> userRecordMap = new Map<String,Object>();
        userRecordMap.put('LastName','Last Name 1');
        userRecordMap.put('Username','testweworkuser1@test.com');
        userRecordMap.put('Email','testuser1@test.com');
        User user1 = TestingUtility.insertUserWithAssert(weworkSystemAdmin.Id, userRecordMap, true);
        
        Deal__c deal1 = new Deal__c();
        deal1.Name = 'Deal 1';
        deal1.Priority__c = 'Important / Urgent';
        deal1.Status__c = 'Pencils Down';
        deal1.Phase__c = 'E';
        deal1.Group__c = 'Corporate';
        deal1.Notes__c = 'Hony Investors';
        deal1.Team__c = 'Legal: Rachell';
        deal1.Timing__c = System.today();
        deal1.Adam_Actions__c = 'Adam to discuss status of Jin Jiang and China Oceanwide with John Zhao';
        deal1.Approver_1__c = user1.Id;
        TestingUtility.insertWithAssert(deal1);
        
        deal1.Status__c = 'Closed';
        TestingUtility.updateWithAssert(deal1);
        
        deal1.Status__c = 'Pencils Down';
        TestingUtility.updateWithAssert(deal1);
    }
}