objects/Journey__c.object
<CustomObject>
    <fields>
        <fullName>Primary_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>If journey is for a Lead this will be the Primary Lead. Only Primary Contact or Primary Lead can be specified not both.</description>
        <label>Primary Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Journeys</relationshipLabel>
        <relationshipName>Journeys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unomy_Updated_DateTime__c</fullName>
        <formula>IF( Primary_Lead__c != NULL , Primary_Lead__r.Unomy_Updated_DateTime__c, IF( Primary_Contact__c != NULL, Primary_Contact__r.Unomy_Updated_DateTime__c ,NULL))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unomy Updated DateTime</label>
        <type>DateTime</type>
    </fields>
    <description>We are going to use this object as Sales Journey of the user. Which begins when a person shows interest in one of our products or we decide to reach out to show our products.</description>
    <label>Journey</label>
    <nameField>
        <label>Customer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Journeys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Campaign_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign Id</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead_Assignment_Stage__c</fullName>
        <inlineHelpText>This field will keep track of Lead/Journey Hold Back</inlineHelpText>
        <label>Lead Assignment Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>6</fullName>
                    <label>Hold queue</label>
                </value>
                <value>
                    <fullName>11</fullName>
                    <label>Assignments Run</label>
                </value>
                <value>
                    <fullName>1000</fullName>
                    <label>Bypass Hold Back</label>
                </value>
                <value>
                    <fullName>Lead Converted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unomy_Updated_DateTime__c</fullName>
        <description>The date/time a record was updated from Unomy</description>
        <label>Unomy Updated DateTime</label>
        <type>DateTime</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/MetadataSetting__mdt.object
<CustomObject>
    <fields>
        <fullName>Data__c</fullName>
        <description>This is used to store new Journey Creation criteria</description>
        <inlineHelpText>Journey Creation criteria</inlineHelpText>
        <label>Data</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <description>This is used to filter for Journey creation criteria.</description>
    <label>MetadataSetting</label>
    <pluralLabel>MetadataSettings</pluralLabel>
</CustomObject>

classes/LeadProcessingTest.cls
/*****************************************************************************************************************************
  Yet to do
  1. Modularize the code into multiple method calls.
  2. Put comments for each method call to establish references.
  3. Get it reviewed from the peer team.
******************************************************************************************************************************
    Author      :  Krishana Tupe  
    Description :  This class contains the business logic related to Lead Routing and Conversion
    History     :  --
    
    ----------------------------------------------------------------------------------------------------------------------------------
    VERSION                 DATE            ISSUE       AUTHOR                          DETAIL
    1                       29 Nov 2018      -     		Krishana Tupe                   Initial Developement    
******************************************************************************************************************************/
@isTest
public class LeadProcessingTest {
    public static string strHoldBackQueueId;
    static {
        if(String.isBlank(strHoldBackQueueId)){
            MetadataSetting__mdt objJourneyCreationMDT = Settings.getMetadataSettingByDevName('Hold_Back_Queue');  
            strHoldBackQueueId = String.isNotBlank(objJourneyCreationMDT.Data__c) ? objJourneyCreationMDT.Data__c : null;      
        }        
    }
   
  /************************************************************************************************************************************
        Author              :   Krishana Tupe
        Description         :   This setup method is used to create a test data for LeadProcessingTest
      	Created Date  		:   27 Nov 2018        
 *************************************************************************************************************************************/
    @TestSetup
    public static void testSetup(){
        SalesConsoleSettings.createSettings(); 
    }
    
    
/************************************************************************************************************************************
        Author              :   Krishana Tupe
        Description         :   This method is used to verify the Lead/Journey Hold Back Flow from Process Builder 
      	Created Date  		:   27 Nov 2018        
 *************************************************************************************************************************************/
    @isTest
    public static void verifyLeadInsertionHoldBack(){
        List<Lead> lstLeads = new List<Lead>(); 
        LeadRoutingHelperTest.getLeadRecords(lstLeads, 1, 6, null, null);
        RESTInboundLeadAPIHelper.isLeadFromWeb = true;       
        TestingUtility.insertListWithAssert(lstLeads);        
        List<Lead> lstLeadsInserted = [SELECT Id, Name, Email, Campaign_Id__c, OwnerId, Lead_Assignment_Stage__c, (SELECT Id, OwnerId FROM Journeys__r) FROM Lead WHERE Id IN : lstLeads AND IsConverted = false];
        System.assertEquals(6, lstLeadsInserted.size()); 
        LeadRoutingHelperTest.verifyAssertions(lstLeadsInserted, 1, Id.valueOf(strHoldBackQueueId), '6');
        for(lead objLead : lstLeadsInserted){
            objLead.Unomy_Updated_DateTime__c = System.now(); 
        }
        RESTInboundLeadAPIHelper.isLeadFromWeb = false; 
        Test.startTest();
        LeadProcessing.routeLeadsToHoldBack(lstLeadsInserted);
        Test.stopTest();
        
        lstLeadsInserted = [SELECT Id, Name, OwnerId, Lead_Assignment_Stage__c, (SELECT Id, OwnerId FROM Journeys__r) FROM Lead WHERE Id IN : lstLeads AND IsConverted = false];
        System.assertEquals(6, lstLeadsInserted.size()); 
        for(Lead objLead : lstLeadsInserted){
            System.assertEquals('11',objLead.Lead_Assignment_Stage__c); 
            System.assertNotEquals(Id.valueOf(strHoldBackQueueId), objLead.OwnerId); 
            System.assert(objLead.Journeys__r.size() == 1);
            System.assertEquals(objLead.OwnerId, objLead.Journeys__r[0].OwnerId);
        }
    }
    
}