objects/Journey__c.object
<CustomObject>
    <fields>
        <fullName>Outreach_Result__c</fullName>
        <label>Outreach Result</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Left Voicemail</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Outreach_Stage__c</fullName>
        <description>Captures the value of the follow-up from the NMD team</description>
        <inlineHelpText>Captures the value of the follow-up from the NMD team</inlineHelpText>
        <label>Outreach Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Call 1</fullName>
                </value>
                <value>
                    <fullName>Call 2</fullName>
                </value>
                <value>
                    <fullName>Manual Outreach</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Primary Contact of the Journey</description>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Journeys</relationshipLabel>
        <relationshipName>Journeys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>If journey is for a Lead this will be the Primary Lead. Only Primary Contact or Primary Lead can be specified not both.</description>
        <label>Primary Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Journeys</relationshipLabel>
        <relationshipName>Journeys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>New Field to Capture Journey Status</description>
        <label>Journey Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Started</fullName>
                    <default>true</default>
                    <label>Started</label>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Trying to Reach</fullName>
                </value>
                <value>
                    <fullName>In Contact</fullName>
                </value>
                <value>
                    <fullName>Nurture</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Transferred</fullName>
                </value>
                <value>
                    <fullName>Unresponsive</fullName>
                </value>
                <value>
                    <fullName>No Contact</fullName>
                </value>
                <value>
                    <fullName>Unqualified</fullName>
                </value>
                <value>
                    <fullName>Auto-Complete/Expiration</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>We are going to use this object as Sales Journey of the user. Which begins when a person shows interest in one of our products or we decide to reach out to show our products.</description>
    <label>Journey</label>
    <nameField>
        <label>Customer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Journeys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/LogACallController.cls
/************************************************************************************************************************************
    Author      :   Dipak Pawar    
    Description :   This class contain methods that are used in LogACallController
    
    History     :
    ----------------------------------------------------------------------------------------------------------------------------------
    VERSION     DATE                AUTHOR                  DETAIL
    1          31-10-2018         	Dipak Pawar        		Initial Developement
**************************************************************************************************************************************/
global class LogACallController {
    public static Boolean isInvoker = false;
    public static Savepoint sp {get; set;}
    
    static {
        isInvoker = ApexDebugLog.registerRootInvoker(ApexDebugLog.InvokerType.AURA, 'LogACallController' + 'getsObjectPrefix', ApexDebugLog.InvokerType.AURA);        
    }
    
    /****************************************************************************************************************************
        Author              : Dipak Pawar
        Description         : This Method returns the journeyData to Log A Call component for the provided journeyId
        Created Date        : 31-10-2018
       	Issue               : ST-2868
   *****************************************************************************************************************************/
	@AuraEnabled
    public static DatabaseResult getJourneyData(Id journeyId, String querylabel){
        try{
            Map<String, Object> objDatabaseResult = new Map<String, Object>();
            switch on querylabel{
                when 'getJourneyData' {
                    List<Journey__c> lstJourneys = new List<Journey__c>([SELECT Id, Name, Outreach_Stage__c, Primary_Lead__c, Primary_Contact__c, Status__c FROM Journey__c WHERE Id =: journeyId]);
                    objDatabaseResult.put('journeyRecord', lstJourneys[0]);
                }           	
            }
            return new DatabaseResult(objDatabaseResult);
        } catch(Exception pEx){
            ApexDebugLog.logException(pEx, journeyId + ' ' + querylabel, 'LogACallController', 'getJourneyData');            
            return (new DatabaseResult(pEx));
        }
    }
    
    /****************************************************************************************************************************
        Author              : Dipak Pawar
        Description         : This Method saves the call log for given journey.
        Created Date        : 31-10-2018
       	Issue               : ST-2868
   *****************************************************************************************************************************/
    @AuraEnabled
    public static DatabaseResult saveCallLogs(Journey__c objJourney, Boolean leftAVoicemail, String callComments){
        try{            
            List<Task> lstTasksToCreate = new List<Task>();
            
            if(leftAVoicemail){
                objJourney.Outreach_Result__c = 'Left Voicemail';
            }
			
            Task objTask = new Task(
                Type = 'Call',
                TaskSubType = 'Call',
                Status = 'Completed',
                Subject = 'Log A Call : ' + objJourney.Outreach_Stage__c,
                CallDisposition = callComments,
                WhatId = objJourney.Id
            );
            lstTasksToCreate.add(objTask);
            
            update objJourney;
            if(lstTasksToCreate.size() > 0){
                insert lstTasksToCreate;
            }
            return new DatabaseResult(true);
        } catch(Exception pEx){
            ApexDebugLog.logException(pEx, JSON.serialize(objJourney) + ' ' + callComments, 'LogACallController', 'saveCallLogs');            
            return (new DatabaseResult(pEx));
        }
    }
    
    public class LogACallControllerException extends Exception{}
}