objects/Journey__c.object
<CustomObject>
    <fields>
        <fullName>Outreach_Stage__c</fullName>
        <description>Captures the value of the follow-up from the NMD team</description>
        <inlineHelpText>Captures the value of the follow-up from the NMD team</inlineHelpText>
        <label>Outreach Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Call 1</fullName>
                </value>
                <value>
                    <fullName>Call 2</fullName>
                </value>
                <value>
                    <fullName>Manual Outreach</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>New Field to Capture Journey Status</description>
        <label>Journey Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Started</fullName>
                    <default>true</default>
                    <label>Started</label>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Trying to Reach</fullName>
                </value>
                <value>
                    <fullName>In Contact</fullName>
                </value>
                <value>
                    <fullName>Nurture</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Transferred</fullName>
                </value>
                <value>
                    <fullName>Unresponsive</fullName>
                </value>
                <value>
                    <fullName>No Contact</fullName>
                </value>
                <value>
                    <fullName>Unqualified</fullName>
                </value>
                <value>
                    <fullName>Auto-Complete/Expiration</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>We are going to use this object as Sales Journey of the user. Which begins when a person shows interest in one of our products or we decide to reach out to show our products.</description>
    <label>Journey</label>
    <nameField>
        <label>Customer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Journeys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TrJourneyOutreachStageStatusTest.cls
/************************************************************************************************************************************
    Author      :   Jitesh Adwani	
    Description :   This class will contain all the test method of TrJourneyOutreachStageStatus.
	Issue No    : 	ST-3039
    History		:
    ----------------------------------------------------------------------------------------------------------------------------------
    VERSION     DATE                AUTHOR                  DETAIL
    1          12 November 2018     Jitesh             Initial Developement
**************************************************************************************************************************************/
@isTest
public class TrJourneyOutreachStageStatusTest {
	
    @testSetup
    static void initData(){
        SalesConsoleSettings.createSettings();
        TestingUtility.getRecords(new Map<String, Object>{'objName'=>'lead', 'numberOfRecords'=>3});
    }
    
/************************************************************************************************************************************
    Author         : Jitesh Adwani
    Description    : This method is used in TrJourneyStageStatus.
    Created Date   : 15 Nov 2018 
    Issue No       : ST-3039
**************************************************************************************************************************************/
    public static testMethod void verifyUpdateJourneyStatusOnOutreachStage() {
        List<Journey__c> lstJourneys = [SELECT Id, Name, Outreach_Stage__c FROM Journey__c];
        List<Journey__c> lstUpdateJourney = new List<Journey__c>();
        for(Journey__c objJourney : lstJourneys){
            objJourney.Outreach_Stage__c = 'Call 1';
            lstUpdateJourney.add(objJourney);
        }
        TestingUtility.updateListWithAssert(lstUpdateJourney);
        List<Journey__c> lstUpdatedJourneys = [SELECT Id, Name, Outreach_Stage__c, Status__c FROM Journey__c];
        for(Journey__c objJourney : lstUpdatedJourneys){
            System.assertEquals(objJourney.Status__c.toLowerCase(), 'trying to reach', 'Status didn\'t update');
        }
    }
}