objects/Journey__c.object
<CustomObject>
    <fields>
        <fullName>Lead_Source_Detail__c</fullName>
        <description>Details of Lead Source from where Tour was booked. e.g. specific form of the website.</description>
        <label>Lead Source Detail</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Source__c</fullName>
        <description>Source of the Tour, how it was booked.</description>
        <label>Lead Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>42 Floors</fullName>
                </value>
                <value>
                    <fullName>ads-twitter</fullName>
                </value>
                <value>
                    <fullName>Adwords</fullName>
                </value>
                <value>
                    <fullName>Affiliate Referral</fullName>
                </value>
                <value>
                    <fullName>Broker Referral</fullName>
                </value>
                <value>
                    <fullName>Cold Call</fullName>
                </value>
                <value>
                    <fullName>Cold Email</fullName>
                </value>
                <value>
                    <fullName>Community Team Referral</fullName>
                </value>
                <value>
                    <fullName>Craigslist Ad</fullName>
                </value>
                <value>
                    <fullName>Employee Referral</fullName>
                </value>
                <value>
                    <fullName>Event</fullName>
                </value>
                <value>
                    <fullName>Facebook</fullName>
                </value>
                <value>
                    <fullName>Google</fullName>
                </value>
                <value>
                    <fullName>Guest</fullName>
                </value>
                <value>
                    <fullName>Guest Wifi</fullName>
                </value>
                <value>
                    <fullName>Id</fullName>
                </value>
                <value>
                    <fullName>Inbound Call</fullName>
                </value>
                <value>
                    <fullName>Inbound Email</fullName>
                </value>
                <value>
                    <fullName>Landing Page Campaign</fullName>
                </value>
                <value>
                    <fullName>LinkedIn Paid</fullName>
                </value>
                <value>
                    <fullName>Member Referral</fullName>
                </value>
                <value>
                    <fullName>Newsletter</fullName>
                </value>
                <value>
                    <fullName>Newsletter Campaign</fullName>
                </value>
                <value>
                    <fullName>Olark Chat</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Other Referral</fullName>
                </value>
                <value>
                    <fullName>Outbound Email/Cold Call</fullName>
                </value>
                <value>
                    <fullName>Partner Referral</fullName>
                </value>
                <value>
                    <fullName>Phone Call</fullName>
                </value>
                <value>
                    <fullName>Press Campaign</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>NMD_Next_Contact_Date__c</fullName>
        <description>Date on which Journey Primary Member should be next contacted on.

This is key to manage the reminders for the Journey.</description>
        <label>Next Contact Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Primary Contact of the Journey</description>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Journeys</relationshipLabel>
        <relationshipName>Journeys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>If journey is for a Lead this will be the Primary Lead. Only Primary Contact or Primary Lead can be specified not both.</description>
        <label>Primary Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Journeys</relationshipLabel>
        <relationshipName>Journeys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>New Field to Capture Journey Status</description>
        <label>Journey Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Started</fullName>
                    <default>true</default>
                    <label>Started</label>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Trying to Reach</fullName>
                </value>
                <value>
                    <fullName>In Contact</fullName>
                </value>
                <value>
                    <fullName>Nurture</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Transferred</fullName>
                </value>
                <value>
                    <fullName>Unresponsive</fullName>
                </value>
                <value>
                    <fullName>No Contact</fullName>
                </value>
                <value>
                    <fullName>Unqualified</fullName>
                </value>
                <value>
                    <fullName>Auto-Complete/Expiration</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>We are going to use this object as Sales Journey of the user. Which begins when a person shows interest in one of our products or we decide to reach out to show our products.</description>
    <label>Journey</label>
    <nameField>
        <label>Customer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Journeys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Generate_Journey__c</fullName>
        <defaultValue>true</defaultValue>
        <description>If this check box is checked , create journey for converted lead</description>
        <label>Generate Journey</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lead_Source_Detail__c</fullName>
        <label>Lead Source Detail</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Setting__c.object
<CustomObject>
    <fields>
        <fullName>Data__c</fullName>
        <description>This should contain JSON formatted data for each setting record. The JSON object will vary from setting to setting.</description>
        <label>Data</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <description>We are creating object for Settings instead of using Custom Object because we need to store larger size of data which Custom Setting does not support. e.g. Mapping of Fields from Contact to Lead etc. which may go beyond 255 characters. 

It will not use caching but give more flexibility for coding.</description>
    <label>Sales Console Setting</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Console Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/JourneyUpdateOwnerBatchTest.cls
/*
* Created By : Amol Darekar
* Date : 20/Dec/2016
*/
@isTest
public class JourneyUpdateOwnerBatchTest {
    @TestSetup
    static void initData(){
        SalesConsoleSettings.createSettings();
    }
    static void createUsers() 
    {
        /*List<Setting__c> lstSettings = new List<Setting__c>();
        lstSettings.add(new Setting__c(Name = 'AccountCleansingSetting',Data__c = '{"starts_with":["The","An","A"],"ends_with":["pvt","ltd"],"specialCharacters":"@#^&*!():?/><"}'));
        Insert lstSettings;*/
        Profile weworkSystemAdmin = [SELECT Id FROM Profile WHERE Name='System Administrator'];
        Map<String,Object> userRecordMap = new Map<String,Object>();
        userRecordMap.put('LastName','Last Name 1');
        userRecordMap.put('Username','testweworkuser1@example.com');
        userRecordMap.put('Email','testweworkuser1@example.com');
        User testUser = TestingUtility.insertUserWithAssert(weworkSystemAdmin.Id, userRecordMap, true); 
        
        userRecordMap = new Map<String,Object>();
        userRecordMap.put('LastName','Last Name 2');
        userRecordMap.put('Username','testweworkuser2@example.com');
        userRecordMap.put('Email','testweworkuser2@example.com');
        User testUser1 = TestingUtility.insertUserWithAssert(weworkSystemAdmin.Id, userRecordMap, true);   
        
        Setting__c testSettings = new Setting__c();
        testSettings.Name = 'User/Queue Journey Creation';
        testSettings.Data__c = '{"allowedUsers":[{"userName":"'+ testUser.Username +'","Id":"'+testUser.Id +'"},{"userName":"'+ testUser1.Username +'","Id":"'+testUser1.Id +'"}],"allowedQueues":[]}';//{"Id":"'+ testGroup1.Id +'","queueName":"'+ testGroup1.Name +'"}
        TestingUtility.insertWithAssert(testSettings);
    }
    static testMethod void updateJourenyOwnerTest() {
        createUsers();
        Lead lead = new Lead();
        Lead lead1 = new Lead();
        Journey__c[] journeys;
        string leadId;
        Lead[] leads;
        Task[] tasks;
        
        User u = [Select Id from user where username =:'testweworkuser1@example.com']; 
        system.assertNotEquals(null, u);
        
        User u1 = [Select Id from user where username =:'testweworkuser2@example.com']; 
        system.assertNotEquals(null, u1); 
        
       // lead = LeadConvertorTest.prepareLead('Smith', 'WeWork Test Company', 'testLead1@example.com', null);       
        lead.Company = 'Test Company';
        lead.Generate_Journey__c = true;
        lead.LeadSource= 'Broker1123';
        lead.ownerId = u.Id;
        lead.Lead_Source_Detail__c = 'Broker1123';
        lead.Email = 'testLead1@example.com';
        lead.LastName = 'Smith';
        insert lead; 
        
        Journey__c testJourney1 = new Journey__c();
        testJourney1.Name = 'testJourney';
        testJourney1.NMD_Next_Contact_Date__c = Date.today();
        testJourney1.Primary_Lead__c = lead.Id;
        testJourney1.Status__c = 'Started';
        testJourney1.ownerId = u1.Id;  
        testJourney1.Lead_Source__c = 'Event';
        insert testJourney1;
        
       // lead = LeadConvertorTest.prepareLead('Smith', 'WeWork Test Company', 'testLead2@example.com', null);      
        lead1.Company = 'Test Company';
        lead1.Generate_Journey__c = true;
        lead1.LeadSource= 'Broker123';
        lead1.ownerId = u.Id;
        lead1.Lead_Source_Detail__c = 'Broker1123';
        lead1.Email = 'testLead2@example.com';
        lead1.LastName = 'Smith';
        insert lead1;
        
        Journey__c testJourney2 = new Journey__c();
        testJourney2.Name = 'testJourney';
        testJourney2.NMD_Next_Contact_Date__c = Date.today();
        testJourney2.Primary_Lead__c = lead1.Id;
        testJourney2.Status__c = 'Started';
        testJourney2.ownerId = u1.Id;  
        testJourney2.Lead_Source__c = 'Event';
        insert testJourney2;
        
        Test.setCreatedDate(lead1.Id,system.today().addDays(-2));  
        
        Test.startTest();
        JourneyUpdateOwnerBatch Jowner = new JourneyUpdateOwnerBatch();
        Database.executeBatch(Jowner,2); 
        Database.QueryLocator ql = Jowner.start(null);
        Jowner.execute(null);
        Jowner.Finish(null);
        Test.stopTest();
        
        //First Journey ownerID should get changed because it's lead is created within 1 hour
        //Second lead is created before 2 days even if journey is created within one hour it's owner Id do not update.
        list<Journey__c> testLstUpdatedJourneys = [SELECT Id, OwnerId, Primary_Lead__c,Primary_Contact__c FROM Journey__c order by CreatedDate asc];
        System.assertEquals(u.Id, testLstUpdatedJourneys[0].OwnerId); 
        System.assertEquals(u.Id, testLstUpdatedJourneys[1].OwnerId);  
        
    }
}