objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Referrer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This will be the contact who referred us the Lead. It can be a member, employee or a broker.</description>
        <inlineHelpText>Enter the contact who referred us the Lead. It can be a member, employee or a broker.</inlineHelpText>
        <label>Referrer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Leads (Referrer)</relationshipLabel>
        <relationshipName>ReferredLeads</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/MetadataSetting__mdt.object
<CustomObject>
    <fields>
        <fullName>Data__c</fullName>
        <description>This is used to store new Journey Creation criteria</description>
        <inlineHelpText>Journey Creation criteria</inlineHelpText>
        <label>Data</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <description>This is used to filter for Journey creation criteria.</description>
    <label>MetadataSetting</label>
    <pluralLabel>MetadataSettings</pluralLabel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Broker_Involvement_Indicated__c</fullName>
        <description>This field is created for new created opportunity page, Used for ST-3250</description>
        <inlineHelpText>Stores the broker involvement values from create opportunity page.</inlineHelpText>
        <label>Is Broker Involved ?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Referrer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referrer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Referrer)</relationshipLabel>
        <relationshipName>Opportunities3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Region_Name__c</fullName>
        <description>Formula reference through building/portfolio/territory to region table</description>
        <formula>IF(!ISBLANK(Building__c),Building__r.Region_Name__c,Geography__r.Nearest_Building__r.Region_Name__c)</formula>
        <inlineHelpText>Region for THIS opportunity</inlineHelpText>
        <label>Region Name</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/TrOpportunityEmailAlertForBrokerInvolved.cls
/************************************************************************************************************************************
    Author      :   Ashish Mishra
    Description :   Trigger on opportunity ,fire when Referrer__c is not null, Lead Source not equal to Broker Reffral and Check region name
					Accouding to region name send email notification which is assign to that region.(on Insert and on Update).
	Issue No.	:	ST-3276

    History:
    ----------------------------------------------------------------------------------------------------------------------------------
    VERSION     DATE                AUTHOR                  DETAIL
    1           2 Jan 2019    		Ashish Mishra         	Initial Developement
**************************************************************************************************************************************/
public class TrOpportunityEmailAlertForBrokerInvolved implements IProcessHandler{
    
    public void handle(List<sObject> triggerNew, Map<Id, sObject> triggerOldMap) {              
        emailAlertForBrokerInvolved((List<Opportunity>)triggerNew, triggerOldMap);
    }
    
    static void emailAlertForBrokerInvolved(List<Opportunity> lstNewOpportunities, Map<Id, sobject> mapOldOpportunities){
        MetadataSetting__mdt brokerInvolvedNotificationMetadata = Settings.getMetadataSetting('BrokerInvolvedNotification');
        
        if(brokerInvolvedNotificationMetadata != null){
            BrokerInvolvedNotificationMetada objBrokerInvolvedNotificationMetadata = (BrokerInvolvedNotificationMetada)JSON.deserialize(brokerInvolvedNotificationMetadata.Data__c, BrokerInvolvedNotificationMetada.class);
            if(objBrokerInvolvedNotificationMetadata != null){
                Map<String, String> mapRegionRelatedEmails = getRegionRelatedEmails(objBrokerInvolvedNotificationMetadata.RegionRelatedEmails);
                Set<String> setExcludedLeadSources = getOpportunityExcludedLeadSources(objBrokerInvolvedNotificationMetadata.ExcludedOpportunityLeadSource);
                
                Map<Id, String> mapOpportunityRelatedEmails = new Map<Id, String>();
                
                if(mapRegionRelatedEmails != null){
                    for(Opportunity newOpportunity : lstNewOpportunities){
                        Opportunity oldOpportunity = mapOldOpportunities != null ? (Opportunity)mapOldOpportunities.get(newOpportunity.Id) : null;
                        Boolean isValidOpportunityForNotification = validateOpportunityForNotification(newOpportunity, oldOpportunity, setExcludedLeadSources, mapRegionRelatedEmails.keySet());
                        if(isValidOpportunityForNotification){
                            mapOpportunityRelatedEmails.put(newOpportunity.Id, mapRegionRelatedEmails.get(newOpportunity.Region_Name__c.toLowerCase()));
                        }
                    }
                    
                    if(mapOpportunityRelatedEmails.size() > 0){
                        String strEmailTemplateName = objBrokerInvolvedNotificationMetadata.EmailTemplateName;
                        sendBrokerInvolvedNotifications(mapOpportunityRelatedEmails, strEmailTemplateName);
                    }
                }
            }
        }
    }
    
    static Boolean validateOpportunityForNotification(Opportunity newOpportunity, Opportunity oldOpportunity, Set<String> setExcludedLeadSources, Set<String> setRegions){
        Boolean isValidOpportunityForNotification = String.isNotBlank(newOpportunity.LeadSource) && String.isNotBlank(newOpportunity.Referrer__c) && newOpportunity.Broker_Involvement_Indicated__c == 'Yes' && !setExcludedLeadSources.contains(newOpportunity.LeadSource.toLowerCase()) && String.isNotBlank(newOpportunity.Region_Name__c) && setRegions.contains(newOpportunity.Region_Name__c.toLowerCase());
        if(isValidOpportunityForNotification && (oldOpportunity == null || ((oldOpportunity != null && newOpportunity.Broker_Involvement_Indicated__c != oldOpportunity.Broker_Involvement_Indicated__c || newOpportunity.Referrer__c != oldOpportunity.Referrer__c)))) { 
            return true;
        }
        return false;
    }
    
    static Map<String, String> getRegionRelatedEmails(Map<String, String> mapMetadataRegionEmails){
        Map<String, String> mapRegionRelatedEmails = new Map<String, String>();
        for(String regionName : mapMetadataRegionEmails.keySet()){
            mapRegionRelatedEmails.put(regionName.toLowerCase(), String.valueOf(mapMetadataRegionEmails.get(regionName)));
        }
        return mapRegionRelatedEmails;
    }
    
    static Set<String> getOpportunityExcludedLeadSources(List<String> lstExcludedOpportunityLeadSources){
        Set<String> setExcludedLeadSources = new Set<String>();
        for(String strLeadSource : lstExcludedOpportunityLeadSources){
            setExcludedLeadSources.add(strLeadSource.toLowerCase());
        }
        return setExcludedLeadSources;
    }
    
    static void sendBrokerInvolvedNotifications(Map<Id, String> mapOpportunityRelatedEmails, String strEmailTemplateName){
        List<Messaging.SingleEmailMessage> lstBrokerInvolvedNotificationEmails = new List<Messaging.SingleEmailMessage>();
        EmailTemplate objEmailTemplate = Settings.getEmailTemplateByDeveloperName(strEmailTemplateName);
        Messaging.SingleEmailMessage objSingleMail;
        for(Id opportunityId : mapOpportunityRelatedEmails.keySet()){
            String strEmailAddress = mapOpportunityRelatedEmails.get(opportunityId);  
            if(String.isNotBlank(strEmailAddress)){
                objSingleMail = new Messaging.SingleEmailMessage();
                objSingleMail.setTemplateID(objEmailTemplate.Id); 
                objSingleMail.setTargetObjectId(UserInfo.getUserId());
                objSingleMail.setWhatId(opportunityId);
                objSingleMail.setSenderDisplayName('WeWork');
                objSingleMail.setTreatTargetObjectAsRecipient(false);
                objSingleMail.setSaveAsActivity(false);
                objSingleMail.setToAddresses(new List<String>{strEmailAddress});
                
                lstBrokerInvolvedNotificationEmails.add(objSingleMail);   
            }
        }
        
        if(lstBrokerInvolvedNotificationEmails.size() > 0){
            Messaging.sendEmail(lstBrokerInvolvedNotificationEmails, false);
        }
    }
    
    class BrokerInvolvedNotificationMetada {
		public List<String> ExcludedOpportunityLeadSource;
		public Map<String, String> RegionRelatedEmails;
		public String EmailTemplateName;
	}
}