objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Lead_Source_Detail__c</fullName>
        <label>Lead Source Detail</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Number_of_Desks_2016__c</fullName>
        <description>This is a new field to capture no of desks from website and other external systems, moving forward we will be referring this field only</description>
        <label>Number of Desks 2016</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1 desk</fullName>
                </value>
                <value>
                    <fullName>2-5 desks</fullName>
                </value>
                <value>
                    <fullName>6-10 desks</fullName>
                </value>
                <value>
                    <fullName>11-20 desks</fullName>
                </value>
                <value>
                    <fullName>21-50 desks</fullName>
                </value>
                <value>
                    <fullName>51+ desks</fullName>
                </value>
                <value>
                    <fullName>1desk</fullName>
                </value>
                <value>
                    <fullName>20-100 People</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unomy_Location_City__c</fullName>
        <label>Unomy Location City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/UnomyDataMigrationTest.cls
@isTest
public class UnomyDataMigrationTest {
    @TestSetup
    public static void dataSetup()
    {
        SalesConsoleSettings.createSettings();
        Lead lead = new Lead(           
            FirstName = 'Test', 
            LastName = 'Test',
            Company = 'Test',
            Email = 'Test1@example.com',
            LeadSource = 'Broker',
            Lead_Source_Detail__c = 'Broker1',
            Status = 'TestStatus',
            CurrencyIsoCode = 'USD',
            Number_of_Desks_2016__c = '2-5 desks',
            Unomy_Location_City__c='MUMBAI'
        );
        insert lead;
        Lead lead2 = new Lead(           
            FirstName = 'Test1', 
            LastName = 'Test1',
            Company = 'Test',
            Email = 'Test1@example.com',
            LeadSource = 'Broker',
            Lead_Source_Detail__c = 'Broker1',
            Status = 'TestStatus',
            CurrencyIsoCode = 'USD',
            Number_of_Desks_2016__c = '2-5 desks',
            Unomy_Location_City__c='Bangluru'
        );
        insert lead2;
    }
    
    @isTest
    public static void UpdateUnomyLoacationcity()
    {
        String q='SELECT Id,Unomy_Location_City__c From Lead LIMIT 10';
        Map<String,String>mapoffield=new Map<String,String>();
        mapoffield.put('Unomy_Location_City__c','');
        Test.startTest();
        Database.executeBatch(new UnomyDataMigration(q,mapoffield));
        Test.stopTest();
        List<Lead> lstlead=[Select Id,Name,Unomy_Location_City__c From Lead LIMIT 10 ];
        for(Lead l:lstlead)
        {
            System.assertEquals(l.Unomy_Location_City__c,null);
        }
        
    }
}