objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Last_Lead_Processing_Update__c</fullName>
        <label>Last Lead Processing Update</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Processing_Stage__c</fullName>
        <defaultValue>"Created"</defaultValue>
        <label>Processing Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Enriched</fullName>
                </value>
                <value>
                    <fullName>Demographic Scored</fullName>
                </value>
                <value>
                    <fullName>Market Identified</fullName>
                </value>
                <value>
                    <fullName>Assignment Complete</fullName>
                </value>
                <value>
                    <fullName>Behavioural Scored</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unomy_Location_City__c</fullName>
        <label>Unomy Location City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unomy_Location_Country__c</fullName>
        <label>Unomy Location Country</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unomy_Location_State__c</fullName>
        <label>Unomy Location State</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unomy_Updated_DateTime__c</fullName>
        <description>The date/time a record was updated from Unomy</description>
        <label>Unomy Updated DateTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Update_HQ_Market_Status__c</fullName>
        <description>This field show the status where the batch is updated record or not.</description>
        <label>Update HQ Market Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Retry Round 1</fullName>
                </value>
                <value>
                    <fullName>Retry Round 2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/TrLeadUpdateMarket.cls
/************************************************************************************************************************************
	Author		: 	Krishana Tupe
	Description	: 	This trigger is used to update market on Lead.
					Runs on Before insert and Before update.
	----------------------------------------------------------------------------------------------------------------------------------
	VERSION		DATE	        	AUTHOR                     	DETAIL
	1	    	17 December 2018	Krishana Tupe       	Initial Developement
	2	    	23 January 2019		Krishana Tupe           Made changes for Lead update Market logic
**************************************************************************************************************************************/
public class TrLeadUpdateMarket implements IProcessHandler {
	
    /************************************************************************************************************************************
        Author              :   Krishana Tupe
        Description         :   Overide handle method from IProcessHandler.
        Created Date  		:   17 December 2018
		LastModified Date	:	24 January 2019
		Issue No.			:	ST-3255,ST-3343
    **************************************************************************************************************************************/    
    public void handle(list<sObject> triggerNew, map<Id, sObject> triggerOldMap){       
        for(Lead objLead : (List<Lead>) triggerNew){           
            Lead  objOldLead = triggerOldMap != NULL ? (Lead)triggerOldMap.get(objLead.Id) : NULL;
            if(objOldLead != NULL && Settings.isChanged(objLead.Processing_Stage__c, objOldLead.Processing_Stage__c)){
                objLead.Last_Lead_Processing_Update__c = System.now();  
            }else if(objOldLead == NULL && objLead.Last_Lead_Processing_Update__c == NULL){
                objLead.Last_Lead_Processing_Update__c = System.now();     
            }            
            if(!objLead.IsConverted && checkValidForUpdateMarket(objLead, objOldLead)){
                objLead.Update_HQ_Market_Status__c = 'Pending';                
            }
        }
    }
    
    /************************************************************************************************************************************
        Author              :   Krishana Tupe
        Description         :   This method is usde to validate if Lead record data is enough to find market.
        Created Date  		:   06 December 2018
		LastModified Date	:	24 January 2019
		Issue No.			:	ST-3255,ST-3343
    **************************************************************************************************************************************/    
    public Boolean checkValidForUpdateMarket(Lead objNewLead, Lead objOldLead){       
        Boolean isAddressCriteriaMatched = ((String.isNotBlank(objNewLead.City) && String.isNotBlank(objNewLead.State)) || (String.isNotBlank(objNewLead.City) && String.isNotBlank(objNewLead.Country)) || String.isNotBlank(objNewLead.Country));
        Boolean isUnomyAddressCriteriaMatched = ((String.isNotBlank(objNewLead.Unomy_Location_City__c) && String.isNotBlank(objNewLead.Unomy_Location_State__c))|| (String.isNotBlank(objNewLead.Unomy_Location_City__c) && String.isNotBlank(objNewLead.Unomy_Location_Country__c)) || String.isNotBlank(objNewLead.Unomy_Location_Country__c));
        Boolean isUnomyDateTimeUpdated = (objOldLead != null && String.isNotBlank(String.valueOf(objNewLead.Unomy_Updated_DateTime__c)) && objNewLead.Unomy_Updated_DateTime__c != objOldLead.Unomy_Updated_DateTime__c);
        Boolean isUnomyAddressChanged = (objOldLead != null && (Settings.isChanged(objNewLead.Unomy_Location_City__c, objOldLead.Unomy_Location_City__c)  || Settings.isChanged(objNewLead.Unomy_Location_State__c, objOldLead.Unomy_Location_State__c) || Settings.isChanged(objNewLead.Unomy_Location_Country__c, objOldLead.Unomy_Location_Country__c)));
        Boolean isAddressChanged = (objOldLead != NULL && (Settings.isChanged(objNewLead.City, objOldLead.City)  ||  Settings.isChanged(objNewLead.State, objOldLead.State) || Settings.isChanged(objNewLead.Country, objOldLead.Country)));
        if(objOldLead == NULL && (isUnomyAddressCriteriaMatched || isAddressCriteriaMatched)){
            return true;
        }else if(objOldLead != NULL && ((isUnomyAddressChanged && isUnomyAddressCriteriaMatched) || (isUnomyDateTimeUpdated && (isAddressCriteriaMatched || isUnomyAddressCriteriaMatched)) || (isAddressCriteriaMatched && isAddressChanged))){
            return true;
        }
        return false;
    }
}