objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Broker_Involved_DateTime__c</fullName>
        <label>Broker Involved DateTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Broker_Involved_Rep__c</fullName>
        <label>Broker Involved Rep</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Broker_Involved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Broker Involved [OLD]</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Broker_Involvement_Indicated__c</fullName>
        <description>This field is created for new created opportunity page, Used for ST-3250</description>
        <inlineHelpText>Stores the broker involvement values from create opportunity page.</inlineHelpText>
        <label>Is Broker Involved ?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/BrokerInvolvedController.cls
/*****************************************************************************************************************************
    Author 		:  Pragalbha Mahajan
    Description :  This class is used to BrokerInvolvedController
    Date		:  19 December 2018
    Issue		:  ST-3250
    ----------------------------------------------------------------------------------------------------------------------------------
    VERSION					DATE					AUTHOR							DETAIL
    1.0					15,July 2018		    Sunil Bhosale	                Initial Developement
******************************************************************************************************************************/
global without sharing class BrokerInvolvedController {
    
    /************************************************************************************************************************************
        Author              :   Pragalbha Mahajan
        Description         :   This method is used to update broker on opportunity.
        Created Date  		:   19 December 2018
		Issue No.			:	ST-3250
    **************************************************************************************************************************************/    
    @AuraEnabled
    webservice static Boolean updateBrokerInvolved(Id opportunityId){
        List<Opportunity> lstOpportunity = [SELECT Id, Broker_Involved__c, Broker_Involved_DateTime__c, Broker_Involvement_Indicated__c FROM Opportunity WHERE Id = :  opportunityId AND (Broker_Involvement_Indicated__c <> 'Yes' OR Broker_Involved_DateTime__c = NULL OR Broker_Involved_Rep__c = NULL)];
        if(!lstOpportunity.isEmpty()){
            Boolean isUpdate = false;
            Opportunity objOpportunity = lstOpportunity[0];
            if(String.isBlank(objOpportunity.Broker_Involvement_Indicated__c) || !objOpportunity.Broker_Involvement_Indicated__c.equalsIgnoreCase('Yes')){
                objOpportunity.Broker_Involvement_Indicated__c = 'Yes';
                isUpdate = true;
            }            
            if(String.isBlank(String.valueOf(objOpportunity.Broker_Involved_DateTime__c))){
                objOpportunity.Broker_Involved_DateTime__c = Date.today();
                isUpdate = true;
            }            
            if(String.isBlank(objOpportunity.Broker_Involved_Rep__c)){
                objOpportunity.Broker_Involved_Rep__c = UserInfo.getFirstName()+' '+UserInfo.getLastName();  
                isUpdate = true;
            }
            if(isUpdate){
                update objOpportunity;   
                return true;
            } 
        } 
        return false;
    } 
}