objects/Referral__c.object
<CustomObject>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <description>To check if the reference is a active reference or not ?</description>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Referral_Email__c</fullName>
        <description>Captures the email of the new lead coming to the system with reference of a referrer.</description>
        <label>Referral Email</label>
        <type>Email</type>
    </fields>
    <description>This object will represent references made by either Member/Broker/Employee to certain person identified by email. 

This is generally valid for 60 days and may be extended by another 60 days based on certain events like if referred person books a tour, completes a tour or paperwork is sent to the person referred.</description>
    <label>Referral</label>
    <nameField>
        <label>Referral Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referrals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ReferralTriggerHandler.cls
/************************************************************************************************************************************
	Author 		: -
	Description : This class contains unit tests for validating the behavior of Apex classes and triggers.
 	
History:
----------------------------------------------------------------------------------------------------------------------------------
	VERSION			DATE				AUTHOR					DETAIL							ISSUE
	1				-					Amol Darekar			Initial Developement			-
	2				01 February 2018	Krishana Tupe			Added new trigger structure.	-			
**************************************************************************************************************************************/
public class ReferralTriggerHandler extends ITriggerHandler{
    
    /************************************************************************************************************************************
      Author 			: Krishana Tupe
      Description 		: This is ITriggerHandler constructor which will be used in future.
      Created Date		: 01 February 2018          
    **************************************************************************************************************************************/     
    public ReferralTriggerHandler(){
        super('Referral__c');
        
    }
    
   	/************************************************************************************************************************************
      Author 				: Krishana Tupe
      Description 			: This method overrides before insert method from ITriggerHander which will control the execution flow.
      Last Modified Date	: 01 February 2018
      Last Modified By		: Krishana Tupe (added Comment)
	**************************************************************************************************************************************/
    public override void BeforeInsert(List<SObject> listNewItems){
        PreventDuplicateActiveReference(listNewItems);        
    }
    
    /************************************************************************************************************************************
      Author 			: -
      Description 		: PreventDuplicateActiveReference.
      Created Date		: -
      Modified Date 	: 01 February 2018
      Last Modified By	: Krishana Tupe	  
    **************************************************************************************************************************************/ 
    public static void PreventDuplicateActiveReference(List<SObject> listNewItems){
        if(TriggerSettings.mappedField.Referral_PreventDuplicateActiveReference){
            set<string> setReferenceEmails = new set<string>();
            set<string> setExistingReferenceEmails = new set<string>();
            list<Referral__c> lstReferences = listNewItems;
            Boolean errorFlag = false;
            
            for(Referral__c currentReference : lstReferences){
                if(!String.isBlank(currentReference.Referral_Email__c)){
                    setReferenceEmails.add(currentReference.Referral_Email__c.toLowerCase());
                }   
            }
            list<Referral__c> lstExistingReferences = [Select Id, Name, Referral_Email__c , IsActive__c from Referral__c where Referral_Email__c IN : setReferenceEmails and IsActive__c = true];
            for(Referral__c currentReference : lstExistingReferences){
                setExistingReferenceEmails.add(currentReference.Referral_Email__c.toLowerCase());
            }
            for(Referral__c currentReference : lstReferences){
                if(!String.isBlank(currentReference.Referral_Email__c)){
                    setReferenceEmails.add(currentReference.Referral_Email__c.toLowerCase());
                }
            }
            for(Referral__c currentReference : lstReferences){
                if(!String.isBlank(currentReference.Referral_Email__c)){
                    if(setExistingReferenceEmails.contains(currentReference.Referral_Email__c.toLowerCase())){
                        errorFlag = true;
                    }
                }
            }
            if(errorFlag)
                listNewItems[0].addError('Duplicate reference');
        }        
    }
}