objects/Reservable_Hold__c.object
<CustomObject>
    <fields>
        <fullName>UUID__c</fullName>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Reservable Hold</label>
    <nameField>
        <displayFormat>RH{000000}</displayFormat>
        <label>Hold Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reservable Holds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Setting__c.object
<CustomObject>
    <fields>
        <fullName>Data__c</fullName>
        <description>This should contain JSON formatted data for each setting record. The JSON object will vary from setting to setting.</description>
        <label>Data</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <description>We are creating object for Settings instead of using Custom Object because we need to store larger size of data which Custom Setting does not support. e.g. Mapping of Fields from Contact to Lead etc. which may go beyond 255 characters. 

It will not use caching but give more flexibility for coding.</description>
    <label>Sales Console Setting</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Console Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/QueueReservableHold.cls
/************************************************************************************************************************************
	Author		: 	Samadhan Kadam
	Description : 	QueueReservableHold

	History:
	----------------------------------------------------------------------------------------------------------------------------------
	VERSION		DATE	        	AUTHOR                       DETAIL
	1	    	1 December 2017	  	Samadhan Kadam               Initial Developement
**************************************************************************************************************************************/
public class QueueReservableHold implements Queueable, Database.AllowsCallouts{   
    List<Reservable_Hold__c> lstHoldsToBeReleased = new List<Reservable_Hold__c>();
    public QueueReservableHold(List<Reservable_Hold__c> lstHoldsToBeReleased){
        this.lstHoldsToBeReleased = lstHoldsToBeReleased;
    }
    /************************************************************************************************************************************
        Author				:	Samadhan Kadam 
        Description			:	This method executes business logic for QueueReservableHold class. 
        Last Modified Date	: 	1 January 2018
        Last Modified By	:	Samadhan Kadam 
    **************************************************************************************************************************************/
    public void execute(QueueableContext context) {
        try{
            for(Reservable_Hold__c newHoldRecord : lstHoldsToBeReleased){                
                debug.Log('newHoldRecord::'+newHoldRecord);
                //Modified by Samadhan kadam for CSI-512 as we have only 2 Status Hold and Released
                Setting__c HoldReservable = Settings.get('HoldReservableSettings'); 
                debug.log('HoldReservableSetting'+HoldReservable);     
                HoldReservableController.HoldReservableSettings settingData = new HoldReservableController.HoldReservableSettings();
                settingData = (HoldReservableController.HoldReservableSettings)JSON.deserialize(HoldReservable.Data__c, HoldReservableController.HoldReservableSettings.class);
                String endPointUrl;
                String userId = UserInfo.getUserId();
                endPointUrl = settingData.HoldoffAPI.url.replace('HOLD_UUID',newHoldRecord.UUID__c);
                Http http = new Http();
                HttpRequest request = new HttpRequest();
                request.setEndpoint(endPointUrl);
                request.setMethod('POST');
                request.setHeader('Content-Type','application/json');
                request.setHeader('Authorization',settingData.HoldoffAPI.Headers.get('Authorization'));
                request.setHeader('CONTEXT_SALESFORCE_ID',userId);
                HTTPResponse response = http.send(request);
            }
        }catch(Exception exc){
            Debug.log('exc ::'+exc);
        }
        
    }
}