objects/User.object
<CustomObject>
    <fields>
        <fullName>Director_Email__c</fullName>
        <label>Senior Director Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Director__c</fullName>
        <description>Director of Sales Rep</description>
        <label>Senior Director</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Manager_Email__c</fullName>
        <label>Manager Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Manager_Name__c</fullName>
        <label>Manager Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Role__c</fullName>
        <description>Role of Sales Rep</description>
        <label>Sales Function</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ENT - Pod Director</fullName>
                </value>
                <value>
                    <fullName>ENT - Global VP</fullName>
                </value>
                <value>
                    <fullName>ENT - Account Director</fullName>
                </value>
                <value>
                    <fullName>ENT - Regional VP</fullName>
                </value>
                <value>
                    <fullName>ENT - Senior Director</fullName>
                </value>
                <value>
                    <fullName>ENT - BD Rep</fullName>
                </value>
                <value>
                    <fullName>ENT - BD Global VP</fullName>
                </value>
                <value>
                    <fullName>ENT - BD Regional Director</fullName>
                </value>
                <value>
                    <fullName>ENT - REA Senior Director</fullName>
                </value>
                <value>
                    <fullName>ENT - REA Global VP</fullName>
                </value>
                <value>
                    <fullName>ENT - REA Sr. Associate</fullName>
                </value>
                <value>
                    <fullName>ENT - Account Executive</fullName>
                </value>
                <value>
                    <fullName>AM - Enterprise</fullName>
                </value>
                <value>
                    <fullName>AM - Hybrid</fullName>
                </value>
                <value>
                    <fullName>AM - Manager</fullName>
                </value>
                <value>
                    <fullName>AM - Regional</fullName>
                </value>
                <value>
                    <fullName>AM - Community</fullName>
                </value>
                <value>
                    <fullName>MLB - AE</fullName>
                </value>
                <value>
                    <fullName>MLB - AE (ACTING)</fullName>
                </value>
                <value>
                    <fullName>MLB - SD</fullName>
                </value>
                <value>
                    <fullName>MLB - SD (ACTING)</fullName>
                </value>
                <value>
                    <fullName>MLB - SM</fullName>
                </value>
                <value>
                    <fullName>MLB - SM (ACTING)</fullName>
                </value>
                <value>
                    <fullName>Consumer - AE</fullName>
                </value>
                <value>
                    <fullName>Consumer - SM</fullName>
                </value>
                <value>
                    <fullName>Consumer - SD</fullName>
                </value>
                <value>
                    <fullName>Regional Head of Growth</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>VP_Email__c</fullName>
        <label>Regional VP Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>VP__c</fullName>
        <description>VP of Sales Rep</description>
        <label>Regional VP</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/ScheduleBatchToUpdateUserSalesHierarchy.cls
/************************************************************************************************************************************
    Author 		: Rupesh Patil
    Description : This batch apex will run every one hour and identify Director of Sales and VP of Sales for each user for which Sales Role is specified and update the user

    History:
	----------------------------------------------------------------------------------------------------------------------------------
	VERSION		DATE				AUTHOR					DETAIL
    1			7 Mar 2018			Rupesh Patil			Initial Developement.
	2			12 Mar 2018			Rupesh Patil			Modifications
**************************************************************************************************************************************/
public class ScheduleBatchToUpdateUserSalesHierarchy implements Schedulable, Database.Batchable<sObject> {
    public User GetParentUserWithRole(User userRole, String role){
        Debug.log('UserRole::'+userRole.Sales_Role__c + 'Role::'+role);
        //Validation
        if(userRole.Sales_Role__c == role)
            return userRole;
        if(userRole.Manager.Sales_Role__c == role)
            return userRole.Manager;
        if(userRole.Manager.Manager.Sales_Role__c == role)
            return userRole.Manager.Manager;
        if(userRole.Manager.Manager.Manager.Sales_Role__c == role)
            return userRole.Manager.Manager.Manager;
        if(userRole.Manager.Manager.Manager.Manager.Sales_Role__c == role)
            return userRole.Manager.Manager.Manager.Manager;
        return null;
    }
    public Database.QueryLocator start(Database.BatchableContext bc){
        DateTime dtLastModified = DateTime.now().addHours(-2);      
        String query = 'SELECT Id,Sales_Role__c,Name,Email,Manager.Id,Manager.Email, Manager.Sales_Role__c, Manager.Name,Manager.Manager.Id, Manager.Manager.Sales_Role__c, Manager.Manager.Name,Manager.Manager.Email,Manager.Manager.Manager.Id,Manager.Manager.Manager.Sales_Role__c,Manager.Manager.Manager.Name,Manager.Manager.Manager.Email,Manager.Manager.Manager.Manager.Id,Manager.Manager.Manager.Manager.Sales_Role__c, Manager.Manager.Manager.Manager.Name,Manager.Manager.Manager.Manager.Email FROM User WHERE IsActive = true And Sales_Role__c != \'\' And (LastModifiedDate > :dtLastModified OR VP__c = \'\' )';         
        if(Test.isRunningTest()){
            query += ' LIMIT 50';
        }        
        return Database.getQueryLocator(query);
    }
     public void execute(SchedulableContext sc){
        ScheduleBatchToUpdateUserSalesHierarchy objBatch = new ScheduleBatchToUpdateUserSalesHierarchy(); 
      	database.executebatch(objBatch);
    }
    public void execute(Database.BatchableContext bc,List<User> listRecords){        
        if(listRecords.size() != 0){
            for(User lstUser : listRecords){
                lstUser.Manager_Name__c = lstUser.Manager.Name;
                lstUser.Manager_Email__c = lstUser.Manager.Email;
                User objUserVP = GetParentUserWithRole(lstUser,'VP of Sales');
                User objUserDirector = GetParentUserWithRole(lstUser,'Director of Sales');
                if(objUserVP != null){
                    lstUser.VP__c = objUserVP.Name;
                    lstUser.VP_Email__c = objUserVP.Email;
                }
                if(objUserDirector != null){
                    lstUser.Director__c = objUserDirector.Name;
                    lstUser.Director_Email__c = objUserDirector.Email;
                }
            }
        }        
       	Database.update(listRecords);
    }
    public void finish(Database.BatchableContext bc){
        //finish
    }
    
}