objects/WWSync_Setup__c.object
<CustomObject>
    <fields>
        <fullName>Email_Catcher_Contact_ID__c</fullName>
        <label>Email Catcher Contact ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>apex_notification_email__c</fullName>
        <label>apex notification email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>endpoint__c</fullName>
        <label>endpoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>payment_endpoint__c</fullName>
        <label>payment_endpoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>token__c</fullName>
        <label>token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>WWSync Setup</label>
</CustomObject>

classes/CustomSettingsServices.cls
public with sharing class CustomSettingsServices {
	public static void loadDefaultTestValues() {
		//get object
		WWSync_Setup__c setup = CustomSettingsServices.default();
	}

	public static WWSync_Setup__c default() {
		//get object
		WWSync_Setup__c setup = WWSync_Setup__c.getOrgDefaults();
		
		if (Test.isRunningTest()) {
			//load defaults
			setup.token__c 		= 'abc123456';
			setup.endpoint__c = 'wework.testapi.com/app/test';
			setup.payment_endpoint__c = 'payments.wework.com/api/';
			setup.email_catcher_contact_id__c = null;
			setup.apex_notification_email__c = 'cmhelp@wework.com';

			//dml
			upsert setup;	
		}

		return setup;	
	}
}